### ISSUE TITLE
errore 400

### ISSUE THREAD

**Issue by rglauco** [pagopa/pdnd-interop-frontend#1006]
Questo il msg di errore: "code":"015-0008","detail":"Unable to generate a token for the given request"
Ho fatto il debug della client_assertion e risulta valida.
Ho provato tramite altri servizi gia' in produzione e non ottengo il voucher.

**Il codice IPA del tuo ente**
c_h022

**Data e ora del tentativo**
13/11/2024 h. 8:59:13

**Ambiente**
Produzione 

**client_id**
`3499010c-cc80-4cac-b31f-9cd4b701b5bb`

**correlationId**
`bb90a10f-b46e-4f04-860d-46934b9e968e`

**purposeId**
`1edd6926-efd8-470e-9adb-887320373c64`

**Comment by FedericaSicchiero** [comment]
Buongiorno, controlliamo e aggiorno la issue appena ci sono novità

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo risolto il blocco che c'era, potete gentilmente riprovare a staccare un token? Grazie
