### ISSUE TITLE
Rallentamenti su piattaforma di collaudo

### ISSUE THREAD

**Issue by mircogamberinirer** [pagopa/pdnd-interop-frontend#1007]
Su piattaforma di collaudo, segnalo dei rallentamenti o problemi vari (non riesco a creare il servizio o non mi carica elenco servizi che erogo), sembra problema di timeout.

Per replicare, basta navigare o creare un nuovo e-service

Mi aspetto di avere delle risposte senza attendere caricamento infinito

data problema: 14.50 13/1124

ambiente: collaudo

ho i permessi di admin

**Comment by FedericaSicchiero** [comment]
Salve, dovremmo aver risolto da poco proprio la vostra segnalazione.
Potete gentilmente riprovare e vedere se è ancora così lento?
Grazie

**Comment by mircogamberinirer** [comment]
Purtroppo ancora lentissimo.

**Comment by FedericaSicchiero** [comment]
Con quale ente state provando a lavorare su PDND?

**Comment by mircogamberinirer** [comment]
Ente Regione Emilia-Romagna

**Comment by FedericaSicchiero** [comment]
Grazie, controlliamo e appena ho novità aggiorno la issue

**Comment by FedericaSicchiero** [comment]
Lato nostro il problema sembra essere rientrato, potete darci conferma anche lato vostro?

**Comment by mircogamberinirer** [comment]
Confermo che ora funziona correttamente e vi ringrazio per il supporto
