### ISSUE TITLE
Errore caricamento

### ISSUE THREAD

**Issue by aangioi** [pagopa/pdnd-interop-frontend#1009]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

Durante il caricamento di un e-service su selfcare pagoPa ho un errore nel caricamento

Andando in area personale, in ambiente di Produzione, sezione Interoperabilità in area Erogazione, procedo con la bozza del servizio.
Essendo il servizio con tecnologia SOAP è necessario il caricamento di un file . WSDL.
Durante il caricamento di tale file però ho un errore di caricamento.

Il processo è stato effettuato come amministratore in 3 enti diversi, i comuni di:
Lodè: c_e647
Sennariolo: c_i613
Palmas Arborea: c_g286 

![errore sennariolo](https://github.com/user-attachments/assets/7ec4cacd-7854-4eb7-bf22-9e9aef087e5f)

In attesa di un gentile riscontro, Antonio.

**Comment by aangioi** [comment]
Grazie a voi

**Comment by FedericaSicchiero** [comment]
Buongiorno, entro fine giornata rilasciamo il fix per questo bug. Appena rilasciato chiudo la issue, grazie
