### ISSUE TITLE
errore nella schermata di visualizzazione di un client

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [pagopa/pdnd-interop-frontend#1016]
**Descrivi il bug**
Accedendo alla piattaforma nel client specifico https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/client/0942c15a-d88d-4ea5-9ff1-b2ee0629f082 e dopo pochi secondi ottengo il seguente errore: redirect su questa pagina https://selfcare.uat.interop.pagopa.it/ui/it/404?tab=clientOperators con messaggio "Pagina inesistente
404 - La pagina cercata purtroppo non esiste."

**Step per riprodurre il bug**
1. Vai su Fruizione -> I tuoi client e-service
2. Clicca su Test_TnDigit
3. Vedi l'errore

**Comportamento atteso**
Consentire di operare nei vari tab, (chiavi, script, etc...) come per gli altri client (gli altri funzionano è solo Test_TnDigit che crea problemi)

**Il codice IPA del tuo ente**
p_TN Provincia Autonoma di Trento

**Data e ora in cui si è riscontrato il problema**
29/11/2024 h. 11:00

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Operatore API, Operatore di sicurezza

**Screenshot**
appena si clicca su visualizza dopo pochi secondi appare l'errore
![image](https://github.com/user-attachments/assets/9baf3d17-90ac-4653-9487-1934f3ba4320)

**Note**
Per pochi secondi si riesce a vedere il client con i suoi dati ma poi non riesce a recuperare una risorsa e va in errore, vedi console del browser:
index-cac72355.js:40 sv
    at https://selfcare.uat.interop.pagopa.it/ui/assets/index-cac72355.js:391:61505
    at async Jb.request (https://selfcare.uat.interop.pagopa.it/ui/assets/index-cac72355.js:390:1874)
    at async Object.lrt [as getSingle] (https://selfcare.uat.interop.pagopa.it/ui/assets/index-cac72355.js:410:68595)
    at Jb.request (https://selfcare.uat.interop.pagopa.it/ui/assets/index-cac72355.js:390:1967)
    at async Object.lrt [as getSingle] (https://selfcare.uat.interop.pagopa.it/ui/assets/index-cac72355.js:410:68595)
Z6 @ index-cac72355.js:40

**Comment by sara-gasperetti** [comment]
Lo stesso errore avviene anche con utente Amministratore. 
In console compare già un errore quando col mouse ci si posiziona sul pulsante "Visualizza" senza cliccare.

`GET https://selfcare.uat.interop.pagopa.it/1.0/backend-for-frontend/clients/0942c15a-d88d-4ea5-9ff1-b2ee0629f082 404 (Not Found)`

Cliccando sul pulsante "Visualizza" (solo del client specificato nel bug) si apre questa schermata e non è possibile fare nessuna operazione.
![image](https://github.com/user-attachments/assets/2fff4b40-b49d-444f-8fd1-b3911f705a04)
