### ISSUE TITLE
Impossibile richiamare API C019 tramite client java (e anche Postman)

### ISSUE THREAD

**Issue by valerio65xz** [pagopa/pdnd-interop-frontend#1017]
Buonasera,
sto provando con svariati tentativi e combinazioni a chiamare la seguente API
https://www.interop.pagopa.it/catalogo/fd741918-cac1-4d5f-9437-15b520b4cce3/

E ho seguito diverse guide e step, senza riuscire a chiamare l'API. In particolare:

- Seguendo la guida per staccare un voucher dal client nel portare interop, non e' sufficiente per chiamare l'API
- Manca a quanto pare tutta la parte di Agid JWT
- Provando a segure le seguenti 2 guide: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher e https://github.com/italia/anpr/files/11999717/Documento.operativo.-.Pattern.sicurezza.-.v1.1.pdf, non e' chiaro come dovrei strutturare la chiamata (se ad esempio devo usare Bearer Token con access token generato dalla CURL di esempio del portale interop, e poi definire l'header a parte, se usare JWT bearer come metodo di autenticazione al posto di Bearer Token, come creare e su che base il JWS ecc) quindi mi ricollego alla proposta in questo thread: https://github.com/pagopa/pdnd-interop-frontend/issues/792

Comunque ho provato ad usare il client java disponibile qui https://github.com/italia/anpr/issues/4488

Dando questi campi

```
baseurlapi=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
#kid della chiave pubblica caricata su pdnd es. 4OWnyvd6Lkxx5iee12qpoRkuweSMgJONUWwg4ZsrOaw
kidPdnd=zANUbX-rd1_4pZLHGbX0wsvJYyLR205_jO8JFwaM-Oc
#clientid restituito da pdnd al client censito sulla piattaforma es. 371867ab-5331-4bb0-8743-f5f04048be3c
clientIdPdnd=539619b1-967c-46ec-9f98-612ba03a637b
#purposeid restituito dalla pdnd a seguito della dichiarazione della finalità es. c6f72cd8-bd62-4315-a0fe-743332ee4946
purposeIdPdnd=54f1add6-f333-4137-9b4d-58576cf21159
audPdnd=auth.uat.interop.pagopa.it/client-assertion
urltokenPdnd=https://auth.interop.pagopa.it
#Token Agid-Jwt-Signature
audTokenAgidJwtSignature=https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1
proxyhost=
proxyport=
proxyuser=
proxypwd=
fileTest=test1
```

E questo payload in test1

```
{
   "idOperazioneClient":"1",
   "criteriRicerca":{
      "codiceFiscale":"TDAMHL88B26I849Y"
   },
   "datiRichiesta":{
      "dataRiferimentoRichiesta":"2024-12-03",
      "motivoRichiesta":"1",
      "casoUso":"C019"
   }
}
```

ma ottengo il seguente errore (sto gia' utilizzando la mia chiave privata relativa alla pubblica che ho aggiunto nel portale interop)

```
{
   "correlationId":"db227979-f5bb-4c92-9889-4be73eeb8870",
   "errors":[
      {
         "code":"015-0008",
         "detail":"Unable to generate a token for the given request"
      }
   ],
   "status":400,
   "title":"The request contains bad syntax or cannot be fulfilled.",
   "type":"about:blank"
}
```

Potreste aiutarmi a capire dove sbaglio? Grazie

**Data e ora in cui si è riscontrato il problema**
es. 03/12/2024 h. 10:20

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Operatore API, Operatore di sicurezza

**Comment by FedericaSicchiero** [comment]
Buongiorno, mi può dire per quale ente e su quale e-service sta provando a staccare il token? Grazie

**Comment by valerio65xz** [comment]
Buongiorno, alla fine sono riuscito a risolvere qui. Chiudo il thread, grazie comunque per l'aiuto

https://github.com/italia/anpr/issues/4431#issuecomment-2514640526
