### ISSUE TITLE
Monitoraggio per l'erogatore dei dati delle richieste 

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#1018]
Buonasera, 
vorrei sapere se è previsto lo sviluppo di un cruscotto di monitoraggio sulla PDND che consenta all’erogatore di monitorare i dati  e lo stato delle richieste dei propri eservice.
In particolare sarebbe molto utile una funzionalità che conteggi il numero complessivo delle richieste autorizzate per ogni eservice in modo da  prevenire lo sforamento della soglia complessiva.
Grazie

**Comment by FedericaSicchiero** [comment]
Buonasera, 
al momento è disponibile un canale in pull attraverso il quale si può ottenere una lista di eventi tipo un e-service che viene sospeso, una richiesta di fruizione riattivata, ecc. (v. documentazione https://docs.pagopa.it/interoperabilita-1/manuale-operativo/api-esposte-da-pdnd-interoperabilita#endpoint-di-notifica-eventi).
È in programma per il prossimo futuro lo sviluppo di una notifica per la soglia delle chiamate API per avvisare il suo eventuale sforamento.

Una dashboard vera e propria per singolo fruitore non è al momento in programma, ma teniamo conto della segnalazione per eventuali sviluppi futuri, grazie.

**Comment by azabatta** [comment]
grazie
