### ISSUE TITLE
Domanda sul valore dell'attributo idANPR dello schema TipoIdentificativi - E-Service C015

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#102]
Buongiorno @azabatta,

avremmo bisogno di un charimento sul significato ed il valore che potrebbe avere l'attributo idANPR dello schema TipoIdentificativi.
Tale attributo rappresenta l'identificatrivo univoco di una occorrenza di anagrafica di persona fisica?
Il suo valore può essere alterato a seguito di aggiornamenti dei sui dati o rimane costante per tutto il cilco di vita? 

Restiamo in attesa di un cortese feedback.
Grazie della collaborazione.
Buon lavoro

**Comment by azabatta** [comment]
Buongiorno,
si tratta di un identificativo univoco di un  cittadino che  non muta con le variazioni anagrafiche.
Al momento non è ancora attivo.
Saluti

**Comment by giovannidenicola** [comment]
Grazie,

cosa intende per non attivo, in ambiente di test ci viene restituito durante le interrogazioni, in ambiente di produzione ciò non avviene?

Restiamo in attesa di un cortese feedback.
Grazie della collaborazione.
Buon lavoro

**Comment by azabatta** [comment]
Forse non stiamo parlando dello stesso campo.
Si riferisce al campo "idSchedaSoggettoANPR"? Se così fosse si tratta di un progressivo di ANPR, univoco per cittadino, presente nella sezione Generalità ed è sempre valorizzato.
Resto in attesa di un suo cortese riscontro.
Saluti

**Comment by ruggerocastagnola** [comment]
Chiudo per inattività. Se necessario, riapritela. Grazie mille
