### ISSUE TITLE
Modulo aggiunta / revoca Amministratore

### ISSUE THREAD

**Issue by pezz99** [pagopa/pdnd-interop-frontend#1020]
**Bug**
Nell'area riservata, al momento dell'aggiunta di un nuovo utente, non è più presente il bottone che porta al link per il download del modulo di revoca (o di aggiunta) di un amministratore.
Dal momento che la documentazione è stata aggiornata due giorni fa volevo chiedervi se le modalità sono cambiate nuovamente.

**Comportamento atteso**
Bottone con link al modulo di aggiunta / revoca di un amministratore 

codice IPA: c_c815

**Data e ora in cui si è riscontrato il problema**
es. 06/12/2024 h. 12:00

**Ambiente**
Area Riservata

**Quali permessi ha la tua utenza?**
Amministratore

**Comment by FedericaSicchiero** [comment]
Dovrebbe arrivare il file per la nomina direttamente alla PEC dell'ente per farlo firmare al Rappresentante legale. 
Se non vi arriva la PEC fatemi sapere che sento il team che si occupa dell'area riservata. Grazie

**Comment by pezz99** [comment]
Come avviene la richiesta? tramite una semplice pec da parte del comune?

**Comment by pezz99** [comment]
Sì sì, avevo letto la documentazione. Il problema è che non è più presente l'icona posizionata a destra per poter proseguire con la richiesta.

**Comment by FedericaSicchiero** [comment]
Perchè ora avviene tutto via PEC per PDND. 
Nel caso mi serve uno screen così lo passo al team di competenza perchè non seguiamo noi quella parte

**Comment by FedericaSicchiero** [comment]
Buongiorno, il team che gestisce i ruoli ha fatto rollback sul processo quindi la documentazione è stata aggiornata con quello da seguire attualmente. Grazie
