### ISSUE TITLE
piattaforma pdnd di produzione

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#103]
non mi fa scaricare l'interfaccia openapi di m2m.
a proposito mi ricordare l'url per richiamare i servizi?

**Comment by ruggerocastagnola** [comment]
Ciao Angelo,

grazie della segnalazione, trovato il bug. Allora, per sbloccarti subito:
- [questa](https://github.com/pagopa/interop-be-api-gateway/blob/1.0.x/src/main/resources/interface-specification.yml) è l'url del file OpenAPI;
- [questa](https://interop.selfcare.pagopa.it/api-gateway/1.0) è l'URL dell'API gateway per l'ambiente di sperimentazione (interop.selfcare.pagopa.it); nel caso tu stessi lavorando nel vecchio ambiente di test (cioè uat.gateway.test.pdnd-interop.pagopa.it), l'URL è [questa](https://uat.gateway.test.pdnd-interop.pagopa.it/api-gateway/0.1)

Grazie mille e a presto,

Ruggero

**Comment by amollicone1982** [comment]
Per la client assertion utilizziamo questa
https://interop.selfcare.pagopa.it/authorization-server/
o
https://interop.selfcare.pagopa.it/authorization-server/1.0?

**Comment by ruggerocastagnola** [comment]
Dovrebbe essere quella segnata sulla UI, chiedo conferma a @beetlecrunch così faccio anche un check che sia tutto in ordine

**Comment by beetlecrunch** [comment]
@amollicone1982 per effettuare lo generazione di un token va usata questa:

**Comment by amollicone1982** [comment]
e la risorsa è /as/token.oauth2?

**Comment by amollicone1982** [comment]
abbiamo fatto una chiamata alle 16:06 a https://uat.gateway.test.pdnd-interop.pagopa.it/authorization-server/token.oauth2 e otteniamo 400

**Comment by ruggerocastagnola** [comment]
Ciao Angelo, posso chiederti di condividerci, eventualmente per email, i dettagli della richiesta? L'errore in output è volutamente criptico per evitare di dare indizi ad un eventuale malintenzionato

**Comment by amollicone1982** [comment]
voi non siete in grado di vedere subito l'errore? è la prima chiamata che facciamo in ambiente di prod

**Comment by ruggerocastagnola** [comment]
Verifico internamente

**Comment by amollicone1982** [comment]
faccio la segnalazione anche perchè non siamo sicuri dell'aud visto che sul portale compare un aud sicuramente sbagliato

![image](https://user-images.githubusercontent.com/29304687/182634655-68b8b241-4e4d-40fa-a2a5-20ab0f94fd52.png)

**Comment by ruggerocastagnola** [comment]
Confermo, dai loro risulta sbagliata l'audience segnata sulla UI. Grazie mille della segnalazione, provvediamo a correggere. Quella corretta per quest'ambiente è `interop.selfcare.pagopa.it/client-assertion`.

**Comment by amollicone1982** [comment]
questa è quella che mi ha mandato stefano per mail:

Ciao Angelo,
ecco le informazione che hai richiesto:

- interop audience: [interop.selfcare.pagopa.it/m2m](http://interop.selfcare.pagopa.it/m2m)
- well-known: https://interop.selfcare.pagopa.it/.well-known/jwks.json

Resto a disposizione per chiarimenti.
Saluti,
Stefano

**Comment by amollicone1982** [comment]
quindi non m2m ma client-assertion finale?

**Comment by beetlecrunch** [comment]
> questa è quella che mi ha mandato stefano per mail:
> 
> Ciao Angelo, ecco le informazione che hai richiesto:
> 
> * interop audience: [interop.selfcare.pagopa.it/m2m](http://interop.selfcare.pagopa.it/m2m)
> * well-known: https://interop.selfcare.pagopa.it/.well-known/jwks.json
> 
> Resto a disposizione per chiarimenti. Saluti, Stefano

Ciao Angelo,
questa mail evidenziava l'aud contenuta nel token destinato al flusso m2m.

Se tu hai bisogno di ottenere un token da interop devi usare sempre l'aud per la client assertion, che in questo momento è effettivamente errato in UI.
Provvediamo a sistemarlo nel frattempo di riporto il suo valore corretto di seguito:

**Comment by amollicone1982** [comment]
Siamo riusciti ad ottenere il token ed a chiamarvi. Otteniamo 500 penso perché il purposeid che vi passiamo non esiste. Ve lo confermate?

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by beetlecrunch** [comment]
Se state cercando di contattare le nostre api, allora non è necessario il purposeId.
Il purposeId va utilizzato solo quando si spende il token presso un e-service di un servizio erogatore.
Mi confermi che state chiamando l'api-gateway?

**Comment by amollicone1982** [comment]
Stiamo chiamando api gateway. Mi pare che non l'abbiamo messo. Il motivo del 500 è che inseriamo un purposeid?

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by beetlecrunch** [comment]
Ok @amollicone1982 , ho verificato nei log.
Effettivamente la finalità che richiedete non esiste.
Va sicuramente tornato un 404 e non un 500.
Provvediamo al modificare il comportamento.

**Comment by amollicone1982** [comment]
Ok, grazie della collaborazione

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ruggerocastagnola** [comment]
Chiudo questa issue, per il valore errato dell'audience è stata rilasciata una fix in ambiente. Se ci sono ulteriori questioni, per favore riaprite
