### ISSUE TITLE
Mancata risposta di idANPR tramite C030 massivo a fronte di specifici codici fiscali

### ISSUE THREAD

**Issue by andrimega** [pagopa/pdnd-interop-frontend#1034]
Sto utilizzando il servizio C030 massivo ElabMassivaAccertIdUnicoNazionale in ambiente di collaudo e ho riscontrato un possibile bug. Il servizio risponde correttamente molto spesso, ma a fronte dell'invio di alcuni codici fiscali specifici ritorna una risposta successful ma con contenuto vuoto.

**Step per riprodurre il bug**
1. Inviare della lista di codici fiscali zippato e encodato
2. Attendere la fine dell'elaborazione
3. Scaricare l'output dell'elaborazione.

Non sembra ci sia alcuna correlazione tra i codici fiscali per i quali questo bug si presenta.
Per le richieste ho utilizzato il client Java da voi fornito.

**Comment by FedericaSicchiero** [comment]
Buonasera, per questa issue vi rimando direttamente alla repository ANPR https://github.com/italia/anpr/issues che vi può dare maggiori info. Essendo un servizio offerto da loro noi non abbiamo visibilità dei dati come piattaforma e possiamo aiutarvi solo nel caso di errore sui token staccati o problemi di piattaforma.
