### ISSUE TITLE
Errore voucher e-service consultazione Registro Imprese

### ISSUE THREAD

**Issue by giovanniverdesca** [pagopa/pdnd-interop-frontend#1036]
**Descrizione del problema**
E' stato creato un client per la fruizione del servizio consultazione Registro Imprese erogato da Unione Italiana delle Camere di Commercio Industria, Artigianato e Agricoltura. Inoltre è stato generato il voucher che è stato inserito come Authorization header nella chiamata al servizio. Otteniamo tuttavia il seguente errore: 401 Utente sconosciuto.

**Il codice IPA del tuo ente**
APMes

**Data e ora del tentativo**
11/12/2024 h. 10:23

**Ambiente**
Collaudo

**client_id**
a070f0e0-383c-4c28-a90b-713e98aadde3

**purposeId (solo per i client e-service)**
aeabd22d-f2f4-4584-a3a3-8834dbc82016

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad utilizzare il tool di debug della client assertion presente in piattaforma?

**Comment by giovanniverdesca** [comment]
Buongiorno, abbiamo utilizzato il tool di debug della client assertion e ci indica che la richiesta è valida ed è possibile ottenere un voucher per l'e-service.

**Comment by FedericaSicchiero** [comment]
Allora vuol dire che lato piattaforma funziona tutto e che bisogna sentire direttamente l'erogatore per capire come mai ricevete quell'errore. Potete trovare la mail di contatto all'interno dell'e-service che erogano
