### ISSUE TITLE
Chiave pubblica per verifica token

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#105]
Buongiorno, dove è possibile trovare la chiave pubblica per verificare la signature degli access token JWT generati dalla PDND?

Grazie,
Marco

**Comment by mrubiero** [comment]
Buondì Ruggero, 

grazie per la risposta e il link alla documentazione.

L'ambiente dove sto facendo dei test è quello di test/demo uat.gateway.test.pdnd-interop.pagopa.it dove provando a replicare il path del well known sembra non funzionare (404 dal reverse proxy); ho provato anche a  loggarmi e  controllare sulla scheda assistenza se fossero presenti link diversi alle chiavi ma non sono riuscito a trovarle.

Cambia qualcosa per questo ambiente o mi sono perso un pezzo?

Grazie per il supporto.

Marco

**Comment by ruggerocastagnola** [comment]
Buongiorno Marco,

ho capito, siete nell'ambiente di UAT che andrà verso la dismissione. Rispetto a quello attuale, è rimasto congelato alle feature di diverse settimane fa ed è possibile che alcune cose siano leggermente diverse da quello che c'è in guida. In caso non tornasse qualcosa, ti chiedo di aprire una issue qui che provvedo a darti supporto. In quell'ambiente l'indirizzo del well known è [questo](https://pdnd-interop-test-public.s3.eu-central-1.amazonaws.com/.well-known/jwks.json).

Per qualsiasi cosa, fammi sapere.

A presto

Ruggero
