### ISSUE TITLE
Attributi PDND e loro uso: esempi significativi

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#106]
Buongiorno,
per Città di Torino la partecipazione alla sperimentazione PDND significa, oltre ad effetture i test di chiamata, apprenderne meglio il funzionamento, anche per poterne diffondere la conoscenza all'interno dell'organizzazione. Da questo punto di vista abbiamo qualche difficoltà a spiegare ai colleghi l'uso degli attributi certificati, dichiarati, verificati. 
Qualcuno può suggerire esempi di specifici attributi che ne chiarisca l'uso?
Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, grazie mille per il feedback. Mi confronto internamente e torno con degli esempi pratici. Nel frattempo colgo l'occasione che abbiamo pubblicato una prima beta della [documentazione](https://docs.pagopa.it/interoperabilita-1/) a disposizione degli sperimentatori.

**Comment by ctamietti** [comment]
Buongiorno Ruggero,
grazie per le informazioni.

In attesa delle informazioni sull'uso degli attributi, propongo un primissimo feedback sulla documentazione relativa a PDND da te linkata: nel paragrafo relativo alla 'Richiesta di fruizione' (ma mi pare anche altrove) non si cita la necessità di siglare un 'Accordo di Interoperabilità', a differenza di quanto invece viene indicato nelle Linee Guida PDND su docs.italia.it ( https://docs.italia.it/AgID/documenti-in-consultazione/lg-pdnd-docs/it/bozza/doc/02_Allegato%202/04_stipula-accordi.html . 

Questo perciò mi porta ad una seconda domanda: la richiesta di fruizione ( https://docs.pagopa.it/interoperabilita-1/manuale-operativo/richieste-di-fruizione ) sostituisce 'in toto' la redazione di un accordo di Interoperabilità oppure quest'ultima azione, ed in particolare lo scambio di un documento di accordo tra fruitore ed erogatore è comunque necessaria?

Se preferite posso aprire un issue specifico per questa seconda domanda.

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Grazie, sì, se è possibile creare una nuova issue meglio, mi agevola nel lavoro di tracciamento attività. Ma in sostanza sì, le richieste rimpiazzano in toto gli accordi

**Comment by ctamietti** [comment]
Va bene, grazie; apo subito altra issue ..

**Comment by ruggerocastagnola** [comment]
Ciao Corrado,

anche qui grazie mille della domanda. Abbiamo aggiornato la [documentazione con un esempio](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/attributi#un-esempio-di-utilizzo-degli-attributi). Vista la complessità degli attributi, abbiamo colto l'occasione per scorporare la logica degli attributi e dedicarle uno spazio.

Intanto chiudo l'issue, ma se vuoi dare un feedback sulla chiarezza della documentazione, riaprila ed è ovviamente il benvenuto. Aggiungeremo appena possibile anche alcuni screenshot dalla UI in modo da chiarire ulteriormente il processo.

Intanto grazie e a presto

Ruggero
