### ISSUE TITLE
Richiesta di fruizione PDND = Accordo di Interoperabilità?

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#107]
Buongiorno,

un primissimo feedback sulla documentazione relativa a PDND (https://docs.pagopa.it/interoperabilita-1/) : nel paragrafo relativo alla 'Richiesta di fruizione' (ma mi pare anche altrove) non si cita la necessità di siglare un 'Accordo di Interoperabilità', a differenza di quanto invece viene indicato nelle Linee Guida PDND su docs.italia.it ( https://docs.italia.it/AgID/documenti-in-consultazione/lg-pdnd-docs/it/bozza/doc/02_Allegato%202/04_stipula-accordi.html .

La richiesta di fruizione ( https://docs.pagopa.it/interoperabilita-1/manuale-operativo/richieste-di-fruizione ) sostituisce 'in toto' la redazione di un accordo di Interoperabilità oppure quest'ultima azione, ed in particolare lo scambio di un documento di accordo tra fruitore ed erogatore è comunque necessaria?

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, 

grazie mille della domanda, in effetti non è chiaro ed è importante disambiguare. Abbiamo aggiornato la documentazione aggiungendo una [FAQ dedicata](https://docs.pagopa.it/interoperabilita-1/faq/per-i-dpo#accordo-di-interoperabilita-o-richiesta-di-fruizione). Chiudo questa issue, per qualsiasi siamo a disposizione. 

A presto
Ruggero
