### ISSUE TITLE
PA Capofila: solo nello scenario di Erogazione?

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#108]
Buongiorno,
le LG PDND indicano che "Le pubbliche amministrazioni Erogatrici POSSONO delegare una o più Capofila tra quelle che si sono candidate a tal fine sull’Infrastruttura interoperabilità PDND".

Se una PA, ad esempio un piccolo comune, è solo Fruitrice non può dunque delegare a una PA Capofila? In caso positivo, questa scelta è legata al fatto che è stato ritenuto che i delegati non debbano poter gestire anche le parti private del materiale crittografico dei deleganti?

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Ciao Corrado, questa settimana siamo a forze ridotte e ho bisogno un confronto interno per sapere se dico sciocchezze. Così a naso posso risponderti che quella dei capofila, anche se prevista, è una feature che non abbiamo ancora preso in carico a livello implementativo, dunque non abbiamo ancora ragionato sulle possibili ramificazioni pratiche. Onestamente un meccanismo di delega lato fruitore non mi suona nuovo, però faccio un approfondimento prima di rispondere. Anche se non è del tutto esatto, taggo questa issue come "feature request"

**Comment by ctamietti** [comment]
Ciao Ruggero,
va benissimo; se vi servono degli approfondimenti fatemi sapere; attendo le vostre indicazioni.
Ciao,
Corrado

**Comment by marcocipri** [comment]
Buongiorno,
la funzione di capofila è in via di analisi con l'obiettivo di venire implementata nel corso del 2023.
