### ISSUE TITLE
Dubbio su stima di carico nella finalità

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#109]
Buon pomeriggio, 
mi è venuto un dubbio relativo alla stima di carico dichiarata nelle finalità; spero non sia troppo banale:
- il n°  indicato nelle finalità è da riferire alle chiamate verso l'API esposta dall'Erogatore oppure a quelle verso PDND per l'ottenimento del voucher?
- l'enforcement della policy di limitazione del numero di chiamate nell'unità di tempo è attuata da PDND o è di esclusiva responsabilità dell'Erogatore?

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado,

mi scuso per il ritardo, mi ero perso la notifica, colpa mia. Dunque:
- il numero della stima di carico è rispetto all'API dell'Erogatore;
- in questo momento non è emersa una linea guida chiara per l'enforcement. Sicuramente di fondo ci si appoggia al fair use da parte dei fruitori ma è un tema sul quale dobbiamo ancora fare approfondimenti, anche alla luce delle proposte e dei suggerimenti che ci arrivano.

Grazie mille e a presto

Ruggero

**Comment by ctamietti** [comment]
Anch'io mi scuso pe ril ritardo;
grazie delle informazioni; per favore teneteci informati sul meccanismo di enforcement.
Se volete possiamo chiudere questo issue.

Cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Grazie, chiudo io e sì, seguiranno aggiornamenti. Credo ci vorrà tempo perché non è una tematica semplice. Un saluto!
