### ISSUE TITLE
Variazione Provincia Comune di nascita Persona Fisica - ANPR

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#111]
Salve,

nel caso in cui, nel tempo, la provincia del comune di nascita subisca una variazione, tale evento sarà gestito da ANPR? (Es. Nel 2009 i comuni Busnago, Caponago, Cornate d'Adda, Lentate sul Seveso e Roncello sono passati dalla provincia di Milano alla provincia di Monza e della Brianza).

Grazie

**Comment by ruggerocastagnola** [comment]
Buongiorno Giovanni, chiedo supporto ad @azabatta o ad @amollicone1982 che immagino possano avere la risposta per questi servizi

**Comment by azabatta** [comment]
Buongiorno,
certo, le variazioni che riguardano i comuni devono essere necessariamente gestite da ANPR. Il punto di innesco è costituito dagli aggiornamenti "ufficializzati" da ISTAT. 
In generale, sempre in base ai dati di ISTAT, ANPR gestisce lo storico dei comuni (accorpamenti, soppressioni, cambio di denominazione etc.) al fine di continuare a gestire correttamente gli eventi anagrafici (es. comune di nascita che resta ovviamente quello valido alla data di nascita anche se il comune viene soppresso).
Saluti

**Comment by giovannidenicola** [comment]
Grazie per la risposta.
