### ISSUE TITLE
Gestione Provincia Nascita Comuni Istriani - ANPR

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#112]
Salve,

per il caso di persone fisiche nate nei comuni Istriani: province PL (Pola), FU (Fiume), ZA (Zara), etc..
La persona fisica è considerata nata in Italia oppure all'estero?

Grazie

**Comment by ruggerocastagnola** [comment]
Buongiorno Giovanni, in questo caso fa riferimento ai servizi di ANPR? Così so come smistare la richiesta

**Comment by giovannidenicola** [comment]
Si, mi riferisco ai servizi ANPR, scusate per l'omissione.

**Comment by ruggerocastagnola** [comment]
Buongiorno Giovanni, mi scuso per l'enorme ritardo. Anche qui chiedo supporto ad @azabatta o ad @amollicone1982 che immagino possano avere la risposta per questi servizi

**Comment by azabatta** [comment]
Buongiorno,
per questi cittadini la discriminante è la data di nascita: se il cittadino è nato quando i comuni citati facevano parte del territorio italiano risulteranno nati in un comune italiano. Quelli nati successivamente risulteranno nati in uno stato estero (i cittadini nati all'estero non hanno il comune di nascita ma lo stato di nascita, il comune potrebbe essere presente come dato aggiuntivo).

**Comment by giovannidenicola** [comment]
Grazie mille per la risposta
