### ISSUE TITLE
Richiesta casi di test per integrazione ANPR

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#118]
Salve,

ai fini dell'integrazione con gli e-service di ANRP C015 e C020 avremmo bisogno dei seguenti casi di test:
- codice fiscale e dati generalità di una persona fisica deceduta
- codice fiscale e dati generalità di una persona con carattere diacritico nel nome o nel cognome
- codice fiscale e dati generalità di una persona con lunghezza del nome maggiore di 35 caratteri
- codice fiscale e dati generalità di una persona con lunghezza del cognnome maggiore di 35 caratteri

Restriamo in attesa di un cortese feedback.
Grazie per la collaborazione.

**Comment by ruggerocastagnola** [comment]
Buongiorno Giovanni, anche qui chiedo supporto ad @azabatta o ad @amollicone1982 che immagino possano avere la risposta per questi servizi

**Comment by amollicone1982** [comment]
codice fiscale e dati generalità di una persona fisica deceduta -> HBRHSL16R21A509C
    codice fiscale e dati generalità di una persona con carattere diacritico nel nome o nel cognome -> HBRCST62S11Z112Q
    codice fiscale e dati generalità di una persona con lunghezza del nome maggiore di 35 caratteri -> BRTLRD10T25Z114N
    codice fiscale e dati generalità di una persona con lunghezza del cognnome maggiore di 35 caratteri -> PCCDLL72L48Z614U

**Comment by giovannidenicola** [comment]
Grazie per la risposta.
