### ISSUE TITLE
e-Service attivabile mostra il messaggio "Il tuo ente non ha gli attributi certificati necessari per iscriversi"

### ISSUE THREAD

**Issue by riccafi** [pagopa/pdnd-interop-frontend#122]
**Descrivi il bug**
e-Service attivabile mostra il messaggio "Il tuo ente non ha gli attributi certificati necessari per iscriversi" nonostante si operi per un ente che risulta conforme agli attributi richiesti dall'e-Service.

**Step per riprodurre il bug**
1. Accedere al catalogo degli e-Service sulla piattaforma di esercizio
2. Ispezionare l'e-Service Consultazione ISEE - v1
3. Sebbene si operi per un Comune e tra gli attributi certificati alternativi risulti presente "Comuni e loro Consorzi e Associazioni", compare il messaggio "Il tuo ente non ha gli attributi certificati necessari per iscriversi". Non sono presenti altri attributi dichiarati o verificati richiesti.

**Comportamento atteso**
Che l'e-Service fosse attivabile da parte del Comune.

**Ambiente:**
 - OS: Ubuntu
 - Browser Chrome

**Comment by riccafi** [comment]
![Schermata da 2022-09-19 12-57-24](https://user-images.githubusercontent.com/66056766/191909285-2bd4e15f-5be3-4ff7-8574-91380bf9d3f9.png)
![Schermata da 2022-09-19 12-57-28](https://user-images.githubusercontent.com/66056766/191909288-e312d287-862f-429e-84e8-ccedf865697a.png)

**Comment by ruggerocastagnola** [comment]
Buongiorno, posso chiedere cortesemente per quale ente sta provando a fare l'iscrizione all'e-service?

**Comment by riccafi** [comment]
Salve, l'ente di riferimento è il Comune di Firenze

**Comment by ruggerocastagnola** [comment]
Grazie, facciamo una verifica

**Comment by ruggerocastagnola** [comment]
Buongiorno Riccardo, ok, abbiamo trovato. 

C'è effettivamente un bug ma abbiamo riscontrato che la richiesta di iscrizione di cui parla è partita da un'utenza con permessi da "operatore di sicurezza", non autorizzata a farla. Quindi anche risolvendo il bug che lei ha riscontrato, quell'utenza non potrebbe comunque effettuare l'iscrizione al servizio. Se provate a farla con un'utenza admin, dovrebbe andare a buon fine. Mi faccia sapere!
