### ISSUE TITLE
Anomalia approvazione

### ISSUE THREAD

**Issue by ValentinaIdromela12** [pagopa/pdnd-interop-frontend#129]
**Descrivi il bug**
Nonostante tutti gli attributi siano stati verificati, la piattaforma PDND non consente di approvare la richiesta di fruizione da parte di un comune e chiede la verificare nuovamente gli attributi.

**Step per riprodurre il bug**
1. Vai su 'Verifica nuovamente'
2. Clicca su 'Attiva'
3. Vedi l'errore "Non è stato possibile attivare la richiesta. Accertarsi che tutti gli attributi siano stati verificati e riprovare"

**Comportamento atteso**
Cosa ti aspetteresti?  
A seguito della verifica degli attributi la richiesta di fruizione dovrebbe essere approvata.  

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Ambiente:**
 - OS: [es. macOS Big Sur]
 - Browser [es. chrome, safari]
 - Version [es. 99.0.4844.51 (Official Build) (x86_64)]

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by ValentinaIdromela12** [comment]
Buongiorno,
l'URL è il seguente: https://interop.selfcare.pagopa.it/ui/it/erogazione/richieste

**Comment by ruggerocastagnola** [comment]
Buon pomeriggio, non ho scritto immediatamente ma confermo che abbiamo preso in carico l'attività e stiamo facendo una verifica

**Comment by ValentinaIdromela12** [comment]
Buongiorno, ci sono novità sul problema segnalato? Ad oggi la piattaforma non consente di approvare la richiesta di fruizione nonostante la verifica degli attributi.

**Comment by beetlecrunch** [comment]
Buongiorno, abbiamo individuato l'anomalia.
Il rilascio della fix è previsto per lunedì 17/10.

**Comment by ruggerocastagnola** [comment]
Il fix è stato rilasciato e testato lunedì 17, chiudo quest'issue. In caso di problemi si può riaprire senza problemi
