### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by mfortini** [pagopa/pdnd-interop-frontend#131]
* I link nel footer sono in realtà dei "button", sarebbe più semplice se fossero dei link veri e propri
* Manca la dichiarazione di accessibilità
* Mancano le Note Legali
* I Termini e Condizioni fanno riferimento a www.pagopa.it
* Il bottone "Diritto alla protezione dei dati personali" rimanda a una form che non è molto immediata da capire

**Comment by ruggerocastagnola** [comment]
Ciao Matteo, grazie per il feedback, provo a rispondere a tutto. Dunque:
- la documentazione è stata ultimata e inserita ma non deployata negli ambienti disponibili all'esterno, andrà su con i rilasci dei prossimi giorni; manca un aggiornamento alla dichiarazione di accessibilità che arriverà comunque nella seconda metà della settimana, ed è parte di una checklist di controllo per il rilascio
- quella dei button è una necessità aziendale su componenti comuni e per il momento non è rilavorabile. Sempre nella checklist ho un punto di attenzione per assicurarmi che gli aria siano correttamente impostati per evitare problemi di accessibilità
- grazie anche per il feedback sulla form di "Diritto alla protezione dei dati personali". Se hai punti specifici li riporto all'interno. È una form prodotta e utilizzata su tutti i prodotti a livello aziendale e c'è una pipeline di controllo e approvazione per eventuali modifiche

**Comment by ruggerocastagnola** [comment]
Ciao Matteo, intanto chiudo quest'issue per pulizia. Se ci sono feedback puntuali sul Diritto alla protezione dei dati personali, possiamo usare il processo condiviso tra PagoPA e il DTD per definire le priorità in modo da non perderci niente
