### ISSUE TITLE
Anomalia durante la generazione dell'access token ambiente pdnd test

### ISSUE THREAD

**Issue by EmaPace** [pagopa/pdnd-interop-frontend#132]
Buongiorno,

Abbiamo integrato, per conto del Ministero dei Trasporti e delle mobilità sostenibili, in ambiente di test pdnd, gli eService C015 e C020, pe rla verifica delle generalità e residenza e stiamo riscontrando, da qualche giorno, delle anomalie sulla generazione dell'access token.

questa è la risposta che riceviamo

400 Bad Request: [{"errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}]

il comportamento è randomico e non riusciamo a capirne la  motivazione

Di seguito una client assertion che ha generato l'errore

client id: 350e7ccf-34f5-4c64-a7d7-b527f2152371
url auth: https://uat.gateway.test.pdnd-interop.pagopa.it/authorization-server/token.oauth2

client assertion:
eyJraWQiOiJGVTV1UU9wM3d5Mk9SRU0xTGhpcUxDSEI0N01EbnlSMF92YllCUDFjZGRZIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJzdWIiOiIzNTBlN2NjZi0zNGY1LTRjNjQtYTdkNy1iNTI3ZjIxNTIzNzEiLCJhdWQiOiJ0ZXN0LmludGVyb3AucGFnb3BhLml0L2NsaWVudC1hc3NlcnRpb24iLCJpc3MiOiIzNTBlN2NjZi0zNGY1LTRjNjQtYTdkNy1iNTI3ZjIxNTIzNzEiLCJwdXJwb3NlSWQiOiJiN2YyOGIwYy1iNjRkLTQzMDgtOGJiMi0wMTY2YTI3MmY2NWEiLCJleHAiOjE2NjU0MDAyODkwODEsImlhdCI6MTY2NTM5MzA4OTA4MSwianRpIjoiYTg4OGU0YzItMjMwYi00YjkxLWIzOTItOTM1OWQyY2VmZDJhIn0.BZfPQbZBmnR_snvFU-RSYAJc_QG94yoMSB5ZBR8b2BnfmL44AXi0i-SgLQ4JK_LihikNe3zzkcpXJObHIvc13SigUkjTg6CUZLqK0jitwgSlpKmDZ46PtrbRrWCo7tPeE4GndDnJ_VuaDCtzPi83ZLltfvErJtIKAjrdPSP775camHAN_ymPLE4MewrSu-j19HU0_ztFIx2BAye6NzqWqWSnRV65NLOgWbcMIqRlvzvrsWh5RHvSy714pmbrVEI63eBAyyV6m1gs09VqHZa1Ehxqo2yOawsu6D477uJTT3-aOGN5tT_Bqlbll3lgQeQ6uZeWlhpn3BY9r7RHV59pQQ

Grazie per il supporto

**Comment by ruggerocastagnola** [comment]
Buonasera, le anomalie dovrebbero essere state risolte al completamento delle operazioni di messa in esercizio, ma se emergessero nuove criticità, la prego di aprire una nuova issue. Intanto chiudo questa
