### ISSUE TITLE
Lista dei client e finalità archiviate

### ISSUE THREAD

**Issue by mfortini** [pagopa/pdnd-interop-frontend#136]
La lista dei client mostra anche le associazioni dei client a Finalità archiviate e sostituite e la cosa può trarre in inganno se la Finalità mantiene la denominazione.

**Comment by ruggerocastagnola** [comment]
Ciao Matteo, perdona l'enorme ritardo, ora che la situazione si è stabilizzata ripulisco la board. Grazie mille del feedback, ho inserito questa verifica come bug nel nostro backlog interno, intanto chiudo questa issue per pulizia
