### ISSUE TITLE
Impossibile recuperare l'analisi del rischio inserita

### ISSUE THREAD

**Issue by mfortini** [pagopa/pdnd-interop-frontend#137]
Non si vede l’analisi del rischio inserita. Come si fa a controllarla per poi eventualmente, se serve, modificarla?

**Comment by ruggerocastagnola** [comment]
Ciao Matteo, perdona, non ti avevo risposto i giorni del go live e quest'issue è andata in stale. La chiudo, ma se riemergesse la necessità si può riaprire. 

Grazie e a presto, 
Ruggero
