### ISSUE TITLE
🚨 [Maintenance]

### ISSUE THREAD

**Issue by ruggerocastagnola** [pagopa/pdnd-interop-frontend#141]
# Activity window
Per gli aggiornamenti e adeguamenti legati all'entrata in esercizio di Interoperabilità, gli ambienti di test e sperimentazione saranno a tratti instabili o offline. Ci scusiamo per il disagio

### data di fine prevista: 17/10/2022

**Comment by mrubiero** [comment]
Buondì, l'ambiente di test è ancora sotto aggiornamenti/adeguamenti?

Grazie,
Marco

**Comment by ruggerocastagnola** [comment]
Buongiorno Marco, mi scuso per il ritardo. Abbiamo avuto necessità di fare ulteriori adeguamenti ma da ieri sia l'ambiente di test che di produzione sono stabili e pubblicati. Chiudo l'issue di maintenance
