### ISSUE TITLE
Impossibile creare un e-service

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#166]
Buondì,
accedendo al portale di TEST (https://uat.selfcare.pagopa.it/) e provando a creare un e-service, dopo aver compilato i campi nome e descrizione obbligatori, non sembra possibile avanzare allo step successivo in quando premendo il pulsante per avanzare viene segnalato un errore.
L'eventuale aggiunta di uno o più attributi all'e-service non sembra cambiarne il comportamento.

Analizzando la chiamata fatta verso il backend si nota lo status code http 400 sulla stessa.

Grazie,
Marco

**Comment by ruggerocastagnola** [comment]
Buongiorno Marco, l'ambiente dovrebbe essere stabile e lato mio riesco a creare un e-service correttamente. Riscontra ancora l'errore?
