### ISSUE TITLE
Impossibile accedere all'Interoperabilitá su ambiente di TEST

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#168]
Buondì,
accedendo al portale di TEST (https://uat.selfcare.pagopa.it/), dopo aver fatto login e autorizzato l’utilizzo dei dati
![image](https://user-images.githubusercontent.com/9409505/196484351-0db7a8bb-911a-4c97-a49d-ec1e56a41dab.png)
e selezionato l’ente
![image](https://user-images.githubusercontent.com/9409505/196484395-5b5354fe-0179-4ac2-a854-ab10161197c1.png)
andando a cliccare o sul pulsante Gestisci su Interoperabilitá o oppure selezionando la stessa voce dal menù a tendina in alto a sx (come evidenziato sullo screenshot)
![image](https://user-images.githubusercontent.com/9409505/196484489-be40b5ac-d394-4a00-b1e6-5fdca5fa0819.png)
e selezionando l’ambiente di Test
![image](https://user-images.githubusercontent.com/9409505/196484611-8e77b782-ef80-4706-a765-5ac7d4671431.png)
si viene redirezionati sulla pagina precedente di selezione dell’ ente impedendo l’ accesso all’Interoperabilitá.

Grazie,
Marco

**Comment by ruggerocastagnola** [comment]
Buongiorno Marco, la configurazione dovrebbe essere a posto, e riesco ad accedere all'ambiente di test correttamente. Riscontra ancora il problema?

**Comment by mrubiero** [comment]
Buongiorno Ruggero, 
sì sembra verificarsi ancora. 
È scomparso il pulsante "Collaudo" tra gli ambienti ma l'accesso a Test non funziona con il redirect alla pagina precedente mentre l'accesso a Produzione funziona correttamente.

Se può essere utile ho notato che per TEST tra le chiamate fatte dal frontend verso il BFF una è in http status code 500 https://selfcare.dev.interop.pagopa.it/backend-for-frontend/0.0/session/tokens ; la stessa chiamata accedendo a Produzione va in 200.

Marco

**Comment by mrubiero** [comment]
Buongiorno Ruggero, i test precedenti sono stati fatti sempre con cache pulita. 
Ho rifatto oggi una login, sempre in incognito, ma il problema sembra essere lo stesso. Ho fatto fare lo stesso test su un'altra macchina mai acceduta al sito da un collega, in incognito per ulteriore precauzione, ma si ripete la problematica del redirect.

Il tema potrebbe essere sulle utenze che utilizziamo? Sono quelle portate da vecchio ambiente Demo/UAT https://uat-idp.gateway.test.pdnd-interop.pagopa.it

Sono a disposizione per qualunque tipo di test.

Marco

**Comment by ruggerocastagnola** [comment]
Grazie mille per le nuove indicazioni e mi spiace per il problema, verifichiamo e riporto indietro non appena ho novità

**Comment by ruggerocastagnola** [comment]
Buonasera Marco, credo di aver capito cosa è successo. Il punto è che sia l'ambiente di test che quello di produzione sono disponibili attraverso la login su https://selfcare.pagopa.it previa adesione dell'ente. C'è un'unica login per entrambe gli ambienti. La ragione è che così l'ente può firmare un solo contratto per avere a disposizione entrambi gli ambienti a regime normale (il regime di sperimentazione è finito questo lunedì con il rilascio di produzione).

L'ambiente a cui sta tentando di accedere lei (quello a cui si accede attraverso l'entry point https://uat.selfcare.pagopa.it) è quello usato solo per fini interni alla nostra azienda e non può essere utilizzato dall'esterno, per cui viene correttamente estromesso all'atterraggio sul prodotto.

**Comment by mrubiero** [comment]
Buonasera, ok grazie per il chiarimento.  Stiamo sbrigando le pratiche per l'accesso all'ambiente https://selfcare.pagopa.it/ , appena avremo le credenziali aggiorno la issue se abbiamo altri problemi di accesso.

Grazie per il supporto,
Marco
