### ISSUE TITLE
e-Service "Verifica Booleana CodiceFiscale" non più disponibile su Prod/Esercizio

### ISSUE THREAD

**Issue by riccafi** [pagopa/pdnd-interop-frontend#174]
**Descrivi il bug**
Accedendo come operatore di sicurezza alla piattaforma di esercizio, non è più visibile nel catalogo l'e-Service "Verifica Booleana CodiceFiscale"

**Step per riprodurre il bug**
1. Vai su Fruizione e poi su Catalogo e-Service
2. Sono visibili solamente e-Service di Ministero dell'Interno e INPS

**Comportamento atteso**
Vedere l'e-Service "Verifica Booleana CodiceFiscale"

**Ambiente:**
 - OS: Ubuntu Linux
 - Browser Chrome

**Comment by ruggerocastagnola** [comment]
Buonasera, grazie mille della segnalazione. Faccio una verifica interna e torno con aggiornamenti

**Comment by ruggerocastagnola** [comment]
Da una rapida verifica risulta che AdE abbia portato l'e-service in stato "sospeso", e dunque in questo momento non è più disponibile sul catalogo per nuove iscrizioni fino a che non verrà riattivato

**Comment by riccafi** [comment]
Ma quindi noi come Comune di Firenze, dovremmo avere comunque l'e-service in erogazione attivo, vero?

**Comment by riccafi** [comment]
avevamo infatti già l'e-Service in fruizione

**Comment by ruggerocastagnola** [comment]
Se l'erogatore sospende l'e-service è sospeso per tutti i fruitori, inclusi quelli che avevano già attivato una richiesta di fruizione, come indicato nel [manuale operativo](https://docs.pagopa.it/interoperabilita-1/funzionamento-generale#operativita-e-sospensioni-dei-servizi). Stiamo finalizzando l'implementazione della mail di contatto, in modo che gli enti abbiano a disposizione un canale diretto tra loro. A regime normale un ente non dovrebbe mai sospendere un e-service senza darne comunicazione preventiva. Onestamente non so se questa circostanza eccezionale dipenda da adeguamenti necessari all'erogatore nel passaggio dalla sperimentazione alla messa in esercizio

**Comment by riccafi** [comment]
Bene, grazie per la spiegazione, attendiamo allora che l'erogatore riattivi l'e-service.  
Effettivamente una comunicazione preventiva potrebbe aiutare ad evitare disservizi non previsti per gli utilizzatori finali di servizi costruiti sopra agli e-service.
