### ISSUE TITLE
Generazione access token in ambiente di test: rilevato disallineamento con indicazioni nel documento "PDND-Interop tech V 4.2.pdf"

### ISSUE THREAD

**Issue by fontanels** [pagopa/pdnd-interop-frontend#176]
Buonasera,
abbiamo rilevato, in fase di sperimentazione, un disallineamento tra alcune indicazioni nel documento PDND-Interop tech V 4.2.pdf e il comportamento dell'authorization server di PDND per il rilascio  dell'access token:

- nell'esempio “curl” di "Access Token Request" a pagina 14 si esplicita il passaggio di "resource=https://erogatore.example/v1". Nell'esempio di chiamata suggerita all'Operatore di Sicurezza nel portale PDND non è presente e quindi lo abbiamo omesso anche nel nostro client (Postman + script di pre-request). 
- nell'esempio di client_assertion a pagina 15, viene riportata la presenza dell'attributo "nbf" con valore pari a “iat”. Ma, nell'esempio che si può generare usando lo script python fornito da portale PDND all'Operatore di Sicurezza, questo attributo non è presente. Se viene passato nel nostro client, seguendo le indicazioni del documento, questo determina un messaggio di errore da parte dell'Authorization  Server. Omettendolo dal client siamo riusciti ad ottenere l'access token. Chiediamo conferma su quale sia lato client il comportamento corretto, tenendo conto dell’impatto, in termini di sicurezza, della mancata valorizzazione di questo attributo.

**Comment by fontanels** [comment]
Buonasera, come ho indicato sulla descrizione della issue le indicazioni nel "backoffice all'operatore sicurezza" ci risultano corrette.Il documento invece l'abbiamo ricevuto a Settembre 2022 ma nella testata si riporta "v 4.2, pubblicato 25-07-2022.". 

La segnalazione corrente è appunto sul documento di quella versione, ma se ne esiste una più recente e corretta chiederemo di averne copia.

Se invece è un documento superato, faremo riferimento a quanto presente nel backoffice (che presuppone un accesso alla piattaforma) e quanto accessibile via web nel manuale operativo. 
Grazie

**Comment by ruggerocastagnola** [comment]
Confermo che il documento è superato e fanno fede back office e la documentazione indicata. Può darmi la url dell'ambiente sul quale sta operando? Così capisco se servono indicazioni aggiuntive

Un saluto
Ruggero

**Comment by fontanels** [comment]
Abbiamo sperimentato ad Ottobre l'integrazione nell'ambiente di test e rilevato il disallineamento tra quando suggerito nel documento e quanto indicato in backoffice e il comportamento del sistema.

https://uat.gateway.test.pdnd-interop.pagopa.it/authorization-server/token.oauth2

Per quanto mi riguarda, la issue si può chiudere avendo ricevuto già indicazione che il documento è superato.
Grazie
