### ISSUE TITLE
Impossibile accedere a https://uat.gateway.test.pdnd-interop.pagopa.it/ui/it/fruizione/catalogo-e-service

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#183]
Buongiorno,

provando ad accedere alla url: 

https://uat.gateway.test.pdnd-interop.pagopa.it/ui/it/fruizione/catalogo-e-service

si ottiene un errore  'certificato scaduto' ancor prima di poter effettuare il login; ci aiutate a capire quale è il problema per favore?

Grazie e buona giornata,
Corrado Tamietti
CSI Piemonte

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, grazie per la segnalazione, facciamo una verifica interna

**Comment by ctamietti** [comment]
Buon pomeriggio,
siamo in attesa di feedback .. avete avuto modo di fare qualche verifica?

Grazie e cordiali saluti,
Corrado Tamietti
CSI Piemonte

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, mi scuso molto per il ritardo, è servito tempo ma l'ambiente è stato ripristinato. Ho fatto una prova d'accesso e riesco a entrare correttamente. Segnalo che questo ambiente andrà in dismissione e l'ambiente per testare sarà quello gemello di quello di produzione, al quale si può accedere attraverso [Area Riservata](https://selfcare.pagopa.it). Per qualsiasi cosa sono a disposizione

**Comment by marcocipri** [comment]
Buongiorno,
l'ambiente è di nuovo operativo.

**Comment by ctamietti** [comment]
Grazie Ruggero e ma

**Comment by ctamietti** [comment]
Grazie Riggero e Marco.
Buon pomeriggio.

Corrado Tamietti
