### ISSUE TITLE
Tipo utente

### ISSUE THREAD

**Issue by marcob71** [pagopa/pdnd-interop-frontend#189]
Buongiorno,
ci siamo accreditati come Comune e stiamo procedendo con i test di adesione ai servizi come fruitori.
Ho notato che per iscriversi ad un servizio non è possibile farlo se il profilo è 'operatore api' o 'operatore sicurezza' ma solo se si è amministratori. Non ci risulta però che sia possibile assegnare tale ruolo ad un nuovo utente iscritto.
Questo ci complica molto il alvoro perchè di fatto al momento risulta con il ruolo amministratore solo chi ha proceduto all'adesione della piattaforma. Potete darci riscontro?

grazie
Marco

**Comment by marcocipri** [comment]
La funzione di adesione di un nuovo utente Delegato è in corso di realizzazione.
Nel frattempo è possibile compilare i documenti in allegato e inviarli firmati dal rappresentante legale dalla casella PEC dichiarata in IPA dell'ente. 

[Nomina Operatore Amministrativo_PDND.docx](https://github.com/pagopa/pdnd-interop-frontend/files/10070250/Nomina.Operatore.Amministrativo_PDND.docx)
[Revoca Operatore Amministativo_PDND.docx](https://github.com/pagopa/pdnd-interop-frontend/files/10070251/Revoca.Operatore.Amministativo_PDND.docx)
