### ISSUE TITLE
Impossibile generare un token per la richiesta (Unable to generate a token for the given request)

### ISSUE THREAD

**Issue by fabiologiudice** [pagopa/pdnd-interop-frontend#191]
Sto cercando di realizzare un connettore verso uno dei servizi esposto da INPS, per la precisione il servizio di consultazione della attestazioni ISEE.
Abbiamo già definito una nuova finalità (che risulta ancora in attesa di valuatazione) e associato ad essa un nuovo client.
Seguendo però le indicazioni delle video guide..ho cercato di generare il token dopo aver creato con successo l'asserzione, ma ottendo l'errore di seguito indicato.

{"errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

Rimetto di seguito la richiesta che ho provato a fare con quello che era l'asserzione creata.

curl --location --request POST [https://auth.interop.pagopa.it/token.oauth2](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fauth.interop.pagopa.it%2Ftoken.oauth2&data=05%7C01%7C%7C2bc46bd886b04570c83108dac94c0b2f%7C998142c0c15a4dc5961d142e4aa199fb%7C0%7C0%7C638043625692108273%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3PoQQg5OPBP76HF9pW4AGbPOEO1eQ4Ml9MHxNQxGzNI%3D&reserved=0) --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=1b8d5896-1afa-4b33-8e10-bc2aaea3c705' --data-urlencode 'client_assertion=**MIA_ASSERZIONE**' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'grant_type=client_credentials'

**Comment by beetlecrunch** [comment]
Buongiorno,
ci risulta che la finalità connessa al client sia in attesa di approvazione da parte dell'erogatore.
Per questa ragione non è possibile ottenere un token.

A disposizione per chiarimenti.

**Comment by fabiologiudice** [comment]
Come mai ci sono tempi così lunghi per l'attivazione di una finalità?



____________________________________
Dr. Fabio Lo Giudice
Responsabile P.O. Progetti Innovativi dei Sistemi Informativi
Servizio Gestione Infrastrutture Tecnologiche
Direzione Sistemi Informativi
Comune di Firenze

Tel:        055/3283831
Mobile:  329/9019762
Fax:       055/3283823

Certificates:
- RedHat RHCE 804006930719990
- Microsoft MCP (70-294 MCPID: 3837072)
________________________________
Da: Stefano Perazzolo ***@***.***>
Inviato: mercoledì 23 novembre 2022 09:39
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Lo Giudice Fabio ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] Impossibile generare un token per la richiesta (Unable to generate a token for the given request) (Issue #191)


Buongiorno,
ci risulta che la finalità connessa al client sia in attesa di approvazione da parte dell'erogatore.
Per questa ragione non è possibile ottenere un token.

A disposizione per chiarimenti.

**Comment by marcocipri** [comment]
l'attivazione di una finalità dipende completamente dall'erogatore.
L'infrastruttura di iteroperabilità supporta questa operazione ma resta un processo gestito dall'Ente che è titolare del servizio e per eventuali ritardi va contattato l'Ente in questione.
