### ISSUE TITLE
Definizione user PDND: solo in fase di accerditamento

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#194]
Buongiorno,
apro questo issue per una semplice domanda: per uno user PDND con profilo admininstrator è possibile definire un altro user con lo stesso profilo anche dopo la conclusione della fase di acceditaento dell'ente?

Grazie e cordiali saluti,
Corrado Tamietti
CSI Piemonte

**Comment by FedericaSicchiero** [comment]
Buongiorno Corrado,
al momento non è possibile farlo dalla piattaforma ma stiamo implementando un nuovo processo che verrà allegato in fondo alla [Guida all'adesione](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione).
Chiediamo di tenere monitorata la pagina in quanto verrà aggiornata in tempi brevi proprio per rispondere a questa esigenza.

Grazie e buona giornata,
Federica Sicchiero

**Comment by ctamietti** [comment]
Va bene, grazie Federica.
Chiudo l'isuue ..
Cordiali saluti,
Corrado Tamietti
CSI Piemonte
