### ISSUE TITLE
non è possibile vedere i dettagli del servizio come operatore in ambiente di test

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [pagopa/pdnd-interop-frontend#199]
**Descrivi il bug**
accedendo a https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/client
entrando come operatore di sicurezza in modalità fruizione accedo al catologo servizi, non posso eseguire l'azione "ispeziona" il sistema mi restituisce l'errore:
Spiacenti
Si è verificato un errore temporaneo del server. Torna alla home.

**Step per riprodurre il bug**
1. Vai su 'Fruizione -> Catalogo e-service'
2. Clicca su 'service-catalogue, v. 1' -> ' ispeziona
3. Vedi l'errore

**Comportamento atteso**
vedere il dettaglio del servizio, con relativi YAML e documentazione

**Screenshot**
![image](https://user-images.githubusercontent.com/100349014/204506784-20ec00a9-4bb5-4388-bed7-5575945eae15.png)

**Ambiente:**
 - OS: Windows 10
 - Browser: chrome
 - Version 107.0.5304.121 (Build ufficiale) (a 64 bit)

**Note**

**Comment by ruggerocastagnola** [comment]
Buonasera Gianpaolo,

abbiamo preso in carico l'issue. Posso cortesemente chiedere qual è l'ente per il quale sta operando? Ci facilita nel debugging.

Un saluto

Ruggero

**Comment by gianpaolo-tndigit** [comment]
Buongiorno Ruggero,

grazie per aver preso in carico l'issue, l'Ente per il quale sto operando è: Provincia Autonoma di Trento

grazie e buon lavoro

**Comment by gianpaolo-tndigit** [comment]
Buongiorno Ruggero,

confermo che il problema è stato risolto, chiudo la issue. 

grazie 1000 e a presto
