### ISSUE TITLE
non recupero il token di accesso dalla piattaforma di TEST

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [pagopa/pdnd-interop-frontend#202]
**Descrivi il bug**
seguendo passo passo le "istruzioni ottenimento Access Token" riesco ad ottenere la Client assertion (creando l'enviroment con libreria jose ed eseguendo lo script python) una volta ottenuto tento di eseguire il comando CURL con l'assertion precedentemente ottenuta ma restituisce sempre lo stesso errore.

{"errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

**Step per riprodurre il bug**
1. Vai su 'https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/client/'
2. Clicca su 'Client assertion' 
3. Ottieni la client assertion
4. Clicca su avanti 'Access Token'
5. Utilizza la client assertion nella chiamata CURL al posto di 'LA_TUA_CLIENT_ASSERTION'
6. Effettua la chiamata CURL così modificata
7. Vedi l'errore

**Comportamento atteso**
un access token per effettuare le chiamate

**Il codice IPA del tuo ente**
p_TN 
PIVA 00337460224

**Data e ora in cui si è riscontrato il problema**
06/12/2022 h. 16:00

**Quali permessi ha la tua utenza?**
Operatore API

**Screenshot**
{"errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

**Note**
Tentata la chiamata sia cambiando gli apici con le virgolette ma il risultato non cambia (ottengo sempre lo stesso messaggio di errore)
Tentata la chiamata anche tramite POSTMAN ma il risultato non cambia (ottengo sempre lo stesso messaggio di errore)

**Comment by ruggerocastagnola** [comment]
Buonasera Gianpaolo, confermo che l'issue è stata presa in carico. Ancora per questa settimana potrebbe registrarsi qualche rallentamento nella risoluzione. Ad ogni modo, seguiranno aggiornamenti qui

**Comment by ruggerocastagnola** [comment]
Buonasera, è stato effettuato un controllo e non sembra essere un bug. Ad ogni modo, stiamo lavorando per migliorare la visibilità delle informazioni perché concordiamo che è poco chiaro. La finalità per la quale si sta provando a generare un token risulta "in attesa di approvazione" perché supera la soglia di carico imposta dall'erogatore. Finché la finalità non è attiva, la piattaforma si rifiuta di rilasciare un token.

L'e-service per il quale è stata creata la finalità è erogato sempre dal vostro ente?

**Comment by gianpaolo-tndigit** [comment]
Buonasera Ruggero, 
effettivamente non avevo capito che fosse questo il problema dal messaggio di errore pensavo fosse un problema del server.
Il servizio che abbiamo VCF1 - Verifica Booleana Codice Fiscale è attivato ma "in attesa di approvazione".
La motivazione non riesco a vederla dalla mia interfaccia e non vedo nemmeno lo stato di approvazione.
No l'e-service è erogato dalla Agenzia delle Entrate.

**Comment by gianpaolo-tndigit** [comment]
grazie Ruggero, 
invio subito una mail per il contatto.
buona giornata
