### ISSUE TITLE
Accesso al servizio INPS - ISEE su PDND di TEST

### ISSUE THREAD

**Issue by ComuneGenova** [pagopa/pdnd-interop-frontend#214]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Mancato accesso al servizio INPS ISEE**
Dopo aver generato il JWS ed il JWT per accedere alle risorse del servizio, l'ultima schermata riferita all'API GATEWAY DI INTEROPERABILITA' ci restituisce il seguente errore

curl https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml

**{"errors":[{"code":"013-9000","detail":"Invalid parameter found - No API path found that matches request '/api-gateway/1.0/interface-specification.yml'."}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}**

**Step per riprodurre il bug**
1. Vai su 'i tuoi client api interop' https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/interop-m2m/5da94021-f2b3-40a3-9793-28c58b02f878
2. Clicca su 'INETRFACCIA OPENAPI' [Interfaccia OpenAPI](https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml) 
3. Vedi l'errore. 
**{"errors":[{"code":"013-9000","detail":"Invalid parameter found - No API path found that matches request '/api-gateway/1.0/interface-specification.yml'."}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}**

**Comportamento atteso**
Cosa ti aspetteresti? ottenere le specifiche del gateway di interoperabilità in formato yaml

**c_d969**

**21/12/2022 h. 11.00**

[**Amministratore**]

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging
![2022-12-21](https://user-images.githubusercontent.com/46749848/208882813-fe837098-683f-40bc-9a71-2066c24ed093.png)

**Comment by FedericaSicchiero** [comment]
Buongiorno,
per il link al file OpenAPI dell'API gateway stiamo lavorando a sistemare tutto.

Per quanto riguarda i problemi con il token, allego qui per chiarezza la parte della guida su come si associano i client e-service alla finalità (sezione finalità https://docs.pagopa.it/interoperabilita-1/manuale-operativo/finalita e pagine successive).

Vi segnalo però che se intendete staccare un voucher per un e-service INPS, dovete farlo associando un "client e-service" alla finalità relativa all'e-service INPS e seguire quella procedura, non un "client API gateway". Non è possibile staccare un voucher per un e-service con un client API gateway di Interoperabilità e non si può staccare un voucher per l'API gateway di Interoperabilità con un client dedicato agli e-service. 

Le client assertion che vanno prodotti per questi due casi d'uso sono leggermente diverse.

Fatemi sapere se è tutto chiaro o se posso essere d'aiuto in altro modo.

Grazie,
Federica

**Comment by ComuneGenova** [comment]
Buongiorno,
confermo che stiamo effettuando le prove con una chiave specifica per interoperabilità. l'esempio è riferito a questo caso.
Rispetto all'esempio riportato nella documentazione https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher non ci è chiaro quindi se stiamo generando una asserzione jws senza le voci jti, iat, exp. Ci siamo basati sull'esempio in python per la creazione del jws che mi sembra non contempli tali parametri. Inoltre non ci è chiaro se il parametro --audience, nello script python di esempio, debba essere valorizzato con auth.uat.interop.pagopa.it/client-assertion oppure con quello indicato nella descrizione del servizio INPS - ISEE https://api.collaudo.inps.it/pdnd/soap/ConsultazioneISEE/v1 . Grazie

**Comment by FedericaSicchiero** [comment]
Purtroppo è proprio la procedura che si sta seguendo che non è corretta perchè avete creato un client API gateway con cui state provando ad accedere ad un e-service e la cosa non è fattibile. 

Bisogna seguire la procedura standard, cioè: 
- fare richiesta di fruizione per quell'e-service
- aspettare che l'erogatore la approvi
- creare finalità associata a quell'e-service
- associare un client e-service a quella finalità
- caricare almeno una chiave all'interno di quel client
- seguire la procedura descritta all'interno del client per lo stacco del voucher dove poi si trova anche l'audience corretta

In linea generale, per l'audience:
per la client assertion per ottenere un token da Interoperabilità l'audience sarà sempre Interoperabilità (quindi auth.uat.interop...) mentre per chiamare il servizio dell'erogatore, l'audience da utilizzare sarà quella indicata dall'erogatore nella scheda dell'e-service (in questo caso `https://api.collaudo.inps.it/pdnd/soap/ConsultazioneISEE/v1`)
