### ISSUE TITLE
Proposte di aggiunte alla UI della PDND

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#222]
Buongiorno,
nell'utilizzo della PDND ho constatato che relativamente alle finalità per cui il Fruitore ha chiesto un utilizzo ultronio alle soglie definite per un'e-service, l'attuale UI prevede la possibilità per un Erogatore di gestire la stessa dal tab "Finalità da evadere" presente nella scheda dello specifico e-service.

In merito vi chiedo di valutare la possibilità:
- di aggiungere il riferimento al Fruitore richiedente e l'indicazione della "Richiesta di Accesso" relativa alla finalità da evadere, al fine di permettere all'Erogatore di avere contezza del consteso entro cui la richiesta è stata generata

A mio avviso è utile permettere all'Erogatore, relativamente ai propri e-service, di avere contezza non solo delle "richieste di fruizione" da parte dei Fruitori, attualmente possibile dalla scheda "Richieste di fruizione", ma anche delle finalità registrate dai Fruitori relativamente alle stesse richieste (incluse quelle esplicitamente abilitate anche nell'ipotesi di finalità con soglie superiori a quelle definire per l'e-service).

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno Vincenzo,
grazie della segnalazione. Lo faccio presente ai dev e in caso di aggiornamenti ti faccio sapere.

Buona giornata

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo,
chiudo questo ticket in quanto l'implementazione che segnalavi è stata portata in tutti gli ambienti.

Grazie,
Federica
