### ISSUE TITLE
Accesso al servizio di interoperabilità INPS - ISEE su PDND di TEST

### ISSUE THREAD

**Issue by ComuneGenova** [pagopa/pdnd-interop-frontend#232]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Mancato accesso al servizio INPS ISEE
Dopo aver generato il JWS con l'aud = api.collaudo.inps.it/pdnd/soap/ConsultazioneISEE/v1
 non riusciamo ad ottenere il token JWT per accedere alle risorse del servizio. Abbiamo provato con il comendo

#JWS in test
ISEE: INPS ambiente di TEST
creazione del jws (assertion per il passo sucessivo, inizia per "ey")
python c:\temp\pdndt\create_m2m_client_assertion.py --kid DO8hG9HMiHa-r9JVJO4yALhJUnJmN_eFc1WT1V3lKII --alg RS256 --typ JWT --issuer c8e7ddc7-0ad9-42d6-82a8-1c5b4edf3351 --subject c8e7ddc7-0ad9-42d6-82a8-1c5b4edf3351 --audience api.collaudo.inps.it/pdnd/soap/ConsultazioneISEE/v1 --keyPath c:\temp\pdndt\inps-isee-fdc.rsa.priv > c:\temp\pdndt\client-test-keypair-inps-wso2.rsa.jws

#crea JWT
curl --location --request POST https://auth.uat.interop.pagopa.it/token.oauth2 --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode client_id=5da94021-f2b3-40a3-9793-28c58b02f878 --data-urlencode client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IkRPOGhHOUhNaUhhLXI5SlZKTzR5QUxoSlVuSm1OX2VGYzFXVDFWM2xLSUkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJjOGU3ZGRjNy0wYWQ5LTQyZDYtODJhOC0xYzViNGVkZjMzNTEiLCJzdWIiOiJjOGU3ZGRjNy0wYWQ5LTQyZDYtODJhOC0xYzViNGVkZjMzNTEiLCJhdWQiOiJhcGkuY29sbGF1ZG8uaW5wcy5pdC9wZG5kL3NvYXAvQ29uc3VsdGF6aW9uZUlTRUUvdjEiLCJqdGkiOiJjYWIyYWU4My0zZjg3LTRlODktOWY1NS03ZjYwNTIyODI4NjMiLCJpYXQiOjE2NzQ0Njg4NTYsImV4cCI6MTY3NzA2MDg1Nn0.LPagxM5yeQnPYnwoPKC-XqNqdO97oqj4UFJiSvmg4dYeGi_k2k7BnXrwRX1vrfjcKoQNxmOGqeYJwzfvZupVR_j167qj6d7zCwtkrIsw-qsFZO1gIjxBBbmeaHvUf-zj44hX70bkTahGgblmQ4ePoniLjRPTFL97VCH3wmsBxp2ni3prL5WpGU4QkgjKIt5nXKcYBN9x3RqZ2sadlGDUp-AQwE4YcM-o80VAHc9AFvKAjzRj4UYag6xDuqW8cJx8nXSikaC7z8pJgVcVQiVckT635Z8AMG4uBzfu6pv0WFxH6_z0nRmtyOg-PWQTGsI-zKV6BLYfihBvy5Q6rsnvtA --data-urlencode client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer --data-urlencode grant_type=client_credentials

ci restituisce il seguente errore

{"correlationId":"a9852279-d32d-44cd-a1a9-ea2c66f37968","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}curl: (6) Could not resolve host: application

**Comportamento atteso**
Il token JWT

**Il codice IPA del tuo ente**
c_d969

**Data e ora in cui si è riscontrato il problema**
23/01/2023 h. 11:15

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
Buongiorno,
grazie per la segnalazione del bug che è già stato passato al team. Appena ci sono novità aggiornerò il ticket.

Grazie,
Federica

**Comment by FedericaSicchiero** [comment]
Buongiorno, 
abbiamo controllato e l'errore è dovuto al fatto che si sta usando l'aud dell'e-service e non quella per la client assertation, che è questa: http://auth.uat.interop.pagopa.it/client-assertion - dovrebbe funzionare tutto con questa nuova audience.

Grazie,
Federica
