### ISSUE TITLE
Specifiche API Interop

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#233]
non riesco a ottenere le specifiche OpenAPI delle API di Interop.
Dovrebbero essere a questo URL: "https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml" ma non ci sono (risposta con status code 400 e messaggio "Invalid parameter found - No API path found that matches request").
Provato sia da browser sia tramite una request con il token JWT precedentemente acquisito.
Mi attenderei che le specifiche fossero ad accesso libero.

Chiesto giorni fa all'assistenza senza aver ricevuto ancora risposta.

Magari qualcuno qui ha la risposta (o le specifiche)

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio, ci guardiamo subito e appena troviamo la soluzione aggiorniamo il ticket.

Grazie,
Federica

**Comment by franthemanIT** [comment]
Chiedo scusa, ma intanto potrei avere una risposta interlocutoria?
Pongo una domanda da sì o no:
L'URL https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml chiamato senza ulteriori formalismi dovrebbe restituire le specifiche OpenAPI?

**Comment by FedericaSicchiero** [comment]
La risposta è si, il fix è stato rilasciato ieri in test e oggi verrà rilasciato anche in prod.
