### ISSUE TITLE
Approvazione per Consultazione ISEE (INPS)

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#243]
Da almeno una settimana ho inoltrato richiesta di fruizione per l'e-service INPS che risulta ancora in fase di approvazione.

L'assistenza di Interop mi ha risposto qualche giorno fa che "affinché un e-service venga approvato, il fruitore deve solo attendere la convalida degli attributi da parte dell'erogatore".

La documentazione dell'e-service indica ulteriori adempimenti per attivare l'e-service (tipo scambio di certificati e comunicazione di IP), senza indicare con chi interloquire.

Quale è la sequenza dei passaggi da seguire per farsi attivare l'e-service in ambiente di test?

Osservo che dieci giorni per approvare una richiesta che ha come requisito un solo attributo certificato sono decisamente eccessivi, passa la voglia di fare dei test.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
abbiamo di recente rilasciato una nuova funzione che permetterà di vedere le mail di contatto degli enti erogatori proprio per sentirli nel caso di problemi come questi, ma dovranno inserirla gli stessi enti. Se riusciamo a trovare una mail di contatto da condividere la aggiungerò al ticket.

Grazie,
Federica
