### ISSUE TITLE
Interfaccia di Interop: suggerimento di nuova feature

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#244]
Buongiorno,
suggerisco di inserire fra i dati relativi alle richieste inoltrate anche dei riferimenti temporali.
Al momento non mi pare che sia possibile vedere quando la richiesta è stata inviata e, immagino, quando è stata approvata.
Sono informazioni utili a più livelli, non ultimo quello giuridico-amministrativo.

EDIT: aggiungerei anche una funzione di ricerca nel catalogo API (almeno per erogatore, nome dell'e-service, fruitori attesi)

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie per i consigli.
Per la parte di ricerca di e-service posso già anticipare che è in programma e che verrà implementata a breve, mentre per i riferimenti temporali lo faccio presente al team e vediamo di programmare una sua programmazione.

Grazie,
Federica

**Comment by mrubiero** [comment]
Buongiorno, 
ci sono update sull'implementazione della funzionalitá di ricerca nel catalogo? 

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco,
l'update è previsto con il prossimo rilascio in produzione, non abbiamo ancora una data precisa perchè stiamo aggiungendo dei fix e delle altre funzioni in modo da deployare tutto assieme, ma confermo che sarà nel breve periodo.

Grazie,
Federica
