### ISSUE TITLE
Dove trovo il "consumerId"?

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#249]
Mi scuso per la/e domanda/e forse banale.
Sto facendo delle prove con le API di Interop. 
In particolare con `agreements` per recuperare la lista degli accordi (che mi pare il primo passo di un'implementazione più articolata).

In input si richiede almeno uno fra `consumerId `e `producerId`: dove si trovano da interfaccia questi dati?
Opzionali le chiavi `eserviceId `o `descriptorID`: anche queste, dove si trovano?

Qua e là nella specifiche mi sembra di vedere varie ID che da interfaccia sono poco visibili. Gli ID degli stessi client (almeno quelli di interoperabilità) non sono evidenti ma si evincono solo dagli esempi di script per richiedere il token, per esempio.

Ultima: il file di descrizione YAML fa riferimento a un percorso per gli schemi JSON delle risposte (es.: `$ref: '#/components/schemas/Agreement'`). Come ci si accede? **EDIT: mi ci sono risposto da solo**

**Comment by FedericaSicchiero** [comment]
Buongiorno, ho passato la segnalazione al team di front end e aggiornerò il ticket con tutte le risposte.

**Comment by ruggerocastagnola** [comment]
Buonasera Francesco, internamente al team questa attività è tracciata come [PIN-2687](https://pagopa.atlassian.net/browse/PIN-2687). Sarà implementata verosimilmente entro questa settimana e rilasciata con il primo rilascio disponibile. Potrebbero volerci fino a 14 giorni perché arrivi in ambiente di test in questo momento.

Indico una soluzione temporanea, sicuramente scomoda ma che non blocca gli sviluppi lato vostro. `eserviceId` e `descriptorId` sono reperibili nella URL della pagina del singolo e-service, che è strutturata così: `/fruizione/catalogo-e-service/{{ESERVICE_ID}}/{{DESCRIPTOR_ID}}`. Il primo id nell'URL è quindi l'`eserviceId`, il secondo il `descriptorId`. Per quanto riguarda `producerId` e `consumerId`, non sono attualmente esposti ma è possibile reperirli sfruttando i developer tools del browser. Se si usa Chrome, si possono aprire andando su "View > Developer > Developer Tools", quindi la tab "Network". Se si ricarica la pagina, in quella tab sarà listata una serie di chiamate che il client effettua verso il server, tra le quali un per ottenere la singola richiesta di fruizione (in ambiente di test l'URL della richiesta al server dovrebbe essere `https://selfcare.uat.interop.pagopa.it/backend-for-frontend/1.0/agreements/{{AGREEMENT_ID}}`). Aprendo il contenuto del corpo di quella risposta nella sottotab "Preview", si troveranno il `producer.id` dell'erogatore e il `consumer.id` del fruitore.

PS: ho visto anche il post su LinkedIn sulla PDND di qualche giorno fa, mi sono proposto di rispondere ma ancora non l'ho fatto. Ad ogni modo grazie per le segnalazioni e l'attenzione, molto apprezzate.

**Comment by franthemanIT** [comment]
Buongiorno Ruggero e grazie per le utilissime indicazioni. 
Riesco a interagire con la API di Interop egregiamente, con qualche dubbio sulla strada migliore da seguire, ma un passo alla volta.
Temo però di dover aprire un'altra issue, non me ne vogliate :)
