### ISSUE TITLE
Descrizione errata

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#252]
**Descrivi il bug**
Errata descrizione della page "Richieste di fruizione"

**Step per riprodurre il bug**
1. vai a https://selfcare.uat.interop.pagopa.it/ui/it/erogazione/richieste

**Comportamento atteso**
La descrizione della page dovrebbe essere:

> **Le richieste ai tuoi e-service**
> In quest'area puoi gestire tutte le richieste di fruizione pervenute dai Fruitori ai tuoi e-service._
> 

**Il codice IPA del tuo ente**
agid

**Data e ora in cui si è riscontrato il problema**
31/01/2023 15:09

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, grazie della segnalazione la prendiamo in carico e aggiorno il ticket quando abbiamo novità.

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, chiudo il ticket perchè il fix verrà rilasciato col prossimo deploy.
Grazie,
Federica
