### ISSUE TITLE
Problemi di accesso a  portale PDND e problemi nell'ispezionamento dei client

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#254]
Buongiorno,

a seguito della accettazione della richiesta di accesso ad un API del Min. Lav. in ambiente di test PDND  per conto di Regione Piemonte, della creazione di client e della finalità per l'accesso, abbiamo notato due problemi:
- non riusciamo ad ispezionare il client creato perché in portale PDND riporta segnalazioni di errore, richiedendo il reload della pagina, azione a seguito della quale viene ripresentato lo stesso errore;
- da pochi minuti anche l'accesso al portale PDND ha smesso di funzionare correttamente e da errori di accesso (usiamo PosteId come provider SPID).

Potete verificare e darci eventuali indicazioni per cortesia?

Cordiali saluti?
Corrado Tamietti
CSI Piemonte

**Comment by FedericaSicchiero** [comment]
Buongiorno Corrado,
potete dirmi a quale endpoint state cercando di accedere? Perchè abbiamo fatto delle prove e a noi funziona tutto.

Grazie,
Federica

**Comment by ctamietti** [comment]
Buongiorno Federica, certo: https://selfcare.pagopa.it/dashboard

**Comment by FedericaSicchiero** [comment]
Grazie dell'aggiornamento, verifichiamo tutto e torniamo con una risposta.

**Comment by ctamietti** [comment]
update: ulteriore richiesta: il nostro scopo ewra iniziare a fare una prova di ottenimento del voucher PDND. Avendo il probelam che vi abbiamo segnalato ci mancano i dati del client per comporre la richesta di ottenimento del voucher.
Di conseguenza vorremmo chiedervi: in atrtesa che venga risolto il problema di accesso alla videata PDND relativa ai client, sarebbe possibile per voi innviarci tutte le informazioni necessarie e comporre la request del voucher, ad esempio URL endpoint, iss, sub, aud, purpose Id ecc. , eventualmente alle mail corrado.tamietti@csi.it e maurizio.muni@csi.it?

Grazie 1000 in anticipo,
Corrado Tamietti
CSI Piemonte

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
abbiamo rilasciato in test i fix per i bug segnalati.
Chiudo questa issue in modo da tenere aperta solo la #255 e nel caso commentare lì.

Grazie,
Federica
