### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by maurizio-muni** [pagopa/pdnd-interop-frontend#255]
Buongiorno,
stiamo provando a generare il token per conto di Regione Piemonte ma anche seguendo passo passo gli step suggeriti sul portale PDND otteniamo una bad request con il seguente errore:
{
    "correlationId": "b0b8fe3b-8e64-4868-816e-faf90a2191c2",
    "errors": [
        {
            "code": "015-0008",
            "detail": "Unable to generate a token for the given request"
        }
    ],
    "status": 400,
    "title": "The request contains bad syntax or cannot be fulfilled.",
    "type": "about:blank"
}

Potete darci riscontro ?
Grazie
Maurizio Muni
CSI Piemonte.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
si ci stiamo lavorando, abbiamo risposto alla issue aperta da Corrado https://github.com/pagopa/pdnd-interop-frontend/issues/254 e dopo l'ultimo update il team sta cercando di capire perchè vi dia quel problema.

Grazie,
Federica

**Comment by ctamietti** [comment]
Grazie Federica,
abbiamo aperot un secondo issue perché non eravamo ceeti che le due cose fossero collegate ..

**Comment by maurizio-muni** [comment]
Buongiorno,
avete novità sul problema segnalato ? 
Aggiungo come dettaglio che stiamo utilizzando la curl ricavata dalle "Istruzioni ottenimento access token" presenti sul portale PDND 
curl --location --request POST https://auth.uat.interop.pagopa.it/token.oauth2 \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'client_id=xxxxxxxxxxxxxx' \
  --data-urlencode 'client_assertion=LA_TUA_CLIENT_ASSERTION' \
  --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
  --data-urlencode 'grant_type=client_credentials'

Il problema segnalato da Corrado sulla issue #254 non si è più verificato.

Grazie
Maurizio Muni

**Comment by FedericaSicchiero** [comment]
Buongiorno,
il team ci sta ancora lavorando e appena sarà pronta la lavorazione aggiornerò subito il ticket. 
Nel frattempo ieri hanno finito il #254 e lo stanno testando quindi per quello Corrado non l'ha più visto e chiuderò il ticket appena il fix sarà portato in ogni ambiente

Grazie,
Federica

**Comment by ctamietti** [comment]
Buongiorno,
non abbiamo più avuto notizie sull'issue apertro dal collega Maurizio. 

Ricordo che abbiamo seguito le istruzioni di ottenimento del voucher pubblicate su PDND stessa; a nostra volta riceviamo dai colleghi che stanno testando l'applicazione di back end richieste di spiegare loro perché stiamo avendo questo ritardo senza saper loro indicare quale possa essere il problema.
Posso chiedervi di aiutarci almeno a individuare la causa?

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Buonasera Corrado e Maurizio, 

ci sta volendo più del previsto, mi dispiace. Abbiamo rilasciato un fix per questo problema in ambiente di sviluppo ma va tutto verificato ci vorrà ancora qualche giorno per poterlo portare in ambiented di test, purtroppo era connesso ad altre modifiche che è necessario rilasciare assieme. La nostra stima è che andrà in ambiente tra martedì e mercoledì, ma vedo di aggiornarvi tempestivamente appena è tutto a posto. 

Vi ringrazio molto per la pazienza e resto a disposizione

Ruggero
