### ISSUE TITLE
Analisi del rischio per la registrazione ad un API: esiste un template per i progetti verticali?

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#260]
Buongiorno,
ci sono casi in cui, quando uno user amministratore esegue la registrazione di un'API su PDND, deve essere affiancato dai riferimenti delle applicazioni verticali che di fatto utilizzeranno l'API, che sono i veri 'esperti di dominio', per la compilazione dell'analisi del rischio.

Sarebbe utile avere un template di quest'analisi, ad esempio un file .doc o simili, idealmente accompagnato dalle informazioni utili alla sua compilazione, da consegnare in anticipo agli 'esperti di dominio' in modo che possano preparare le risposte più corrette in anticipo rispetto all'azione di registrazione.

Potremmo creare questo template in autonomia, ma ci chiediamo se avete già predisposto qualcosa di simile.

Grazie per il supporto,
Corrado Tamietti
CSI Piemonte

**Comment by FedericaSicchiero** [comment]
Buongiorno Corrado,
abbiamo già in programma di implementare un template simile ma purtroppo non è una lavorazione realizzabile in breve tempo.
In ogni caso lascio il ticket aperto così da aggiornarlo quando il lavoro sarà completato.

Grazie,
Federica

**Comment by ctamietti** [comment]
Buongiorno,
desidereri sapere se ci sono aggiornamenti su questo issue.

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by FedericaSicchiero** [comment]
Buongiorno Corrado,
alla fine per modifiche all'analisi del rischio non è stato possibile e non sarà possibile creare un template da esportare.

Grazie

**Comment by FedericaSicchiero** [comment]
Pesanti evoluzioni credo e spero di no, ma ogni tanto evoluzioni si anche a seconda dei casi (ad esempio stavamo studiando una possibilità di analisi del rischio specifica per i comuni in modo da aiutarli nella compilazione) e quindi una versione unica non è possibile metterla a disposizione di tutti

**Comment by ctamietti** [comment]
Grazie Federica.
Come vedrai nei precedenti messaggi non si richiede una versione unica. Se bisogna differenziare a seconda dell'ente, e se si torna al contesto originale in cui ho esporesso la richiesta, ciò mi sembra un motivo in più per produrre un template; in ogni caso non un impedimento. 

Quale altro meccansimo oltre a questi issue su guthub possiamo usare per ribadire la richiesta?
