### ISSUE TITLE
Possibilitá di aggiungere gli attributi a una nuova versione

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#263]
Buongiorno,
sarebbe possibile implementare l'aggiunta di attributi su una nuova versione di un servizio, richiedendo quindi nuovamente l'adesione al servizio per la nuova versione?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco,
prendo in considerazione la tua osservazione e la condivido col team in modo da parlarne poi assieme. Al momento, come saprai, non è possibile aggiungere gli attributi ad una nuova versione perchè prende in automatico quelli scelti per la prima versione dell'e-service, ma nel caso implementassimo la funzione ti faremo sapere.

Grazie,
Federica

**Comment by FedericaSicchiero** [comment]
Chiudo il ticket in quanto la feature è attualmente in valutazione e nel caso la aggiungeremo nel changelog quando rilasciata.

**Comment by mrubiero** [comment]
Buonasera, 
per caso la funzionalitá è stata rilasciata? 
Dall'interfaccia dell'ambiente di collaudo sembra di sì ma non riesco a capire quando dal changelog.

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco, 
si è stata rilasciata e probabilmente non è stata specificata ma inserita all'interno di questo rilascio: https://docs.pagopa.it/interoperabilita-1/informazioni-utili/changelog#id-1.0.64

**Comment by mrubiero** [comment]
Ciao Federica,
perfetto, grazie.
Quindi ci possono cambiare gli attributi tra le varie versioni, sia rimuovendone che aggiungendone?

**Comment by mrubiero** [comment]
Ok perfetto, grazie mille per il supporto.
