### ISSUE TITLE
Problemi download specifiche e-service

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#271]
**Descrivi il bug**
Ho rilevato che nella scheda di ispezione di un e-service il download della "Specifica API" non restituisce lo yaml atteso.

Vi evidenzio che il presente bug si presenta su Google Chrome Versione 110.0.5481.100 (64bit) e Firefox versione 109.0.1 (64bit).

**Step per riprodurre il bug**
A titolo esemplificativo riporto uno scenario per uno specifico e-service, segnalandovi che ho provato anche altri e-service constatando lo stesso comportamento

1. Vai su ['scheda e-service VPIVA1 - Verifica Partita Iva'](https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/catalogo-e-service/fb1d22fe-3c89-4fcd-9703-7c67ffb78aa1/f7cc5b0c-a109-4511-b67c-8e425f147f15)
2. Clicca su 'Specifica API'
3. Ottengo il file "Specifica API.yaml" il cui contenuto non è l'OpenAPI atteso ma 

> `{"contentType":"application/octet-stream","id":"cff880a0-7744-4946-bc3a-819746d90eab","name":"VerificaPartitaIvaGovWay_Val.yaml","path":"test/eservices/docs/cff880a0-7744-4946-bc3a-819746d90eab/VerificaPartitaIvaGovWay_Val.yaml","prettyName":"Specifica API"}
> `

Nello specifico del presente servizio rilevo che anche il download "Nota fruizione servizi" restituisce in file pdf il cui contenuto ASCII è 

> `
> {"contentType":"application/octet-stream","id":"0b90775e-3091-4ce3-8569-30ab5693b2d0","name":"Note fruizione servizio.pdf","path":"test/eservices/docs/0b90775e-3091-4ce3-8569-30ab5693b2d0/Note fruizione servizio.pdf","prettyName":"Nota fruizione servizi"}
> `

non utilizzabile (sto utilizzando il reader PDF Adobe Acrobate X Pro versione 10.1.16).

**Comportamento atteso**
Download dei file specifici.

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
16/02/2023 8:10

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, abbiamo aperto il bug anche sulla nostra board, grazie della segnalazione.

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, abbiamo deployato i fix oggi. Aspetto una tua conferma che tutto funzioni lato tuo prima di chiudere il ticket, grazie.

**Comment by vintra73** [comment]
Grazie, il problema è risolto
