### ISSUE TITLE
Recupero PuroposeID

### ISSUE THREAD

**Issue by AlessandroCimarelli** [pagopa/pdnd-interop-frontend#272]
Ciao,
potete aiutarci a capire quali api rest esposte bisogna utilizzare per recuperare il purposeID associato ad un nostro client e una specifica finalità?

Non ci è chiaro quale informazione in nostro posesso (esempio: consumerID) bisogna utilizzare per fare le richieste e quali api ci fornisco l'infomazione del purposeID utilizzando tale dato.

Grazie
Alessandro Cimarelli

**Comment by FedericaSicchiero** [comment]
Ciao Alessandro,
per vedere il purposeID di una finalità si può fare tutto dal back office di Interoperabilità andando su Fruizione --> I tuoi client e-service --> Ispeziona e quando si apre la schermata scorrere in basso fino alla sezione di Payload dell'asserzione dove viene indicata la purposeID.
Nello screen puoi vedere la sezione di cui parlo e dove scorrendo in basso trovi tutti i dati.

A disposizione,
Federica

![Snip20230216_1](https://user-images.githubusercontent.com/116075083/219381160-b176832b-f2df-4779-848b-19f76fb416dd.png)

**Comment by AlessandroCimarelli** [comment]
Ciao Federica,
si, questo modo mi era chiaro, ma volevo sapere se utilizzando le api rest che vengono esposte, senza utilizzare la parte web, è possibile recuperare il purposeid associato al client e alla specifica finalità, in modo da farlo in modo dinamico, tramite dei nostri servizi.


Alessandro

**Comment by FedericaSicchiero** [comment]
Ciao Alessandro,
appena ho una risposta chiara torno da te e aggiorno il ticket.

Grazie,
Federica

**Comment by AlessandroCimarelli** [comment]
Ciao Federica, 
da quello che ho visto,  diversi degli e-service a cui abbiamo chiesto la fruizione e già utilizziamo, hanno messo una versione nuova e deprecato la precedente, però il nostro client è ancora associato alla versione deprecata, e non abbiamo ricevuto nessun informazione sulla nuova versione.

Quindi vorremmo capire come operare, quando viene esposta una nuova versione.

grazie in anticipo
Alessandro

**Comment by FedericaSicchiero** [comment]
Ciao Alessandro,
per il discorso delle api rest al momento non esponiamo le informazioni in quel modo, ma ci segniamo la tua osservazione e nel caso in cui ci fosse necessità la implementeremo.

Grazie,
Federica
