### ISSUE TITLE
Problemi con upload Specifiche API (OpenAPI)

### ISSUE THREAD

**Issue by vix-db** [pagopa/pdnd-interop-frontend#273]
**Descrizione**
Ci risulta impossibile caricare un file di specifica API REST (OpenAPI) per un nostro e-service di test.
Nonostante il file di specifica non contenga in alcun modo la stringa "localhost" lo screenshot in allegato riportante l'errore restituito sostiene il contrario.
Il file di specifica è stato validato usando il validatore ufficiale: https://italia.github.io/api-oas-checker/

**Il codice IPA del tuo ente**
c_b674

**Data e ora in cui si è riscontrato il problema**
ultima volta: 16/02/2023 h. 17:50

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
![Screenshot from 2023-02-15 15-47-55](https://user-images.githubusercontent.com/47904600/219433051-3cfa6c51-f5c2-4f90-b7c0-e65302a7f9b7.png)

**Comment by FedericaSicchiero** [comment]
Buongiorno Vittorio,
abbiamo preso in carico il bug e ci stiamo lavorando, appena avrò aggiornamenti aggiorno il ticket.

Grazie,
Federica

**Comment by FedericaSicchiero** [comment]
Buongiorno Vittorio,
il fix per questo bug è stato rilasciato quindi dovrebbe funzionare tutto ora.
Aspetto una tua conferma per chiudere la issue.

Grazie,
Federica

**Comment by vix-db** [comment]
Buongiorno,
il problema persiste. Allego la definizione delle API REST se può essere utile.
Ho rimosso soltanto l'indirizzo IP del server di test (che non è localhost, si intende).

[api-spec-2023-02-16T16_29_28.737Z.zip](https://github.com/pagopa/pdnd-interop-frontend/files/10791342/api-spec-2023-02-16T16_29_28.737Z.zip)

**Comment by vix-db** [comment]
Svuotando la cache del browser sono riuscito a fare l'upload.
Grazie del supporto.
Il problema sembra quindi risolto.
