### ISSUE TITLE
Chimenti sul versioning

### ISSUE THREAD

**Issue by AlessandroCimarelli** [pagopa/pdnd-interop-frontend#274]
Ciao,
volevo capire come viene gestito il versioning degli e-service.
Se un client chiede la fruizione a una e-eservice, poi se quest'ultima mette una nuova versione, il client è automaticamente associato alla nuova versione o bisogna fare una richiesta di fruizione?

Grazie in anticipo
Alessandro Cimarelli

**Comment by FedericaSicchiero** [comment]
Ciao Alessandro,
quando un e-service viene aggiornato alla versione successiva tutto resta com'è e non bisogna fare nuove richieste. Sarà indicato poi ai fruitori che possono aggiornare la loro richiesta di fruizione alla versione più recente dell'e-service.

A disposizione,
Federica

**Comment by FedericaSicchiero** [comment]
Ciao Alessandro,
copio qui la risposta a questo ticket che però hai inserito sull'altro e ti rispondo in fondo:

"Ciao Federica,
da quello che ho visto, diversi degli e-service a cui abbiamo chiesto la fruizione e già utilizziamo, hanno messo una versione nuova e deprecato la precedente, però il nostro client è ancora associato alla versione deprecata, e non abbiamo ricevuto nessun informazione sulla nuova versione.

Quindi vorremmo capire come operare, quando viene esposta una nuova versione.

grazie in anticipo
Alessandro"

Al momento non esiste un servizio di notifica quando un e-service viene aggiornato, ma dovresti vedere la possibilità di aggiornare la tua richiesta di fruizione quando succede un caso simile. Ti metto [qui](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/richieste-di-fruizione#fruitore-aggiornare-una-richiesta-di-fruizione) il link alla nostra documentazione dove viene spiegato bene tutto e se non dovesse essere chiara dimmi pure che vedo di spiegarla meglio.

Grazie,
Federica

**Comment by AlessandroCimarelli** [comment]
Ottimo,
grazie mille
Alessandro
