### ISSUE TITLE
Cancellazione e modifica E-Service

### ISSUE THREAD

**Issue by AlessandroCimarelli** [pagopa/pdnd-interop-frontend#275]
Ciao, 
forse non l'ho trovato io il modo, ma è possibile cancellare o modificare un e.service?

Può capitare di sbagliare delle informazioni, o caricare un openapi errato, quindi o modificando o cancellando l'e-eservice possiamo eliminare gli errori, soprattuttto non rimangono nel catalog e-service errati che rimangono comunque consultabili.

Grazie in anticipo
Alessandro

**Comment by vix-db** [comment]
Stesso problema.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
scusate ho visto ora che la domanda era rimasta senza risposta. Stiamo lavorando ad un meccanismo di archiviazione di e-service proprio per pulire il proprio catalogo, ma al momento questa funzionalità non è disponibile. Per la modifica dello stesso si può solo creare una nuova versione con una nuova descrizione, ma il nome resta uguale. Questo vuol dire che se ci sono errori sugli attributi o parti modificabili dovrebbe risolversi con la nuova versione, altrimenti conviene crearne uno nuovo e quando sarà disponibile la feature archiviare quelli in disuso.
