### ISSUE TITLE
Impossibile creare un nuovo client, utente non autorizzato

### ISSUE THREAD

**Issue by mcasamassima** [pagopa/pdnd-interop-frontend#283]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Quando un utente abilitato con profilo di operatore API e operatore di sicurezza tenta di creare un nuovo client in ambiente di produzione gli compare il messaggio di non essere abilitato a farlo

**Step per riprodurre il bug**
1. Vai su 'I tuoi client e-service'
2. Clicca su 'Crea nuovo client'
3. Vedi l'errore "utente non autorizzato"

**Comportamento atteso**
Visualizzazione form di inserimento dati nuovo client

**Il codice IPA del tuo ente**
INAIL

**Data e ora in cui si è riscontrato il problema**
N/A

**Quali permessi ha la tua utenza?**
Operatore API, Operatore di sicurezza

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio, 
al momento solo l'amministratore ha questo potere ma stiamo valutando se e come estendere i permessi anche agli operatori autorizzati.
Aggiornerò il ticket appena avremo novità.

Grazie

**Comment by AlessioMarinelli** [comment]
Questa limitazione è tale anche nell'ambiente di test o solo di produzione?

**Comment by mcasamassima** [comment]
Solo produzione

**Comment by AlessioMarinelli** [comment]
Chiedevo perché sto avendo lo stesso problema in test... ma probabilmente l'errore allora è altrove

**Comment by mcasamassima** [comment]
mi è venuto un dubbio però non ho modo di provare perchè io sono
amministratore e a me non si presenta il problema, dovrebbe provare un
ruolo diverso, ma in questo momento è assente

Il giorno gio 23 feb 2023 alle ore 11:29 Alessio Marinelli <
***@***.***> ha scritto:

**Comment by AlessioMarinelli** [comment]
io ho i due ruoli Operatore, appena possibile farò una prova con il collega (Amminstratore)... intanto grazie
