### ISSUE TITLE
Errore 015-0008 durante la richiesta voucher

### ISSUE THREAD

**Issue by vix-db** [pagopa/pdnd-interop-frontend#284]
Dopo aver creato il JWS firmato, non riusciamo ad effettuare con successo la curl di test per la richiesta di voucher verso l’authorization server di Interoperabilità PDND.

**Descrivi il bug**

`{"correlationId":"9b7c4297-93c7-42e0-a1ba-995137ebcf36","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}
`

**Step per riprodurre il bug**

```
python create_client_assertion.py \
  --kid f7FP3SPkulK5iPFK6RfviDwFrdsRNbRleHFjnt9zJWc \
  --alg RS256 \
  --typ JWT \
  --issuer 2cb585ef-1ae2-4add-9d4e-c2c0380eca40 \
  --subject 2cb585ef-1ae2-4add-9d4e-c2c0380eca40 \
  --audience auth.uat.interop.pagopa.it/client-assertion \
  --purposeId bbc15f2d-65d1-431d-a4a6-78aba4360d1d \
  --keyPath keys/client-test-eservice-keypair.rsa.priv
```

CA="ey... <OMISSIS>"   // output del comando precedente

```
curl --location --request POST https://auth.uat.interop.pagopa.it/token.oauth2 \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'client_id=2cb585ef-1ae2-4add-9d4e-c2c0380eca40' \
  --data-urlencode 'client_assertion=$CA' \
  --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
  --data-urlencode 'grant_type=client_credentials'
```

**Comportamento atteso**
Voucher spendibile presso l'e-service dell’erogatore (noi stessi). 

**Il codice IPA dell'ente**
c_b674

**Data e ora in cui si è riscontrato il problema**
ultima volta 22/02/2023 h. 17:41

**Quali permessi ha la tua utenza?**
Amministratore

**Note**
```
(venv) [vix@delorean interop]$ python3 --version
Python 3.8.16
```

```
(venv) [vix@delorean interop]$ pip3 freeze
ecdsa==0.18.0
pyasn1==0.4.8
python-jose==3.3.0
rsa==4.9
six==1.16.0
```

**Comment by FedericaSicchiero** [comment]
Buongiorno Vittorio,
il problema risulta essere la client assertation  perchè il parametro che state passando 'client_assertion=$CA'
con i singoli apici non fa sostituire la variabile CA, quindi invece della client assertion noi riceviamo la stringa $CA e il sistema automaticamente la blocca.

**Comment by vix-db** [comment]
Pardon, ero convinto di averli lasciati doppi gli apici. Effettivamente così la variabile non veniva interpolata...
