### ISSUE TITLE
PDF indicati firmati digitalmente da PagoPA

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#300]
**Descrivi il bug**
Ho constatato che per i documenti PDF in cui risulta indicato "Firmato digitalmente da PagoPA S.p.A.", ad esempio il documento Analisi del rischio, non è possibile effettuare download della versione firmata.

**Step per riprodurre il bug**
1. Vai a https://selfcare.interop.pagopa.it/ui/it/erogazione/finalita/6ae6ac16-4842-4983-8eb6-7a410b829449
2. Clicca su "Analisi del rischi"
3. Il PDF non risuta firmato digitalemente

**Comportamento atteso**
La possibilità di effettuare download del file firmato digitalemente da PagoPA

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
28/02/2023 h. 13:10

**Quali permessi ha la tua utenza?**
 Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, abbiamo delle task proprio su questo problema che verranno implementate prossimamente anche se non so darti delle tempistiche al momento. Grazie della segnalazione.

**Comment by FedericaSicchiero** [comment]
Chiudo il ticket qui ma è tracciato nel nostro backlog in quanto da linee guida abbiamo bisogno di tempo per valutarla ma è in fase di programmazione e confermiamo che verrà sviluppata.
