### ISSUE TITLE
[Maintenance] 1/03/23 h. 17 - 20

### ISSUE THREAD

**Issue by FedericaSicchiero** [pagopa/pdnd-interop-frontend#308]
Activity window

1/03/23 h. 17 - 20

**Comment by AlessandroCimarelli** [comment]
Ciao,
da questa mattina non è possibile accedere all'ambiente di test, solo produzione.

Alessandro

**Comment by FedericaSicchiero** [comment]
ciao Alessandro, 
da oggi invece dell'ambiente di test c'è quello chiamato ambiente di collaudo a cui si accede sempre nello stesso modo. Se hai il ruolo di Amministratore ti si dovrebbe aprire il pop up come sempre che ti fa scegliere tra i due ambienti, se invece quando accedi ti rimanda direttamente all'ambiente di produzione ti chiedo di farmi contattare dalla persona che ha il ruolo di Amministratore in modo da spiegare il processo, perchè deve ancora essere inserita la nuova documentazione sulla nostra pagina Gitbooks.

Grazie,
Federica

**Comment by AlessandroCimarelli** [comment]
Ciao Federica,
io sono operatore. Quindi ti faccio contattare dall'amministratore. In che modo ti può contattare? qui o per email?

grazie
Alessandro

**Comment by AlessandroCimarelli** [comment]
ottimo.

grazie
Alessandro
