### ISSUE TITLE
Ambiente di Test non accessibile

### ISSUE THREAD

**Issue by vix-db** [pagopa/pdnd-interop-frontend#310]
Quando accediamo alla [dashboard](https://selfcare.pagopa.it/dashboard) e selezioniamo il prodotto **Interoperabilità** non viene più proposta la scelta tra l'ambiente di **Test** e quello di **Produzione** ma si viene rediretti direttamente all'ambiente di **Produzione**.

**Comportamento atteso**
Alla scelta del prodotto Interoperabilità mi aspetterei di visualizzare la finestra modale per la scelta dell'ambiente di lavoro (Test vs Produzione)

**Il codice IPA del tuo ente**
c_b674

**Data e ora in cui si è riscontrato il problema**
ultima volta: 01/03/2023 h. 12:00

**Quali permessi ha la tua utenza?**
Amministratore

**Comment by FedericaSicchiero** [comment]
Ciao Vittorio, 
grazie della segnalazione, stanno facendo delle lavorazioni e al momento non abbiamo delle tempistiche su quando tornerà disponibile.
Aggiorneremo il ticket.

Grazie,
Federica

**Comment by vix-db** [comment]
L'ambiente di Test sembra sia tornato disponibile. Grazie.
