### ISSUE TITLE
Richiesta voucher in errore "code":"015-0008"

### ISSUE THREAD

**Issue by csimone77** [pagopa/pdnd-interop-frontend#312]
Buongiorno, vi scrivo come amministratore dell'ente Agenzia delle entrate - Riscossione. Il nostro problema è il seguente:
abbiamo creato un nuovo client da zero, abbiamo creato una nuova finalità per l'eservice sottoscritto. 
Risulta tutto attivo ma quando chiamiamo per avere il voucher ci ritorna il seguente json:
{"correlationId":"0f9fd389-a37c-4e39-b38c-10f1ff21592e","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

La richiesta è fatta con un token generato usando i seguenti parametri nello script python di esempio:
--kid OXbcx3eYzAmQ3tkbwRRCF6FxmAGiLxm6Ybtym4nAgGU --alg RS256 --typ JWT --issuer 25d98217-5e43-428b-942e-42b493e21117  --subject 25d98217-5e43-428b-942e-42b493e21117 --audience auth.uat.interop.pagopa.it/client-assertion --purposeId 9aafbf76-57f3-4bb4-816d-3024dcd426f9

a disposizione per eventuali altre info

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
abbiamo preso in carico il bug e aggiornerò la issue appena avremo aggiornamenti.

Grazie,
Federica

**Comment by FedericaSicchiero** [comment]
Dai nostri log vediamo che state cercando di fare un richiesta token con una client assertion che contiene questo subject 25d98217-5e43-428b-942e-42b493e21117.
Mentre il clientId della richiesta è 94116b17-e772-413e-adb8-842acadebd2e (che è un altro client).

Cambiando il campo clientId nella access token request in 25d98217-5e43-428b-942e-42b493e21117 dovrebbe risolversi il problema.

Al netto della client assertion quindi la chiamata che dovrete fare sarà:

POST /token.oauth2 HTTP/1.1
Host: auth.uat.interop.pagopa.it
Content-Type: application/x-www-form-urlencoded
Content-Length: 200

client_id=25d98217-5e43-428b-942e-42b493e21117&client_assertion=LA_CLIENT_ASSERTION&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&grant_type=client_credentials

A disposizione,
Federica

**Comment by csimone77** [comment]
Funziona grazie
