### ISSUE TITLE
Accesso all'ambiente di test PDND non attivo?

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#313]
Buongiorno,
stamattina, accedendo a PDND, ci pare che non sia possibile accedere all'ambiente di test e che veniamo indirizzati, senza l'usuale possibilità di scelta, direttamente sull'ambiente di prod.
Di conseguenza non vediamo le informazioni sui client definiti in test e le richieste di registrazione alle API.

E' cambiato qualcosa nelle modalità di accesso a PDND in test?

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by FedericaSicchiero** [comment]
Buongiorno Corrado,

da ieri è stato portato online l'ambiente di collaudo che sostituisce quello di test. Se la tua utenza è operatore API / operatore di sicurezza vieni rimandato direttamente all'ambiente di produzione perchè devi farti abilitare dall'amministratore per entrare nell'ambiente di collaudo.

Puoi trovare qui tutte le informazioni e la procedura passo per passo: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/ambiente-di-collaudo

Se il problema dovesse essere un altro vedremo di risolverlo al più presto.

Grazie,
Federica

**Comment by ctamietti** [comment]
Grazie Federica, facciamo una prova ed eventualmente torniamo.

Buona giornata.
