### ISSUE TITLE
Client non visibili post-migrazione da ambiente di test a collaudo

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#318]
Buongiorno, 
dopo la migrazione da ambiente di test a ambiente di collaudo non riusciamo più a vedere i nostri client e-service che avevamo in precedenza, è normale? Dovrebbero essere stati migrati o oppure no?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco, 

a seguito di alcuni fix la sezione dei client può essere vista solo dgli amministratori e operatori di sicurezza. Chiediamo quindi di rendere amministratori dell'ambiente di sicurezza gli operatori API e poi aggiungerli al client.

Se così non dovesse funzionare vediamo di approfondire la questione.

Grazie,
Federica

**Comment by mrubiero** [comment]
Ciao Federica,
scusami, dobbiamo richiedere di renderci amministratori oppure operatori di sicurezza, oltre al ruolo di operatore API, per  accedere ai client? Corretto?

Grazie,
Marco

**Comment by mrubiero** [comment]
Ciao Federica, per l' aggiunta di un amministratore, anche per l' ambiente di collaudo bisogna seguire questa procedura e inviare il documento via PEC? 
https://docs.pagopa.it/interoperabilita-1/faq/per-gli-aderenti#come-posso-aggiungere-o-rimuovere-un-operatore-amministrativo

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco,
no per l'ambiente di collaudo è molto più semplice e puoi trovare tutte le indicazioni qui: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/ambiente-di-collaudo#sono-un-operatore-api-operatore-di-sicurezza-come-faccio-ad-entrare-nellambiente-di-collaudo
Ti anticipo già che solo un amministratore di produzione può nominare amministratore di collaudo un qualsiasi operatore.

Grazie,
Federica

**Comment by mrubiero** [comment]
Ciao Federica,
con l'abilitazione a amministratore riusciamo a vedere anche i client.

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ottimo allora chiudo il ticket!
