### ISSUE TITLE
client non più visibili

### ISSUE THREAD

**Issue by maurizio-muni** [pagopa/pdnd-interop-frontend#319]
Buongiorno,
dopo che è stato portato online l'ambiente di collaudo in sostituzione di quello di test, non riesco più a visualizzare i client creati dal mio collega Corrado Tamietti, sui quali stavo lavorando fino a prima della sostituzione dell'ambiente
Aggiungo che sono stato abilitato all'ambiente di collaudo e mi sono state date le opportune autorizzazioni. 
Potete verificare ?

Grazie
Maurizio Muni
CSI Piemonte

**Comment by FedericaSicchiero** [comment]
Buongiorno Maurizio,
qual è il tuo ruolo all'interno dell'ambiente di collaudo? 
Così sappiamo da dove partire per le verifiche.

Grazie,
Federica

**Comment by maurizio-muni** [comment]
I miei ruoli sono Operatore API e Operatore Sicurezza.

Grazie

**Comment by FedericaSicchiero** [comment]
Come Operatore di sicurezza non dovrebbero esserci problemi a vedere i client in collaudo. Si può fare una prova e chiedere ad un amministratore di renderti amministratore a tua volta ma dell'ambiente di collaudo, che è l'altra figura che dovrebbe vedere i client senza problemi.

Le istruzioni per essere nominati amministratori di collaudo si trovano qui: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/ambiente-di-collaudo#sono-un-operatore-api-operatore-di-sicurezza-come-faccio-ad-entrare-nellambiente-di-collaudo

**Comment by maurizio-muni** [comment]
Grazie Federica mi sono fatto abilitare al ruolo di amministratore dell'ambiente di collaudo e adesso vedo i client.

Grazie per il supporto
Saluti

**Comment by FedericaSicchiero** [comment]
Ottimo! Chiudo il ticket.
