### ISSUE TITLE
Ottenere informazioni relative a purposeId

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#320]
Buonasera,
dall'interfaccia è possibile ottenere le informazioni relative a un determinato purposeId oppure è necessario utilizzare le API con il client interop?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco,
al momento stiamo lavorando proprio per semplificare il processo ma ora come ora purtroppo si può ottenere solo tramite url:
![Screenshot 2023-03-08 at 17 36 59](https://user-images.githubusercontent.com/116075083/223774536-77f8b413-4d40-4a9c-a437-757864e17af5.png)

Grazie,
Federica

**Comment by mrubiero** [comment]
Ciao Federica,
ok perfetto così funziona però non vedo informazioni per identificare il fruitore con quella finalitá; nel mio caso appunto vorrei capire estraendo la finalitá dal token chi sta provando a chiamare i servizi, non lo sto vedendo o al momento non è possibile recuperare l'informazione?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco, 
al momento non è possibile ma abbiamo già dei ticket aperti per lavorarci.
Ti aggiorno appena viene portata su la lavorazione.

Grazie,
Federica

**Comment by mcasamassima** [comment]
scusate ma il purpose id non è quello che si vede nelle informazioni del client una volta selezionata la finalità giusta?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
si esatto quando si associano client e finalità si può vedere il purposeID, ma nel caso in cui lo si volesse recuperare in altri modi l'unica via è l'URL.

**Comment by mrubiero** [comment]
Buongiorno,
ci sono aggiornamenti su questa funzionalitá? 
Ci tornerebbe molto utile per implementare delle autorizzazioni selettive per le diverse operation di un singolo servizio, senza la necessitá di dividerle in più servizi per poter autorizzare diversi fruitori per solo alcune operation.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
abbiamo rilasciato di recentemente un aggiornamento alla UI grazie alla quale ora si possono trovare tutti i dati all'interno della piattaforma, nello specifico - come da screen - all'interno del client quando si è selezionata la finalità e la chiave di riferimento.
![Snip20231206_2](https://github.com/pagopa/pdnd-interop-frontend/assets/116075083/c3e3eb58-9bff-4cd6-8536-3fd2460e45fe)
