### ISSUE TITLE
Permettere ai Fruitori di avere evidenza per quale degli e-service fruiti l'Erogatore ha aggiornato la versione

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#325]
Buongiorno,
nell'utilizzo dell'intefaccia di PDND evidenzio che un Fruitore non ha un'evidenza immediata degli e-service, da lui fruiti, hanno avuto un aggiornamento di versione da parte dell'Erogatore, allo stato il Fruitore deve analizzare singolarmentele singole finalità (non ho trovato altre modalità).

Suggerisco di aggiungere alla tabella delle finalità registrate da un Fruitore (https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/finalita) una colonna in cui evidenziare che per l'e-service relativo alla finalità è disponibile una nuova versione.

Grazie

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo,
grazie della segnalazione, l'ho passata al team per prenderla in considerazione.

Grazie,
Federica
