### ISSUE TITLE
EXP nel token di collaudo

### ISSUE THREAD

**Issue by AlessandroCimarelli** [pagopa/pdnd-interop-frontend#369]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Il token che viene generato dalla PDND ha il tempo nel valore exp dell'istante con cui viene generato, invece di avere un valore superiore di 5 minuti

**Step per riprodurre il bug**
questo payload è stato generato alle ore 12:54:52 e l'exp ha valore 11:54:53 
{
  "aud": "apidhub.osdhbcl.infocamere.it/rest/callback",
  "sub": "a75043f0-c478-420c-84bd-194ecedb45e8",
  "nbf": 1680692093,
  "purposeId": "d07ff7e3-a300-4119-a373-ef9771c514f4",
  "iss": "uat.interop.pagopa.it",
  "exp": 1680695693,
  "iat": 1680692093,
  "client_id": "a75043f0-c478-420c-84bd-194ecedb45e8",
  "jti": "cccaf807-3427-4f10-a601-2430281e3217"
}

**Comportamento atteso**
che il valore exp sia di 5 minuti superiore rispetto all'orario di generazione

**Il codice IPA del tuo ente**
Se non lo sai, lo trovi così: 
INAIL

**Data e ora in cui si è riscontrato il problema**
es. 05/04/2023 h. 12:54 circa

**Quali permessi ha la tua utenza?**

**Screenshot**

**Note**
Il valore exp non corretto, non permette di essere autorizzati correttamente dai servizi esposti sulla PDND.

Grazie
Alessandro Cimarelli

**Comment by AlessandroCimarelli** [comment]
Aggiungo una nota, il problema si evidenzia dal 1 aprile

Alessandro Cimarelli

**Comment by FedericaSicchiero** [comment]
Ciao Alessandro,

la purpose indicata nell’issue d07ff7e3-a300-4119-a373-ef9771c514f4 fa riferimento all’eservice 92e57f50-bbdd-4f2f-943c-05fc5a18a5fb con nome "Composizione Negoziata - Callback documenti", il cui unico descrittore ha indicata una durata del token generato di 3600 secondi.
La durata del token generato è quindi di 1 ora, tenendo conto che il campo iat (“issued at”) è definito come unix timestamp in UTC e quindi col fusorario diventa GMT+2.

Grazie,
Federica

**Comment by AlessandroCimarelli** [comment]
Ciao Federica,
scusami, ma ho inserito i dati sbagliati, visto che stavo facendo diversi test.
Il nostro problema si verifica quando richiamiamo tutti i servizi SDG presenti nel catalog con cui abbiamo la fruizione con il nostro clienti.
Di seguito ti metto una delle richieste con tutte le informazioni:



Timestamp | 12:08:58 - 5 aprile 2023
Servizio | sdg
Tipo servizio | FRUITORE
Tipo messaggio | Richiesta
Cooperante | AgID
Metodo/Path | GET /servicecatalogue/v1/publicService/mapping?ipaCode=inail&name=da1
Content-Type | application/json
Eccezione | 403 - {"message":"User is not authorized to access this resource with an explicit deny"}
T. servizio | 151ms (151ms)
T. backend | 146ms (146ms)
T. attr. | 4ms (4ms)

e questo è il token che viene generato dall'authorization server PDND e che passiamo nella request 

Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJ2NCIsInN1YiI6ImE3NTA0M2YwLWM0NzgtNDIwYy04NGJkLTE5NGVjZWRiNDVlOCIsIm5iZiI6MTY4MDY4OTMzMSwicHVycG9zZUlkIjoiZjQ2NmYwMmUtZjg2Yi00MmVhLWI1MWQtMTE2NTgyZTM4MWZmIiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNjgwNjg5OTMxLCJpYXQiOjE2ODA2ODkzMzEsImNsaWVudF9pZCI6ImE3NTA0M2YwLWM0NzgtNDIwYy04NGJkLTE5NGVjZWRiNDVlOCIsImp0aSI6IjI3NDZkZWVhLTRkMTItNDA0YS1hZDQ4LTk5YzNmN2M0OTc2ZSJ9.4BZoHGcbmnHkJaN9baIglBDbHK3zAobfiMg3ncHjXdH5yw12vs3ZcvhE8jnRmhX0rN23BeAWqKtRQpR25q63YbqraMDdAqgKBMlWsj8vu2X2lT-Ujg6ktUHfO2hfgjq88mOnkngb56xGxfcN3gJN9r7lnzhw9aR4xyPKimD2LX9S5MPCa7sx0jToWpzUKCTIejDZumVlaXzYRbl__GZ7CCRZTKDOlAEOAJr4qW4E3HKN6rong8zfqJDWjsDmraErWfjmrpp_qvpRzcg8h3Wk05MoFQBk_Nm9QsBs3475JjMFyVM3r4EGfDNogzI2s4N_xoDgH0_kYnYrRNlx6Dvjkw
Connection: Keep-Alive
Content-Length: 0
Content-Type: application/json

{
  "aud": "v4",
  "sub": "a75043f0-c478-420c-84bd-194ecedb45e8",
  "nbf": 1680689331,
  "purposeId": "f466f02e-f86b-42ea-b51d-116582e381ff",
  "iss": "uat.interop.pagopa.it",
  "exp": 1680689931,
  "iat": 1680689331,
  "client_id": "a75043f0-c478-420c-84bd-194ecedb45e8",
  "jti": "2746deea-4d12-404a-ad48-99c3f7c4976e"
}

il token è generato poco prima della richiesta al servizio. Come puoi vedere il servizio è stato richiamato alle ore 12:08:58 - 5 aprile 2023, e nell'exp del token la data è  5 aprile 2023 12:18:51, ovviamente questo token non potrà essere validato dai Servizi SDG.

Fino al 31 marzo tutto funzionava correttamente, mentre dal 3 aprile è iniziato il problema, dove i servizi SDG ci rispondono 403 not authorize.

Visto che noi non abbiamo fatto modifiche, e sentendo il gruppo tecnico di SDG, anche loro mi dicono di non aver fatto modifiche, e che il token di authorizzazione viene genrato dalla PDND, ho indagato e ho riscontrato questa incongruenza nel exp.

Spero tu possa aiutarci a comprendere il problema, perchè attualmente, per i servizi SDG di collaudo siamo bloccati.

Grazie
Alessandro

**Comment by AlessandroCimarelli** [comment]
Aggiungo, che come hai scritto, per il servizio Infocamere l'exp è corretto e ha una validità di un ora, infatti con quel servizio non abbiamo problemi, anche con MLPS, dove entrambi hanno un validtà del token di 1 ora. Solo con quelli SDG che hanno validità del token di 10 minuti.

Alessandro


Alessandro

**Comment by AlessandroCimarelli** [comment]
Ciao Federica, come non detto, il problema non è l'exp, che risulta corretto. 
Grazie del supporto
Alessandro
