### ISSUE TITLE
Campi nuovo attributo

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#39]
Quando definiamo un nuovo attributo (verificato) ci vengono richiesti alcuni campi obbligatori:

- Id della fonte autoritativa
- Nome della fonte autoritativa
- Descrizione della fonte autoritativa

cosa intendiamo per fonte autoritativa? L'id dove lo prendiamo?

**Comment by ruggerocastagnola** [comment]
Per il momento chiudo quest'issue. La revisione della scheda di creazione attributo è un processo "ongoing" che proseguirà nei prossimi mesi, le eventuali modifiche saranno segnalate mano a mano
