### ISSUE TITLE
Attributi verificati in or nella richiesta di iscrizione

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#40]
![image](https://user-images.githubusercontent.com/29304687/157706139-21e83453-ca0b-4fb1-adaa-ff73ca3e046e.png)

Facendo un nuovo e-service come erogatore e pubblicandolo con attributi verificati di cui alcuni in or, il fruitore, all'atto della richiesta di iscrizione all'e-service, non ha possibilità di scegliere tra gli attributi in or.
Se il fruitore comunque esegue la richiesta di richiesta di iscrizione mi ritrovo nella situazione allegata nell'immagine di cui sopra

Il test è stato fatto da anpr come erogatore e PUC/Orchestratore come fruitore

**Comment by ruggerocastagnola** [comment]
Dunque, una precisazione: nel backlog abbiamo una task per dare la possibilità al fruitore di inserire della documentazione a corredo degli attributi verificati per la sua richiesta di fruizione, di fatto indicando all'erogatore per quali tra gli attributi in OR va effettuata la verifica. In questo momento, come dici tu, non è possibile, dunque è effettivamente tutto in mano all'erogatore.

Per quanto riguarda il potenziale bug della non attivazione, indago, assieme all'allineamento errato del testo che vedo sopra

**Comment by ruggerocastagnola** [comment]
Abbiamo individuato il bug sul backend, sugli attributi verificati per i quali non è richiesta nuova verifica. È attualmente in correzione

**Comment by marcocipri** [comment]
@amollicone1982  io lo aprirei come enhancement.

**Comment by ruggerocastagnola** [comment]
Ciao a tutti, per chiarire.

Per quanto riguarda il problema che Angelo ha riscontrato ieri, stiamo facendo delle modifiche per fare in modo che __temporaneamente__ non sia possibile trovarsi in quella situazione, visto che attualmente manca una parte di logica che ne permetterebbe il corretto funzionamento lato UI. Le modifiche non sono ancora rilasciate nell'ambiente disponibile a SOGEI, segnalo qui quando lo saranno.

Per quanto riguarda la tua richiesta, abbiamo una task aperta sulla questione. Aggiungo questo requisito in modo che sia dibattuto ed ho aperto [#42] perché si possa tracciare anche qui. Internamente noi tracciamo l'issue su [PIN-1227](https://pagopa.atlassian.net/browse/PIN-1227)

**Comment by beetlecrunch** [comment]
È possibile ora attivare la richiesta di fruizione.
Come già segnalato da Ruggero, sarà inibita temporaneamente la possibilità di creare eservice con attributi verificati con verifica implicita.
