### ISSUE TITLE
Richieste di fruizione per servizi non attivi

### ISSUE THREAD

**Issue by ValentinaIdromela12** [pagopa/pdnd-interop-frontend#404]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Nella piattaforma risultano sei richieste in attesa di approvazione per due servizi che non sono attivi:
-Verifica booleana del codice fiscale V2
-Verifica partita iva V 2

![image](https://user-images.githubusercontent.com/115009462/235628166-c949b00a-8341-48f0-9b23-66c7a965fd18.png)
![image](https://user-images.githubusercontent.com/115009462/235628694-bda837e3-45cc-4964-b817-3706b97e4bde.png)

 
**Step per riprodurre il bug**
1. Vai su '...'
2. Clicca su '....'
3. Vedi l'errore

**Comportamento atteso**
Cosa ti aspetteresti?
Per i servizi non attivi non dovrebbero risultare richieste di fruizione "in attesa di approvazione"

**Il codice IPA del tuo ente**
age

Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente

**Data e ora in cui si è riscontrato il problema**
02.05.2023 h.11:30

**Ambiente**
Produzione 

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo preso in carico il bug e aggiorno la segnalazione appena abbiamo aggiornamenti.
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno,
non si tratta di un bug perchè è normale che le finalità rimangono "in attesa di approvazione" perché le versioni di e-service alle quali sono associate sono sospese e dunque riattivabili. 
Se invece quelle versioni di e-service venissero archiviate anche le finalità verrebbero archiviate o eliminate di conseguenza

**Comment by ValentinaIdromela12** [comment]
Buongiorno,
quindi per non ricevere più richieste di fruizione per e-service sospesi (verifica booleana del CF Versione 2 e Verifica Partita IVA Versione 2) perché non più disponibili, è necessario archiviarli? 
Può indicarmi il procedimento? Nella piattaforma non c’è alcuna funzionalità che consente di scegliere la tipologia di stato “Archiviato”.
Grazie 
Saluti

**Comment by ruggerocastagnola** [comment]
Buonasera, 

la funzionalità di archiviazione è prevista in linee guida ma non ancora implementata in piattaforma per esigenze di prioritizzazione attività. Abbiamo scalato l'importanza della funzionalità e stiamo preparando la lavorazione vista l'urgenza che avete riscontrato. La aggiorno non appena ho maggiori dettagli. 

Grazie mille della segnalazione, e a disposizione.

Un saluto

Ruggero

**Comment by FedericaSicchiero** [comment]
Chiudo il ticket ma mi segno di aggiornare quando la funzionalità di archiviazione verrà implementata.
