### ISSUE TITLE
Richieste di fruizione

### ISSUE THREAD

**Issue by micheleselea** [pagopa/pdnd-interop-frontend#409]
Buongiorno volevo sapere se è possibile inoltrare in qualche modo una richiesta di fruizione per un eservice di cui si è anche erogatori, questo per fare un test in ambiente di collaudo. Se non è possibile devo usare obbligatoriamente un altro ente per fare un test di fruizione?

**Comment by FedericaSicchiero** [comment]
Buongiorno, si è possibile iscriversi ad un e-service di cui si è erogatori. In quel caso però la richiesta di fruizione viene accettata automaticamente e attivata senza doverlo fare manualmente.

**Comment by micheleselea** [comment]
Ok però non vedo il pulsante ISCRIVI se vado nell'eservice di cui sono erogatore, c'è solo la voce in alto che dice "sei l'erogatore di questo e-service" ma non trovo ISCRIVI

**Comment by FedericaSicchiero** [comment]
Può fare qualche screen e allegarli? Così se è un bug lo tracciamo e risolviamo

**Comment by micheleselea** [comment]
Forse manca ancora un passaggio ovvero la creazione client api interop, provo a fare quello per vedere se poi mi fa accedere alla fruizione

**Comment by micheleselea** [comment]
Ah ok però il problema è che come operatore API e Sicurezza non ho il permesso di farlo

**Comment by FedericaSicchiero** [comment]
Per fruire di un e-service non serve creare le API prima, però confermo che solo gli amministratori hanno il potere di iscriversi, i vari operatori no.

**Comment by micheleselea** [comment]
Ok, allora a quanto pare se entro dentro un eservice vedo solo questo che allego. In fondo vedo solo torna al catalogo e-service
![2](https://user-images.githubusercontent.com/5929871/236404289-b8a582bf-e150-4642-8e52-dc285f351dc3.jpg)
![1](https://user-images.githubusercontent.com/5929871/236404295-0deca9c0-8830-42e7-ad88-602b705ab6df.jpg)

**Comment by FedericaSicchiero** [comment]
Si è giusto che appaia così se il ruolo è quello di Operatore. Solo gli Amministratori possono iscriversi agli e-service quindi per fare tutti i test del caso bisogna che un amministratore cambi il ruolo da Operatore ad Amministratore di collaudo.

**Comment by micheleselea** [comment]
ah ok capito, niente allora chiudo il ticket, cerco di recuperare l'amministratore del comune
