### ISSUE TITLE
Chiamate a nuovo ambiente di collaudo

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#412]
Prendo 
{"correlationId":"f3627305-0a57-4b65-94b1-3d9d003a51c2","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

nella chiamata al nuovo ambiente di collaudo con token:

{
  "aud": "auth.uat.interop.pagopa.it/client-assertion",
  "sub": "371867ab-5331-4bb0-8743-f5f04048be3c",
  "nbf": 1683298109,
  "purposeId": "c6f72cd8-bd62-4315-a0fe-743332ee4946",
  "digest": {
    "alg": "SHA256",
    "value": "dNpHsawKB+5M2cb/Toeu5UNINTEz4SZojSbT/NlWQAo="
  },
  "iss": "371867ab-5331-4bb0-8743-f5f04048be3c",
  "exp": 1683298409,
  "iat": 1683298109,
  "jti": "44cb22fb-12fa-401a-a34f-60312b22a159"
}

**Comment by FedericaSicchiero** [comment]
Buonasera, l’hashing del valore in value non è quello corretto, per quello ci sono i caratteri speciali (+,/ e =) che non dovrebbero esserci nell’output dello sha256

**Comment by amollicone1982** [comment]
Grazie ho risolto. facevo encoding base64
