### ISSUE TITLE
segnalazione attributo certificato revocato su PDND di collaudo ma i servizi funzionano correttamente

### ISSUE THREAD

**Issue by mcasamassima** [pagopa/pdnd-interop-frontend#413]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Siamo fruitori dei servizi SDG esposti da AGID su PDND, ci siamo accorti che compare un messaggio rosso con scritto "sospeso dalla piattaforma" per revoca attributo certificato. Inoltre i servizi in questione continuano a funzionare regolarmente.

**Step per riprodurre il bug**
1. Vai su 'Le tue richeste'
2. Clicca su 'arch-common-service_SDG, v. 8'
3. Vedi l'errore "Stato della richiesta - sospeso dalla piattaforma"

**Comportamento atteso**
Cosa ti aspetteresti?

**Il codice IPA del tuo ente**
INAIL
Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente

**Data e ora in cui si è riscontrato il problema**
08/05/2023 h. 09:58

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore 

**Screenshot**
![image](https://user-images.githubusercontent.com/42301624/236769153-6b17d862-084f-46e2-9f08-af3941ca7f10.png)

**Note**

**Comment by FedericaSicchiero** [comment]
Buongiorno,
grazie della segnalazione abbiamo preso in carica il bug.

**Comment by mcasamassima** [comment]
client_id=a75043f0-c478-420c-84bd-194ecedb45e8&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=client_credentials&client_assertion=ew0KCSJ0eXAiOiAiSldUIiwNCgkiYWxnIjogIlJTMjU2IiwNCgkia2lkIjogIjZ4cEd3ajNoUXhQaW81NzE5TnJpbFFlVW9mOU1BRFVqSHBVbkpjenRNQkkiDQoNCn0.ew0KImlzcyI6ICJhNzUwNDNmMC1jNDc4LTQyMGMtODRiZC0xOTRlY2VkYjQ1ZTgiLA0KImlhdCI6IDE2ODM3ODg4NDUsDQoibmJmIjogMTY4Mzc4OTQ0NSwNCiJleHAiOiAxNjg0OTk5MDQ1LA0KImF1ZCI6ICJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwNCiJqdGkiOiAiR0EzODdEMjMxNTFDQjAzODFDRERCOEY5MDA1MzFDQTYiLA0KInN1YiI6ICJhNzUwNDNmMC1jNDc4LTQyMGMtODRiZC0xOTRlY2VkYjQ1ZTgiLA0KInB1cnBvc2VJZCI6ICIyMzEwODliYS1iZmI3LTQwNzQtYmQ4ZS1hZTEwMTI0MjRhNTkiDQp9.ZSrVR7v1dijrrm0mLGm6tx7We8O3UJOiodNFbLE__xn_wJ6-FcaniNfnowogYExvT58nm4XpehdaC4dROtKfLVLiKyWVXjkoDC-kTeG8og9DjrLFH8ECbKrOVJPS6v6ms7b5g23Z0XF21r32QCGvxBa-buKsQ5euD_alXrRRio1cCUH25vaeDBdKAj_oJfUEd2LGd8XtWGfavTlnmrINwRHY961dgqHwDOJF407j4gOcd-E40TJ5fe5sQQ0YRK6PhRSRILiw-pjPh7leXoM38UHLuco_HvefE72Vh0Ghm7dbRVNYtez61JCoRxhik

**Comment by FedericaSicchiero** [comment]
Buongiorno e mi scuso per il ritardo nella risposta, stiamo lavorando su questo fix e siamo quasi arrivati alla conclusione.
Aggiorno il ticket appena viene rilasciato tutto.

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo visto che l'attributo SDG è stato revocato dall'erogatore che sarebbe quindi da contattare direttamente per capire il motivo.
