### ISSUE TITLE
Problema scelta attributi certificati nella definizione di un e-service

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#415]
**Descrivi il bug**
Nella fase di definizione di un'e-service ottengo un "Errore del server" quando provo a selezione un'attributo certificato.
**Step per riprodurre il bug**
1. Vai su 'Erogazione/I tuoi servizi'
2. Clicca su 'Crea nuovo'
3. Selezione "Aggiungi nuovo attributo" nella sezione "ATTRIBUTI CERTIFICATI"
4. Selezione "Aggiungi"
5. Vedi l'errore

**Comportamento atteso**
Elenco degli attributi certificabili

**Il codice IPA del tuo ente**
agid

**Data e ora in cui si è riscontrato il problema**
11/05/2023 13:35

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
es. Amministratore (operatore amministrativo), Operatore API, Operatore di sicurezza

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, stiamo cercando di capire il problema, grazie della segnalazione

**Comment by vintra73** [comment]
Grazie

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, abbiamo rilasciato il fix per gli attributi, ora dovrebbe funzionare tutto.

**Comment by vintra73** [comment]
Buongiorno @FedericaSicchiero volevo segnalarti che il fix ha risolto il blocco che avevo riscontrato, ma mi risulta che ci sia un errore gli attributi in quanto non ritrovo più le "Catagorie" (ad esempio "Enti Pubblici Non Economici (C3)") delle amministrazioni ma riscontro il riferimento alle singole amministrazione (ad esempio "agid").

Questa nuova configurazione rende complesso la gestione da parte degli eorgatori che si trovereberro nella necessità di settare  nella sngolarità le singole amministrazioni fruitrici.

**Comment by FedericaSicchiero** [comment]
Ciao @vintra73, grazie della segnalazione l'ho passata subito al team.

**Comment by vintra73** [comment]
Ti segnalo che riscontro un'altra issue sullo stesso tema, vedi https://github.com/pagopa/pdnd-interop-frontend/issues/419

**Comment by vintra73** [comment]
Chiudo la presente in quanto ho riscontrato la risoluizione del problema segnalato.

Grazie
