### ISSUE TITLE
Malfunzione su scelta attributi certificati in fase di pubblicazione e-service

### ISSUE THREAD

**Issue by nicolalaginestra** [pagopa/pdnd-interop-frontend#419]
Descrivi il bug
Nella fase di creazione di un nuovo e-service la lista degli attributi certificati contiene una lista non conforme alla documentazione.
Step per riprodurre il bug

Vai su 'Erogazione/I tuoi servizi'
Clicca su 'Crea nuovo'
Selezione "Aggiungi nuovo attributo" nella sezione "ATTRIBUTI CERTIFICATI"
Selezione "Aggiungi"
La lista contiene un elenco di enti preso da non si sa dove, mentre dovrebbe contenere un elenco di categorie
di enti presenti sull'IPA così come indicato in documentazione.

Azienda segnalante
InfoCamere per conto del Comune di Porto San Giorgio

Data e ora in cui si è riscontrato il problema
16/05/2023 11:15

Ambiente
Collaudo

Quali permessi ha la tua utenza?
Operatore API, Operatore di sicurezza

Screenshot
in allegato screen

Note
Avevo segnalato via mail il giorno 11/05/2023 una malfunzione nello stesso punto. La scorsa volta il sistema restituiva tuttavia un errore.
![listaAttributiCertificatiErrata](https://github.com/pagopa/pdnd-interop-frontend/assets/105792858/341b4d6c-b0dc-4686-b88b-f0ba5b45d1bc)

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione. Stiamo controllando come mai si veda così a seguito del fix sugli attributi che in precedenza davano errore.

**Comment by nicolalaginestra** [comment]
Buongiorno, ci sono novità sulla risoluzione di questo bug?
Grazie

**Comment by vintra73** [comment]
Buongiorno @FedericaSicchiero segnalo anche io che constato lo stesso problema:
- per gli attributi certificati in PDND collaudo non riscontro più la possibilità di selezionare la categoria IPA delle PA

Sarebbe auspicabile avere la possibilità di selezionare anche la Titopogia IPA delle PA.

Al momento sembra disponibile solo la possibilità di selezionare la singola PA.

Resto in attesa di aggiornamenti.

Grazie

**Comment by FedericaSicchiero** [comment]
ciao @vintra73, al momento stiamo esponendo i seguenti attributi certificati:
- categorie IPA
- enti IPA
- tipologia “Pubblica Amministrazione”, quindi la tipologia c'è ma limitata a PA

**Comment by nicolalaginestra** [comment]
Buongiorno,
confermo che è possibile scegliere la tipologia dell'IPA. Specifico solo per precisione e completezza che l'attributo tipologia che indica una PA è "Pubbliche Amministrazioni" (al plurale) e non "Pubblica Amministrazione" (al singolare).
Ciò precisato chiudo la issue.

Grazie

**Comment by nicolalaginestra** [comment]
Buongiorno,
confermo che è possibile scegliere la tipologia dell'IPA. Specifico solo per precisione e completezza che l'attributo tipologia che indica una PA è "Pubbliche Amministrazioni" (al plurale) e non "Pubblica Amministrazione" (al singolare).
Ciò precisato chiudo la issue.

Grazie
