### ISSUE TITLE
Granularità degli attributi verificati in OR

### ISSUE THREAD

**Issue by ruggerocastagnola** [pagopa/pdnd-interop-frontend#42]
@amollicone1982 dice: "A noi servirebbe, entro Aprile, che lato fruitore lo stesso possa scegliere tra gli attributi in "oppure" (OR) ed a noi arrivare solo quelli scelti. Farete una cosa del genere?"

**Comment by ruggerocastagnola** [comment]
Tracciato internamente come [PIN-1227](https://pagopa.atlassian.net/browse/PIN-1227)

**Comment by marcocipri** [comment]
per come l'ho capito nella breve chiacchera con Angelo, un Fruitore potrebbe avere diritto ad una richiesta di fruizione in virtù di più di un attributo (per esempio comune del nord, comune con più di 250.000 abitanti).
La richiesta di Sogei è che il fruitore possa dichiarare di volta in volta quali usa per la sua richiesta.
una possibile soluzione è farlo in fase di dichiarazione della Finalità con l'analisi del Rischio?

**Comment by amollicone1982** [comment]
ci vogliamo sentire in una brevissima call di pochi minuti settimana prossima?. Casomai facciamo un giro sul frontend.
Fisssatela voi nel caso

**Comment by ruggerocastagnola** [comment]
Secondo me un'altra soluzione è quella che avevamo anche già progettato, per la quale c'è un design pronto. Cioè che il fruitore, all'atto dell'inoltro della richiesta di fruizione, inserisce la documentazione per gli attributi che vuole verificati. Così potremmo, anche lato erogatore, tenere traccia di quali attributi il fruitore vuole verificati. Sarei per tenere separati attributi e finalità, c'è già molta complessità su quello, specialmente per gli attributi verificati. Comunque parliamone internamente

**Comment by marcocipri** [comment]
il modello si applica se se un fruitore ha necessità di accedere una volta in virtù di "comune del nord" e un'altra volta come "comune con più di 250.000 abitanti" senza dover staccare 2 richieste di fruizione sullo stesso e-service?

**Comment by marcocipri** [comment]
Sogei ha anche la necessità di poter recuperare le caratterisctiche dell'attributo via API.

**Comment by ruggerocastagnola** [comment]
Ah, adesso ho capito meglio. No, purtroppo no, e quello che ho detto prima non lo risolverebbe. Allora dobbiamo capire

**Comment by ruggerocastagnola** [comment]
Chiudo questa issue. La discussione sta avvenendo altrove e questa casistica non dovrebbe presentarsi, stando alle ultime notizie ricevute
