### ISSUE TITLE
Impossibile creare nuove finalità per gli eservice 

### ISSUE THREAD

**Issue by mcasamassima** [pagopa/pdnd-interop-frontend#426]
**Descrivi il bug**
La creazione nuova finalità in produzione non è possibile se non per un solo servizio.

**Step per riprodurre il bug**
1. Vai su 'Le tue finalità'
2. Clicca su 'Crea nuovo'
3. Nella tendina degli e service da associare vedi solo "C001–servizioNotifica erogato da Ministero dell'Interno" e nient'altro, nonostante ci sarebbero gli altri eservice da associare le cui richieste sono attive 

**Comportamento atteso**
tendina degli e service da associare con altre voci e non con una sola

**Il codice IPA del tuo ente**
INAIL

**Data e ora in cui si è riscontrato il problema**
18/05/2023 h. 10:49

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Amministratore 

**Screenshot**
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/42301624/28668450-af07-43d9-9ec1-4322f04d442a)

**Note**

**Comment by FedericaSicchiero** [comment]
Buongiorno, effettivamente è un po' ingannevole la scelta che viene permessa ora e stiamo valutando come sistemarla. 
La lista seleziona automaticamente il primo e-service disponibile dalla lista degli e-service, ma cliccando sulla X e cancellando quindi la selezione dovrebbe comparire la lista di tutti gli e-service per cui la richiesta di fruizione è attiva.
