### ISSUE TITLE
Pubblicazione su PDND di API 'geografiche' di tipo WFS e WMS

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#427]
Buon pomeriggio,
recentemente il Comune di Torino, in uno specifico confronto, ha verificato con AGID che nulla osta, ai fini della partecipazione definiti ai bandi di finanziamento di cui alla misura 1.3.1 del PNRR, relativa all'esposizione di API su PDND, alla scelta di pubblicare su PDND API 'geografiche' di tipo WFS e WMS (o almeno di uno tra i due standard). Questa possibilità è, secondo AGID, giustificabile grazie al fatto che WFS, WMS e simili sono standard internazionali maturi e ampiamente diffusi.

Tuttavia, l'interfaccia utente di PDND chiede, in fase di definizione di un'API da erogare di scegliere tra i soli standard Rest o SOAP. Inoltre, successivamente, l'interfaccia utente di PDND richiede di caricare un file o OPENAPI o WSDL  a seconda della scelta Rest o SOAP. 

La domanda è perciò la seguente: è possibile su PDND definire l'erogazione di un'API WFS o WMS (o di almeno di uno tra i due tipi), che non sono in realtà ne di tipo Rest ne di tipo SOAP (cosa che, come indicavo, AGID ha non ha escluso)?
In particolare, quali azioni devono essere eseguite dallo user che definisce su PDND le caratteristiche dell'interfaccia, partendo dal fatto che, in questo momento, egli dovrebbe scegliere necessariamente uno tra i tipi Rest o SOAP? quali tra i due tipi bisogna scegliere per pubblicare un'API WFS o WMS?
Successivamente, PDND impedirebbe di caricare un file di definizione dell'interfaccia dell'API che non rispetti gli standard WSDL o OpenAPI o accetterebbe file di interfaccia di tipo WFS / WMS?

Grazie e cordiali saluti,
Corrado Tamietti,
CSI Piemonte

**Comment by mfortini** [comment]
Nel catalogo API di Developers Italia è presente la documentazione OpenAPI di un servizio WMS, da cui si potrebbe prendere spunto (non tutti i metodi sono documentati): https://developers.italia.it/it/api/ade-cartografia-wms

**Comment by simone-capitani** [comment]
Buongiorno a tutti,
provo ad integrare le istanze di @ctamietti. La documentazione a cui fa riferimento @mfortini è relativa ad un classico servizio WMS, il cui protocollo però, non è aderente alle specifiche OpenAPI. Ci chiediamo quindi se questa tipologia di servizi (cioè quelli normati dall'Open Geospatial Consortium e basati sostanzialmente su XML ma non su specifiche SOAP) siano ammissibili o meno ai fini della pubblicazione su PDND. Da ciò che abbiamo compreso, questi servizi non troverebbero attualmente implementazione abilitante sulla PDND stessa. In soldoni attenderei il responso del confronto che @FedericaSicchiero avrà con il team di sviluppo. 
E' corretto quanto affermo? 
Grazie mille!
Simone Capitani
CSI Piemonte

**Comment by FedericaSicchiero** [comment]
Buongiorno a tutti,
per rispondere a @ctamietti e @simone-capitani dopo aver sentito il team:
noi per ora utilizziamo solo tecnologia SOAP e REST e non abbiamo visibilità o evidenza sulle iniziative AGID, quindi non possiamo rispondere a proposito di quali azioni seguiranno dal loro lato.
Per quanto riguarda i servizi normati dall'Open Geospatial Consortium e basati su XML ma non su specifiche SOAP sono ammissibili, ma solo se compliant con le tecnologie che usiamo.

A disposizione,
Federica
