### ISSUE TITLE
Timeout durante la richiesta del voucher in ambiente di collaudo

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#434]
Buongiorno, 
abbiamo effettuato dei test in ambiente di collaudo e abbiamo riscontrato un numero elevato di connection timeout nella fase di richiesta del voucher. 
In particolare su un totale di circa 50 richieste nell'intervallo temporale di due ore 25 sono andate appunto in Connection timeout.

Potete darci un riscontro?

**Comment by mrubiero** [comment]
Buonasera,
i test sono stati effettuati dalle 15:08 alle 17:09 del giorno 23/05/2023 con un client del Ministero del Lavoro verso l'ente INPS

**Comment by FedericaSicchiero** [comment]
Buongiorno, stiamo verificando perchè a noi non compaiono segnalazioni di timeout nel periodo indicato.
Usate un proxy per caso?

**Comment by mrubiero** [comment]
Buondì, 
no non usiamo proxy.

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo verificato in tutti i nostri log ma non ci risultano errori di nessun tipo quindi non sappiamo dire perchè è capitato. Se dovesse succedere di nuovo potete avvisarci per tempo? Grazie

**Comment by mrubiero** [comment]
Buongiorno,
abbiamo notato che invocando l'endpoint:
   • https://auth.uat.interop.pagopa.it/token.oauth2
nella response HTTP ricevuta è presente l'header HTTP 'Connection: Keep-Alive', ma non è presente l'header 'Keep-Alive'.

Dai nostri test di integrazione, abbiamo riscontrato che non trovando l'header 'Keep-Alive', il client HTTP che utilizziamo mantiene la connessione attiva per un tempo indefinito e questo ha provocato dei read timeout riscontrati durante i nostri test.

Per modificare il comportamento del nostro client HTTP, abbiamo impostato un parametro di default che nel caso in cui l'header 'Keep-Alive' non fosse presente, consente di chiudere la connessione correttamente, senza generare alcun timeout.

Tuttavia vi volevamo chiedere se fosse opportuno restituire nelle response HTTP del vostro server anche l'header 'Keep-Alive', cosicchè qualsiasi connessione al vostro server possa essere gestita nel modo migliore da qualsiasi client HTTP.

Grazie
