### ISSUE TITLE
Impossibile caricare file OpenAPI in creazione nuovo e-service

### ISSUE THREAD

**Issue by AlessioMarinelli** [pagopa/pdnd-interop-frontend#435]
**Descrivi il bug**
Durante lo step di caricamento del file JSON o YAML OpenAPI che descrive gli endpoint, il frontend restituisce sempre l'errore 

```Non è stato possibile caricare il documento.```
```Assicurati di aver caricato il documento corretto. Per favore riprova! Attenzione: il documento non può contenere la stringa "localhost".```

**Il file non contiene tuttavia né localhost, né 127.0.0.1**

Il file, a cui è stata rimosso solo l'indirizzo reale dell'API da chiamare, che è nel formato `http://<ip>/api/Test-PDND/v1`, è disponibile [a questo indirizzo](https://gist.github.com/AlessioMarinelli/447483445f5b0016f56a13aa62d26d0a).

**Step per riprodurre il bug**
1. Effettua il login a Interop > Collaudo
2. Vai su Erogazione > I tuoi e-service
3. Clicca su 'Crea Nuovo'
4. Compila la scheda 'Generale' e clicca su 'Salva bozza e prosegui'
5. Compila la scheda 'Versione' e clicca su 'Salva bozza e prosegui'
6. Clicca su 'Trascina qui il file o clicca qui per selezionarlo dal tuo computer'
7. Seleziona il file JSON da caricare
8. Clicca su 'Carica'
9. Vedi l'errore

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/93653654/197c2b55-9cb2-44ea-8d62-88ec3a8f4754)

**Comportamento atteso**
Il comportamento atteso è che il caricamento vada a buon fine, o che sia presentato l'errore reale per cui il file viene rifiutato

**Il codice IPA del tuo ente**
r_marche

**Data e ora in cui si è riscontrato il problema**
30/05/2023 h. 12:15

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/93653654/038d9df0-cac1-40f0-bbb3-5a58cfb694c0)

**Note**
Ispezionando la console emerge un endpoint che restituisce 403 Forbidden contestualmente al tentativo di upload del file

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/93653654/08625270-b7b2-40c3-8e34-bd2dbc27e32f)

**Comment by AlessioMarinelli** [comment]
Aggiungo che svuotare la cache (come consigliato in #273 ) o navigare in modalità incognito **NON** risolve il problema

**Comment by ruggerocastagnola** [comment]
Buongiorno Alessio,

ha possibilità di usare un dominio invece di un IP all'interno del file OpenAPI (mi riferisco alla proprietà "servers[n].url" ovviamente)? Se sì, quella è la soluzione veloce. In caso contrario, facciamo una valutazione interna ma credo avremo tempi più lunghi, abbiamo ragioni per valutare se mantenere il blocco

Un saluto

Ruggero

**Comment by AlessioMarinelli** [comment]
Provo a verificare con il dipartimento sistemi

**Comment by FedericaSicchiero** [comment]
Chiudo il ticket ma con possibilità di riaprirlo in caso di aggiornamenti.
