### ISSUE TITLE
Associazione di una finalità ad un client

### ISSUE THREAD

**Issue by fabiologiudice** [pagopa/pdnd-interop-frontend#437]
Salve. ho necessità di associare una finalità ad un client e-service. ma il sistema non mi consente di farlo. Io per il momento sono un operatore di sicurezza/API. Sono necessari altri privilegi per farlo?

**Comment by FedericaSicchiero** [comment]
Buonasera, si per poterlo fare bisogna essere amministratori. Gli operatori hanno poteri limitati in questo caso.

**Comment by fabiologiudice** [comment]
Ho fatto associare il client alla finalità..ma quando faccio la richiesta per ottenere il token JWT continuo ad ottenere lo stesso errore (rif ambiente di produzione): 

{"correlationId":"b05a3511-6dd1-435b-a1af-35976ccc15ab","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

Sotto le chiamate di esempio: 

python create_client_assertion.py \
  --kid=K3PXSh1YlNn82DMWkxR9ovXsB55rqaO_bUeWrcRXjDU \
  --alg=RS256 \
  --typ=JWT \
  --issuer=1b8d5896-1afa-4b33-8e10-bc2aaea3c705 \
  --subject=1b8d5896-1afa-4b33-8e10-bc2aaea3c705 \
  --audience=auth.interop.pagopa.it/client-assertion \
  --purposeId=d532bd30-9ec4-48dd-bfe2-c5ce1fcd6977 \
  --keyPath=isee-key.rsa.priv

curl --location --request POST https://auth.interop.pagopa.it/token.oauth2 --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=1b8d5896-1afa-4b33-8e10-bc2aaea3c705' --data-urlencode 'client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IkszUFhTaDFZbE5uODJETVdreFI5b3ZYc0I1NXJxYU9fYlVlV3JjUlhqRFUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIxYjhkNTg5Ni0xYWZhLTRiMzMtOGUxMC1iYzJhYWVhM2M3MDUiLCJzdWIiOiIxYjhkNTg5Ni0xYWZhLTRiMzMtOGUxMC1iYzJhYWVhM2M3MDUiLCJhdWQiOiJhdXRoLmludGVyb3AucGFnb3BhLml0L2NsaWVudC1hc3NlcnRpb24iLCJwdXJwb3NlSWQiOiJkNTMyYmQzMC05ZWM0LTQ4ZGQtYmZlMi1jNWNlMWZjZDY5NzciLCJqdGkiOiI5M2JhYzY5Yy0xOTQ5LTQ3YzctYTQ2YS0wZDViMDdhZTllMTkiLCJpYXQiOjE2ODU0NTYxNTUsImV4cCI6MTY4ODA0ODE1NX0.ECkoFQDhAPIoiNLrqpTOKfXVAhmvq-5O88YKXH1VXIdvqCsIHW11Ck5zsGhaGPtBK91-2wKhU61EWEdJv-OPNFH37vkpt4pIlHng7ezwKSf2IojOi2U12V54ks_EKfPiBY9lAWd_vV1tKlwyAmMLIiR0JL31_ozT2lx7aqER8mT8NKNTMMbMm8kGrEC1xRy9gvdaodoQrBIOHRhhiiQ0BvhhD_w5JySe9kCHmhF55GInT_5coT13VYYsQgPcufeUnQ_Kr9DdSz7_Cbv0o2c3c34Ytd__AO6d24_rBTt8FCw2d-6LOvoAIA6y9AVbYCAa0EjbWzeqY1LUSnNm6kVyIQ' --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' --data-urlencode 'grant_type=client_credentials'

**Comment by FedericaSicchiero** [comment]
Si da errore perchè la finalità è "In attesa di approvazione" e finchè non passerà a stato Attiva continuerà a dare errore

**Comment by fabiologiudice** [comment]
A me risulta attiva..
![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/105290049/9e69bd1a-8190-45c6-a91d-6d0dc3da29a9)

**Comment by FedericaSicchiero** [comment]
Gli ID incollati sopra corrispondono alla finalità che nello screen è in aggiornamento (quindi come se fosse in attiva)

**Comment by fabiologiudice** [comment]
io mi sto rifererendo alla finalità che si chiama Agevolazio Tariffarie.. che risulta attiva..

**Comment by fabiologiudice** [comment]
--purposeId=d532bd30-9ec4-48dd-bfe2-c5ce1fcd6977

**Comment by FedericaSicchiero** [comment]
Questo purpouseID fa riferimento alla finalità Controllo dichiarazioni a fini tributari, per questo vi da errore. La finalità Agevolazioni tariffarie è attiva ma non state usando il suo purpouseID.

**Comment by fabiologiudice** [comment]
Salve.. il purposeid che stavo utilizzando l'ho preso dalla definizione del client e-service e non dalla finalità.
Come potete vedere sotto dall'immagine il purposeid è quello che vi ho mandato..
Adesso andando a prendere quello della finalità sono riuscito ad ottenere il voucher. Mi chiedo allora che cosa rappresenta il purposeid presente nel client e-service e/o per quale motivo non è allineato con quello indicato nella finalità.

![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/105290049/d5dd7e4d-3fd7-49d0-80bc-05c5c16be021)

**Comment by FedericaSicchiero** [comment]
Perchè più finalità possono essere associate ad un client e più client possono essere associati ad una finalità, per questo la visualizzazione appare in quel modo. In ogni caso lo faccio presente al team in modo da capire se è possibile cambiare la UI e rendere tutto più chiaro, grazie del feedback.

**Comment by fabiologiudice** [comment]
Mi torna quello che dice. Ma chiedevo che : una volta associato un client ad una finalità questa potesse rimanere selezionata nella maschera di ispezione del client e-service.
Cmq Grazie per il supporto.
