### ISSUE TITLE
Assenza e-service attivi nella definizione della finalità

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#446]
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/29304687/3f6bd5b4-23f2-4a61-9e76-6393cdd20462)
Il ministero dell'Interno ha sottoscritto 5 e-service dell'erogatore sdg che risultano in stato attivo (immagine allegata in cui se ne possono vedere due).
Al momento della definizione della finalità (come previsto dalla linee guida) abbiamo la possibilità di sceglierne soltanto uno nella tendina degli e-service da associare (non compaiono gli ulteriori quattro e-service attivi)
![problema](https://github.com/pagopa/pdnd-interop-frontend/assets/29304687/479e5cce-ccb1-41b7-a660-b9e43b9c129b)

Buona giornata

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione, aggiorno il ticket appena ho aggiornamenti.

**Comment by FedericaSicchiero** [comment]
Abbiamo un bug aperto a proposito su cui stiamo lavorando, perchè la lista seleziona automaticamente il primo e-service disponibile dalla lista degli e-service, ma cliccando sulla X e cancellando quindi la selezione dovrebbe comparire la lista di tutti gli e-service per cui la richiesta di fruizione è attiva.
