### ISSUE TITLE
Errore durante l'indicazione dell'Area Geografica

### ISSUE THREAD

**Issue by RaffaeleReale** [pagopa/pdnd-interop-frontend#449]
**Descrivi il bug**
All'accesso alla piattaforma selfcare alla richieste di indicare "Area Geografica" selezionando l'area e premendo aggiungi appare un errore impresto

**Step per riprodurre il bug**
1. Vai su Dashboard dell'Area Riservata (appena dopo il login SPID)
2. Alla richiesta di Indicare l'area geografica scegliere Nazionale e fare aggiungi
4. Vedi l'errore

**Comportamento atteso**
Che venga valorizzata l'area di competenza del proprio ente attualmente non valorizzata

**Il codice IPA del tuo ente**
c_d123

**Data e ora in cui si è riscontrato il problema**
06/06/2013 12:10

**Ambiente**
Dashboard appena entrati

**Quali permessi ha la tua utenza?**
Operatore API, Operatore di sicurezza

**Screenshot**
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/29810456/c770b960-f312-4291-a84d-3e0b8e94d725)
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/29810456/64225cf6-5b23-45cb-afd8-f8cc3939c271)

**Note**
Probabile issue #361 collegato?

**Comment by FedericaSicchiero** [comment]
ciao Raffaele, passo la segnalazione a Selfcare perchè riguarda la loro area. 
Tra ieri e oggi stanno rilasciando delle nuove funzioni quindi è probabile che questo errore sia dovuto ai deploy che stanno facendo. Come hai detto può essere che la issue 361 sia collegata anche perchè non dovrebbe apparire un pop up con scritto "Test" ma "Collaudo".

**Comment by FedericaSicchiero** [comment]
Buongiorno Raffaele, hanno detto di aver sistemato gli errori segnalati su questo ticket. Già che c'ero ho spinto anche per il bug di entrata su collaudo segnalato nella #361

**Comment by FedericaSicchiero** [comment]
ciao @RaffaeleReale, ci hanno detto di aver sistemato questi problemi se volete riprovare. Grazie

**Comment by RaffaeleReale** [comment]
Grazie si confermo che ora funziona!
