### ISSUE TITLE
Impossibile creare un nuovo client e-service

### ISSUE THREAD

**Issue by marcob71** [pagopa/pdnd-interop-frontend#452]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

In ambiente di collaudo andando a creare un nuovo client e-service viene generato un errore nel momento in cui si selezionano i membri del client

**Step per riprodurre il bug**
1. Vai su 'Ambiente di collaudo' -> 'Fruizione/I tuoi client e-service'
2. Clicca su 'Crea nuovo'
3. inserisci le informazioni del client e clicca su 'Aggiungi' nella sezione 'Membri del client'
4. compare un popup in cui si dovrebbe poter scegliere gli utenti da inserire ma questa maschera va in errore.

**Comportamento atteso**
Dovrei poter aggiungere i membri del client

**Il codice IPA del tuo ente**
c_d969
Comune di Genova

**Data e ora in cui si è riscontrato il problema**
08/06/2023 h. 08:50

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
![1](https://github.com/pagopa/pdnd-interop-frontend/assets/49031428/399fafc2-dc54-4070-85a7-fd91d169f78a)
![2](https://github.com/pagopa/pdnd-interop-frontend/assets/49031428/655f8ee4-87b1-46fa-a1f7-de87e9d765fa)

![Cattura](https://github.com/pagopa/pdnd-interop-frontend/assets/49031428/571431d8-f189-485e-9572-702ac8d59232)

**Comment by FedericaSicchiero** [comment]
Buonasera, abbiamo rilasciato il fix e ora non dovrebbero esserci più errori nella creazione di nuovi client. Grazie

**Comment by FedericaSicchiero** [comment]
Chiudo il ticket, se necessario si può riaprire e aggiungere informazioni per una risoluzione ottimale.
