### ISSUE TITLE
Impossibilità di aggiungere un nuovo utente

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#454]
**Descrivi il bug**
Impossibilità di aggiungere un nuovo utente

**Step per riprodurre il bug**
1. Vai su 'Utenti'
2. Clicca su 'Aggiungi utente'
3. Compila form per l'utente da aggiungere
4. Clicca su 'Continua'
5. Clicca su 'Assegna'
6. Vedi l'errore 'Non è stato possibile aggiungere l'utente.'

**Comportamento atteso**
Aggiunta nuovo utente

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
08/06/2023 h.13.16

**Ambiente**
Produzione e Collaudo

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
ciao Vincenzo, grazie della segnalazione. L'avevo già fatto presente a Selfcare e condivido anche questa issue.

**Comment by vintra73** [comment]
Grazie @FedericaSicchiero,
resto in ascontro su questo tread per aggiornamenti?

**Comment by FedericaSicchiero** [comment]
Si perfetto ti aggiorno qui

**Comment by MaxTheGlue** [comment]
Buongiorno sto riscontrando anche io lo stesso errore

**Comment by FedericaSicchiero** [comment]
@MaxTheGlue avrei bisogno di ruolo, ente e nome di tutte le persone che riscontrano errore così aggiungo tutto al ticket aperto a chi se ne sta occupando

**Comment by MaxTheGlue** [comment]
@FedericaSicchiero si tratta di GEROPA SRL per il ruolo di Amministratore nella persona di Massimiliano Spertino

**Comment by vintra73** [comment]
Buonasera @FedericaSicchiero 
ci sono aggiornamenti in merito il bug segnalato?

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno @vintra73, al momento no, sto seguendo il ticket che ho aperto a Selfcare e ci stanno ancora lavorando

**Comment by vintra73** [comment]
Grazie, resto in attesa

**Comment by andreatantillo** [comment]
Buongiorno,

riscontro anche io il problema “_Non è stato possibile aggiungere l'utente. Riprova._" Tuttavia, segnalo che si presenta solo in ambiente di collaudo. Nell'ambiente di produzione viene aggiunto correttamente.

**Comment by andreatantillo** [comment]
Il problema sembra ora essere rientrato. Un Comune è riuscito ad abilitarmi.

**Comment by FedericaSicchiero** [comment]
@andreatantillo ottimo grazie dell'aggiornamento, io intanto sto spingendo in modo che sistemino anche le altre utenze

**Comment by vintra73** [comment]
ciao @FedericaSicchiero confermo che il roblema segnalato è stato risolto.

Un dubbio, ho visto che è possibile aggiungere il ruolo "Amministratore" in PDND collaudo ad un utente nella fase di registrazione, ma non trovo la feature per assegnare il ruolo "Amministratore" per un utente già registrato. Puoi aiutarmi in merito?

Grazie

**Comment by vintra73** [comment]
confermo che il problema è risolto

chiudo il presente issue

grazie
