### ISSUE TITLE
Errore nell' aggiornare la fruizione alla nuova versione di un e-service

### ISSUE THREAD

**Issue by marcob71** [pagopa/pdnd-interop-frontend#455]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Impossibile aggiornare la richiesta di versione di uno deglie-service ANPR da v1 a v2

**Step per riprodurre il bug**
1. Vai su 'Fruizione/Le tue richieste' e seleziona uno degli e-service in versione 1 di ANPR
2. Clicca su 'Visualizza' e poi premere su 'Aggiorna' e poi 'Conferma'
3. Appare l'errore 'Non è stato possibile aggiornare la richiesta. Per favore, riprova!'

**Comportamento atteso**
l'aggiornamento della richiesta di fruizione alla versione nuova (la v2)

**Il codice IPA del tuo ente**
c_d969

**Data e ora in cui si è riscontrato il problema**
09/06/2023 08:40 circa

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
![errore0](https://github.com/pagopa/pdnd-interop-frontend/assets/49031428/25612a50-4867-4dc2-8916-94f7ade76c81)
![errore](https://github.com/pagopa/pdnd-interop-frontend/assets/49031428/1abd557e-76ad-4b88-82d2-9e710d2cff90)

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione, l'ho fatta presente al team e aggiorno la issue appena abbiamo aggiornamenti.

**Comment by FedericaSicchiero** [comment]
Buonasera, si tratta di un bug che verrà risolto con il prossimo rilascio in produzione perchè se una richiesta di fruizione è in stato "In attesa di approvazione" la stessa non può essere aggiornata alla versione successiva. Grazie
