### ISSUE TITLE
[clarification] Modalità richiesta di client assertion

### ISSUE THREAD

**Issue by faberFabry** [pagopa/pdnd-interop-frontend#456]
Salve,

come asserito nella documentazione paragrafo Client e materiale crittografico , 
la chiave pubblica viene caricata su pdnd interoperabilità mentre la chiave privata rimane in mano all'aderente, quindi all'ente, che la manterrà al sicuro :

in caso di implementazione software da parte di un'azienda esterna  privata, che farà girare il  client su un host esterno all'ente, qual è il modo corretto per dare al fornitore la possibilità di effettuare l'operazione di client assertion?

grazie

Fabrizio

**Comment by FedericaSicchiero** [comment]
Buongiorno,
per questo genere di situazione abbiamo pensato appositamente al client, dove possono essere inserite le utenze di aziende esterne che poi devono effettuare le varie operazioni e che però non hanno poteri limitati per quanto riguarda la creazione di rapporti amministrativi (iscriversi agli e-service, associare questi alle finalità etc.).

Grazie,
Federica

**Comment by faberFabry** [comment]
grazie per la risposta,

quindi è corretto censire un'utenza "operatore di sicurezza" che si riferisce ad una persona di un'azienda privata?

**Comment by FedericaSicchiero** [comment]
Corretto, Operatore API o Operatore di sicurezza sono ruoli che vanno bene per aziende private.

**Comment by faberFabry** [comment]
Perfetto, la ringrazio per il chiarimento !

chiudo il ticket

saluti

Fabrizio
