### ISSUE TITLE
Problemi intermittenti nell'ottenimento del token - PDND Collaudo

### ISSUE THREAD

**Issue by ritaceresi1** [pagopa/pdnd-interop-frontend#457]
Buongiorno, 
negli ultimi giorni stiamo ricevendo, come Ministero di Giustizia, sull'Ambiente di Collaudo di PDND, problemi intermittenti sull'esecuzione  di un API e l'errore sembrerebbe il non ottenimento del Token. Questo sta creando preoccupazione, perchè dovrebbe essere in fase di partenza il piano di test di Servizi API del Ministero da esporre sulla PDND.
Di seguito la descrizione dell'errore che spesso verifichiamo; qualsiasi indicazione, sugerimento per risolvere o capire dove possa essere il problema sarebbe importante. IL fatto che a volte funzioni ci farebbe pensare che la configurazione non sia sbagliata (altrimenti l'errore sarebbe sistematico).
Grazie
Rita

Il servizio SOAP di richiesta (è molto semplice, ma serve come esempio) per cui verifichiamo spesso, ma non sempre l'errore, è il seguente (ovviamente, il testo contenuto nella richiesta può essere qualunque, visto che il servizio si limita a restituire lo stesso testo).

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tes="http://schemi.giustizia.it/testservice">
   <soapenv:Header/>
   <soapenv:Body>
      <tes:TestRequest>
         <tes:TestValue>Prova microfono</tes:TestValue>
      </tes:TestRequest>
   </soapenv:Body>
</soapenv:Envelope>

Quando si verifica l’errore, cioè quasi sempre, con soapUI si riceve la seguente risposta.

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server.APIUnavailable</faultcode>
         <faultstring xml:lang="en-US">The API Implementation is temporary unavailable</faultstring>
         <faultactor>[http://govway.org/integration</faultactor](http://govway.org/integration%3c/faultactor)>
         <detail>
            <problem xmlns="urn:ietf:rfc:7807">
               <type>[https://govway.org/handling-errors/503/APIUnavailable.html</type](https://govway.org/handling-errors/503/APIUnavailable.html%3c/type)>
               <title>APIUnavailable</title>
               <status>503</status>
               <detail>The API Implementation is temporary unavailable</detail>
               <govway_id>01d7c725-069b-11ee-abc4-0050568b0b28</govway_id>
            </problem>
         </detail>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>

Nella schermata seguente l’errore riportato su GovWay.

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/129849094/d77a42fd-b040-4c20-9ea4-d77aaacfc6ac)

Riscontrato errore durante l'inoltro del Messaggio di cooperazione con identificativo [0719c176-069b-11ee-abc4-0050568b0b28] inviato alla parte destinataria [modipa/MinisteroGiustizia] mediante connettore [https] (location: https://interoperabilitaspccoll.giustizia.it:8443/govway/soap/in/MinisteroGiustizia/TestService/v1): Errore avvenuto durante la consegna HTTP: Risposta del servizio di negoziazione token non valida: Connessione terminata con errore (codice trasporto: 400): {"correlationId":"c7ee4fc3-a4a2-41e1-9222-a539a9a55ec1","errors":[{"code":"015-0008","detail":"****Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}****

Sulla PDND il servizio, di cui il Ministero della Giustizia è sia erogatore che fruitore, si chiama Test PDND Giustizia.

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
abbiamo controllato i log: il problema sembra essere collegato al claim nbf della client assertion che risulta essere invalido. Il claim serve ad indicare da quando in JWT utilizzabile. Nel vostro caso potrebbe essere che stia venendo inserita una data nel futuro.
Il consiglio è di metterlo uguale al claim iat, che indicata il momento in cui è stata creata la client assertion.
Altra nota: i valori devono essere Unix timestamp.
