### ISSUE TITLE
Pulsante "collaudo" non disponibile

### ISSUE THREAD

**Issue by dfranzoni** [pagopa/pdnd-interop-frontend#458]
**Descrivi il bug**
Gentilissimi,
ho aderito alla piattaforma, ho fatto accesso, riesco ad accedere alla "produzione" ma il pulsante per accedere al "collaudo" non è disponibile e non saprei come poterci accedere.

**Step per riprodurre il bug**
1. Vai in 'Area riservata'
2. Clicca su 'Panoramica'
3. Vai su "prodotti attivi"
4. Clicca su "Interoperabilità"
5. nella modale appaiono solo i pulsanti "Annulla" e "Produzione"

**Comportamento atteso**
Dalle guide dovrebbe apparire anche il pulsante "Collaudo"

**Il codice IPA del tuo ente**
ccbimvc

**Data e ora in cui si è riscontrato il problema**
13/06/2023 12:43

**Ambiente**
n.d.

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
Allego screenshot

![Acquisisci schermata Web_13-6-2023_124444_selfcare pagopa it](https://github.com/pagopa/pdnd-interop-frontend/assets/29452040/71cf2ff1-c0fc-48f3-9219-dbcf1ffcc6b5)

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione.
Una domanda: la sua utenza è stata creata durante il processo di onboarding o è stata creata successivamente partendo dalla sezione "utenti" dell'area riservata?

**Comment by FedericaSicchiero** [comment]
Grazie dell'informazione, chiedo a chi si occupa di quella sezione e aggiorno la issue appena ho aggiornamenti.

**Comment by FedericaSicchiero** [comment]
Buongiorno, mi hanno confermato di aver risolto il problema, chiudo il ticket con possibilità di riaprirlo in caso fosse necessario. Grazie
