### ISSUE TITLE
Fruizione PUC, PDND ANPR e-service 

### ISSUE THREAD

**Issue by rnapoli1983** [pagopa/pdnd-interop-frontend#46]
Buongiorno sono Roberto Napoli (Sogei),

stamani abbiamo completato la definizione delle richieste di fruizione in oggetto ai due ANPR e-service.

Tuttavia volevo fare due segnalazioni.

**La prima** è che una delle finalità ci risulta "In attesa di valutazione" ma da ANPR ci fanno sapere, tramite @amollicone1982, che a loro non risulta nulla:

![image](https://user-images.githubusercontent.com/30468060/160367650-095ee4b1-2284-401d-8268-ad1273d2c057.png)

**La seconda** è che non capisco il senso del tab "Chiavi pubbliche" in "Fruizione/I tuoi client/Gestisci client":

![image](https://user-images.githubusercontent.com/30468060/160368351-d53df0af-fecf-4b14-81b8-0e882313dd76.png)

Se dovessi pubblicare una chiave, inserirei quella pubblica che abbiamo messo nel client definito sotto "Interop M2M".

Del resto a noi il client, in figura, ci serve per interagire con ANPR definendone, come è stato fatto, due finalità distinte una per e-service (in questo caso C015 e C021).

Anche tentando di inserirla il sistema ci dà un errore, a mio avviso forse corretto, ma a fronte del quale si rafforza il mio dubbio sul significato, in questa sezione, del tab citato:

![image](https://user-images.githubusercontent.com/30468060/160369316-318f0572-4c4a-49d0-bd3e-8d9d5d644d93.png)

Attendo un vostro gentile riscontro.

Buona giornata.

Cordiali saluti.

Roberto Napoli

**Comment by rnapoli1983** [comment]
Ok Ruggero,  ma facendo così come DTD mi dovrei fornire di due chiavi pubbliche generate da due certificati di firma differenti afferenti sempre all'ente per il quale mi presento.

Facciamo così io ora elimino quella chiave dal client di Interop M2M perchè quello che ci interessa è interrogare ANPR con PDND e la inserisco nel client interessato (quello creato per ANPR) che fa parte della sezione "I tuoi client".

Ma poi in futuro mi confermi che se dovessi chiamare le PDND API tipo /aggrements etc. dovrei avere un'atra chiave pubblica da pubblicare stavolta nel client "Interop M2M", corretto ?

**Comment by ruggerocastagnola** [comment]
Su questo aspetto chiedo per favore a @beetlecrunch di chiarire

**Comment by rnapoli1983** [comment]
Scusa @ruggerocastagnola  mi sono appena accorto di un'altra cosa.

Perchè per la finalità afferente al c021 mi dice che posso staccare token:

![image](https://user-images.githubusercontent.com/30468060/160422662-64f50657-34b0-49ec-b961-8975cfeb6a61.png)

mentre per la finalità afferente al c015 no ? Il client è lo stesso la pub key anche ma le finalità sono diverse:

![image](https://user-images.githubusercontent.com/30468060/160422967-9da2d70b-1f88-4e6b-8e93-34c35f01945a.png)

Grazie mille.

**Comment by ruggerocastagnola** [comment]
Nel frattempo @rnapoli1983, ti chiedo per favore di eliminare la finalità che hai creato per C015 e ricrearla con una stima di carico che sia sotto la soglia dell'erogatore (vedo che la soglia è stata impostata a 10.000 chiamate lato erogatore, questa finalità ne ha 99.000).

In questo modo non c'è bisogno di approvarla in questo momento e potete testare in serenità

**Comment by rnapoli1983** [comment]
Buongiorno, 

prima di chiudere la issue gradirei un chiarimento, che alla fine non è arrivato, sulla tematica dei precedenti post che riporto in ordine cronologico:

https://github.com/pagopa/pdnd-interop-frontend/issues/46#issuecomment-1080725130
https://github.com/pagopa/pdnd-interop-frontend/issues/46#issuecomment-1080734749

in quanto penso sia molto importante per tutti i fruitori non solo per noi.

Il fatto di avere più chiavi pubbliche per interagire con la piattaforma PDND a prescindere dalle finalità, ovvero che sia interrogare l'e-service di un fruitore o un API PDND, devo dire la verità mi lascia perplesso.

Attendo un vostro riscontro.

Grazie mille.

Buona giornata.

Cordiali saluti.

Roberto Napoli

**Comment by rnapoli1983** [comment]
Buongiorno chiudo la issue visto che dell'ultimo aspetto ne stiamo parlando per altri canali.

Vi ringrazio per il supporto.
