### ISSUE TITLE
Verifica di un voucher

### ISSUE THREAD

**Issue by MaxTheGlue** [pagopa/pdnd-interop-frontend#462]
Nella documentazione leggo "L'erogatore scarica la lista di chiavi in uso da un file esposto nella cartella .well-known di PDND Interoperabilità (l'URL corretta è disponibile sull'interfaccia nel back office e cambia in funzione dell'ambiente; a titolo esemplificativo, [questa](https://interop.pagopa.it/.well-known/jwks.json) è quella di produzione)."

Non trovo nel back office l'url per la verifica della firma del voucher.

**Comment by FedericaSicchiero** [comment]
Buongiorno, l'url si trova all'interno della scheda del singolo e-service sotto la voce "I miei e-service" nella sezione "Erogazione", v. screen.
![photo_2023-06-15 10 22 42](https://github.com/pagopa/pdnd-interop-frontend/assets/116075083/06f35a4f-bd44-4bee-bbd4-57a7ebde457d)
