### ISSUE TITLE
call api c020

### ISSUE THREAD

**Issue by DarioCosentino** [pagopa/pdnd-interop-frontend#465]
**Descrivi il bug**
Facendo riferimento alla documentazione "Specifica API" che ho anche allegato
Una volta staccato il token correttamente ricevo 
{
    "type": "[https://govway.org/handling-errors/404/NotFound.html"](https://govway.org/handling-errors/404/NotFound.html%22),
    "title": "NotFound",
    "status": 404,
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "3f7e3e2d6491c3dd053a795d"
}
eseguendo la call al servizio e come sotto riportato 
<?php
$curl = curl_init();
curl_setopt_array($curl, array(
  CURLOPT_URL => '[https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/status'](https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C020-servizioAccertamentoResidenza/v1/status%27),
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'Accept-Type: application/json',
    'Content-Type: application/json',
    'Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InBWLVdaVGJWRjNZZElRSlducm5jZ0c3UEU0QjhhRktGbnphSHFZWkIwX3ciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI1MGUxNjM2Zi1hM2NiLTQ4ZTAtYjE1NS00MTgwZjc5OTE4ZWIiLCJzdWIiOiI1MGUxNjM2Zi1hM2NiLTQ4ZTAtYjE1NS00MTgwZjc5OTE4ZWIiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiNGFiZmJkMWItYmEwYS00YWY1LWFmNDQtYzYxNzhmMmY1NDcwIiwiaWF0IjoxNjg3MjczODk3LCJleHAiOjE2ODk4NjU4OTd9.HrO32-PyPPP_S1c1ClumXpLsKAO5m6z9KLuIe2G2Y0c6YBrVZ7w3UGHjSznQUTr4aQV7uVhJdZ1J1EJJ8RVGrscoHjuunPH4rXl44RW5zpfBkeqIUEKFkvVdesg3qTIPBIl5J5Tn-FBHLXLdigIQCLFlK9ces6HoP3U56DshUHZJN0-YJlj9RTuUxjYjUYV_O1BsfQh_Ox9xYXnW
[Specifica API.zip](https://github.com/pagopa/pdnd-interop-frontend/files/11802236/Specifica.API.zip)
aBI6E1VndTrcSZzZwocZXR-nlL1Myik8dAx4u4ZJccb0Cv1QFSKkFxjSQIY2LTR_lEifhmlWCw_EdCu2yesP_yRqRQMlKtVtEDvokUCi9RlCzjlUD4eOTCn5A8QPQSjrEczeXw',
    'accept: application/problem+json'
  ),
));
$response = curl_exec($curl);

curl_close($curl);
echo $response;

**Step per riprodurre il bug**
vedi request e response sopra riportati

**Comportamento atteso**
Qualcosa che mi faccia capire che almeno il server cui sto facendo riferimento è corretto ed attivo 

**Il codice IPA del tuo ente**
codice IPA: c_d869

**Data e ora in cui si è riscontrato il problema**
20/06/2023

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore

**Comment by FedericaSicchiero** [comment]
Buongiorno,
se il token è stato staccato correttamente il fatto che risponda con errore dipende dall'erogatore stesso che sarebbe da contattare. Se gli ha inseriti si possono trovare i contatti dell'ente all'interno degli e-service.

**Comment by DarioCosentino** [comment]
Nel mio caso l'erogatore è il Ministero degli Interni, ovvero SOGEI.
Ma non trovo alcun riferimento cui segnalare il problema.

**Comment by FedericaSicchiero** [comment]
Noi abbiamo abilitato la possibilità di aggiungere una mail di contatto, ma non essendo un obbligo vuol dire che Sogei non l'ha inserita. Noi purtroppo non abbiamo un contatto da condividere.

**Comment by Defkon1** [comment]
lo stesso errore viene lanciato anche su chiamate non autenticate, quindi è proprio un endpoint mancante lato server...

forse l'endpoint /status è stato inserito nelle specifiche API solo per passare la validazione automatica (https://italia.github.io/api-oas-checker/), ma di fatto sembra non esserci un vero servizio dietro

**Comment by FedericaSicchiero** [comment]
Grazie, lo faccio sapere al team ma se resta un problema lato erogatore continuerà a dare errore finchè non lo risolvono. Purtroppo non abbiamo visibilità se ci stiano già lavorando o meno.
Chiudo il ticket con possibilità di riaprirlo nel caso ci siano aggiornamenti.

**Comment by DarioCosentino** [comment]
Salve a tutti 
Chiedo nuovo supporto per la call C020.
Ora ricevo la seguente response
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0c7cf9da-daca-11ee-84b2-005056ae5232"}

**Comment by FedericaSicchiero** [comment]
Buongiorno, anche in questo caso il problema dipende dall'erogatore. L'e-service C020 dovrebbe essere di ANPR se non mi sbaglio e in questo caso abbiamo una loro repository dove poter segnalare il problema: https://github.com/italia/anpr/issues
