### ISSUE TITLE
Impossibile accedere all'area Collaudo

### ISSUE THREAD

**Issue by Defkon1** [pagopa/pdnd-interop-frontend#466]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Effettuando l'accesso a Interoperabilità non è più disponibile il pulsante "Collaudo"

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/686298/cc5ebf7b-f59c-469c-9158-14404d8377cd)

Anche utilizzando il menù a discesa in alto a sinistra, non è possibile accedere all'area di Collaudo.

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/686298/7c89b96a-9c87-4f16-911b-3d23e017e585)

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/686298/492a3e60-5d7c-4d16-98c3-2198ef288934)

**Step per riprodurre il bug**
1. Effettuare il login con SPID
2. Cliccare su 'Prodotti Attivi' > 'Interoperabilità'
3. Nella finestra modale è presente solo il pulsante 'Produzione'

Oppure:
1. Effettuare il login con SPID
2. Cliccare su 'Prodotti Attivi' > 'Interoperabilità'
3. Cliccare su 'Produzione'
4. In alto a sinistra cliccare sul menù a discesa e cliccare su 'Interoperabilità Collaudo'
5. A video viene presentato l'errore generico "Qualcosa è andato storto"
6. in DevTools Console è presente il seguente messaggio:

```Refused to connect to 'https://dev.selfcare.pagopa.it/assets/products.json' because it violates the following Content Security Policy directive: "connect-src 'self' https://api.selfcare.pagopa.it/ https://api-eu.mixpanel.com/track/".```

**Comportamento atteso**
Poter accedere all'ambiente di Collaudo

**Il codice IPA del tuo ente**
r_marche

**Data e ora in cui si è riscontrato il problema**
26/06/2023 h. 13:20

**Ambiente**
Produzione o Collaudo

**Quali permessi ha la tua utenza?**
Operatore di sicurezza, Operatore API

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, lo faccio presente al team che se ne occupa e aggiorno la issue appena ho novità

**Comment by FedericaSicchiero** [comment]
@Defkon1 il team ha detto di aver risolto, aspetto un okay prima di chiudere la issue

**Comment by Defkon1** [comment]
@FedericaSicchiero Confermo la risoluzione del problema, grazie e buon lavoro
