### ISSUE TITLE
Impossibilità Onboarding PDND

### ISSUE THREAD

**Issue by andreatantillo** [pagopa/pdnd-interop-frontend#478]
**Descrivi il bug**
Alcuni comuni segnalano l'impossibilità di effettuare l'Onboarding sulla piattaforma PDND.

**Step per riprodurre il bug**
1. Vai su 'https://www.interop.pagopa.it'
2. Clicca su 'Accedi' e inserisci le credenziali SPID
3. Vedi l'errore 'Accesso non consentito. L'Area Riservata è dedicata agli enti che utilizzano i prodotti di PagoPA. Se lavori per un ente, chiedi a un Amministratore di aggiungerti nella sezione Utenti.'.

**Comportamento atteso**
Possibilità di effettuare l'Onboarding (invio accordo di adesione)

**Il codice IPA del tuo ente**
L'errore si presenta prima della selezione dell'Ente.

**Data e ora in cui si è riscontrato il problema**
Ci è stato segnalato la prima volta il 28 giugno alle ore 13:00.
Ho fatto un test con un collega senza abilitazioni in PDND e si presenta il medesimo problema anche ora.

**Ambiente**
Non rilevante

**Quali permessi ha la tua utenza?**
Non rilevante

**Screenshot**

![image (14)](https://github.com/pagopa/pdnd-interop-frontend/assets/136598770/5d1e6e5e-7f34-489f-bb87-35a79071a475)

**Note**

**Comment by FedericaSicchiero** [comment]
Buongiorno, quali sono i comuni che hanno l'errore? Può essere che una persona stia tentando di fare l'onboarding per vari comuni riutilizzando lo stesso link?

**Comment by andreatantillo** [comment]
Buongiorno Federica,

l'errore viene restituito ancor prima di selezionare il Comune, ossia subito dopo aver effettuato l'accesso con SPID. Ho fatto provare ad una collega senza abilitazione alcuna in piattaforma per simulare l'onboarding, partendo da [](https://www.interop.pagopa.it/).

L'errore ci è stato segnalato per ora da Polesella e Cittadella.

Grazie
Andrea

**Comment by FedericaSicchiero** [comment]
Grazie Andrea dei dettagli, lo sto facendo presente al team che gestisce l'area riservata e aggiorno il ticket appena ho novità.

**Comment by FedericaSicchiero** [comment]
Dopo il login con spid il link a cui andare è https://selfcare.pagopa.it/onboarding/prod-interop - provate a fare l'onboarding direttamente da qui che nel frattempo stanno vedendo come mai il link sul portale non funziona

**Comment by andreatantillo** [comment]
Ciao Federica,

ti ringrazio. Era probabilmente un falso allarme, anche nella [Guida all'Adesione](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione) è indicato di utilizzare il link che mi hai gentilmente fornito. Mi scuso per il disguido e ti ringrazio per la disponibilità e tempestività.

Andrea
