### ISSUE TITLE
Discordanza audience client fruitore ed audience e-service erogatore

### ISSUE THREAD

**Issue by rnapoli1983** [pagopa/pdnd-interop-frontend#48]
Buonasera sono Roberto Napoli (Sogei),

ci siamo accorti che sulla piattaforma c'è una discordanza dell'audience rilevabile nelle finalità del client POD ANPR Client definito sotto "I tuoi client" con quello definito negli e-service dell'erogatore ANPR.

Riporto gli screen-shots:

**Fruitore**:

![image](https://user-images.githubusercontent.com/30468060/160632085-e99270fc-272a-46bb-af1a-75155845f938.png)

![image](https://user-images.githubusercontent.com/30468060/160632329-8b4c8f66-3fbd-441f-96c9-55d3f570702f.png)

**Erogatore** sia nell'e-service C015 che in C021:

![image](https://user-images.githubusercontent.com/30468060/160632625-6b966719-938b-4d9c-9b6e-300577c08e86.png)

Non dovrebbero coincidere ?

Grazie mille

Cordiali saluti

cc: @amollicone1982

**Comment by ruggerocastagnola** [comment]
Ciao Roberto, grazie mille per la segnalazione, questo aspetto va sicuramente chiarito meglio, hai ragione. 
La questione qui è che il primo token sarà da staccare passando per la piattaforma interoperabilità (e dunque l'audience è test.interop.pagopa.it). Una volta che quel token è staccato, si potrà usare quel token per chiamare l'E-Service dell'erogatore che a sua volta avrà una certa audience, da questo stabilita (in questo caso testE002.anpr.interno.it). Non so se è chiaro a sufficienza

**Comment by rnapoli1983** [comment]
Buongiorno se la vostra risposta, poi barrata, è vera,

allora basterebbe al fruitore definirsi un client sotto "Interop M2M" con unq chiave pubblica e non due come avevate detto e fa tutto con quello.

Ovvero richiama sia PDND per il token che gli erogatori per i loro e-service.

Va fatta chiarezza abbastanza in fretta sul tema.

Grazie mille

**Comment by ruggerocastagnola** [comment]
Risolto con commit [9b899d7](https://github.com/pagopa/pdnd-interop-frontend/commit/9b899d71ce8535b9d8c464a5a785ffc9a0678a50), portato in ambiente di test con la [0.1.4](https://github.com/pagopa/pdnd-interop-frontend/releases/tag/0.1.4). Chiudo manualmente
