### ISSUE TITLE
Errore ottenimento voucher

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#481]
**Step di auto-debug**
Prima di aprire un issue, puoi effettuare le seguenti verifiche per escludere un errore di configurazione:
1. Se stai richiedendo un voucher per un e-service, il `purposeId` inserito è quello corretto? 
2. il `client_id` inserito nella richiesta al server autorizzativo corrisponde al valore inserito come subject (campo `SUB`) nella client assertion?
3. la chiave privata con la quale è stata firmata la client assertion corrisponde alla pubblica (campo `KID`) depositata su PDND Interoperabilità?
4. la chiave con la quale firmi l'asserzione (campo `KID`) è inserita all'interno del client che hai indicato (campo `SUB`)?
--> Direi quattro sì

**Il codice IPA del tuo ente**
C_H355

**Data e ora del tentativo**
20230706-135810-501207 
06/07/2023 h. 13:58

**Ambiente**
Produzione

**client_id**
b497dd46-a661-4d7f-9a36-9806522f131a

**correlationId**
1843a6f3-3220-4bf1-adfe-89d7874e484e

**purposeId (solo per i client e-service)**
4dd77328-83c7-4aa9-b655-cf97d9e24f9a

**Comment by FedericaSicchiero** [comment]
Ciao Francesco, hai provato il nuovo tool di debug del voucher che ti dice esattamente dove sta l'errore che ricevi?

**Comment by FedericaSicchiero** [comment]
Controllando a noi risulta che la richiesta sia stata mandata su collaudo e non su prod ma utilizzando l'audience di produzione

**Comment by franthemanIT** [comment]
In effetti in quest'ultima chiamata era rimasto l'url di collaudo... nelle precedenti probabilmente c'era altro che non andava.
Grazie mille e scusate!
