### ISSUE TITLE
Modifica UI/UX gestione chiavi pubbliche client

### ISSUE THREAD

**Issue by rnapoli1983** [pagopa/pdnd-interop-frontend#49]
Buonasera sono Roberto Napoli (Sogei),

come da accordi riportiamo una proposta alternativa di gestione delle chiavi pubbliche e dei client definiti dal fruitore a cui le chiavi stesse vengono associate.

Tale proposta sarebbe finalizzata a semplificare e limitare l'utilizzo di numerosi set di chiavi pubbliche/private da parte del fruitore stesso e consta dei seguenti punti:

- il tab "Chiavi pubbliche", presente nella definizione di un client, diventa una funzionalità del menù di sinistra al pari delle altre con una voce tipo "Le tue chiavi".

- La form sarebbe simile all'esistente con l'aggiunta della funzionalità che permette di associare ad una chiave una lista di Enti erogatori tra quelli che espongono e-service su PDND.

-  Alla definizione di un nuovo client, che rappresenta di fatto l'applicazione di un fruitore, apparirebbe una tendina con le chiavi precedentemente definite con la possibilità di associarne sempre una e una sola.

-  Quando l'utente va ad associare ad una finalità un client, in una tendina dei client associabili ad essa, dovranno apparire solo quei client le cui chiavi associate hanno come attributo l'ente coinvolto in quella finalità.

Facendo una modifica simile si rendono possibili vari scenari ad esempio:

- un fruitore può avere, come nel nostro caso, un client che con una coppia di chiavi possa parlare con diversi Erogatori;

- un fruitore che definisce un nuovo client rappresentante una sua nuova applicazione, può riutilizzare quella medesima coppia di chiavi nel caso in cui debba interrogare gli stessi Erogatori già implicati in definizioni di finalità/client precedenti.

- un fruitore che definisce un nuovo client rappresentante una sua nuova applicazione, che richiama Erogatori diversi,  rispetto a definizioni di finalità/client precedenti, dovrà munirsi di una nuova coppia di chiavi da associare a questo client.

- nel caso in cui un client già precedentemente definito debba richiamare un ulteriore erogatore, sarà possibile estendere la chiave mediante la funzionalità suddetta.

Non sappiamo quanto descritto sia fattibile ma potrebbe essere un punto di partenza su cui ragionare.

Grazie mille.

Buona giornata.

Ciao

Roberto

**Comment by ruggerocastagnola** [comment]
Dunque, a distanza di tempo ringrazio molto per la proposta. Ne ho riportato a suo tempo il contenuto per discussione nell'ambito dei ragionamenti sull'evoluzione del modello finalità-client-chiavi, che sono ancora in corso. L'issue è referenziata nel nostro backlog interno, per ora chiudo questa per ordine
