### ISSUE TITLE
Esempio erogatore

### ISSUE THREAD

**Issue by lucavergantini** [pagopa/pdnd-interop-frontend#503]
Esiste un esempio di erogatore e/o un archetipo?
Esistono librerie a disposizione per le verifiche dei voucher?

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, condivido la nostra [documentazione](https://docs.pagopa.it/interoperabilita-1) dove è possibile trovare esempi e videotutorial di tutte le parti della piattaforma. 
Per la verifica del voucher c'è una nuova sezione proprio all'interno della piattaforma dedicata agli enti per fare debug del voucher e vedere nel caso di errori cosa c'è da sistemare.
