### ISSUE TITLE
Problema nella creazione ed aggiunta di attributi Verificati - Dichiarati nella definizione di un E-Service 

### ISSUE THREAD

**Issue by rzomparelli81** [pagopa/pdnd-interop-frontend#51]
Una volta creati ed aggiunti nuovi attributi Verificati e Dichiarati ad una definizione di un E-Service, questi vengono visualizzati come Unknown

**Step per riprodurre il bug**
1. Andare su Erogazione -> I tuoi E-Service
2. Cliccare  su  +Aggiungi
3. Cliccare su Crea Nuovo Attributo ( per attributi Verificati e Dichiarati)
4. Cliccare su aggiungi Attributo o gruppo 
5. Scegliere l'attributo appena creato e Cliccare su Aggiungi
6. Salvare la bozza ed uscire
7. Riaprire la bozza salvata
8. A questo punto viene visualizzato l'attributo come Unknown

**Comportamento atteso**
Visualizzare il nome corretto dell'attributo creato ed aggiunto all'E-Service

**Screenshot**

![image](https://user-images.githubusercontent.com/103024544/161698981-02dcd16f-e7a3-4382-bb19-f1088c013ba5.png)

**Note**
Gli attributi creati ed aggiunti all'E-Service sono “Attributo Verificato Age 01” e “Attributo Dichiarato Age 01”

**Comment by beetlecrunch** [comment]
Domani dalle ore 10:00 alle 11:00 rilasceremo la modifica, è possibile pertanto qualche disservizio.
Grazie.
