### ISSUE TITLE
Esempio di fruizione servizio C003-servizioVerificaDichGeneralita-approvazione_automatica

### ISSUE THREAD

**Issue by TheVise1975** [pagopa/pdnd-interop-frontend#511]
Ciao a tutti,
sto procedendo con un integrazione al servizio in oggetto tramite C#.

Son riuscito a configurare i client sull'interfaccia di PDND, e a creare il voucher.
Tuttavia ora sono un po' bloccato nel momento in cui provo ad invocare il servizio: 
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C003-servizioVerificaDichGeneralita/v1/anpr-service-e002/

Sinceramente non ho ben capito dal file yaml cosa devo inviare, e infatti ricevo una risposta con http error 400

{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "xxxxxxx-xxxxxx-xxxxx-xxxx-xxxxxxxxxxxxxxx"
}

Qualcuno avrebbe un esempio del JSON da inviare, per questo servizio o per un servizio simile, da condividermi?

grazie
V.

**Comment by FedericaSicchiero** [comment]
ciao, hai già caricato una chiave pubblica all'interno del client e seguito la guida che ti si apre passo per passo?
Nel frattempo se non l'avevi già visto ti condivido la guida con i vari passaggi: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#richiesta-di-un-voucher-spendibile-presso-le-api-di-interoperabilita

**Comment by TheVise1975** [comment]
si si...sono arrivato al momento in cui devo invocare il servizio passando il token e il json con "i criteri di ricerca"

**Comment by FedericaSicchiero** [comment]
Allora lato tecnico non possiamo dare una mano perchè il servizio che si sta chiamando è di ANPR e noi non abbiamo visibilità dei dati, bisognerebbe sentire direttamente loro
