### ISSUE TITLE
Errore salvataggio durata validità voucher

### ISSUE THREAD

**Issue by rzomparelli81** [pagopa/pdnd-interop-frontend#52]
Nel salvare all'interno della definizione dell' E-Service la durata di validità del voucher e chiudendo e riaprendo la bozza questo cambia di valore.

**Step per riprodurre il bug**
1. Vai su Erogazione -> I tuoi E-Service -> +aggiungi
2. Inserire la durata di validità del voucher salvare ed uscire
3. Riaprire la bozza

Valore Salvato

![image](https://user-images.githubusercontent.com/103024544/162154688-183cd417-d815-4b2e-8060-e1b4ec211149.png)

Valore recuperato alla riapertura della bozza 

![image](https://user-images.githubusercontent.com/103024544/162154837-e6e77827-2e26-4704-98c8-09232f1155eb.png)

**Note**
Sembra esserci una conversione da minuti a secondi

**Comment by ruggerocastagnola** [comment]
Grazie ancora per la segnalazione, abbiamo rilasciato un fix in ambiente con la `0.1.7`. Chiudo l'issue manualmente
