### ISSUE TITLE
Errore chiamata verso e-service

### ISSUE THREAD

**Issue by costantinog** [pagopa/pdnd-interop-frontend#528]
Buongiorno, sto facendo dei test con i servizi messi a disposizione dagli erogatori, per l'implementazione viene richiesto la creazione di una client assertion e l'ottenimento di un voucher che successivamente dovrà essere utilizzato(entro un tempo limite) presso l'e-service dell'erogatore. In particolare viene richiesto di passare il token in ogni chiamata prevista dall'e-service inserendolo come Header: "Authorization: Bearer <PDNDVoucher>", tuttavia riscontro un errore "Forbidden 403 message: User is not authorized to access this resource with an explicit deny". Posso avere dei chiarimenti a riguardo?

**Comment by FedericaSicchiero** [comment]
Buongiorno, avremmo bisogno di sapere alcune cose per capire come mai c'è questo errore:
- erogatore
- fruitore
- e-service
- ambiente

Grazie

**Comment by costantinog** [comment]
Erogatore : PagoPA S.p.A.
Fruitore : Comune di Falerna
E-service : SEND - UAT
Ambiente : Collaudo

**Comment by FedericaSicchiero** [comment]
Per questo genere di errori il team di SEND ci ha detto di scrivere a pn-supporto-enti@pagopa.it in modo che possano aiutare al meglio

**Comment by costantinog** [comment]
Perfetto, grazie mille!
