### ISSUE TITLE
[Info/Suggerimento] Libreria verifica token

### ISSUE THREAD

**Issue by lvergantini** [pagopa/pdnd-interop-frontend#548]
Sarebbe possibile, se già non esiste, avere una libreria Java per la verifica dei token?

**Comment by FedericaSicchiero** [comment]
Esiste all'interno della piattaforma un tool di debug del voucher per vedere che tutto funzioni e nel caso di errori capire come mai questi ci siano. Questo tool è disponibile una volta che si è fatto il login sulla piattaforma

**Comment by lvergantini** [comment]
Io intendo un libreria da usare sul servizio fruitore.
Poiché a livello di implementazione esporre il servizio come e-service mi sembra molto semplice, di fatto c'è bisogno solamente di validatore il voucher o, al massimo, interagire con i servizi della PDND per ottenere info aggiuntive, se ci fosse una libreria che già fa tutto, per chi espone il servizio, se ci fosse una libreria, sarebbe una banalità salire a bordo

**Comment by lvergantini** [comment]
Mi sa che non mi sono spiegato bene: servirebbe una libreria lato erogatore che, dati alcuni parametri di configurazione ovviamente, verifichi il token, questo mi pare più che fattibile.
Il processo è sì articolato, ma la verifica tecnica del token parrebbe alquanto semplice.
Idem per quanto riguarda un client per semplificare l'interrogazione ai vostri servizi.

Se ogni erogatore deve implementare da 0 l'acqua calda...

**Comment by ruggerocastagnola** [comment]
Buongiorno Ivan, capisco il punto e mi torna il ragionamento, anche se onestamente è difficile in questa fase potremo mettere a disposizione tooling di questo tipo. Riporto comunque la proposta all'interno del team e ringrazio molto per il feedback, è sempre prezioso

**Comment by lvergantini** [comment]
Diciamo che in generale sarebbe molto bello avere delle librerie, il top sarebbe metterle su maven.
Ora non so i vostri progetti interni, ma su per giù mi sembra essere una cosa banale, magari sul client API ci vuole un po' di più.
Soprattutto in questa fase in cui moltissimi saliranno a bordo, credo sia un plus anche per voi, che evitereste di dover dar supporto a 100 enti su queste tematiche.

**Comment by franthemanIT** [comment]
Mi inserisco..
Ricordiamoci che, in linea teorica, ciò che la p.a. produce o fa produrre ex novo a livello di software dovrebbe essere open source e a riuso sul catalogo di Developers Italia.

**Comment by ggianoglio** [comment]
Buongiorno,
l'esposizione degli endpoint di Token Introspection e Well-known sarebbero utili per poter validare i token in maniera unificata.

**Comment by ggianoglio** [comment]
Buongiorno,
vista la chiusura potete menzionare in questa issue quali sono le evolutive in merito al tema della verifica dei token?
Grazie.
