### ISSUE TITLE
Informazione utenti Operatore API

### ISSUE THREAD

**Issue by MBossiniB** [pagopa/pdnd-interop-frontend#559]
Buongiorno,
non mi è chiaro se l'amministratore per Interoperabilità possa inserire come operatore API un soggetto appartenente al fornitore di servizi digitali (quindi esterno all'ente pubblico). Mi servirebbe saperlo per capire se come fornitori di API possiamo avere libero accesso all'ambiente di collaudo e produzione oppure se si debba sempre passare tramite un referente dell'ente pubblico.
Vi ringrazio in anticipo.
Cordiali Saluti
Martina Bossini

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
mi scuso per il ritardo nella risposta. L'Amministratore di interoperabilità produzione può nominare qualsiasi persona Operatore API/Sicurezza a sua discrezione. Se gli Amministratori sono solo referenti pubblici bisogna passare per forza da loro, ma se siete già in contatto con qualcuno che ha quel ruolo si può chiedere che nomini Operatore API chi deve lavorare sugli e-service.
