### ISSUE TITLE
Errore nella generazione del voucher dopo l'inserimento nel JWS del digest

### ISSUE THREAD

**Issue by Paolovox** [pagopa/pdnd-interop-frontend#565]
**Step di auto-debug**
Gli step eseguiti per il debug sono:

1- tramite lo script python3 create_m2m_client_assertion.py, crea il JWT e restituisce il ENCODED_TOKEN, cioè l'asserzione, priva del campo digest.
2 - calcoliamo l'hash dell'asserzione in questo modo echo -n {ENCODED_TOKEN} | openssl sha256
3- inseriamo il digest appena ottenuto nel jws in questo modo

{
  "header": {
      "alg": "RS256",
      "kid": "xxx",
      "typ": "JWT"
    },
  "payload": {
      "iss": "xxx-b519-40ee-86ca-a35bfd905db8",
      "sub": "xxx-b519-40ee-86ca-a35bfd905db8",
      "aud": "xxx.interop.pagopa.it/client-assertion",
      "jti": "xxx-459d-4659-b6fe-caacd85133d4",
      "iat": xxx,
      "exp": xxx,
      "digest": {
        "alg": "SHA256",
        "value": "xxx"
      }
    },
}

4 - firmiamo il nuovo json con la chiave privata client-keypair.rsa.priv per ottenere l'asserzione completa di digest.
5 - utilizziamo la curl
curl --location --request POST https://auth.interop.pagopa.it/token.oauth2   --header 'Content-Type: application/x-www-form-urlencoded'   --data-urlencode 'client_id=3794da34-b519-40ee-86ca-a35bfd905db8'   --data-urlencode 'client_assertion=LA_TUA_CLIENT_ASSERTION'   --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer'   --data-urlencode 'grant_type=client_credentials'

per ottenere il voucher ma ci viene restituita la risposta:
The request contains bad syntax or cannot be fulfilled.

se invece proviamo a generare il voucher direttamente con l'asserzione generata nel punto 1, il voucher viene generato correttamente.

Quale step è sbagliato? 

**Il codice IPA del tuo ente**
c_l735

**Data e ora del tentativo**
22/09/2023 h. 10:54

**Ambiente**
Produzione

**client_id**
3794da34-b519-40ee-86ca-a35bfd905db8

**Comment by FedericaSicchiero** [comment]
Avete provato a usare il tool di debug del voucher e vedere la risposta che vi da? 
Nel frattempo potete passarci il correlationID in modo da fare delle prove lato nostro?

**Comment by FedericaSicchiero** [comment]
Abbiamo controllato e ricevete errore perchè state chiedendo il digest per le API nostre come Interop che appunto non deve contenerlo. Il digest serve per le chiamate verso un erogatore. Per quello se non lo inserite funziona tutto, mentre da errore se lo aggiungete.
Lato nostro vediamo di implementare un modo per segnalare meglio questo genere di situazioni.

**Comment by FedericaSicchiero** [comment]
Il discriminante in questo caso è il client che state utilizzando.
Per poter utilizzare la funzionalità del digest bisogna creare il client sotto Fruizione -> I tuoi client e-service invece di Fruizione -> I tuoi client API Interop (che serve solo per le API interop).

Spero di aver capito bene il blocco che state incontrando e che questa risposta sia d'aiuto.

**Comment by FedericaSicchiero** [comment]
Il fatto è che se state provando a generare un token con un client API per simulare la comunicazione tra erogatore e fruitore non può funzionare perchè il client API è indirizzato unicamente alle API di interop, non dovrebbe essere usato per fare le prove di comunicazione tra enti. 
Potenzialmente potrebbe essere completamente diverso dal voucher EService (e in parte lo è, ad esempio non è presente la finalità). Una delle feature che non c’è nel token API è appunto quella del digest che se volete testare dovete farlo con un client EService e sarebbe meglio farlo in ambiente di Collaudo e non di Prod, creato apposta per fare i test in un ambiente sicuro.
