### ISSUE TITLE
Paese di origine del Server

### ISSUE THREAD

**Issue by Paolovox** [pagopa/pdnd-interop-frontend#566]
C'è qualche limitazione geografica sul server che ospita le API implementate?

**Comment by FedericaSicchiero** [comment]
No nessuna limitazione ma possiamo fare dei controlli se c'è un qualche errore specifico

**Comment by FedericaSicchiero** [comment]
No perchè alla fine può operare su Interoperabilità solo chi è autenticato e ha le credenziali/ruoli abilitati, quindi si presuppone che l'ente che ha abilitato tutto sappia chi opera e da quale server e ne garantisce la sicurezza
