### ISSUE TITLE
Integrazione come fruitore per PDND - Anpr C029

### ISSUE THREAD

**Issue by tbhole** [pagopa/pdnd-interop-frontend#568]
Buongiorno,
stiamo cercando di integrarci come fruitori del servizio ANPR C029 per estrarre i dati anagrafici di una persona dato il codice fiscale.
Più che un bug si tratta di un debug per la risoluzione del problema di integrazione 

Abbiamo implementato la richiesta con relativa cornice di sicurezza, tutto in ambiente di collaudo per il comune, ma otteniamo errori di integrazione.

Fruitore: Comune di Ripalta Cremasca (c_h315)
Piattaforma: PDND - C029
Ambiente: Collaudo
Data del test: 2023-09-25
Orario: intorno alle 12:25:50,554
Operatore dei test: Amministratore

Abbiamo appena effettuato un test di integrazione per richiedere i dati di un caso d'uso di test e la risposta ottenuta è la seguente:
{
	"type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
	"title": "InteroperabilityInvalidRequest",
	"status": 400,
	"detail": "Received request is not conform to the required interoperability profile",
	"govway_id": "57384f2f-5b85-11ee-abbf-005056ae5232"
}

Se si riuscisse a capire dove sta il problema, poichè dal messaggio restituito non riesco a determinare dove e come intervenire.

Grazie.

**Comment by FedericaSicchiero** [comment]
Buongiorno, in questo caso dovreste sentire l'erogatore sul perchè vi rimanda quell'errore, perchè i log arrivano direttamente dall'e-service e non dipende dalla piattaforma

**Comment by tbhole** [comment]
Grazie, 
per la risposta, ma come contatto l'erogatore?, in questo caso ANPR
Avevo provato via PEC qualche tempo fa e mi era stato risposto di aprire la issue qui.

Grazie.

**Comment by FedericaSicchiero** [comment]
A meno che non abbiano inserito i contatti nella loro anagrafica ente e che quindi dovrebbero apparire all'interno del loro e-service consiglio di riscrivere alla PEC e dire che in questo caso vi serve un contatto con chi gestisce i loro e-service e token in modo che vi spieghino come mai ricevete quell'errore
