### ISSUE TITLE
Finalità non associata al client e-service corretto

### ISSUE THREAD

**Issue by lucamontano98** [pagopa/pdnd-interop-frontend#570]
Dopo aver generato una finalità ed averla associata ad un client e-service risulta errata l'associazione all'interno della definizione del client nella select/option sita all'inizio della pagina

**Step per riprodurre il bug**
1. Vai su PDND interoperabilità collaudo, registra un client **x**, assegna a quest'ultimo una chiave pubblica ed inserisci una finalità **y** da associare al client medesimo, tenendo presente il fatto di avere già definito almeno un'altra istanza di e-service (con un proprio e client ed un'altra finalità ad esso associata).
2. Completa la procedura di registrazione di una nuova finalità y ed associala al client **x**.
3. Vedi l'associazione errata nella pagina di visualizzazione del client e-service **x**.

**Comportamento atteso**
**y** risulti correttamente associata ad **x**

**Il codice IPA del tuo ente**
r_friuve -> Regione Autonoma Friuli-Venezia Giulia

**Data e ora in cui si è riscontrato il problema**
es. 25/09/23 14:50

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Screenshot**
![paginaClientEServiceVerificaCodiceFiscale](https://github.com/pagopa/pdnd-interop-frontend/assets/144030486/0658f2db-a611-4e3a-b74a-aaaf3819ec2d)

**Note**
Segnalo che lo stesso problema lo si ha anche quando si cerca di completare il processo di registrazione di una nuova finalità associandola ad un client e si arriva all'ultima pagina di tale processo (dove si decide di pubblicare la finalità).

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, facciamo dei controlli e torniamo con una risposta

**Comment by lucamontano98** [comment]
Buon pomeriggio,
potete dirmi cortesemente a che punto sono i controlli? Grazie.

Distinti saluti.

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo mandato su un fix quindi chiediamo di provare a staccare e riassociare la finalità al client. Se dovesse dare errore vuol dire che c'è qualcosa di più grande sotto che dobbiamo continuare ad investigare. Grazie

**Comment by lucamontano98** [comment]
Buongiorno, perfetto. Grazie mille per il riscontro. Finora è tutto ok.
