### ISSUE TITLE
Testare api fruitore in ambiente di test

### ISSUE THREAD

**Issue by NETTunoPA** [pagopa/pdnd-interop-frontend#574]
Buongiorno,
abbiamo pubblicato un servizio come fruitore in ambiente di collaudo e vorremmo sapere come è possibile eseguire dei test. 
Avevamo intenzione di effettuare una richiesta di fruizione del nostro servizio dal portale ma  al  momento con il nostro account (operatore) non abbiamo modo di richiedere nessuna fruizione.
Come bisogna procedere?

**Comment by FedericaSicchiero** [comment]
Salve, solo gli utenti con ruolo Amministratore possono fare richiesta di fruizione ad un e-service. Se è per fare prove in ambiente di collaudo potete chiedere che un Amministratore dia ad un utente quel ruolo.
