### ISSUE TITLE
Problema download documentazione e-service

### ISSUE THREAD

**Issue by StefanoFlamigni** [pagopa/pdnd-interop-frontend#59]
Se si prova a scaricare la documentazione  di un e-service si ottiene un file non leggibile (ad eccezione di quelli in plaintext).

Ad esempio andando sul e-service C018 e provando a scaricare Documentazione_eserviceC018.pdf si ottiene un file senza estensione illeggibile anche rinominandolo in pdf.

![image](https://user-images.githubusercontent.com/63600770/168044178-bc761e8d-8bed-436c-992f-05e94eb30180.png)
![image](https://user-images.githubusercontent.com/63600770/168045404-dd76f779-ce97-4d17-b301-9d9dc0b1a18b.png)

**Comment by ruggerocastagnola** [comment]
Buongiorno Stefano, grazie mille per la segnalazione. Riesco a replicare il problema. In ambiente Windows, Acrobat mi dà "Errore durante l'elaborazione di una pagina. ColorSpace non valido". Su Mac, mi apre un file con 4 pagine bianche. Credo sia un problema legato a come è stato esportato il pdf da chi l'ha caricato. Provo a informarmi.

Per quanto riguarda il fatto che i download sono senza estensione, l'ergonomia di questa feature sarà migliorata nella release che andrà su oggi prima delle 15.

**Comment by ruggerocastagnola** [comment]
Grazie per il feedback, lo riporto al team backend per le dovute verifiche

**Comment by ruggerocastagnola** [comment]
Questa issue è riportata sulla board interna come [PIN-1499](https://pagopa.atlassian.net/browse/PIN-1499)

**Comment by ruggerocastagnola** [comment]
Abbiamo rilasciato una fix in ambiente. Chiedo conferma, a noi ora risulta che i documenti pdf siano scaricabili correttamente

**Comment by StefanoFlamigni** [comment]
Problema risolto ora il file è leggibile. 
Grazie ancora.
