### ISSUE TITLE
Errore 500 nel tentativo di staccare un voucher in ambiente di test

### ISSUE THREAD

**Issue by StefanoFlamigni** [pagopa/pdnd-interop-frontend#60]
In ambiente di test, dopo 
- aver sottoscritto l'e-service C018 - SERVIZIO DI ACCERTAMENTO CITTADINANZA, 
- aver creato una finalità 
- aver aggiunto un client con annessa chiave pubblica
- aver creato il jwt con i claims indicati nelle istruzioni, firmato il jwt con chiave privata contrariamente a quanto indicato nelle istruzioni in cui si parla di firma con chiave pubblica ma suppongo sia un refuso perchè la chiave pubblica dovrebbe essere usata da interoperabilità per verificare la mia firma fatta con chiave privata, corretto?
- aver inviato richiesta di token con il jwt sopra citato a  https://uat.gateway.test.pdnd-interop.pagopa.it/api-gateway/0.1/as/token.oauth2

ottengo il seguente errore:
{
    "errors": [
        {
            "code": "013-0011",
            "detail": "Error while creating a token for this request - JWT audience rejected: [https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C018-servizioAccertamentoCittadinanza/v1]"
        }
    ],
    "status": 500,
    "title": "There was an internal server error.",
    "type": "about:blank"
}

E' un problema del mio jwt passato? E' un problema del servizio che deve staccare il voucher?

**Comment by ruggerocastagnola** [comment]
Buongiorno Stefano, sulla documentazione dello stacco del voucher c'è stata un po' di confusione e rimaneggiamenti. Nella versione della UI che sarà online da oggi (andrà su prima delle 15) ci sarà un evidente aggiornamento alla documentazione che dovrebbe facilitare il processo

**Comment by ruggerocastagnola** [comment]
Dunque, la nuova versione è disponibile in ambiente. Confermo che dovrebbe essere possibile completare il giro di stacco dell'access token. Per quanto riguarda la disponibilità degli E-Service immagino di sì ma sono erogati da altri enti e dunque non sono sotto il nostro controllo. In questa fase di test immagino che qualche glitch possa esserci. Se dovesse riscontrare problemi di accesso provi a riportarmelo e vedo se riesco a ottenere feedback.

Per quanto riguarda gli errori, c'è uno [Swagger](https://uat.gateway.test.pdnd-interop.pagopa.it/authorization-server/swagger/docs/index.html#) dell'API ma per il momento non abbiamo della documentazione vera e propria. Gli errori dovrebbero comunque essere meno frequenti con la nuova documentazione. Nel caso sopra, effettivamente sulla UI vecchia era riportata un audience per l'asserzione non corrispondente, e dunque al tentativo di stacco dell'access token il sistema ha risposto con "JWT audience rejected"
