### ISSUE TITLE
E' necessario che il servizio di erogazione dati sia aperto a tutti gli IP in ingresso?

### ISSUE THREAD

**Issue by robertocappuccio** [pagopa/pdnd-interop-frontend#603]
Non sono riuscito a trovare questa informazione nella documentazione di PDND.
La domanda è la seguente: è consentito esporre un servizio di erogazione dati che preveda che il richiedente ci comunichi, all'atto della sottoscrizione, l'IP dal quale arriveranno le sue richieste al nostro servizio? E possiamo noi di conseguenza aggiungere tale IP alla nostra whilelist, negando invece l'accesso a tutti gli IP non presenti nella lista stessa?

**Comment by AlessioMarinelli** [comment]
@robertocappuccio aspettiamo una risposta ufficiale dal team, ma credo che la logica da seguire sia la stessa che Agenzie delle Entrate usa già per i suoi servizi (es. VCF1 - Verifica booleana codice fiscale): l'AdE impone il preventivo invio di un certificato particolare prima di accettare una fruizione, e lo ha specificato allegando una Nota di Servizio alla documentazione dell'e-service

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/93653654/a57c7a39-f891-4034-a560-c6816c962b7c)

**Comment by franthemanIT** [comment]
Mi pare che il ModI preveda ulteriori fattori di autenticazione/sicurezza oltre al token PDND.
Temo pero' che vadano gestiti esternamente alla PDND.
