### ISSUE TITLE
Chiedere accordi di fruizione massivamente o via API: è possibile? 

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#604]
Salve, chiedo qui ché non saprei dove altro chiedere.
Dovendo prendere decisioni sul se e sul come diventare erogatore PDND sfruttando il contributo PNRR per i Comuni, visto che un caso d'uso suggerito e' l'interoperabilità di protocollo, dovendo valutare la sostenibilità tecnica ed economica a medio-lungo termine (e anche l'utilità magari) di quello che stiamo realizzando chiedo:
- e' stato pensato qualcosa per evitare di dover fare 30mila richieste di adesione / accordi di fruizione per poter inviare messaggi protocollati via API REST alle altrettante AOO?
- si possono fare le richieste via API?
- e' previsto qualche automatismo del tipo: sei una AOO allora sei abilitato a tutte le API esposte dalle AOO per il protocollo interoperabile?

Discorsi simili valgono per altre API che sono proposte ai Comuni come erogatori. Se qualcuno fosse interessato a usare e API di un certo argomento esposte da ogni Comune (esempio: scandagliare gli albi pretori online. A che pro?, direte voi. E che ne so, rispondero' io, ma ci e' stato detto che e' un caso d'uso importante, io ho anche dei dubbi che sia legale e nello spirito della pubblicità legale) deve farsi 7904 richieste di fruizione?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
al momento non si può fare qualcosa di massivo o unico per più enti, quindi le richieste di adesione e accordi si dovranno fare per ogni e-service che si vuole consultare, stesso discorso per le varie richieste che devono passare per forza per il percorso classico degli e-service fino ad arrivare allo stacco del token.
Per l'automatismo il discorso è lo stesso e in più il discorso dell'abilitazione dipende dagli attributi che l'erogatore sceglie per il proprio e-service e che il fruitore deve avere per iscriversi.
Quindi riassumendo la risposta alla domanda delle 7904 richieste di fruizione è si.

**Comment by franthemanIT** [comment]
Grazie Federica per la risposta tempestiva e chiara.
Lo stacco del token per ogni richiesta ci sta, tanto la fa la macchina.
Se pero' attivo il protocollo interoperabile via API REST tramite PDND temo che passero' i prossimi due anni lavorativi a fare richieste per abilitare il dialogo con tutti gli enti pubblici italiani. Fateci un pensiero, per favore!

PS: vero che se sono erogatore sono gli altri che fanno richieste a me e qui posso accettarle in automatico, ma il protocollo interoperabile prevede per definizioni che ci sia un insieme di enti che sono insieme erogatori e fruitori ciascuno di tutti gli altri.

**Comment by FedericaSicchiero** [comment]
Lo faccio presente agli altri perchè forse questo scenario non era stato ancora considerato, grazie!

**Comment by marco-deligios** [comment]
Mi permetto di osservare che, essendo le [AOO delle PA italiane](https://indicepa.gov.it/ipa-dati/dataset/aree-organizzative-omogenee/resource/cdaded04-f84e-4193-a720-47d6d5f422aa) 37.783 gli accordi di fruizione totali saranno **1.427.555.089**

**Comment by franthemanIT** [comment]
Buongiorno, ci sono novità al riguardo?
La questione sembrerebbe ripetersi anche per il rivisitato Sistema Informatico degli Sportelli Unici (SUAP/SUE).
Sembrerebbe perché le specifiche non sono chiarissime.
Per quanto il SSU preveda una componente, il catalogo, che censisce tutte le altre componenti (front office SUAP, back office SUAP, back office di enti terzi) pare che gli scambi di dati siano diretti fra le componenti, con autenticazione e sicurezza tramite PDND (schema di di sicurezza Integrity_Rest_01 del ModI: bearerAuth - il token PDND base - e Agid-JWT-SIgnature, che dovrebbe essere la firma del digest del payload con la stessa chiave dichiarata su PDND).

Limitandosi agli aspetti PDND stretti (per non andare OT con il repository):
- se è così, non è che questo potrebbe essere il colpo di grazia dopo il miliardo e mezzo di accordi derivanti dal protocollo interoperabile?
- ma anche per il catalogo stesso, per ogni SUAP (quanti saranno? 6mila?) ci sono almeno 5 API pubblicate, più quelle degli enti terzi (ogni ente terzo deve esporre API al back office dei SUAP con cui ha rapporti, su base territoriale si direbbe). Senza troppi passaggi, sono 6mila*5 + 6mila*5 ? 60.000 API a catalogo.

Se anche la PDND regge il colpo, purtroppo le conseguenze sgradevoli finiscono fuori del perimetro PDND, cioè a casa di fruitori ed erogatori, ma temo che abbiano ripercussioni sull'effettivo utilizzo dell'interoperabilità.

**Comment by FedericaSicchiero** [comment]
Ciao Francesco, scusa il ritardo nella risposta.
Al momento non sono cambiate le cose dall'ultima risposta, quindi non è ancora possibile interrogare le API massivamente ma come sempre ci portiamo a casa i feedback che ci arrivano. 

Il funzionamento della piattaforma non è una cosa che viene scelta da noi di Interop singolarmente, ma ci sono dentro una serie di attori diversi che quindi non rendono automatico realizzare tutti i consigli che ci arrivano, per quello forse alcuni suggerimenti che sarebbero anche utili per l'utente finali ci possono mettere del tempo per poi essere realizzare.

Come sempre grazie per il tempo speso a utilizzare la piattaforma e indicare i miglioramenti!

**Comment by marco-zordan** [comment]
Chiedo se ci sono aggiornamenti sull'argomento.
Avevo posto il seguente quesito sul forum e mi hanno segnalato questa issue che è molto simile:
https://forum.italia.it/t/api-per-caricamento-gestione-massiva-eservice-su-piattaforma-pdnd/39087

Buongiorno esistono delle API per il caricamento/aggiornamento massivo sulla piattaforma PDND degli eservice al fine di aggiornare le specifiche delle API, ossia aggiornare i file yaml di servizi esistenti, piuttosto che cancellare gli esistenti e ricreare dei nuovi eservice con le specifiche aggiornate?
Gestire manualmente vari eservice per centinaia di comuni è al quanto oneroso.
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, al momento non è ancora possibile modificare in maniera massiva gli e-service, soprattutto se appartenenti a enti diversi per una questione amministrativa.
Nel caso in cui questo diventerà possibile vedremo di comunicarlo sulle nostre piattaforme, grazie.

**Comment by marco-zordan** [comment]
Gentilissima dott. Sicchiero mi permetto di riformulare la richiesta per capire se non vi sia proprio una possibile soluzione.

Esiste la possibilità di aggiornare ed eseguire delle operazioni di revisione e aggiornamento di nuova versione delle API del PDND qualora fosse necessario via API per singolo ente senza doverlo eseguire manualemente?

La ringrazio per la gentile attenzione
Cordiali saluti

**Comment by FedericaSicchiero** [comment]
Gentilissimo, anche in questo caso purtroppo la risposta è no perchè quando si cambia qualcosa a livello di e-service si deve sempre passare per la piattaforma e quindi serve un'approvazione manuale delle modifiche. 
Grazie
