### ISSUE TITLE
Tasto di aggiornamento versione non compare per servizi sdg agid

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#613]
In ambiente di collaudo stiamo tentando di aggiornare i servizi sdg (es. evidenceBroker) agid ma il tasto di aggiornamento versione non compare. Su altri servizi invece compare

**Comment by FedericaSicchiero** [comment]
Controlliamo e aggiorniamo la segnalazione, grazie

**Comment by FedericaSicchiero** [comment]
Ciao @amollicone1982, l'aggiornamento lo può fare solo un Amministratore. Se hai i poteri da Operatore API è per quello che non vedi il bottone

**Comment by amollicone1982** [comment]
Avete novità? Abbiamo una certa urgenza per provare i servizi sdg. Come ricordato nel primo post si tratta di una problematica dei solo servizi sdg. Con gli altri l'aggiornamento è possibile

**Comment by FedericaSicchiero** [comment]
Ci stiamo lavorando, appena abbiamo fatto aggiorno la issue

**Comment by FedericaSicchiero** [comment]
@amollicone1982 state cercando di aggiornare la richiesta di fruizione corretto? Non creare una nuova versione di e-service.
Stiamo lavorando al bug ma non ci compare l'utenza della dottoressa Toscano.

**Comment by FedericaSicchiero** [comment]
In particolare ci serve sapere  per quale ente state operando per capire che non si tratti di una questione di attributi mancanti il fatto che solo per i servizi di sdg non sia disponibile la funzione di aggiornamento

**Comment by amollicone1982** [comment]
Il profilo delegato del ministero dell'interno nella persona della dott. Toscano

Vi ripeto che abbiamo urgenza.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FedericaSicchiero** [comment]
Stasera dovrebbe andare su un fix per questo bug in modo da risolverlo totalmente.

**Comment by FedericaSicchiero** [comment]
@amollicone1982 potete provare adesso? grazie

**Comment by amollicone1982** [comment]
Abbiamo risolto. Grazie
