### ISSUE TITLE
Charimenti su attributi certificati per e-service Autorità Anticorruzione

### ISSUE THREAD

**Issue by mcasamassima** [pagopa/pdnd-interop-frontend#614]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Stiamo aderendo agli e-service dell'Autorità Anticorruzione, ma ci troviamo di fronte alla richiesta di attributi certificati indecifrabili

**Step per riprodurre il bug**
1. Vai su 'Catalogo e-service'
2. Clicca su 'PCP - Comunica post pubblicazione'
3. Non si può sottomettere richiesta per mancanza attributo

**Comportamento atteso**
di essere associati come INAIL agli attributi certificati:
1) Gestore che ha in carico una o più componenti non certificate con accesso all'ambiente di qualificazione
2) Gestore che ha sottomesso una richiesta di certificazione per una o più componenti con accesso all'ambiente di qualificazione
3) Gestore che ha in carico una o più componenti certificate con accesso all'ambiente di esercizio

**Il codice IPA del tuo ente**
INAIL

**Data e ora in cui si è riscontrato il problema**
18/10/2023

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore 

**Screenshot**
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/42301624/37befb2f-d74e-41e0-9719-6ecbe9be56c9)

**Note**
La richiesta più che altro è tesa a ricevere maggiori informazioni sugli attributi suddetti e la modalità su come entrarne in possesso.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
noi riceviamo la lista da ANAC degli enti che hanno fatto richiesta per avere questi attributi e quindi potersi iscrivere all'e-service. Maggiori informazioni si possono trovare [qui](https://www.agid.gov.it/it/piattaforme/procurement/regole-tecniche-procurement) ed esiste anche una [repository](https://github.com/anticorruzione/npa/issues) github specifica di ANAC per tutte le domande e chiarimenti.
