### ISSUE TITLE
errore status":400,"title":"The request contains bad syntax or cannot be fulfilled. dopo CURL 

### ISSUE THREAD

**Issue by Gpediconi** [pagopa/pdnd-interop-frontend#620]
to creando il voucher per SEND

Collaudo

client_id :708bf3dc-ef34-444c-862f-65934ba06a05
client_assertion: eyJhbGciOiJSUzI1NiIsImtpZCI6Imk2VnpLMXJrbzV4eHVsVnVwSWNwTDI0ckJmYmhlVG1keWU4NkdjVkFCNlEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI3MDhiZjNkYy1lZjM0LTQ0NGMtODYyZi02NTkzNGJhMDZhMDUiLCJzdWIiOiI3MDhiZjNkYy1lZjM0LTQ0NGMtODYyZi02NTkzNGJhMDZhMDUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwicHVycG9zZUlkIjoiYzQ2N2JlYjItOTMzNS00YzY1LTkyN2MtMjliODAxZjkyNmMzIiwianRpIjoiZjJjMTA0ZWQtYTVhOS00MTNiLWJhMzItYjk5YTZiMzk1MTRkIiwiaWF0IjoxNjk4MTM5ODk1LCJleHAiOjE3MDA3MzE4OTV9.jKPfPCIl_YFCyjx6z6lgBVCigdfKkEXnkMFlcryVwqWPNyShjoZU-ccwD7k8dtl6Jy9V-eHM4l05iiOh2fABS2GNWZADD5uL66wfaTMz3YgRXjevbpWDH8zN5_Jca6y2rff6kjSriX8JbjQfSc2BupodYHypH8CVOpo72gsVTaU5AjGIK1-9A9CfoJy8PKexVLvQ1Uj0YGil6VkeGhrIEH4lBueGrLQDupNVpzmvZ2lnsb_9-EuUqfpxbUzRktCAMcmnQZvQ4JDZ57W2GLM95WtpRhXAF_vzFGHCPnOxQmwhex0d1YW47Td9ci8e2K-pXyCrUvcJUOWyJlk62hbPcw

Utilizzando la vostra funzionalità di debug è tutto ok ma quando eseguiamo il comando CURL per generare il voucher abbiamo il seguente errore:

{"correlationId":"62ce7057-ad68-4b86-8970-9dc243d86362","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

Anche utilizzando POSTMAN stesso risultato:

ecco la chiamata:

curl --location "https://auth.uat.interop.pagopa.it/token.oauth2" --header "Content-Type:application/x-www-form-urlencoded" --data-urlencode "client_id=708bf3dc-ef34-444c-862f-65934ba06a05" --data-urlencode "client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6Imk2VnpLMXJrbzV4eHVsVnVwSWNwTDI0ckJmYmhlVG1keWU4NkdjVkFCNlEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI3MDhiZjNkYy1lZjM0LTQ0NGMtODYyZi02NTkzNGJhMDZhMDUiLCJzdWIiOiI3MDhiZjNkYy1lZjM0LTQ0NGMtODYyZi02NTkzNGJhMDZhMDUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwicHVycG9zZUlkIjoiYzQ2N2JlYjItOTMzNS00YzY1LTkyN2MtMjliODAxZjkyNmMzIiwianRpIjoiZjJjMTA0ZWQtYTVhOS00MTNiLWJhMzItYjk5YTZiMzk1MTRkIiwiaWF0IjoxNjk4MTM5ODk1LCJleHAiOjE3MDA3MzE4OTV9.jKPfPCIl_YFCyjx6z6lgBVCigdfKkEXnkMFlcryVwqWPNyShjoZU-ccwD7k8dtl6Jy9V-eHM4l05iiOh2fABS2GNWZADD5uL66wfaTMz3YgRXjevbpWDH8zN5_Jca6y2rff6kjSriX8JbjQfSc2BupodYHypH8CVOpo72gsVTaU5AjGIK1-9A9CfoJy8PKexVLvQ1Uj0YGil6VkeGhrIEH4lBueGrLQDupNVpzmvZ2lnsb_9-EuUqfpxbUzRktCAMcmnQZvQ4JDZ57W2GLM95WtpRhXAF_vzFGHCPnOxQmwhex0d1YW47Td9ci8e2-pXyCrUvcJUOWyJlk62hbPcw" --data-urlencode "client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer" --data-urlencode "grant_type=client_credentials" --verbose

Potete aiutarmi a capire quale può essere l'errore?

Grazie.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
grazie della segnalazione, controlliamo e aggiorniamo la issue.
Per questioni di sicurezza dei dati consigliamo di non pubblicare la client assertion in uno spazio pubblico, anche se si tratta dell'ambiente di collaudo che non va a impattare produzione.

**Comment by Gpediconi** [comment]
Da ieri ricevo il voucher dopo la chiamata all'api.
Grazie

**Comment by FedericaSicchiero** [comment]
Ottimo!

**Comment by Gpediconi** [comment]
Adesso ho provato a fare la /delivery/attachments/preload e ricevo FORBIDDEN.
Ho creato un'api key in SEND : interop_api1 = 9c332de7-6b3f-4488-bce4-48a... gruppo: interop_api1
creato un voucher con il client in Interoperabilità collaudo  -> Fruizione -> ituoi client e-service ->  "test_invio_notifica"  id_client: 708bf3dc-ef34-444c-862f-65934b....

ma risponde 200 forbidden.

cosa sbaglio?
Grazie

**Comment by Gpediconi** [comment]
Scusate creo nuova discussione

**Comment by FedericaSicchiero** [comment]
Controlliamo anche questo nuovo errore che viene dato
