### ISSUE TITLE
Unknown API Request 404 (e-service VCF1)

### ISSUE THREAD

**Issue by Lending** [pagopa/pdnd-interop-frontend#623]
Salve,

sto cercando di utilizzare in ambiente di collaudo il servizio **VCF1 - Verifica Booleana Codice Fiscale**
Secondo la documentazione risponde a questo indirizzo: **https://modipa-val.agenziaentrate.it/govway/rest/in/AgenziaEntrate/verifica-cf/v2/verifica**

Ho provato ad eseguire la seguente chiamata rest. (l'access token per brevità è sintetizzato)

curl --location 'https://modipa-val.agenziaentrate.it/govway/rest/in/AgenziaEntrate/verifica-cf/v2/verifica' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJ0eXAiOiJhdCtqd3...........wkOAGqDci8TrUHPQmOg' \
--data '{
    "codiceFiscale":"GNNFLV75P18H501N"
}'

Ottengo in risposta

{
    "type": "https://govway.org/handling-errors/404/NotFound.html",
    **"title": "NotFound",
    "status": 404,**
    "detail": "Unknown API Request",
    "X-Global-Transaction-ID": "3f7e3e2d6539193f251718dd"
}

Dove sbaglio?
Grazie

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio, grazie della segnalazione.
Prima di procedere con i controlli mi potete confermare se avete provato ad utilizzare il tool di debug del voucher? Magari può essere d'aiuto a capire cosa si blocca.

**Comment by Lending** [comment]
Il tool del voucher dice che è tutto ok. Viene recuperato senza problemi.
Il problema è che il servizio non esiste a quanto pare oppure ho sbagliato l'url. Potete confermarmi che sia effettivamente
'https://modipa-val.agenziaentrate.it/govway/rest/in/AgenziaEntrate/verifica-cf/v2/verifica' ?

Perchè mi da 404?

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, l'url ve lo può confermare solo l'Agenzia dell'entrate che eroga il servizio. Se hanno inserito una mail di contatto la potete trovare all'interno dell'e-service.
