### ISSUE TITLE
[INFO] servizi Agenzia delle entrate informazioni (e-service VCFANAPF1 e VCF1)

### ISSUE THREAD

**Issue by leonardoonecompany** [pagopa/pdnd-interop-frontend#624]
1) il servizio VCFANAPF1 - verifica corrispondenza CF e Dati Anagrafici PF viene mostrato in collaudo ma non in produzione. Come mai? Se ancora non è stato rilasciato in produzione, quali sono le tempistiche di rilascio?

2) sullo stesso servizio del punto 1 (VCFANAPF1) viene richiesto il comune di nascita come una stringa, ma qual'è l'anagrafica di riferimento? quella istat?

3) abbiamo richiesto IN COLLAUDO per il servizio VCF1 - Verifica Booleana codice fiscale una finalità che prevedeva un incremento della soglia del fruitore da 10 chiamate API/Giorno a 200. La richiesta è da diversi giorni in stato di approvazione. 
Stessa cosa succederà in produzione sia per il servizio VCF1 che VCFANAPF1, in quanto viene dichiarata una soglia di 1000 API/giorno ma a noi servirà sicuramente un incremento sostanziale della soglia di chiamate in quanto gestiamo milioni di utenze e volevamo capire dal fornitore come gestirla o se ci sono effettivamente dei vincoli tecnici.

**Comment by FedericaSicchiero** [comment]
Buongiorno, rispondo seguendo i punti:

1. Questo bisognerebbe chiederlo ad Agenzia dell'Entrate che è l'erogatore del servizio. I motivi per cui ora come ora si trova solo in ambiente di Collaudo possono essere svariati, tra cui anche solo capire se il server è in grado di gestire un eventuale carico. Anche le tempistiche le possono fornire solo loro.
2. Anche qui solo AdE vi può confermare quello che chiede.
3. Le finalità in stato di approvazione rimangono così finchè non vengono approvate dall'erogatore perchè vuol dire che vanno a superare la soglia di chiamate API che l'erogatore è in grado di sopportare quotidianamente. Maggiori informazioni si possono trovare [qui](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/finalita#finalita-con-stato-in-aggiornamento). Anche in questo caso solo AdE può sbloccare la situazione.

**Comment by leonardoonecompany** [comment]
Buongiorno a te e grazie per la risposta,
pensavo che ci fosse con voi un canale di supporto sui servizi erogati. Sapete come si può contattare l'Agenzia delle Entrate? avete un canale con gli erogatori di servizi?

**Comment by FedericaSicchiero** [comment]
Noi diamo supporto su tutto quello che riguarda la parte tecnica della piattaforma in se, ma non su quello che fanno gli erogatori perchè hanno loro la responsabilità di gestire i propri e-service (li creano, decidono gli attributi, i limiti delle chiamate API etc).
Attualmente non abbiamo un canale con gli enti ma potrebbero aver inserito delle email di contatto all'interno dell'e-service quando si sono iscritti alla PDND. Non era ancora obbligatorio inserire una mail quindi non posso dare garanzia che l'abbiano fatto.
