### ISSUE TITLE
[clarification] ambiente di collaudo e-service - utilizzo dati di test

### ISSUE THREAD

**Issue by wwwfabry** [pagopa/pdnd-interop-frontend#625]
Buongiorno,

*ambiente di test *

il nostro fornitore chiede quali codici fiscali è possibile utilizzare per poter effettuare le chiamate di test per e-service C029-servizioAccertamentoDatiAnagrafici, in quanto nella documentazione è asserito di non utilizzare dati reali.

grazie per l'assistenza

saluti

**Comment by FedericaSicchiero** [comment]
Buongiorno,
in questo caso bisognerebbe contattare l'erogatore, perchè noi nella nostra documentazione diciamo quanto ha scritto, ma dovrebbero confermarlo loro o quantomeno chiarire se in questo caso è possibile utilizzare dati reali.
