### ISSUE TITLE
Forbidden in preload

### ISSUE THREAD

**Issue by Gpediconi** [pagopa/pdnd-interop-frontend#626]
Comune di Scafa - 
Interoperabilità collaudo
ho provato a fare la /delivery/attachments/preload e ricevo FORBIDDEN.
Ho creato un'api key in SEND : interop_api1 = 9c332de7-6b3f-4488-bce4-48a... gruppo: interop_api1
creato un voucher con il client in Interoperabilità collaudo -> Fruizione -> ituoi client e-service -> "test_invio_notifica" id_client: 708bf3dc-ef34-444c-862f-65934b....

Ore 11:28

ma risponde 403 forbidden.

cosa sbaglio?
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno,
passiamo questa segnalazione ai colleghi del team SEND che possono dare maggiori informazioni.

**Comment by FedericaSicchiero** [comment]
Nel frattempo potete scrivere a pn-supporto-enti@pagopa.it per un aiuto più diretto, grazie.
