### ISSUE TITLE
Errore generazione token auteticazione - https://auth.uat.interop.pagopa.it/token.oauth2

### ISSUE THREAD

**Issue by Lovecraft81** [pagopa/pdnd-interop-frontend#628]
Buonasera, 
sto provando a generare il token sulla piattaforma per utilizzarlo all'interno del servizio SEND in ambiente di Collaudo.
Ho correttamente registrato la client_assertion con la procedure e recuperato il voucher.
Quando però effettuo la chiamata all'API https://auth.uat.interop.pagopa.it/token.oauth2 con i parametri corretti

client_id: dxxxxxx...
client_assertion: xxxxxx
client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
grant_type: client_credentials

invece di ottenere il token ottengo il seguente errore? Dove sbaglio?

{
    "correlationId": "a0b059da-719a-497d-ba38-100763c41905",
    "errors": [
        {
            "code": "015-0008",
            "detail": "Unable to generate a token for the given request"
        }
    ],
    "status": 400,
    "title": "The request contains bad syntax or cannot be fulfilled.",
    "type": "about:blank"
}

Premetto che fino a venerdì funzionava tutto correttamente. Da stamattina invece ottengo questo errore.

Grazie

Saluti

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo controllato nei nostri log e risulta che il JWT è scaduto, per questo ricevete errore.
Potete rifare il processo e a quel punto il token dovrebbe staccarsi senza problemi, grazie.

**Comment by Lovecraft81** [comment]
Perfetto, grazie.
Solo una domanda, quindi il JWT usato nel campo client_assertion ha una scadenza? Perché nella documentazione non ho trovato questa condizione. 
Io avevo capito che il token per l'utilizzo dei servizi viene generato con l'API token.oauth2, e quello giustamente ha una scadenza, mentre il client-assertion rimane invariato una volta generato. Non è comodo per l'utente dover rifare la procedura da interfaccia.
C'è eventualmente un'API che si può lanciare per midificare il client-assertion senza dover entrare nell'interfaccia?

**Comment by ruggerocastagnola** [comment]
Buongiorno, provo a rispondere a tutto.

Sì, uno dei parametri della client assertion è `EXP`, il timestamp della scadenza. Per comodità, [questo](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#richiesta-di-un-voucher-spendibile-presso-un-e-service-del-catalogo) è il riferimento corretto alla documentazione. Come immagino sappia, è buona pratica di sicurezza impostare una scadenza adeguata alla situazione. Il punto è se la client assertion ben formata e firmata con la vostra chiave privata vi viene sottratta, è possibile per il malintenzionato usarla per ottenere token da Interop al posto vostro.

Non c'è bisogno di un'API per modificare la client assertion, non è un'operazione che riguarda Interop. La client assertion viene creata e firmata dal fruitore che intende ottenere un voucher, e tipicamente si fa tramite script. Quello che vede riportato in UI è semplicemente un esempio su come farlo. Lì sono anche riportati i parametri fissi per generare la client assertion (es. KID, ALG, TYP, SUB, AUD, purposeId), mentre viene riportato che quelli variabili nel tempo (JTI, IAT, EXP) devono essere generati dallo script dell'utente. Il punto di quell'interfaccia è facilitare gli utenti nel reperimento dei parametri fissi per generare la client assertion.

Se invece quello che intende per "modificare la client assertion" è cambiare i valori del kid o del purposeId, questi due valori deve reperirli tramite l'interfaccia la prima volta che genera una finalità (purpose) o carica una chiave pubblica (kid). Una volta che li ha reperiti, li può usare nei suoi script e non dovrebbe essere nuovamente necessario accedere alla UI.

Se ho frainteso qualcosa, sono a disposizione.

Un saluto

**Comment by Lovecraft81** [comment]
Innanzi tutto grazie per la risposta.
Non nego che lo scorso venerdì, facendo dei test, abbiamo capito come gestire il tutto ed è perfettamente in linea con quanto scritto sopra. Concordo sulla buona norma di gestire la scadenza dell'assertion ma non capivamo bene come poter coniugare il tutto con quanto riportato nella guida, ma ora seguendo la spiegazione da lei fornita è tutto più chiaro.

Saluti

**Comment by ruggerocastagnola** [comment]
Se ha trovato che alcuni elementi nella UI o nella documentazione sono ambigui o di difficile comprensione, e ha voglia di condividerli con noi, sicuramente ci aiuta a migliorare. Intanto grazie e un saluto
