### ISSUE TITLE
Nuova versione di un e-service: durata voucher

### ISSUE THREAD

**Issue by saratum** [pagopa/pdnd-interop-frontend#629]
**Descrivi il bug**
Alla creazione di una nuova versione dell'e-service in erogazione, la maschera chiede la compilazione della durata del voucher in minuti, ma questo valore viene poi convertito in ore 

**Step per riprodurre il bug**
1. Andare su "I tuoi e-service"
2. Cliccare su '"Crea bozza" di un e-service esistente
3. Compilare la bozza inserendo come valore 1 per "durata validità"
4. terminare la compilazione della bozza e pubblicarla
5. recarsi sul dettaglio dell'e-service, cliccare su "Vedi i dettagli tecnici"
6. la durata del voucher risulta di 60 minuti

**Il codice IPA del tuo ente**
Amministratore di un ente, Comune di Brunico c_b220

**Data e ora in cui si è riscontrato il problema**
es. 231/10/2023 circa ore 16:15

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
 Amministratore

**Comment by saratum** [comment]
NOTA BENE: dai test effettuati crediamo sia solo un problema di visualizzazione su portale: il voucher dal test condotto DOPO la pubblicazione del nuovo accordo è effettivamente scaduto dopo un minuti

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, lo faccio presente al team.
