### ISSUE TITLE
Operatore con ruolo "admin" e caricamento delle chiavi pubbliche 

### ISSUE THREAD

**Issue by mgminelli** [pagopa/pdnd-interop-frontend#63]
Buongiorno,

Come gestori della piattaforma di interoperabilità dell'ente, il ruolo sulla PDND che più si avvicina alla nostra operatività attuale è quello di "admin", in quanto la nostra unità si occupa di gestire le richieste di uso delle API e anche di procedere alla pubblicazione delle stesse da parte del comune.
Oltre a questo, tra le nostre attività c'è anche la gestione della parte di sicurezza relativa agli accessi e all'interfacciamento tra la piattaforma del Comune e i sistemi esterni, compresa la gestione dei certificati di mutua autenticazione e delle credenziali rilasciate al Comune come ente.

Gli operatori con ruolo "admin" però non possono caricare le chiavi pubbliche per i vari client registrati sulla piattaforma, dato che questa funzionalità è prevista per gli operatori con ruolo "security".

Capiamo che la divisione operatore "API" e operatore "Security" segue le linee guida AgID, ma sarà prevista la possibilità per un utente "admin" di poter eseguire il caricamento delle chiavi pubbliche?
In alternativa, è previsto di avere più ruoli per l'utenza, eventualmente selezionabili quando viene effettuato l'accesso tramite SPID come viene selezionato l'ente per cui si opera?

Grazie mille.

**Comment by marcocipri** [comment]
Buongiorno,
nei prossimi rilasci della piattaforma agli Admin saranno aggiunte le funzionalità di caricamento delle chiavi pubbliche.

grazie del contributo.

**Comment by ruggerocastagnola** [comment]
Chiudo intanto l'issue, internamente è tracciata come [PIN-1502](https://pagopa.atlassian.net/browse/PIN-1502)
