### ISSUE TITLE
Richiesta attributi per e-service ANAC in PDND di collaudo

### ISSUE THREAD

**Issue by mcasamassima** [pagopa/pdnd-interop-frontend#635]
**Descrivi il bug**
Abbiamo la necessità di avere gli attributi in ambiente di COLLAUDO per i seguenti e-service:
•	PCP - Comunica appalto
•	PCP - Comunica post pubblicazione
•	PCP – FVA
•	PCP – FVC
•      PCP - Gestione utenti
•      PCP - Servizi comuni
•      PCP - Pubblica avviso

**Step per riprodurre il bug**
1) vai su anagrafica ente (inail)
2) non compare almeno uno dei seguenti attributi richiesti da anac in pdnd di collaudo ovvero:
- Gestore che ha in carico una o più componenti non certificate con accesso all'ambiente di qualificazione
- Gestore che ha sottomesso una richiesta di certificazione per una o più componenti con accesso all'ambiente di qualificazione
- Gestore che ha in carico una o più componenti certificate con accesso all'ambiente di esercizio

**Comportamento atteso**
Poter inoltrare richiesta di fruizione in pdnd di collaudo per i suddetti e-service

**Il codice IPA del tuo ente**
INAIL

**Data e ora in cui si è riscontrato il problema**
OGGI

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo),

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
è stato completato il processo richiesto da AgID per poter essere autorizzati ad avere questi attributi?

**Comment by mcasamassima** [comment]
Buon pomeriggio l’Istituto è già accreditato su IPA. Il codice IPA è inail e la data di accreditamento risulta essere 01.06.2010.

**Comment by mcasamassima** [comment]
Dai dati presenti in IPA l'accreditamento dovrebbe il 30 gennaio 2005 .

**Comment by FedericaSicchiero** [comment]
Salve, 
in questo caso non c'entra essere su IPA ma l'assegnazione dell'attributo necessario all'accesso per il servizio erogato da ANAC avviene solo a valle della richiesta di certificazione ad AgID e della iscrizione al registro dei gestori delle piattaforme di ANAC.
PDND riceve l'autorizzazione ad assegnare questo attributo solo a conclusione, con successo, di questo processo.
Maggiori informazioni si possono trovare [qui](https://www.agid.gov.it/it/piattaforme/procurement/certificazione-componenti-piattaforme).

**Comment by mcasamassima** [comment]
Salve, vorrei capire se per attestarsi sulla piattaforma di collaudo al fine di poter eseguire i test non sia sufficiente essere iscritti a PDND. D'altra parte sto leggendo le issues sul repository github, nello specifico la seguente https://github.com/anticorruzione/npa/issues/443 e m iè sembrato che fosse sufficiente essere iscritti a pdnd.

**Comment by mcasamassima** [comment]
ok come non detto, ho riletto il caso e il soggetto in questione era già in possesso di utenze ANAC prima ancora di effettuare l'on boarding su PDND

**Comment by FedericaSicchiero** [comment]
Si esatto, noi poi a processo concluso riceviamo l'okay da ANAC e abilitiamo/diamo gli attributi a chi ha fatto richiesta
