### ISSUE TITLE
Attributo certificato non riconosciuto "Comuni e loro Consorzi e Associazioni" per Fruitore Comune di Firenze

### ISSUE THREAD

**Issue by riccafi** [pagopa/pdnd-interop-frontend#64]
**Descrivi il bug**
Richiedendo l'attivazione della fruizione per l'e-Service ConsultazioneISEE, come Comune, si ottiene il messaggio seguente:
"Il tuo ente non ha gli attributi certificati necessari per iscriversi" e non si riesce a perfezionare la richiesta.

**Step per riprodurre il bug**
1. Dal Catalogo degli e-Service selezione del link Ispeziona su "ConsultazioneISEE, v. 1"
2. Vedi l'errore nella parte in basso della pagina "Il tuo ente non ha gli attributi certificati necessari per iscriversi"

**Comportamento atteso**
Ci si aspetterebbe essendo un Comune di avere già attivo l'attributo certificato "Comuni e loro Consorzi e Associazioni"

**Ambiente:**
 - browser Chrome

**Comment by riccafi** [comment]
![Schermata da 2022-05-17 11-55-58](https://user-images.githubusercontent.com/66056766/168785000-baf7ca0e-d377-406d-868c-962e5cf8d834.png)

**Comment by ruggerocastagnola** [comment]
Buongiorno, grazie mille per la segnalazione. Dunque, 

tl;dr: per favore, usate l'E-Service [ConsultazioneISEE - clone](https://uat.gateway.test.pdnd-interop.pagopa.it/ui/it/fruizione/catalogo-e-service/49f5fc89-9e84-488e-bd3e-89defd6b08d2/854ad83a-a69c-43bf-a39b-3ee719fe3382)

**Spiegazione lunga**
INPS ha erroneamente creato la prima volta l'E-Service di consultazione ISEE con tutti gli attributi in lista richiesti. Questo vuol dire che voi dovreste possedere tutti gli attributi nella lista in screenshot contemporaneamente, cosa ovviamente non possibile. Ci era già stato segnalato il problema, e abbiamo dunque sollecitato INPS a ricreare l'E-Service, cosa che hanno fatto con la versione "clone".

Il motivo per il quale l'originale è ancora presente sulla piattaforma è che lato nostro dobbiamo ancora implementare la funzionalità di archiviazione degli E-Service dismessi, prevista nelle prossime settimane.

**Comment by riccafi** [comment]
Ok, 
grazie per il rapido riscontro.
