### ISSUE TITLE
Documentazione e-service, obbligatoria?

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#640]
Sfogliando il catalogo PDND sono sempre di più gli e-service che non hanno documentazione,  tolto il file di definizione YAML o analogo.

Senza una documentazione più diffusa sulla semantica dei dati prelevati o caricati, viene un po' meno il valore e il senso della condivisione di banche dati. In alcuni casi addirittura non si capisce proprio cosa è messo in condivisione. 

È percorribile l'idea di rendere la documentazione "testuale" obbligatoria,  con un minimo di contenuto obbligatorio?

**Comment by FedericaSicchiero** [comment]
Ciao Francesco, si possiamo prenderlo in considerazione anche perchè come dici tu potrebbe togliere eventuali dubbi che gli utenti possono avere verso i servizi. Grazie del feedback!

**Comment by franthemanIT** [comment]
Grazie a te Federica.
Mi permetto di fornire un esempio concreto della situazione, per evitare equivoci da approccio astratto.
Prendo, davvero, un e-service a caso. La situazione e' analoga per altri e-service, di altri enti e di altre software house.

E-service: "Consultazione protocollo"
Erogatore: Comune di Grottammare (e altri tot che si appoggiano su stesso protocollo informatico SaaS, a occhio)

Vedi i dettagli tecnici dell'e-service: presente solo il file "specifica API.yaml"

Attributi richiesti: nessuno, di nessun tipo. Evidentemente (OT rispetto alla issue, ma attiene comunque alla qualità dell'output finale) gli erogatori scelgono di autorizzare le richieste di fruizione "a mano" da interfaccia PDND.

Dal file YAML questo non si capisce, per esempio:
- a chi è rivolta l'API, chi è il fruitore ideale? Verrebbe da pensare che siano amministrazioni che partecipano a procedimenti di cui l'erogatore e' amministrazione procedente (o titolare). E' così?
- riesco a sfogliare tutto il registro di protocollo? Oppure solo alcune registrazioni? E con quali criteri? Tutta la p.a. fruitrice accede a quei dati o solo alcune unità organizzative?
- la possibile response "403 - Autorizzazione non concessa per l'operazione richiesta" lascia pensare che la consultazione sia limitata. Lato fruitore mi farebbe comodo avere qualche indicazione in piu' per implementare le richieste..
- in generale poi, vero che a naso ci si arriva, ma i nomi dei tag JSON di request e resopnse dovrebbero essere esplicitati formalmente nel loro significato per dare un valore (legale e informativo) ai dati scambiati. Fra l'altro nel caso specifico mi pare che ci si discosti anche dai nomi dei tag della segnatura XML ex allegato 6 delle linee guida sul documento informatico (scambio di documenti protocollati fra AOO), quindi sono proprio tag proprietari sui quali sarebbe fondamentale un preventivo accordo...

In generale, poi chiudo, penso che in fase di progettazione - anche solo per valutare il rapporto costi-benefici (*) - si siano individuati i possibili fruitori e alcuni casi d'uso. Ecco, a mio avviso, la documentazione dovrebbe iniziare a dare conto di questi punti e poi entrare nel dettaglio dell'API (semantica, requisiti di accesso ecc.).

(*): il beneficio non è il contributo PNRR ma la trasformazione digitale della p.a. tramite circolazione facile e sicura dei dati
