### ISSUE TITLE
Errore caricamento chiave pubblica

### ISSUE THREAD

**Issue by hsardegna** [pagopa/pdnd-interop-frontend#641]
**Descrivi il bug**
Nel caricare la chiave pubblica sia in Ambiente collaudo che produzione la piattaforma segnala errore
"non è stato possibile caricare la chiave. assicurarsi sia nel formato corretto e riprovare...."

**Step per riprodurre il bug**
1. Vai su interoperabilità collaudo/produzione
2. i tuoi client e-service, tab chiave pubblica

**Il codice IPA del tuo ente**
Comune di Monastir c_f333

**Data e ora in cui si è riscontrato il problema**
es. 20/11/2023 h. 09:30

**Ambiente**
Produzione e Collaudo

**Quali permessi ha la tua utenza?**
 Amministratore

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione. Controlliamo e aggiorniamo la issue appena possibile.

**Comment by hsardegna** [comment]
La piattaforma ora ha accettato.
