### ISSUE TITLE
E-service pubblicato in Produzione ma non visibile dalla piattaforma padigitale2026

### ISSUE THREAD

**Issue by pbrunonmea** [pagopa/pdnd-interop-frontend#648]
Ciao a tutti,
stiamo riscontrando difficoltà nell'adesione dell'ente alla piattaforma padigitale2026, nonostante abbiamo pubblicato con successo e attivato il nostro e-service su PDND. Abbiamo ricevuto comunicazione dalla piattaforma secondo cui PDND al momento non ha trasmesso i dati dell'API 1, risultando in stato "da avviare". Nonostante il catalogo sia pubblicato e visibile in PDND, ci chiediamo perché non risulti visibile dalla piattaforma padigitale2026. Potrebbe essere un problema dell'e-service?

Grazie!

**Comment by FedericaSicchiero** [comment]
Buongiorno,
potete dirci l'ente e l'e-service per cui state facendo questo lavoro?
Avvisiamo che i dati si aggiornano una volta ogni 24 ore, quindi può essere che da oggi siano visibili.

**Comment by pbrunonmea** [comment]
ecco le informazioni:
l'ente è il c_f528 e il servizio è il seguente:
https://www.interop.pagopa.it/catalogo/159c80d9-a0ca-4c90-bc7c-5ba0ccf7814b/
Nel frattempo(stamattina) abbiamo caricato un altro e-service più semplice che non contiene dati geografici.
Grazie per la pronta risposta.
