### ISSUE TITLE
Finalità - aggiunta ruolo per gestione e precaricamento finalità

### ISSUE THREAD

**Issue by mgminelli** [pagopa/pdnd-interop-frontend#65]
Buongiorno,

Per la struttura propria del nostro ente (ma supponiamo condivisa da altri comuni) la parte tecnica che si occupa di interfacciare la PDND e realizzare il dialogo tra i client interni e i soggetti erogatori non conosce le finalità dei vari accessi ai servizi per tutti i client interni all'ente.
Le finalità di accesso e utilizzo ai dati vengono mappate da altri soggetti interni; quindi vi proponiamo di prevedere un ruolo dedicato all'inserimento delle finalità e alla loro manutenzione, in modo da separane la gestione dalla parte tecnica dei client, API e della gestione delle chiavi.

Inoltre, dato che spesso le finalità di accesso ai dati derivano da leggi o fonti giuridiche nazionali, e che spesso sono condivise tra enti dello stesso tipo (es: tutti i Comuni potrebbero accedere ai dati legati alla proprietà di veicoli per l'azione della polizia locale), vi proponiamo di precaricare alcune finalità più comuni da poter associare ai vari client più velocemente.

**Comment by ruggerocastagnola** [comment]
Buonasera, grazie mille per il feedback. Lo taggo come miglioria e lo riporto all'interno del team per valutazione

**Comment by ruggerocastagnola** [comment]
Buongiorno, dunque, ringrazio ancora e rispondo sui due punti:
- sulle utenze, ci aspettiamo che la persona addetta a compilare e gestire le finalità sia di fatto un'utenza con permessi di amministrazione ("amministratore" o "delegato") mentre chi gestirà la fruizione degli E-Service tramite i client sarà un "operatore di sicurezza". Questo modello vi torna, o vi immaginereste altre figure terze (es. "operatore legale")?
- per quanto riguarda i template pre-composti dell'analisi del rischio, richiederà un po' di tempo ma è una feature già presente nel nostro backlog, e sarà implementata

**Comment by ruggerocastagnola** [comment]
Chiudo questa issue, le attività necessarie sono nel nostro backlog e l'avvenuta implementazione sarà segnalata nel changelog del rilascio
