### ISSUE TITLE
Errata visualizzazione validità voucher nei dettagli tecnici dell'e-service

### ISSUE THREAD

**Issue by andreatantillo** [pagopa/pdnd-interop-frontend#657]
**Descrivi il bug**
Errata visualizzazione validità voucher nei dettagli tecnici dell'e-service disponibili a catalogo.

**Step per riprodurre il bug**
1. Selezionare un qualsiasi e-service presente nel catalogo
2. Clicca su 'Vedi dettagli tecnici dell'e-service'
3. La 'durata del voucher' non corrisponde a quella inserita in sede di pubblicazione dell'e-service.

**Comportamento atteso**
Che la durata visualizzata coincida con quella inserita

**Ambiente**
Produzione

**Screenshot**
![chrome_0uvQpFYDkv](https://github.com/pagopa/pdnd-interop-frontend/assets/136598770/8090b8f7-bb8f-4e02-8dc0-be4c4e94cf01)

**Note**
Credo che il sistema converta i minuti inseriti in sede di pubblicazione (es. 3 minuti), in secondi (es. 180 secondi), ma venga mantenuta come unità di misura visualizzata il minuto. E' importante capire se è un mero refuso rispetto all'unità di misura visualizzata (minuti al posto dei secondi) oppure influisce sulla validità del voucher.

**Comment by FedericaSicchiero** [comment]
Buongiorno, si confermo che è un errore di unità di misura e abbiamo mandato su il fix che sistema il disguido.
