### ISSUE TITLE
Problema con voucher spendibile in e-service C020 servizioAccertamentoResidenza

### ISSUE THREAD

**Issue by nahid998** [pagopa/pdnd-interop-frontend#658]
Ciao, Ho un problema quando provo ad usare il voucher che creo nell'audience (**_https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C020-servizioAccertamentoResidenza/v1_**) ,
riesco a crea il voucher con successo e a mandare la richiesta al nostro endpoint (**_https://auth.interop.pagopa.it/token.oauth2_**)
ma come potete vedere dalle immagini qua sotto quando proviamo ad usarla nel audience mi da questa risposta
![Screenshot (8)](https://github.com/pagopa/pdnd-interop-frontend/assets/58596489/9527addf-73db-4f82-8ab1-c657c1909a24)
Mi sapreste indirizzare su come risolvere questo problema.
Grazie mille.

**Comment by FedericaSicchiero** [comment]
Buongiorno, in questo caso bisogna contattare direttamente ANPR/Ministero dell'interno perchè l'errore che ricevete dipende da loro. Purtroppo non abbiamo un contatto diretto da condividere.
