### ISSUE TITLE
InteroperabilityInvalidRequest - ANPR

### ISSUE THREAD

**Issue by nrinaldi01** [pagopa/pdnd-interop-frontend#659]
Sto tentando di accedere al servizio C015 di ANPR. Ottengo con successo l'access token, ma quando interrogo ANPR ricevo:
Response: {"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"834418c2-94df-11ee-bb7f-005056ae1884"}

Sto operando in ambiente di test e sto passando un codice fiscale di quelli dati in esempio.

Sto programmando in Java.

Potete aiutarmi a capire dove sbaglio?
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno,
avete provato a usare il tool di debug del voucher presente in piattaforma come primo step per capire come mai ricevete errore?

**Comment by nrinaldi01** [comment]
Buongiorno,
Si ho già provato e va tutto a buon fine, non ho problemi con la richiesta dell'access token, il problema è successivo, quando chiamo ANPR, servizio C015.

**Comment by FedericaSicchiero** [comment]
Allora bisogna sentire ANPR e capire come mai danno quella risposta. Purtroppo non abbiamo dei contatti diretti da condividere per aiutarvi
