### ISSUE TITLE
Richiedi cambio piano in produzione

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#665]
Stiamo cercando di fare Richiedi cambio piano per una finalità in attesa di approvazione ma prendiamo errore nel momento in cui clicchiamo su aggiorna

Potete farci sapere?

**Comment by FedericaSicchiero** [comment]
Buongiorno, essendo la finalità ancora da approvare ma non più in stato di bozza non è possibile aggiornare la stima di carico. Una volta approvata si potrà modificare il numero di chiamate API indicato.
