### ISSUE TITLE
Impossabile attivare finalità Fruitore

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#669]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Impossabile attivare finalità fruitore 

**Step per riprodurre il bug**
vedi https://selfcare.uat.interop.pagopa.it/ui/it/erogazione/finalita/ee8e75fb-6ca6-4f15-81ca-e891f88583a9

1. cliccando su "attiva ora"

**Comportamento atteso**
l'attivazione della finalità indicata dal Fruitore

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
12/12/2023 17:55

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, ieri stavamo facendo degli aggiornamenti all'ambiente di collaudo, l'errore potrebbe essere dipeso da quello.
Potresti gentilmente riprovare oggi e vedere se ricapita? Grazie

**Comment by vintra73** [comment]
Buongiorno,
come richiesto ho riprovato in questo momento è ancora non riesco ad avere effetti dalla call to action "Attiva ora".

Evidenzio che la finalità era attiva ma è stato effettuato una variazione della stima di carico da parte del Fruitore mantenendo immutato il numero di "Chiamate API/giorno".

Grazie

**Comment by FedericaSicchiero** [comment]
Abbiamo fatto dei controlli e confermo che non si può attivare perchè al momento la finalità è sospesa dal fruitore. Stiamo lavorando per sistemare gli avvisi in modo che quando capitano questo genere di situazioni sia più chiaro il perchè "non funzionino" come dovrebbero.
