### ISSUE TITLE
Errore in compilazione analisi del rischio

### ISSUE THREAD

**Issue by StefanoFlamigni** [pagopa/pdnd-interop-frontend#67]
Otteniamo un errore cercando di compilare l'analisi del rischio di una finalità (RER Finalità test ISEE INPS) definita all'interno del e-service ConsultazioneISEE - clone | Istituto Nazionale Previdenza Sociale - INPS

Si allega file con schermate dei dati inseriti e messaggio di errore finale.
[ErroreAnalidiRischio.docx](https://github.com/pagopa/pdnd-interop-frontend/files/8753385/ErroreAnalidiRischio.docx)

**Comment by ruggerocastagnola** [comment]
Buongiorno Stefano, grazie della segnalazione. Faccio una verifica

**Comment by ruggerocastagnola** [comment]
Confermo che siamo riusciti a replicare il bug. Ho appena rilasciato una fix in ambiente, e dai miei test sembra funzionare. Chiedo per cortesia conferma

**Comment by StefanoFlamigni** [comment]
Abbiamo fatto una prova ed il salvataggio è andato a buon fine :) grazie mille per la sollecitudine
