### ISSUE TITLE
Come gestire l'accesso a PDND dei fornitori e implementare le fruizioni

### ISSUE THREAD

**Issue by franthemanIT** [pagopa/pdnd-interop-frontend#671]
Non è un bug ma una richiesta di confronto.
In due parti.

PARTE 1
Quando un fornitore deve sviluppare o anche solo dispiegare la fruizione di un e-service tramite PDND, sulla PDND stessa sono da fare un bel po' di operazioni: accordo di fruizione, finalità, creazione client e-service, caricamento chiave pubblica.

Stando al glossario le prime tre operazioni puo' farle solo l'utente amministratore. come è corretto che sia del resto (almeno per le prime due abbastanza inequivocabile, si stanno assumendo impegni e responsabilità per conto dell'Amministrazione fruitrice dell'e-service).

Premesso che non è una buona idea nominare un fornitore esterno amministratore (fra l'altro possono essere tre in tutto, quindi anche tappandosi entrambe le narici...), chiedo se la seguente e' l'unica procedura esperibile e se corretta:

L'amministratore (delegato dal legale rappresentante dell'ente):
- chiede l'accordo di fruizione dell'e-service
- crea (almeno) una finalità per ogni e-service fruito
- censisce come utente uno o piu' operatori del fornitore
- crea (almeno) un client per ogni fornitore e gli associa gli utenti del punto precedente come operatori di sicurezza
- alle finalità create in precedenza associa il client del fornitore interessato a quell'e-service.

L'operatore di sicurezza (fornitore):
- vede il client e-service a cui è abilitato;
- ci carica la chiave pubblica
- preleva i dati per voucher e tutto il resto.

PARTE 2
Dando per scontato che ogni ente fruitore abbia la capacità di condurre quanto di sua competenza, pensavo per esempio a cosa comporti per un comune implementare gli e-service di ANPR secondo la circolare DAIT: https://dait.interno.gov.it/servizi-demografici/circolari/circolare-dait-n73-del-31-maggio-2023
Osservando la tabella dell'allegato 1, si devono creare 250 finalità?
Possibile pensare a qualche facilitazione, visto che abbiamo un documento ufficiale DAIT, frutto di accordi con ANCI e ANUSCA, che circoscrive le finalità?

**Comment by FedericaSicchiero** [comment]
Ciao Francesco, grazie du questo tuo feedback e confronto.

Allora per la parte 1 ti confermo che funziona così come dici, ma aggiungo qualche chiarimento:
- l'amministratore non deve essere per forza un delegato dal rappresentante legale, perchè lo stesso rappresentante non deve essere per forza un sindaco una persona al vertice, ma la persona che si assume la responsabilità di firmare l'accordo di adesione e che può corrispondere all'amministratore;
- quella che dici è la procedura corretta ma non per forza l'unica, perchè sta all'ente decidere se "rischiare" e nominare amministratore un fornitore. Anche se volendo lo può nominare amministratore di collaudo e fargli fare tutte le prove lì, così quando poi si arriva in produzione il processo è più veloce perchè si sa già cosa si deve fare (cioè creare i rapporti amministrativi (fruizione, finalità etc) e poi lasciare la parte tecnica al fornitore come operatore di sicurezza o operatore API).

Per la parte 2 stiamo lavorando per vedere se si riesce a semplificare il processo lato PDND, ma non essendo una cosa che abbiamo deciso noi non possiamo neanche pensare di metterci le mani e modificare chissà quali cose.
