### ISSUE TITLE
Posizionamento chiave voucher

### ISSUE THREAD

**Issue by Silvio1970** [pagopa/pdnd-interop-frontend#672]
Buonpomeriggio,
come da oggetto volevo sapere come posizionare i voucher nella chiamata all'api pcp anac in quanto negli yaml tecnici non ne fa riferimento. O per lo meno io non lo individuo.
Sperando in una risposta celere.
saluti

**Comment by FedericaSicchiero** [comment]
Buonasera, in questo caso consigliamo di chiedere direttamente ad ANAC aprendo una issue sul loro [repository](https://github.com/anticorruzione/npa/issues) in modo da ricevere la risposta corretta, grazie
