### ISSUE TITLE
Richiesta assistenza

### ISSUE THREAD

**Issue by robragu** [pagopa/pdnd-interop-frontend#673]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Dopo aver ottenuto correttamente il voucher siamo passati a testare alcune richieste ed inevitabilmente, per qualsiasi richiesta, la risposta ottenuta è:
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"0e8bc78b-9c12-11ee-8e81-0050568e9679"}

Potete aiutarci per capire dove sbagliamo?
Se avete bisogno che vi posti il json e il codice che stiamo utilizzando non c'è problema.

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
 Amministratore

**Comment by FedericaSicchiero** [comment]
Buongiorno, se avete provato anche il tool di debug del voucher presente in piattaforma e vi da come risposta che tutto funzuona correttamente - motivo per cui riuscite anche a staccare il voucher - vuol dire che l'errore dipende dai sistemi dell'erogatore. 
Per quale e-service state cercando di staccare il voucher?

**Comment by robragu** [comment]
Buongiorno, grazie per la risposta.
Stiamo testando il servizio S2, perché è uno di quelli di cui avevamo una struttura json comprensibile.
Il problema è che non abbiamo ben capito la struttura della chiamata, quali header passare, cosa ci deve andare dentro, in tutta onestà stiamo andando per tentativi, non avendo chiara la situazione. 
E devo dire che la documentazione non ci sta aiutando molto, forse per colpa nostra, non saprei.

**Comment by FedericaSicchiero** [comment]
Buongiorno, servizio S2 esposto da chi?
Perchè da quello che diceva sopra il token viene staccato, quindi l'errore dipende dall'erogatore.
Io nel frattempo vi posso condividere questo [video](https://youtu.be/fb-CDltaeqw?feature=shared) che magari è d'aiuto, anche se non si trova in documentazione perchè non è aggiornato alle modifiche più recenti. Fa parte di una playlist con altri video sempre sul tema che spiegano come usufruire al meglio della piattaforma e come staccare il voucher.

**Comment by robragu** [comment]
Scusi, il servizio S2 è esposto da ANAC.
Per quanto riguarda il video postato lo abbiamo già visto e comunque riguarda il voucher, fase che abbiamo superato e che funziona.
La nostra incognita è come costruire la chiamata al servizio.

**Comment by FedericaSicchiero** [comment]
Allora a questo punto vi consiglio di aprire una issue direttamente sulla repository di ANAC (https://github.com/anticorruzione/npa/issues) in modo che vi possano dare tutte le informazioni necessarie. Grazie

**Comment by robragu** [comment]
Grazie a lei
