### ISSUE TITLE
Impossibile nominare nuovi Amministratori

### ISSUE THREAD

**Issue by AlessioMarinelli** [pagopa/pdnd-interop-frontend#674]
**Descrivi il bug**
L'interfaccia non consente di nominare nuovi Amministratori in Interoperabilità produzione

**Step per riprodurre il bug**
1. Vai su [selfcare.pagopa.it](https://selfcare.pagopa.it/dashboard)
2. Clicca su Accedi come ente (con un utente Amministratore)
3. Clicca su Utenti
4. Clicca su Aggiungi Utenti
5. Compila i dati 
6. Seleziona il prodotto Interoperabilità produzione
7. Nell'elenco Ruoli sono disponibili solo "Operatore API" e "Operatore Sicurezza"

**Comportamento atteso**
Poter inserire un nuovo utente con ruolo Amministratore (attualmente abbiamo un solo amministratore in Interoperabilità produzione), come indicato nella documentazione: https://dait.interno.gov.it/documenti/circ-dait-073-servdemo-31-05-2023-all2.pdf

**Il codice IPA del tuo ente**
r_marche

**Data e ora in cui si è riscontrato il problema**
18/12/2023 10:00

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
Buongiorno, chi sta provando a fare questa operazione è amministratore di produzione o di collaudo?

**Comment by AlessioMarinelli** [comment]
Amministratore sia in produzione che collaudo (registrato con l'onboarding originario)

**Comment by FedericaSicchiero** [comment]
Grazie del chiarimento, lo faccio presente al team che si occupa dei ruoli.
Nel frattempo potete passarmi nome e codice fiscale di chi volete aggiungere come amministratore?
Per privacy vi chiedo di mandare tutto alla mail federica.sicchiero@pagopa.it grazie
