### ISSUE TITLE
Urgente: Errore nello stacco del token su produzione

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#676]
{"correlationId":"95aff162-cc68-4c5a-a805-0e75312aeb0f","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}]

Potete risponderci?

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete usato il tool di debug del voucher nel frattempo?

**Comment by amollicone1982** [comment]
Si tratta di un voucher che fino a ieri sera alle 20:10 andava bene.

**Comment by amollicone1982** [comment]
Scusami c'era un errore sulla chiave con cui firmavamo.

Grazie per la collaborazione
