### ISSUE TITLE
[Maintenance] Abilitazione ente fruizione e-service

### ISSUE THREAD

**Issue by CorradoVersolato** [pagopa/pdnd-interop-frontend#677]
Buongiorno, si richiede l'abilitazione dell'ente INSIEL SPA alla fruizione degli e-service PCP di ANAC per procedere ai test in qualità di ente gestore (titolare Regione Friuli Venezia Giulia). Grazie
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/153733278/afba45dc-1d4d-460c-a2f7-f246cd1f26f4)

Insiel - Informatica per Il Sistema Degli Enti Locali S.P.A.
Tipologia
Gestore di servizi pubblici
Categoria
Societa' in Conto Economico Consolidato
Area geografica
Italia
Ragione sociale
Insiel - Informatica per Il Sistema Degli Enti Locali S.P.A.
Codice Fiscale / P.IVA
00118410323
Indirizzo PEC primario
protocollo@pec.insiel.it
Sede Legale
Via San Francesco D'assisi 43 - 34133

**Comment by FedericaSicchiero** [comment]
Salve, stiamo lavorando per aggiungere gli attributi per l'e-service. Vi aggiorniamo appena è stato fatto.

**Comment by FedericaSicchiero** [comment]
Dai nostri sistemi ci risulta che quando ANAC ci ha inviato il documento per abilitarvi e aggiungere gli attributi non ha compilato tutti i campi necessari. Ho aperto una [issue](https://github.com/anticorruzione/npa/issues/922) sulla loro repository in modo che sistemino il file.

**Comment by FavaroInsiel** [comment]
Per INSIEL questo è il codice IPA
Cod IPA | iiisd

Codice Fiscale | 00118410323

https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente/scheda-ente/12689

**Comment by FedericaSicchiero** [comment]
Grazie dell'indicazione, ma deve arrivarci in un documento specifico che ci da ANAC. In questa settimana faremo dei controlli per vedere che sia arrivato tutto.
