### ISSUE TITLE
Chiarimento fruizione versione servizio deprecata

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#678]
Buonasera,
è possibile per un fruitore fare richiesta di fruizione per una versione deprecata ma non archiviata di un servizio?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Buonasera, 
no non è possibile. Rimangono attive solo le richieste di fruizione legate a quella versione finchè il fruitore non le aggiorna e a quel punto la versione deprecata viene archiviata automaticamente dalla piattaforma.

**Comment by mrubiero** [comment]
ok perfetto, grazie mille
