### ISSUE TITLE
Errore nella creazione di un attributo Verificato

### ISSUE THREAD

**Issue by diegopedone** [pagopa/pdnd-interop-frontend#68]
Non risulta possibile creare un nuovo attributo verificato in quanto quando clicco su Crea attributo mi mostra il messaggio "Non è stato possibile creare il nuovo attributo. Per favore, riprova!"

**Step per riprodurre il bug**
1. Vai su Crea E-Service
2. Clicca sulla Crea un nuovo attributo nella sezione Verificati 
3. Compilo il form di inserimenti
4. Clicca su Crea attributo
5. Vedi l'errore "Non è stato possibile creare il nuovo attributo. Per favore, riprova!"

**Ambiente:**
 - OS: Windows 10
 - Browser  chrome
 - Version 101.0.4951.67 (Build ufficiale) (a 64 bit)

**Comment by ruggerocastagnola** [comment]
Ciao Diego, grazie mille del feedback. Non riesco a replicare il problema in questo momento, ho chiesto un check più approfondito per Windows e ti faccio sapere nel pomeriggio. Nel frattempo, se non è oneroso per te posso chiederti di aprire la console di sviluppo e incollarmi l'errore che ti dà? 

Di seguito le istruzioni se non avessi familiarità con il processo:
- cliccare sul menù di Chrome in alto
- selezionare Visualizza > Sviluppo > Developer Tools (non so se in italiano è tradotto con Strumenti per sviluppatori o qualcosa del genere)
- selezionare la tab "Network" e filtrare per "Fetch/XHR" (il bottone subito di fianco a "All" o "Tutti")
- a quel punto compila il modulo e prova a creare un nuovo attributo
- dovresti trovarti una nuova riga rossa con nome "attributes"
- cliccaci sopra e vai alla tab "Preview" (o anteprima, non so se è tradotto in italiano)
- lì dentro c'è il messaggio di errore, se puoi incollarmelo qui

Incollo qui uno screenshot della vista dei Developer tools sperando che semplifichi un po' il processo
<img width="1450" alt="Screenshot 2022-05-24 at 12 28 42" src="https://user-images.githubusercontent.com/6032099/170011406-5d2e045a-ab3c-4658-ad09-e09d306e00a4.png">

**Comment by ruggerocastagnola** [comment]
Ciao Diego, 

abbiamo testato anche da Windows con la versione di Chrome indicata e non replichiamo il problema. Ho un altro sospetto: che sia scaduta la tua sessione ma che per un qualche bug il sistema non ti abbia obbligato a fare logout, e quindi tutti i tentativi che fai non vanno a buon fine.

Ti chiedo per favore di fare logout e login, e di ritentare. Se continuassi a riscontrare il problema anche così, ti chiedo la cortesia di segnalarmelo, e organizziamo un momento per vedere assieme nel dettaglio

**Comment by ruggerocastagnola** [comment]
Ciao @diegopedone, posso chiederti se questa è risolta? Così pulisco un po' la board

**Comment by diegopedone** [comment]
si si risolta
