### ISSUE TITLE
Client E-service errore

### ISSUE THREAD

**Issue by GhineaAlexandra** [pagopa/pdnd-interop-frontend#680]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

Buongiorno, ho un problema con il comune di Numana codice fiscale 00113090427, codice ipa c_f978 , non riesco inviare la richiesta di fruizione perchè non mi vede il client e-service. 
Quando devo aggiungere mi da l'errore.
Se entro nel ambiente Interoperabilità -> Produzione -> Client e-service
Non riesco vedere il client creato. 

**Data e ora in cui si è riscontrato il problema**
02/01/2024

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
 Amministratore

![2024-01-02_121543](https://github.com/pagopa/pdnd-interop-frontend/assets/155565560/49c9fba1-3e10-48cc-a372-e22be6427de2)
![2024-01-02_121746](https://github.com/pagopa/pdnd-interop-frontend/assets/155565560/c16ce02e-21cf-4fac-adf2-b39643721f92)
![2024-01-02_122037](https://github.com/pagopa/pdnd-interop-frontend/assets/155565560/ae717559-46d5-48fe-b679-a10dde4ad4e6)

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, facciamo i nostri controlli e torniamo con una risposta

**Comment by GhineaAlexandra** [comment]
Grazie.

**Comment by GhineaAlexandra** [comment]
Buongiorno, avete qualche risposto. Abbiamo bisogno di fare la configurazione perchè dobbiamo asseverare entro 17/01. Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, ci stiamo lavorando,
Nel frattempo potete darci il correlationID del vostro ente? Si può recuperare in piattaforma con tastro dx --> ispeziona --> console. Grazie

**Comment by GhineaAlexandra** [comment]
X-Correlation-Id: "46828cde-d642-4124-b8b6-be86ce22faf7"

**Comment by GhineaAlexandra** [comment]
![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/155565560/f7c37552-3c3a-486e-9447-6cdb7a8aeb16)

**Comment by FedericaSicchiero** [comment]
Grazie, stiamo facendo tutti i controlli per capire

**Comment by FedericaSicchiero** [comment]
Chiudo il ticket perchè non ci sono più aggiornamenti.
