### ISSUE TITLE
Errore chiamata verso Endpoint Crea-Appalto

### ISSUE THREAD

**Issue by pwerner67** [pagopa/pdnd-interop-frontend#682]
Dopo aver seguito tutte le istruzioni riusciamo a farci rilasciare un Access Token da utilizzare in Authorization Bearer.
L'errore arriva sulla chiamata finale verso EndPoint crea-appalto in quanto il server ritorna Status Code 403 - Insufficient token claims.

Non riusciamo a capire quali siano i Token Claims mancanti e soprattutto dove
a) nella creazione del Client Assertion ?
b) nella creazione del primo JWS ?

Qualcuno ha avuto lo stesso errore e ci puo' aiutare ?

Di seguito il Payload utilizzato per il pirmo JWS:
{
"iat": 1704474580,
"nbf": 1704474580,
"exp": 1704560980,
"aud": "https://apigw-test.anticorruzione.it/modi/rest/ComunicaAppalto/v1",
"jti": "402c0d26-9e70-43b3-88fe-d89076b036cb",
"userCodiceFiscale": "PRVTST67l18b582l",
"userRole": "RP",
"userLoa": "3",
"userIdpType": "SPID",
"SACodiceFiscale": "12345678901",
"SAcodiceAUSA": "154591",
"regCodicePiattaforma": "0000067",
"regCodiceComponente": "0000067",
"businessFlowID": "00000000-0000-0000-0000-000000000000",
"traceID": "bef3a64a-ed96-4bdb-b93f-22760e9aef51",
"spanID": "d03ce40f-3c1f-4f9b-ac2d-29b663e30120"
}
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti ad assisterti più rapidamente.
NB: la tua client assertion è un'informazione sensibile: non inserirla all'interno di questa issue. Ogni richiesta contenente informazioni riservate o sensibili sarà rimossa senza preavviso dagli amministratori.

**Step di auto-debug**
Prima di aprire un issue, puoi effettuare le seguenti verifiche per escludere un errore di configurazione:
1. Se stai richiedendo un voucher per un e-service, il `purposeId` inserito è quello corretto? SI
2. il `client_id` inserito nella richiesta al server autorizzativo corrisponde al valore inserito come subject (campo `SUB`) nella client assertion? SI
3. la chiave privata con la quale è stata firmata la client assertion corrisponde alla pubblica (campo `KID`) depositata su PDND Interoperabilità? SI
4. la chiave con la quale firmi l'asserzione (campo `KID`) è inserita all'interno del client che hai indicato (campo `SUB`)? SI

comune peschiera del garda

**Il codice IPA del tuo ente**
Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente

**Data e ora del tentativo**
es. 05/01/2024 h. 17:20

**Ambiente**
Collaudo

**client_id**
Es. `3b0d583b-7d4c-4bcf-a27c-1d82e81fa321`

**correlationId**
Il campo che identifica la richiesta, viene restituito dal backend all'interno della risposta assieme all'errore. Es. `47508f4c-bc49-4d34-8adb-a85f734b45b9`

**purposeId (solo per i client e-service)**
È uno dei campi che hai inserito all'interno della client assertion. Es. `69fb9f60-bd47-4b4d-9652-9747f7953234`

**Comment by FedericaSicchiero** [comment]
Buongiorno,
se riuscite a staccare il token e ricevete errore solo in seguito vuol dire che qualcosa non funziona lato erogatore, che a vedere dall'audience indicata è ANAC.
Vi consiglio di aprire una issue sulla loro repository: https://github.com/anticorruzione/npa/issues

Grazie
