### ISSUE TITLE
dopo aver creato il voucher non riesco ad interrogare l'api, ricevo errore 404

### ISSUE THREAD

**Issue by gp-elips** [pagopa/pdnd-interop-frontend#685]
Salve,
dopo aver creato il Bearer Token, provo a fare una POST sull'API che ho trovato nel file Yaml dell'e-service, ma ricevo errore 404
vedi screenshot allegato.
Dove sto sbagliando?

Grazie in anticipo

Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
descrizione sopra

**Step per riprodurre il bug**
creo il token
col token provo a lanciare una post sull'URI dell'API che ho trovato nel file Yaml e provo a passare la richiesta nel body, ma ricevo errore 404

**Comportamento atteso**
mi aspetterei una risposta dall'API endpoint, ma mi dice errore 404, non trovato

**Il codice IPA del tuo ente**
Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente

**Data e ora in cui si è riscontrato il problema**
09/01/2024 ore 17.50 circa

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
 Amministratore

**Screenshot**
allegato
![2tlklbu9](https://github.com/pagopa/pdnd-interop-frontend/assets/156077693/8431676c-bda1-40a1-9b6d-02f4e203a71f)

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Buongiorno,
in questo caso quando il token si riesce a staccare ma poi si ottiene errore nella risposta andando a richiamare le API vuol dire che qualcosa non torna all'erogatore (che a vedere dallo screen è ANPR/Ministero dell'Interno). Bisogna contattare loro e chiedere chiarimenti.
