### ISSUE TITLE
[Collaudo] C019-servizioAccertamentoEsistenzaVita-approvazione_automati, versione 4

### ISSUE THREAD

**Issue by ivano-manara** [pagopa/pdnd-interop-frontend#687]
Vi informo che non riusciamo a chiamare il servizio:

https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002

utilizzano i dati di test proposti da tracciato:

 {
   "idOperazioneClient": "1",
     
    "criteriRicerca": {
      "codiceFiscale": "STTSGT90A01H501J"
    },
    "datiRichiesta": {
     "dataRiferimentoRichiesta": "2023-12-13",
      "motivoRichiesta": "1",
      "casoUso": "C001"
    }
  }
  
il vostro servizio fornisce il seguente errore:

GovWay-Transaction-ID: c20db63c-b04e-11ee-8857-005056ae1884
{"type":"https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html","title":"InteroperabilityInvalidRequest","status":400,"detail":"Received request is not conform to the required interoperability profile","govway_id":"c20db63c-b04e-11ee-8857-005056ae1884"}

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad utilizzare il tool di debug del voucher presente in piattaforma?
Perchè se utilizzandolo vi da tutte le spunte verdi ma l'errore persiste vuol dire che dipende dal server dell'erogatore, in questo caso ANPR e non da PDND Interoperabilità.

**Comment by ivano-manara** [comment]
Buongiorno, 
utilizzando il tool di debug le spunte sono tutte verdi.
Grazie del veloce feedback

**Comment by gp-elips** [comment]
@ivano-manara Ciao Ivano, mi chiamo Gaetano. Ho anche io lo stesso problema, mi potresti aiutare? Come hai risolto?
Anche io utilizzando il tool di debug ho tute le spunte verdi
