### ISSUE TITLE
Mancanza servizio https://uat.gateway.test.pdnd-interop.pagopa.it/api-gateway/0.1/as/token.oauth2 in ambiente di collaudo

### ISSUE THREAD

**Issue by diegopedone** [pagopa/pdnd-interop-frontend#69]
Da oggi ci siamo accorti che il servizio https://uat.gateway.test.pdnd-interop.pagopa.it/api-gateway/0.1/as/token.oauth2 non è più disponibile. 
Anche su Swagger https://uat.gateway.test.pdnd-interop.pagopa.it/api-gateway/0.1/swagger/docs/index.html risulta non presente tale servizio.
In alternativa a tale servizio come possiamo richiedere il token alla PDND?

**Comment by ruggerocastagnola** [comment]
Buongiorno Diego,

`as/token.oauth2` è un vecchio endpoint che è stato spostato. Le istruzioni aggiornate per lo stacco del token sono disponibili direttamente in pagina all'interno del client associato alla finalità per la quale si vuole staccare il token. In sostanza, andare su Fruizione > I tuoi client, selezionare il client di interesse e dovrebbe esserci subito una tab "Istruzioni ottenimento access token" oppure in [questo video](https://www.youtube.com/watch?v=6TJmBDuVQBo&list=PLISbU7YluIuhjINKwYcohBR1YhPq2B5mT&index=11) della playlist introduttiva. Allego screenshot sotto per chiarezza e segnalo ai miei colleghi che è rimasta una parte di documentazione non aggiornata

<img width="1527" alt="Screenshot 2022-05-25 at 16 34 44" src="https://user-images.githubusercontent.com/6032099/170288387-319231f1-9dd7-415e-9814-0fef4df4dede.png">

**Comment by ruggerocastagnola** [comment]
Chiudo questa issue. In caso il problema non fosse risolto chiedo cortesemente di riaprirla e aggiungere ulteriori dettagli
