### ISSUE TITLE
Errore creazione chiavi pubbliche utilizzo piattaforma CIG.

### ISSUE THREAD

**Issue by Eugenio1983** [pagopa/pdnd-interop-frontend#692]
Buongiorno.

Seguendo le Vostre indicazioni, con il supporto della società affidataria del servizio di supporto informatico per il Comune di Venzone, non è stato possibile concludere l'iter di produzione della coppia delle chiavi pubbliche indispensabili per fruire del servizio.
In particolare emerge l'errore di cui all'immagine allegata.
Preciso che si è proceduto a cercare di produrre le chiavi sia con CMD che con PowerShell.
Inoltre chiedo cortesemente se può essere fornita una guida per la produzione delle chiavi per Windows e non per Mac.

Restando in attesa di un Vostro cortese riscontro, porgo cordiali saluti.

dott. Eugenio Bortolotti
 
 
Responsabile Area Amministrativa - Contabile,
Manutentiva e del patrimonio

Comune di Venzone
Piazza Municipio, 1
33010 Venzone (Ud)
Tel. 0432.985266 (int. 207)
[Errore.pdf](https://github.com/pagopa/pdnd-interop-frontend/files/13940819/Errore.pdf)

**Comment by FedericaSicchiero** [comment]
Buonasera, controlliamo e vi aggiorniamo. Per quanto riguarda la guida, grazie vedremo di realizzarla in tempi brevi.

**Comment by Eugenio1983** [comment]
Buongiorno.

Ci sono novità in merito alla segnalazione di errore?


Grazie mille


dott. Eugenio Bortolotti





Responsabile Area Amministrativa - Contabile,

Manutentiva e del patrimonio

Comune di Venzone
Piazza Municipio, 1
33010 Venzone (Ud)
Tel. 0432.985266 (int. 207)
e-mail ***@***.***<https://posta.um.fvg.it/ecp/Customize/redir.aspx?C=XB3jfM0OJlGf-znkeXefp-eKwG7kJBlA1tRluKSqwelz-UOzvujWCA..&URL=mailto%3aeugenio.bortolotti%40comunedivenzone.it>



________________________________
Da: Federica Sicchiero ***@***.***>
Inviato: lunedì 15 gennaio 2024 17:04:54
A: pagopa/pdnd-interop-frontend
Cc: Bortolotti Eugenio - Venzone; Author
Oggetto: Re: [pagopa/pdnd-interop-frontend] Errore creazione chiavi pubbliche utilizzo piattaforma CIG. (Issue #692)


Buonasera, controlliamo e vi aggiorniamo. Per quanto riguarda la guida, grazie vedremo di realizzarla in tempi brevi.

**Comment by FedericaSicchiero** [comment]
Buongiorno, l'errore che ricevete è perchè il terminale non riconosce openssl essendo istruzioni per il Mac. Stiamo lavorando per la guida per Windows ma non sappiamo darvi una tempistica su quando sarà pronta. Nel frattempo potete provare seguendo i link [qui](https://www.google.com/search?q=generate+rsa+key+pair+windows&oq=generate+rsa+key+pair+windows&gs_lcrp=EgZjaHJvbWUyCwgAEEUYExg5GIAEMgkIARAAGBMYgAQyCggCEAAYExgWGB4yCggDEAAYExgWGB4yCggEEAAYExgWGB4yCggFEAAYExgWGB4yCggGEAAYExgWGB4yCggHEAAYExgWGB7SAQg4NDQxajBqN6gCALACAA&sourceid=chrome&ie=UTF-8) e noi cercheremo di esservi di massimo supporto tramite questa issue.

**Comment by FedericaSicchiero** [comment]
Chiudo la issue con possibilità di riaprirla in caso di necessità
