### ISSUE TITLE
Errore Interrogazione API

### ISSUE THREAD

**Issue by gp-elips** [pagopa/pdnd-interop-frontend#696]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Creato il voucher (verificato attraverso il debug ed è tutto ok)
creato il token
eseguito questo comando per lo STATUS (bearer token oscurato):
```
curl -X 'GET' \
  'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/status' \
  -H 'accept: application/problem+json' \
  -H 'Authorization: Bearer eyJ0eXAiOiJhxxxxx' 
```
risultato:
body
`{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "c76a3279-b618-11ee-9bf8-005056ae091b"
}`
headers
`cache-control: no-cache 
 content-length: 274 
 content-type: application/problem+json 
 date: Thu,18 Jan 2024 16:09:23 GMT 
 etag: W/"112-Hpz31JLsw54Q0bCj2laZl8N4hkA" 
 expires: -1 
 govway-message-id: c879f4cd-b618-11ee-9bf8-005056ae091b 
 govway-transaction-errortype: InteroperabilityInvalidRequest 
 govway-transaction-id: c76a3279-b618-11ee-9bf8-005056ae091b 
 pragma: no-cache 
 server: nginx 
 vary: * 
 x-backside-transport: FAIL FAIL 
 x-content-type-options: nosniff 
 x-global-transaction-id: db4aa80165a94d333068995d 
 x-powered-by: Express 
 x-ratelimit-limit: 50000 
 x-ratelimit-remaining: 49969 
 x-ratelimit-reset: 24636 `

Eseguito il comando per il POST /anpr-service-e002

Comando:
`curl -X 'POST' \
  'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer eyJ0eXAxxxxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "idOperazioneClient": "asdasd131312sadsad",
  "criteriRicerca": {
    "codiceFiscale": "XXXXXX84H21G288L",
    "idANPR": "",
    "cognome": "",
    "senzaCognome": "",
    "nome": "",
    "senzaNome": "",
    "sesso": "",
    "datiNascita": {
      "dataEvento": "2021-11-15",
      "senzaGiorno": "",
      "senzaGiornoMese": "",
      "luogoNascita": {
        "luogoEccezionale": "",
        "comune": {
          "nomeComune": "",
          "codiceIstat": "",
          "siglaProvinciaIstat": "",
          "descrizioneLocalita": ""
        },
        "localita": {
          "descrizioneLocalita": "",
          "descrizioneStato": "",
          "codiceStato": "",
          "provinciaContea": ""
        }
      }
    }
  },
  "datiRichiesta": {
    "dataRiferimentoRichiesta": "2021-11-15",
    "motivoRichiesta": "",
    "casoUso": ""
  }
}'`

risposta:
`{
  "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
  "title": "InteroperabilityInvalidRequest",
  "status": 400,
  "detail": "Received request is not conform to the required interoperability profile",
  "govway_id": "2d997277-b61a-11ee-85c7-005056ae6555"
}`

**Comportamento atteso**
una risposta 200 con l'esito sul codice fiscale interrogato

**Il codice IPA del tuo ente**
Assicurazione

**Data e ora in cui si è riscontrato il problema**
18-01-2024, tutto il giorno

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/156077693/d6c07f8d-9ff0-4d7d-9a25-999a5e824e54)

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Buonasera, avete provato ad usare il tool di debug del voucher presente in piattaforma? Perchè se li tutte le spunte sono verdi vuol dire che il problema sta nel server dell'erogatore e bisognerebbe contattare direttamente loro.

**Comment by gp-elips** [comment]
Buonasera Federica,

si, voucher debuggato ed è tutto regolare. 
Lato erogatore abbiamo la certezza che funzioni, perchè altri colleghi di altre compagnie riescono ad utilizzarlo.

Ci sono altre cose che possiamo fare?

**Comment by FedericaSicchiero** [comment]
Al momento no, facciamo anche noi dei controlli ulteriori e aggiorno la issue se ci sono novità. Grazie

**Comment by afrontera85** [comment]
Buongiorno, state facendo dei test in ambiente di produzione anzichè collaudo... 
In collaudo l'url è questo:
https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
Anche il voucher pdnd va staccato dall'ambiente di collaudo.
L'errore 400 comunque è un errore generico relativo all'implementazione della cornice di sicurezza, nello specifico relativamente al govway_id": "2d997277-b61a-11ee-85c7-005056ae6555 l'errore è il seguente:
**Validazione security token ModI 'INTEGRITY' della richiesta fallita: Header HTTP 'Agid-JWT-Signature' non presente**.
Quì trovate un esempio di client che implementa i profili di cui Anpr necessita: 
[](https://github.com/italia/anpr/issues/3964)
Potete usarlo per la chiamata al servizio modificando opportunamente il file pdnd.properties.

**Comment by gp-elips** [comment]
@afrontera85 grazie per la risposta.
Buongiorno.
In reatlà non passiamo l'Agid-JWT-Signature, perchè da doc ho interpretato che andava passato l'Agid-JWT-TrackingEvidence.

questa è l'ultima chiamata che ho provato ieri sera:

`.\curl.exe -X 'POST' `
>>   'https://modipa.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002' `
>>   -H 'accept: application/json' `
>>   -H 'Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS5hbnByLmludGVybm8uaXQvZ292d2F5L3Jlc3QvaW4vTWluSW50ZXJub1BvcnRhQU5QUi9DMDE5LXNlcnZpemlvQWNjZXJ0YW1lbnRvRXNpc3RlbnphVml0YS92MSIsInN1YiI6ImJhYmQzY2M2LWVkOWUtNGE1Mi05YmU3LWVmODI4MTVhZDNjMCIsIm5iZiI6MTcwNTYxOTY1MCwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiMjkwNjhhNmVlZjM5MTJkZjU4OGVhNDJhZDZkNzU1MTA4NzIwMDFmNWUxZTQyOGM5OGZjZGQyNWMxZDM4YmVmNyJ9LCJwdXJwb3NlSWQiOiJkYmI1NGY1ZS01ODY1LTRiMWYtODE4OC04YWRiNDIzZTE5MGMiLCJpc3MiOiJpbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTcwNTYyMDI1MCwiaWF0IjoxNzA1NjE5NjUwLCJjbGllbnRfaWQiOiJiYWJkM2NjNi1lZDllLTRhNTItOWJlNy1lZjgyODE1YWQzYzAiLCJqdGkiOiI3MzNlNDkzOC03NWZhLTQzNTctOTdlNy1mN2VkYmE1NGNjZDEifQ.Yw4F5qvQS5vZLaRLOLVWi1VYS8vHnBpPR36QNI_V3TvZBpUAEoS0LyVQvK7PtMcyX60Rf5yaFzYpuE4qeiFALC2njd6WyH98NJEY6vWvoHioxPBYLyNhQGFA-0VRx-gvNiD6cYqm6xBd4ikN1P7hzC8uVIXxdx0AB8ygxx5UGhuNAaPdqBJCh6GJOHfMLErNQv0eIolkbL6gs18U7EoKgjEadNofNo7nGtcvwgC3IpIZzxVITtjwfQSDiXQ7jbd4R5-RPaw1fMET49EFJLF46caXm-CUefEZRkFBv9bJeGeAqLFSynFz70fmocW-qK_ijaNEzFnQ0kHUn_yU_wpPXA' `
>>   -H 'Agid-JWT-TrackingEvidence: eyJhbGciOiJSUzI1NiIsImtpZCI6ImcyR2hPa3NYc05kU0NDVG9yZWFUaGFwQURzRjRqRjRYMnhEZTFRNUNsbG8iLCJ0eXAiOiJKV1QifQ.eyJkbm9uY2UiOiI0NTM5ODQ1MDE4Mjg3IiwiaXNzIjoiYmFiZDNjYzYtZWQ5ZS00YTUyLTliZTctZWY4MjgxNWFkM2MwIiwiYXVkIjoiaHR0cHM6Ly9tb2RpcGEuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFItUERORC9DMDE5LXNlcnZpemlvQWNjZXJ0YW1lbnRvRXNpc3RlbnphVml0YS92MSIsInB1cnBvc2VJZCI6ImRiYjU0ZjVlLTU4NjUtNGIxZi04MTg4LThhZGI0MjNlMTkwYyIsImp0aSI6ImFjNjhhMzhlLTYyNzMtNDRmMS04Y2M1LTBlNTE2MGJjN2MwOCIsImlhdCI6MTcwNTYxODk5MSwiZXhwIjoxNzA4MjEwOTkxfQ.AS3O9-s_53wvYzRzlY1q5b2OM4BdpETdqnD4ni7k1O_1Fyd-0vN8ZYdk86SiEDYUjtBwWpgeWXhNBSQOUJ2lkUr4x28USxUgo8a1j22a9p6Be8fcCqfzaOFoVe5SatNZWh4YqiJmqnocp1HoTNltdFxe94If8H5DGvQVExBUufoeBrrZOo1DiORbXXf93TN-D23YzV_9Zj8TQyAVzn37ZBGrtGTRa80xTS309nsNMiy4oQ3qDB_QLiTd9kHy-ECW6ABPyrSxWxrixHrETwrgcVDLRpI4X7eJMxlnFoBuNeTTcn7J3EgWDWHEU9BB7J4hgTc9DXO4pzzPAEsWioaqlQ' `
>>   -H 'Digest: SHA-256=29068a6eef3912df588ea42ad6d75510872001f5e1e428c98fcdd25c1d38bef7' `
>>   -H 'Content-Type: application/json' `
>>   -d @"
>> {
>>   \"idOperazioneClient\": \"asdasd13123\",
>>   \"criteriRicerca\": {
>>     \"codiceFiscale\": \"PRRGTN84H21G288L\",
>>     \"idANPR\": \"\",
>>     \"cognome\": \"\",
>>     \"senzaCognome\": \"\",
>>     \"nome\": \"\",
>>     \"senzaNome\": \"\",
>>     \"sesso\": \"\",
>>     \"datiNascita\": {
>>       \"dataEvento\": \"\",
>>       \"senzaGiorno\": \"\",
>>       \"senzaGiornoMese\": \"\",
>>       \"luogoNascita\": {
>>         \"luogoEccezionale\": \"\",
>>         \"comune\": {
>>           \"nomeComune\": \"\",
>>           \"codiceIstat\": \"\",
>>           \"siglaProvinciaIstat\": \"\",
>>           \"descrizioneLocalita\": \"\"
>>         },
>>         \"localita\": {
>>           \"descrizioneLocalita\": \"\",
>>           \"descrizioneStato\": \"\",
>>           \"codiceStato\": \"\",
>>           \"provinciaContea\": \"\"
>>         }
>>       }
>>     }
>>   },
>>   \"datiRichiesta\": {
>>     \"dataRiferimentoRichiesta\": \"2021-11-15\",
>>     \"motivoRichiesta\": \"123asd\",
>>     \"casoUso\": \"C019\"
>>   }
>> }
>> "@`

Risultato:
`{ "type": "https://govway.org/handling-errors/404/NotFound.html", "title": "NotFound", "status": 404, "detail": "Unknown API Request", "X-Global-Transaction-ID": "7dbb991665a9b37f01666ced" }`


Alcune domande:

- dobbiamo quindi configurare anche collaudo prima di usare prod?
- negli headers cosa dobbiamo agigungere Agid-JWT-Signature o Agid-JWT-Tracking evidence?
- cosa dobbiamo aggiugnere in questi headers? per il momento in Agid-JWT-TrackingEvidence stiamo mettendo il JWS di Audit che creiamo all'inizio.

Grazie in anticipo per il supporto

**Comment by afrontera85** [comment]
attendete, però vi pregherei di aprire una issue lato ANPR. Grazie

**Comment by gp-elips** [comment]
@afrontera85 , dove si apre una issue lato ANPR?
Grazie in anticipo

per quanto riguarda queste info:

- dobbiamo quindi configurare anche collaudo prima di usare prod?
- negli headers cosa dobbiamo agigungere Agid-JWT-Signature o Agid-JWT-Tracking evidence?
- cosa dobbiamo aggiugnere in questi headers? per il momento in Agid-JWT-TrackingEvidence stiamo mettendo il JWS di Audit che creiamo all'inizio.

**Comment by afrontera85** [comment]
[https://github.com/italia/anpr/issues](url)

**Comment by gp-elips** [comment]
Risolto per il portale collaudo.
Adesso stiamo usando il client che ci avete fornito e riceviamo questo esito con il seguente body di richiesta:

body
`[4:21 PM] Gaetano Parrello
{

   "idOperazioneClient": "1",

    "criteriRicerca": {

      "codiceFiscale": "XXXXXX84H21G288L"

    },

    "datiRichiesta": {

     "dataRiferimentoRichiesta": "2022-12-13",

      "motivoRichiesta": "1",

      "casoUso": "C019"

    }

  }`

esito:
`GovWay-Transaction-ID: 28cb8c6b-b6dd-11ee-834e-005056ae1d2a
{"type":"[https://govway.org/handling-errors/404/UndefinedOperation.html","title":"UndefinedOperation","status":404,"detail":"Operation](https://govway.org/handling-errors/404/UndefinedOperation.html%22,%22title%22:%22UndefinedOperation%22,%22status%22:404,%22detail%22:%22Operation) undefined in the API specification","govway_id":"28cb8c6b-b6dd-11ee-834e-005056ae1d2a"}
 
Process finished with exit code 0`

**Comment by FedericaSicchiero** [comment]
Chiudo questa issue perchè aperta correttamente nella repository di ANPR
