### ISSUE TITLE
Richiesta Info sull'ambiente di test PDND

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#70]
Per l'esecuizone del test PDND per conto del Comune di Torino, avrei bisogno di ricevere le seguenti info:

1) all'URL https://uat.gateway.test.pdnd-interop.pagopa.it/api-gateway/0.1/swagger/docs/index.html , che è quella indicata nellle informazioni da voi fornite, non vedo il metodo per ottenere il token, quello che, nella documentazione tecnica che ci avete messo a disposizione sul google drive, era indicato come

        GET /api/vx.x/as/token.oauth2 HTTP/1.1

        HOST: https://pdnd_interop_domain/

    Potete suggerirmi l'url a cui inviare la richiesta di Voucher?

2) vorremmo testare il servizio "INAD API PUBBLICHE CONSULTAZIONE (PER ATTRIBUTO MOCK)",  ma al mpmento dell'iscrizione viene indicaro che "Il tuo ente non ha gli attributi certificati necessari per iscriversi".

- E' possibile aggiungere l'attributo richiesto al Comune di Torino in test? come?

- in caso contrario, il servizio non è testabile?

- oppure esiste un servizio analogo che non richiede l'attributo?

3) h provato la registrazione al servizio "ConsultazioneISEE - clone, versione 1"; ora la richiesta è in attesa di approvazione. Quest'ultima operazione sarà gestita direttamente  da INPS oppure posso fare qualcosa io per applicare l'approvazione? 

Grazie e cordiali saluti,
corrado.tamietti@csi.it

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, grazie mille per le domande. Dunque:

1. la rimando alla risposta in un'altra issue, [qui](https://github.com/pagopa/pdnd-interop-frontend/issues/69#issuecomment-1137346785)
2. faccio un check interno per capire
3. l'approvazione è in mano ad INPS, anche qui faccio un check interno per capire se in questa fase di test c'è modo di velocizzare l'approvazione

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, rispondo sugli altri due punti:
2. abbiamo chiesto chiarimenti a nostra volta per capire. Se non c'è un servizio senza l'attributo di mock probabilmente sarà creato ex novo dall'Erogatore, siamo in attesa di risposta. Appena ho aggiornamenti mi faccio vivo
3. abbiamo segnalato all'Erogatore che c'è la vostra richiesta in attesa in modo che sia presa in carico

**Comment by ctamietti** [comment]
Grazie Ruggero, attendiamo aggiornamenti.

**Comment by marcocipri** [comment]
Buongiorno,
il servizio C009 non dovrebbe essere già recuperabile dal comune indipendentemente da PDND-interop?

**Comment by vintra73** [comment]
Buongiorno @ctamietti 
in merito all'accesso al servizio "INAD API PUBBLICHE CONSULTAZIONE (PER ATTRIBUTO MOCK)", indicato al precedente punto 2, le segnalo che lo stesso è un mock utilizzato per i test in corso da parte dello stesso sistema INAD e non è previsto l'accesso agli altri Aderenti della PDND. Conclusi i test del sistema INAD sarà disponibile l'equivalente servizio INAD utile agli integratrion test degli Aderenti, limitatamente alle pubbliche amministrazioni e gestori di pubblici servizi cosi come indicato nelle LG INAD adottate da AgID.

**Comment by ctamietti** [comment]
> Buongiorno, il servizio C009 non dovrebbe essere già recuperabile dal comune indipendentemente da PDND-interop?

Buongiorno Marco,
premesso che non intrndo se la sua domanda è rivolta al Comune di Torino o ad altri, chiarisco comunque che l'intento nel registrarsi a quel servizio non è tanto l'accesso al servizio di per se, quanto avere un servizio su cui poter procedere ai passaggi successivi all'approvazione dell'iscrizione da parte dell'Erogante.
5. Colgo l'occasione per chiedere se tra quelli elencati nel catalogo c'è un E-Service a cui registrarsi e per il quali possiamo avere approvazione in tempi rapidi.

Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ctamietti** [comment]
> Buongiorno @ctamietti in merito all'accesso al servizio "INAD API PUBBLICHE CONSULTAZIONE (PER ATTRIBUTO MOCK)", indicato al precedente punto 2, le segnalo che lo stesso è un mock utilizzato per i test in corso da parte dello stesso sistema INAD e non è previsto l'accesso agli altri Aderenti della PDND. Conclusi i test del sistema INAD sarà disponibile l'equivalente servizio INAD utile agli integratrion test degli Aderenti, limitatamente alle pubbliche amministrazioni e gestori di pubblici servizi cosi come indicato nelle LG INAD adottate da AgID.

Grazie 1000 Vincenzo.
il servizio INAD utile agli integratrion test degli Aderenti sarà pubblicato nel catalogo PDND quando sarà disponibile?
Cordiali saluti,
Corrado Tamietti

**Comment by vintra73** [comment]
@ctamietti 
si corrado, il servizio INAD utile agli Aderenti sarà disponibile solo su PDND.

Grazie

**Comment by marcocipri** [comment]
Buongiorno,
C009 dovrebbe essere stato attivato per il comune di Torino.
Potete confermare?

**Comment by ctamietti** [comment]
> Buongiorno, C009 dovrebbe essere stato attivato per il comune di Torino. Potete confermare?

Buon pomeriggio,
si, confermo che l'isrizione è stata attivata; procedo con creazione della finalità e dei client. Lo scopo è arrivare a ottenere un voucher PDND e spenderlo nella chiamata all'API.

Perciò aggiungo ulteriori richieste:
6. indicatemi per favore se questo servizio non è adatto allo scopo;
7. presumo che per la chiamata all'API del Mininstero dell'Interno sia necessario uno scambio di materiale crittografico con loro. E' corretto? Avete un riferimento del Ministero che possiamo contattare?

Grazie e a presto

**Comment by marcocipri** [comment]
per il punto 6 : una volta che siete abilitati alla fruizione del servizio potete staccare un Voucher autorizzativo dalla PDND da "spendere" sul servizio dell'erogatore.
Ulteriori cornici di sicurezza (per esempio Mutual TLS....) e il protocollo di di comunicazione (rest/soap etc etc) sono caratteristiche definite da ogni Erogatore all'interno del Modello di Interoperabilità di AgID.

**Comment by ctamietti** [comment]
> Buongiorno, C009 dovrebbe essere stato attivato per il comune di Torino. Potete confermare?

Buon pomeriggio,
si, confermo che l'isrizione è stata attivata; procedo con creazione della finalità e dei client. Lo scopo è arrivare a ottenere un voucher PDND e spenderlo nella chiamata all'API.

Perciò aggiungo ulteriori richieste:
6. indicatemi per favore se questo servizio non è adatto allo scopo;
7. presumo che per la chiamata all'API del Mininstero dell'Interno sia necessario uno scambio di materiale crittografico con loro. E' corretto? Avete un riferimento del Ministero che possiamo contattare?

Grazie e a presto

**Comment by ctamietti** [comment]
Chiudo questo issue; in caso di bisogno lo riapro o ne definisco un altro.
Grazie a tutti.
