### ISSUE TITLE
Errore chiamata servizio - Collaudo

### ISSUE THREAD

**Issue by LucianoCFAss** [pagopa/pdnd-interop-frontend#700]
Nella generazione del client assertion tramite lo script create_client_assertion.py qual’è il valore del campo aud che si deve settare per poter richiedere correttamente il voucher per l’accesso al servizio https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1 ?

Lasciando la generazione con il parametro di default, ovvero auth.uat.interop.pagopa.it/client-assertion la generazione del voucher avviene correttamente ma poi quel token non funziona nella chiamata effettiva al servizio di AccertamentoEsistenzaVita.

**Comment by FedericaSicchiero** [comment]
Buongiorno, in questo caso vi consiglio di aprire una issue direttamente a ANPR (https://github.com/italia/anpr/issues) in modo che possano dirvi il valore che richiedono per l'audience. Grazie

**Comment by LucianoCFAss** [comment]
Buongiorno,
grazie per il suggerimento. Procediamo immediatamente,

Luciano Polinari
________________________________
Da: Federica Sicchiero ***@***.***>
Inviato: mercoledì 24 gennaio 2024 09:28
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Luciano Polinari ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] Errore chiamata servizio - Collaudo (Issue #700)


Buongiorno, in questo caso vi consiglio di aprire una issue direttamente a ANPR (https://github.com/italia/anpr/issues) in modo che possano dirvi il valore che richiedono per l'audience. Grazie
