### ISSUE TITLE
problema WS di accertamento esistenza in vita di un soggetto

### ISSUE THREAD

**Issue by mario-rossi-italia** [pagopa/pdnd-interop-frontend#701]
15.01.2024

Buonasera,
stiamo procedendo con l’integrazione del servizio di accertamento esistenza in vita all’interno dei nostri sistemi informatici. Abbiamo completato la fase di accreditamento sul portale e riusciamo a recuperare correttamente il token JWT chiamando il servizio https://auth.uat.interop.pagopa.it/token.oauth2
Non riusciamo invece a contattare il WS di accertamento esistenza in vita di un soggetto, ma probabilmente stiamo sbagliando qualcosa nell’URL richiamata e/o nel JSON della request (vedi sotto i riferimenti da noi utilizzati).
 
Potete per cortesia dirci dove stiamo sbagliando?
 
POST https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002
 
{
    "idOperazioneClient": "GRMA_20240115153000",
    "criteriRicerca": {
        "codiceFiscale": "STTSGT90A01H501J"
    },
    "datiRichiesta": {
        "dataRiferimentoRichiesta": "2024-01-15",
        "motivoRichiesta": "prova",
        "casoUso": "C001"
    }
}
 
Cordiali saluti

**Comment by FedericaSicchiero** [comment]
Buongiorno, in questo caso vi consiglio di aprire una issue direttamente sulla repository di ANPR (https://github.com/italia/anpr/issues) in modo che possano darvi le indicazioni corrette. Lato PDND quando si riesce a staccare correttamente il voucher vuol dire che funziona tutto. Grazie
