### ISSUE TITLE
Richiesta integrazione risposta api di interoperbilità

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#702]
Buongiorno,  sottoponiamo alla vostra attenzione una richiesta di integrazione della risposta dell’api di interoperabilità la cui interfaccia è riportata in allegato. Se possibile avremmo bisogno delle seguenti informazioni aggiuntive:

-	data della richiesta da parte del fruitore 
-	data di approvazione da parte dell’erogatore (ove prevista). 

In merito a quest’ultima informazione,  consultando uno specifico eservice dal catalogo di PDND  c’è la possibilità di capire se è prevista l’approvazione automatica o manuale?
Grazie

[interface-specification.txt](https://github.com/pagopa/pdnd-interop-frontend/files/14037589/interface-specification.txt)

**Comment by FedericaSicchiero** [comment]
Buongiorno, ne discutiamo internamente e aggiorno il ticket con la risposta.
Nel frattempo posso confermare che lato fruitore non c'è modo di avere conferma che la richiesta di fruizione sia approvata automaticamente o manualmente, è una feature a sola discrezione dell'erogatore.
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, ne abbiamo parlato come team e la modifica non sarà possibile portarla sulla piattaforma nel breve periodo, ma ce la siamo segnata e quando ci sarà una lavorazione massiva alle API inseriremo anche quanto segnalato, grazie.

**Comment by azabatta** [comment]
Grazie
