### ISSUE TITLE
[Invocazione Eservice C019] Errore "The request contains bad syntax or cannot be fulfilled"

### ISSUE THREAD

**Issue by jonnypa** [pagopa/pdnd-interop-frontend#703]
Buonasera,

provando ad invocare l'e-service C019-servizioAccertamentoEsistenzaVita stiamo riscontrando degli errori durante la generazione del voucher. La response ricevuta è la seguente

`{"correlationId":"fb6f5c74-a6c6-46ba-b624-2766b73dd8a6","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}`

**Data e ora del tentativo**
25/01/2024 h. 16:16

**Ambiente**
Collaudo

**client_id**
4fd016fd-7a2d-4e6d-b4dd-47316742e23e

**correlationId**
fb6f5c74-a6c6-46ba-b624-2766b73dd8a6

**purposeId**
5eeea247-4db0-4e2f-8333-a570d06ab20c

Potreste aiutarci a capire in cosa stiamo sbagliando?

Grazie anticipatamente

**Comment by FedericaSicchiero** [comment]
Buongiorno,
avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by jonnypa** [comment]
Buongiorno, abbiamo fatto una verifica anche noi tramite tool di debug di piattaforma e la finalità risultava ancora in attesa di approvazione. Abbiamo provato a generare una nuova richiesta che è stata subito approvata. Alla luce di questo, tramite il tool di debug, abbiamo verifica che adesso viene generato correttamente il token. E' possibile chiudere la issue.
