### ISSUE TITLE
C019 - errore in prod EN122 (stessa chiamata in collaudo funziona)

### ISSUE THREAD

**Issue by gp-elips** [pagopa/pdnd-interop-frontend#705]
Lanciando chiamata in Prod riceviamo questi errori:

GovWay-Transaction-ID: 1fe31267-bc29-11ee-8478-005056ae6555
{"listaErrori":[{"codiceErroreAnomalia":"EN122","testoErroreAnomalia":"La richiesta effettuata non produce alcun risultato","tipoErroreAnomalia":"E"}],"
idOperazioneANPR":"1612483399"}

GovWay-Transaction-ID: 3f7bc0fb-bc29-11ee-9412-005056ae1d2a
{"listaErrori":[{"codiceErroreAnomalia":"EN122","testoErroreAnomalia":"La richiesta effettuata non produce alcun risultato","tipoErroreAnomalia":"E"}],"
idOperazioneANPR":"1612483432"}

Lo stesso body inviato in collaudo funziona.

Id Operazione lanciate in collaudo con esito positivo:
"idOperazioneANPR":"59952566"
"idOperazioneANPR":"59952567"

Grazie in anticipo per il supporto

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad usare il tool di debug del voucher? Se le chiamate vanno in collaudo ma non in produzione potrebbe essersi ripetuto qualche elemento di un ambiente che non funziona nell'altro

**Comment by FedericaSicchiero** [comment]
Buongiorno, confermo che l'errore dipende dal server dell'erogatore. Consiglio quindi di aprire una issue sulla repository di ANPR (mi sembra di capire che sono loro gli erogatori), grazie

**Comment by gp-elips** [comment]
Potete chiudere, errore nostro nell'utilizzo di codici fiscali non validi.
Saluti
