### ISSUE TITLE
Richiesta elenco IP/HOST invocazione servizi PCP [Piattaforma di E-procurement]

### ISSUE THREAD

**Issue by FAlessandroLC** [pagopa/pdnd-interop-frontend#710]
Buongiorno,
premettiamo che ANAC ci ha indicato di scrivere a PAGOPA e il supporto di PAGOPA ci ha indicato di aprire una issue.
In qualità di gestori della piattaforma di E-procurement, con la presente siamo a richiedere il vostro supporto per completare le configurazioni per le chiamate ai Servizi PCP.
Nel dettaglio, per l’invocazione dei servizi della PCP abbiamo abilitato la navigazione ai seguenti host:
https://auth.interop.pagopa.it/
https://apigw.anticorruzione.it/
Da uno dei due veniamo reindirizzati verso una serie di IP ed avendo delle limitazioni sul firewall siamo costretti a richiedere l’abilitazione per ogni singolo IP.
Al momento abbiamo individuato 5 IP diversi.
Volevamo sapere se è disponibile la lista completa dei possibili IP, in alternativa il relativo nome dns.
In attesa di un vostro cortese riscontro, ringraziamo per la preziosa collaborazione.
Un saluto cordiale,

**Ambiente**
Entrambi gli ambienti Produzione e Collaudo

**Comment by FedericaSicchiero** [comment]
Buongiorno, noi come PDND abbiamo IP dinamici ma al momento non abbiamo una lista completa che possiamo condividere. Tuttavia il nostro dns da poter autorizzare è proprio https://auth.interop.pagopa.it/
Se invece è l'altro host che vi reindirizza verso la serie di IP allora vi consiglio di aprire una issue sulla [repository](https://github.com/anticorruzione/npa/issues) ANAC in quanto sono loro a gestirlo. Grazie

**Comment by FAlessandroLC** [comment]
Buon pomeriggio,
in riferimento alla issue precedente poiché non è possibile per la nostra infrastruttura aprire completamente il DNS, la nostra area tecnica chiede se sia possibile avere una subnet o, in alternativa, un range di IP in modo da poter impostare correttamente una regola.
Grazie, un saluto cordiale
