### ISSUE TITLE
URL swagger e-service ANPR

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#72]
Salve,

nella documentazione on line non riusciamo a trovare la URL per i servizi rest degli e-service ANPR da richiamare per le integrazioni via PDND.

**Comment by ruggerocastagnola** [comment]
Buongiorno, grazie mille della segnalazione. Dunque, ho verificato, e all'interno dei file OpenAPI caricati dagli Erogatori e disponibili da scaricare nei vari E-Service mi sembra di vedere la URL dei servizi, come mi aspetterei. Ha un esempio specifico, così verifichiamo?

**Comment by giovannidenicola** [comment]
Buongiorno,

grazie per il feedback.

abbiamo provato a verificare la URL indicata nei dettagli dell'E-service per il quale siamo fruitori ma non risulta essere raggiungibile. Preciso che la richiesta è riferita all'ambiente di test. Grazie

![image](https://user-images.githubusercontent.com/106265229/170947332-a3413f99-6fe5-4dd6-9067-249528f75bff.png)

**Comment by ruggerocastagnola** [comment]
Buongiorno, mi scuso per il ritardo. I colleghi di SOGEI hanno appena aggiornato la documentazione e pubblicato una nuova versione dell'E-Service in cui c'è la documentazione e l'endpoint (screenshot sotto).

Segnalo che, se avete una richiesta di fruizione già attiva, dovrete fare l'upgrade alla nuova versione dell'E-Service prima di poter staccare un token. Per farlo, andare su 
- Fruizione > Le tue richieste
- Selezionare la richiesta di fruizione per l'E-Service C015 e cliccare su Ispeziona
- All'interno della nuova pagina ci sarà un pulsante "Aggiorna". Cliccare

Se avesse difficoltà a seguire la procedura, la prego di segnalarmelo

![uat gateway test pdnd-interop pagopa it_ui_it_fruizione_catalogo-e-service_a07349bd-7e27-42f8-b68e-65c6c89a2cc5_630f0e15-7655-4f58-879d-602833f9f269(Macbook Pro – Screenshot)](https://user-images.githubusercontent.com/6032099/171123449-f5e2b8a8-3735-416d-95aa-8e78b6c5c11b.png)

**Comment by ruggerocastagnola** [comment]
Ho visto l'attività su #74, ringrazio molto per la proattività. Chiudo quest'issue
