### ISSUE TITLE
Eventi per l'ente erogatore

### ISSUE THREAD

**Issue by ggianoglio** [pagopa/pdnd-interop-frontend#720]
Un ente erogatore può definire che le richieste di fruizione siano approvate automaticamente, in questo modo però non si ha alcun riscontro su nuove fruizioni attivate dal portale PDND.
Esiste una piattaforma di eventi all'interno della quale sottoscrivere API che vengano invocate per notificare l'approvazione di nuove fruizioni?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
può trovare maggiori informazioni sull'argomento nella nostra documentazione [qui](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/api-esposte-da-pdnd-interoperabilita#endpoint-di-notifica-eventi).
Dovrebbe rispondere alla sua domanda ma se servissero maggiori informazioni siamo a disposizione.

**Comment by ggianoglio** [comment]
Buongiorno,
ho visto che nella documentazione viene menzionata la piattaforma di API, non ho però i dettagli tecnici (swagger, strutture dati, endpoints...) per poter invocare gli eventi e reperire le informazioni utili.
Dove posso recuperare tutte queste informazioni?
Grazie.

**Comment by FedericaSicchiero** [comment]
Si possono trovare maggiori informazioni sulla sezione della documentazione [Client](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/client-e-materiale-crittografico#creare-un-client-api-interop) e in quelle successive e una volta creato un client all'interno della piattaforma ci sono istruzioni aggiuntive per lo stacco del token verso PDND Interoperabilità.

**Comment by ggianoglio** [comment]
Ho trovato il link di questo swagger: https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml come faccio a sapere quale evento sottoscrivere per essere notificato di una richiesta di fruizione approvata in modo da recuperare client id e purpose id dell'ente che ha creato la fruizione?

**Comment by FedericaSicchiero** [comment]
Buonasera, si al momento i risultati sono un po' scarni e stiamo lavorando per rilasciare una versione aggiornata delle API in modo che siano più esaustive. Sto raccogliendo le informazioni e aggiorno il ticket appena le ho tutte.

**Comment by ggianoglio** [comment]
Buongiorno,
vista la chiusura di questa issue, potete menzionare in questo thread quali sono le evoluzioni in merito alla gestione degli eventi e dove ottenere la documentazione a corredo?
Grazie.
