### ISSUE TITLE
Chiamata servizio C019 in ambiente di produzione

### ISSUE THREAD

**Issue by LucianoCFAss** [pagopa/pdnd-interop-frontend#722]
Salve,
stiamo provando ad invocare il servizio C019 in ambiente di produzione ma riceviamo il seguente errore

{
“detail”: “Received request is not conform to the required interoperability profile”,
“govway_id”: “85f7654c-c4e2-11ee-b28b-005056ae091b”,
“status”: 400,
“title”: “InteroperabilityInvalidRequest”,
“type”: [Documentazione](https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html)
}

Il test sulla creazione del voucher all’interno della piattaforma funziona correttamente.

Potreste aiutarci ? Grazie

Luciano

**Comment by FedericaSicchiero** [comment]
Buongiorno,
in questo caso vuol dire che qualcosa non torna al server dell'erogatore. Vi consiglio di aprire una issue direttamente sulla repository di [ANPR](https://github.com/italia/anpr/issues). Grazie
