### ISSUE TITLE
C019-servizioAccertamentoEsistenzaVita - errore InteroperabilityInvalidRequest - Received request is not conform to the required interoperability profile

### ISSUE THREAD

**Issue by paolochinellato** [pagopa/pdnd-interop-frontend#723]
Verificata con successo la assertion sul portale PDND per lo stacco del voucher, l'invocazione del servizio C019-servizioAccertamentoEsistenzaVita in base ai patterns AUDIT_REST_02 e INTEGRITY_REST_02 indicati nelle "Linee Guida sull’interoperabilità tecnica delle Pubbliche Amministrazioni – Pattern di sicurezza"  

riceve la risposta

{
   "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
   "title": "InteroperabilityInvalidRequest",
   "status": 400,
   "detail": "Received request is not conform to the required interoperability profile",
   "govway_id": "bfa1acd6-c66e-11ee-83c1-005056ae5232"
}

con la seguente invocazione rest:

POST https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR-PDND/C019-servizioAccertamentoEsistenzaVita/v1/anpr-service-e002 HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjMyZDhhMzIxLTE1NjgtNDRmNS05NTU4LWE5MDcyZjUxOWQyZCJ9.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAxOS1zZXJ2aXppb0FjY2VydGFtZW50b0VzaXN0ZW56YVZpdGEvdjEiLCJzdWIiOiIwMmU5Y2VkZi0wYzA5LTQ1NTMtYTNlMC1mYjA2ODMyZGNlZjEiLCJuYmYiOjE3MDczOTA4ODUsImRpZ2VzdCI6eyJhbGciOiJTSEEyNTYiLCJ2YWx1ZSI6IjhhMzg1NWZiNGUzMTQxZmFkODI2ZDU1NzQ3MWFhMTE5MGI1NTk0OTM0NGNjYjViODE0OWU3NTEzZDZmNzBmN2MifSwicHVycG9zZUlkIjoiODkwYjI2NDgtMzYzNC00MmE0LWJlN2EtN2NlM2FlNzFkNjQ5IiwiaXNzIjoidWF0LmludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzA3MzkxNDg1LCJpYXQiOjE3MDczOTA4ODUsImNsaWVudF9pZCI6IjAyZTljZWRmLTBjMDktNDU1My1hM2UwLWZiMDY4MzJkY2VmMSIsImp0aSI6ImFiYWNhMWRjLWQwMWYtNDY1ZS04OGM2LTBlODg4MDZmODBhZiJ9.FyHMIM1Xovb-7ICkbE6BYAEK9K5j4GcFFypZ0FDUIPgg78CtYXQzIHgDXAnNM45Px3tSmJpUY60qqJGPeTTJzTfrL7X_t0mCfXJdfFSTb9wOagvwRHMATo9K0FCWwVYLoY9iCv6nSxHRpj_F4S6HRCnGXLuzFn0mQoHOCcjIzPAsDvDeYFbdk6weYha2nYEGQWowBLG4iki8arp2mx3UDQWxvrghQgfwTZFduWgZjHaPk2hDDLdt4v7fCCqrbsPQ7o_y_TXq4hGPq5_W92OoKyj3LYkj9LN6noKlM1lRcvUgoGRcKE1nAXHOTpD3Ea6UAvHywyekh3wq9VLst8WwnQ
Digest: SHA-256=YxzFLyZ5UQ0B2KZMkv9wRNw6sHML2P0jYlTPk8ADBM4=
Agid-JWT-Signature: eyJ0eXAiOiJKV1QiLCJraWQiOiJFbGlWd1JFQzRhdmh0YVRwaWxSNXJZTllnU0JVX2JPUklDRmgzMkJJcEg4IiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAxOS1zZXJ2aXppb0FjY2VydGFtZW50b0VzaXN0ZW56YVZpdGEvdjEiLCJzdWIiOiIwMmU5Y2VkZi0wYzA5LTQ1NTMtYTNlMC1mYjA2ODMyZGNlZjEiLCJuYmYiOjE3MDczOTA4ODUsImlzcyI6IjAyZTljZWRmLTBjMDktNDU1My1hM2UwLWZiMDY4MzJkY2VmMSIsInNpZ25lZF9oZWFkZXJzIjpbeyJkaWdlc3QiOiJTSEEtMjU2PVl4ekZMeVo1VVEwQjJLWk1rdjl3Uk53NnNITUwyUDBqWWxUUGs4QURCTTQ9In0seyJjb250ZW50LXR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn1dLCJleHAiOjE3MDc5OTA4ODUsImlhdCI6MTcwNzM5MDg4NSwianRpIjoiYjAzMmFkZmQtZGFkMi00NzE0LWFjNGUtNTcwYjQxYjBhMjYxIn0.x0qd4d-h6NEzPGL-t6VbBe8UI_FpFEzbBJFRPtWke9jUh6lMPy2FU-KUpvyNaeQcQ9GxkfjwRBdGWg1iOHhmCSXkkHsDA0T9fdQfXm_zh7hj-9WFmN8Xl4HZKOzGjK3s5yAld4Tj6aCbOq-mYwT3eFRvZSBV0JRHgQ1DORgT7pIp4UwkFQyOcPA6ORmq14zLkSGBWEBnf5OHfyGFZaGQ5RlEDI6O4yTer3m5IDqhoKLTCeCcBti88aYXRJjxN2Zur26EFaWEZGAwh4N026zLNaBBY0exFRw-lJywf5xkENbj1d0UWgq11j7gEGZ0T7sR31NdSh3Hnica7sFaPdjkfQ
Agid-JWT-TrackingEvidence: eyJ0eXAiOiJKV1QiLCJraWQiOiJFbGlWd1JFQzRhdmh0YVRwaWxSNXJZTllnU0JVX2JPUklDRmgzMkJJcEg4IiwiYWxnIjoiUlMyNTYifQ.eyJhdWQiOiJodHRwczovL21vZGlwYS12YWwuYW5wci5pbnRlcm5vLml0L2dvdndheS9yZXN0L2luL01pbkludGVybm9Qb3J0YUFOUFIvQzAxOS1zZXJ2aXppb0FjY2VydGFtZW50b0VzaXN0ZW56YVZpdGEvdjEiLCJzdWIiOiIwMmU5Y2VkZi0wYzA5LTQ1NTMtYTNlMC1mYjA2ODMyZGNlZjEiLCJuYmYiOjE3MDczOTA4ODQsInB1cnBvc2VJZCI6Ijg5MGIyNjQ4LTM2MzQtNDJhNC1iZTdhLTdjZTNhZTcxZDY0OSIsImlzcyI6IjAyZTljZWRmLTBjMDktNDU1My1hM2UwLWZiMDY4MzJkY2VmMSIsInVzZXJMb2NhdGlvbiI6IjI2LjIuMTIuMjMiLCJleHAiOjE3MDc5OTA4ODQsImRub25jZSI6IjEyMzQ1Njc4OTAxMjMiLCJ1c2VySUQiOiJVc2VyMTIzIiwiaWF0IjoxNzA3MzkwODg0LCJqdGkiOiJlMjcxNzgwZS00NDVjLTQ3NWYtOGNiMy1lY2VkM2IxMjc3YzQiLCJMb0EiOiJMT0EzIn0.Imqllbg5R2Y-TEtUCnix5yvuwW0G_t3_znqS644Mxpn6WjqH53jR1NGIasmT3iimnfR05ebvfDQVY_qldWYFynHqE6fjTmKkOieD09EeDUH_REGxBsGAhOwCCUZkd8hZJR8Z1DhwUPbzmWT91HqML4J_ppOQSVmrrjhIw80nNjNc48KPXV2kV3k73oNBR1jSfufinb0P_8DC-6dGofrEE57-m_Lnl1LrmyGLyeki-6qzVHiLrXLYWbwKNAzN2zR0fr-__m6wYG2qeeHHSDKPO_9LECIxHdZIBa_z-CHw1yMZF0EnvWl-BA0PBFx2KvP89diY9cbMFNWqaP03qLJZlw
Content-Length: 241
Host: modipa-val.anpr.interno.it
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.5 (Java/12.0.1)

 {
   "idOperazioneClient": "1", 
    "criteriRicerca": {
      "codiceFiscale": "DPLPRM90R10H501I"
    },
    "datiRichiesta": {
     "dataRiferimentoRichiesta": "2024-02-04",
      "motivoRichiesta": "1",
      "casoUso": "C019"
    }
  }

Fruitore: Assicurazioni Generali
Piattaforma: PDND
Ambiente: Collaudo
Data del test: 2024/02/08
Orario: intorno alle 12:18

**Comment by FedericaSicchiero** [comment]
Buongiorno,
in questo caso vuol dire che qualcosa non torna al server dell'erogatore. Vi consiglio di aprire una issue direttamente sulla repository di [ANPR](https://github.com/italia/anpr/issues). Grazie
