### ISSUE TITLE
Errore recupero voucher

### ISSUE THREAD

**Issue by sommafa** [pagopa/pdnd-interop-frontend#729]
Buongiorno,
cercando di recuperare il token ottengo errore per il servizio C019.
Di seguito i dettagli:

Ambiente di collaudo
clientId: c38bab8a-cef1-47b0-8031-aa4a22913fb0
purposeId: f6abadff-775a-4414-8cc0-9d1cd8796143
correlationId: 905e9eb5-b8d9-4b92-aee4-627b3c388c4f

tentativo eseguito oggi alle 17:19

grazie

**Comment by sommafa** [comment]
purtroppo non ho ora accesso al tool di debug

**Comment by sommafa** [comment]
buongiorno @FedericaSicchiero 

purtroppo non ho accesso diretto al tool di debug, quindi sono ancora in attesa.

Ho bisogno però di supporto per capire se la chiamata per il token sia corretta a partire dalla client assertion.

Questi sono i valori che sto inserendo per creare la client assertion:

```
Headers:
"kid" _settings.KeyId
"alg" RS256
"typ" JWT

Payload:
"iss", _settings.Issuer
"sub", _settings.Subject
"aud", _settings.Audience
"purposeId" _settings.PurposeId
"jti" jti (calcolato al momento)
"iat" issued (calcolato al momento)
"exp" expire_in (calcolato al momento)
```

al payload, aggiungo inoltre il valore `digest` così composto

```
"alg" "SHA256"
"value" digest (dell'agid tracking signature)
```

come audience, sto usando auth.uat.interop.pagopa.it/client-assertion

Tutto viene poi firmato con la chiave privata e inviato all'endpoint del token aggiungendo

```
clientId
client_assertion
client_type urn:ietf:params:oauth:client-assertion-type:jwt-bearer
grant_type client_credentials
```

Il token ottenuto, lo voglio usare per interrogare il servizio C019 di esistenza in vita.

Riesci per favore ad aiutarmi a capire se almeno questo passaggio è corretto? ho provato anche a chiedere più volte assistenza ad ANPR ma non risponde nessuno da giorni e noi siamo bloccati.

Grazie
Fabio

**Comment by FedericaSicchiero** [comment]
Buongiorno @sommafa,
mi puoi dire per quale ente e con quale utenza (amministratore /operatore) stai facendo le prove?

**Comment by sommafa** [comment]
> Buongiorno @sommafa, mi puoi dire per quale ente e con quale utenza (amministratore /operatore) stai facendo le prove?

Ciao, sto facendo le prove per conto di AXA

**Comment by FedericaSicchiero** [comment]
@sommafa quale axa? avrei bisogno del nome completo per fare delle verifiche, perchè hanno fatto l'onboarding anche AXA Life, AXA France etc

**Comment by sommafa** [comment]
Sto cercando di reperire l'informazione, nel frattempo dandoti il clientId non ti aiuto in qualche modo?

**Comment by FedericaSicchiero** [comment]
Al momento non molto solo perchè il team è in trasferta in questi giorni e non riusciamo a fare le verifiche necessarie. In ogni caso ho visto che su AXA Assicurazioni c'è un client che fa riferimento ad ANPR ma non ha una chiave, quindi l'errore potrebbe essere dato da quello

**Comment by sommafa** [comment]
In trasferta il team ANPR intendi?

Parliamo cmq di assicurazione, questo senza ulteriori specifiche te lo posso garantire.
Il client che vedi senza chiave, è questo? c38bab8a-cef1-47b0-8031-aa4a22913fb0

**Comment by FedericaSicchiero** [comment]
A noi risulta che l'audience chiamata sia questa `https://modipa-val.anpr.interno.it/govway/rest/in/MinInternoPortaANPR/C019-servizioAccertamentoEsistenzaVita/v1` e non quella indicata sopra, per quello c'è errore

**Comment by sommafa** [comment]
grazie federica, rifatto ora la chiamata e ottengo il token (spero sia giusto)

ottengo però un errore nella chiamata al servizio, con il govway c38bab8a-cef1-47b0-8031-aa4a22913fb0 mi sai gentilmente dare delle indicazioni?

**Comment by FedericaSicchiero** [comment]
Figurati! 
In questo caso l'errore che ricevi dipende dal server ANPR e noi come team PDND non abbiamo visibilità e ti devo rimandare alla loro repository

**Comment by sommafa** [comment]
peccato, loro purtroppo a differenza tua non rispondono da giorni.

cmq sia, davvero grazie per il tuo aiuto

**Comment by FedericaSicchiero** [comment]
A disposizione. Chiudo la issue ma se serve si può riaprire.
