### ISSUE TITLE
Servizio per la restituzione dell'indirizzo di residenza 

### ISSUE THREAD

**Issue by marcobelf** [pagopa/pdnd-interop-frontend#731]
Buongiorno,
tra i vari servizi esposti su PDND non riesco a trovarne uno che mi restituisca, oltre ai dati anagrafici, anche informazioni sull'indirizzo di residenza. C'è un servizio tra quelli presenti che restituisce questa informazione?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
da catalogo pubblico vedo che è presente [questo](https://www.interop.pagopa.it/catalogo/8fe27f7f-b559-4c51-90b6-a4d6eae4ae01/) e-service di ANPR che potrebbe essere utile, ma noi come piattaforma non abbiamo visibilità su cosa espongono i singoli erogatori. 
Se non dovesse dare i dati che cercate vi consiglio di chiedere direttamente ad [ANPR](https://github.com/italia/anpr/issues).

**Comment by marcobelf** [comment]
Grazie mille, verificherò il servizio che mi ha segnalato e in caso di problemi contatterò ANPR.
Buona Giornata.
