### ISSUE TITLE
Link Json well-known per e-service

### ISSUE THREAD

**Issue by lazzf** [pagopa/pdnd-interop-frontend#733]
Abbiamo pubblicato un eservice per il Comune di Brusaporto sulla piattaforma PDND: abbiamo bisogno del link al json che contiene i dati necessari per la verifica delle richieste al nostro servizio e quindi per l'autenticazione dei fruitori (parametri `kid` e `n`). Il problema è che l'unico link disponibile è quello di esempio presente anche nella documentazione [link](https://interop.pagopa.it/.well-known/jwks.json).
Abbiamo provato a fare anche richiesta di fruizione per il nostro stesso eservice (sempre come Comune di Brusaporto) ma il link rimane sempre allo stesso json.

Step per riprodurre il bug:
1. Accedere a PDND come Comune di Brusaporto
2. Clicca su Erogazione > I Tuoi eservice
3. 'Aree verdi'
4. Nei dettagli dell'eservice c'è il link di esempio

Comportamento atteso:
Nel dettaglio dell'eservice dovrebbe esserci il link al json con i dati dei fruitori

Codice IPA ente: c_b223

Ambiente: Produzione

Permessi utenza:
Abbiamo provato ad accedere sia come Amministratore che come Operatore di sicurezza.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
per avere un elenco dei fruitori ai vostri servizi trovate il link per scaricare un csv all'interno dell'e-service come si vede in screen 
![Screenshot 2024-02-16 alle 11 10 02](https://github.com/pagopa/pdnd-interop-frontend/assets/116075083/63710df9-06d2-4787-97f1-ac8b5be4aed4)


altrimenti dovete creare un client sotto la voce "I tuoi client dati Interop" sotto la sezione "Fruizione" e interrogare le API di piattaforma in modo da ottenere uno stream di eventi (maggiori info in documentazione [qui](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/api-esposte-da-pdnd-interoperabilita#endpoint-di-notifica-eventi)).
Al momento i risultati sono un po' scarni e stiamo lavorando per rilasciare una versione aggiornata delle API in modo che siano più esaustive.
