### ISSUE TITLE
Richiesta informazioni su E-Service ANPR - modalità di contatto

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#74]
Buon pomeriggio, ho provato a contattare il canale di assistenza ANPR ([Assistenza.anpr@pec.sogei.it](mailto:Assistenza.anpr@pec.sogei.it)), per provare a chiedere loro alcune informazioni (riporto la mail in calce); mi è venuto però il dubbio che essendo l'indirizzo una PEC, non riceva le mie mail; qualcuno può indicarmi se c'è un modo alternativo per contattare l'assistenza ANPR o se c'è modo di far loro leggere questo issue?
Grazie e cordiali saluti,

> _Buongiorno,
> 
> sono Corrado Tamietti del CSI Piemonte; per conto della Città di Torino (che legge in CC) vi contatto in merito alla sperimantazione in corso sulla piattaforma di Interoperabilità PDND proposta da AGID e PagoPA (nel caso vi servissero dettagli sulla sperimentazione, credo che psssiate contattare questi ultimi due enti).
> 
> Stiamo facendo un primo test utilizzando l'E-service "C009 - SERVIZIO DI VERIFICA DICHIARAZIONE STATO DI FAMIGLIA" presente sul catalogo dell'istanza di test della PDND.
> 
> Nella documentazione del servizio viene indicato che:
> 
> "è necessario implementare i seguenti profili di sicurezza ModI dettagliati nelle linee guida sull' interoperabilità della pubblica amministrazione:
> - Profilo di sicurezza Modl ID_AUTH_CHANNEL_02
> - Profilo di sicurezza Modl INTEGRITY_REST_01
> Per tale scopo il fruitore dovrà generare una coppia chiave pubblica/privata per il canale di comunicazione (ID_AUTH_CHANNEL_02) e un’altra per la firma del payload della request (INTEGRITY_REST_01)."
> 
> Vorrei chiedere se possiamo procedere alla generazione delle due coppie di chiavi in autonomia, cioè creando un certificato digitale autogenerato oppure se richidetete che, già in ambiente di test il materiale crittografico, debba rispettare vincoli specifici, ad esempio essere legati ad una CA 'ufficale' o requisiti di altro genere.
> 
> In caso non richiediate per l'ambiente di test vincoli specifici, procederemmo alla generazione del materiale crittografico e a spedirvi le chiavi pubbliche. Attendiamo vostro feedback.
> 
> Grazie per il supporto e cordiali saluti,
> Corrado Tamietti_

**Comment by amollicone1982** [comment]
Assistenza.anpr@pec.sogei.it
in questa prima fase mettete in copia me (amollicone@sogei.it)

**Comment by giovannidenicola** [comment]
Salve @amollicone1982 , avremmo la medesima esigenza di @ctamietti, possiamo procedere in analogia?
Grazie
