### ISSUE TITLE
Attivazione degli e-service su PDND da parte del Soggetto Attuatore

### ISSUE THREAD

**Issue by AlessandraB19** [pagopa/pdnd-interop-frontend#742]
Come soggetto attuatore, sono stati attivati due nuovi servizi ed è stata creata una nuova versione di uno già esistente. Quanto tempo è necessario affinchè queste operazioni siano effettive? I servizi sono presenti nel catalogo degli e-service, ma non risultano ancora disponibili sulla piattaforma PA digitale 2026, pur essendo passato un giorno, come indicato nel documento Allegato 5 - Completamento delle attività e verifiche tecniche Avvisi 1.3.1.

**Comment by FedericaSicchiero** [comment]
Buongiorno, sono passate 24 ore effettive da quando sono stati creati?
E altra domanda: quando gli e-service sono stati creati sono stati usati dati simili o addirittura identici ad altri servizi già presenti a catalogo? Perchè in quel caso PA Digitale vede le API come una sola e non conta i servizi come due differenti

**Comment by AlessandraB19** [comment]
Buongiorno,
sono passate più di 24 ore dall'ultimo creato ex novo, con dati differenti
da quelli creati precedentemente, e dalla creazione di una nuova versione
per due servizi che contenevano lo stesso file OpenApi, ma su PA Digitale
vediamo ancora solo il primo servizio creato.

Attendo vostre.
Cordiali saluti,
Alessandra Belviso

Il giorno ven 23 feb 2024 alle ore 17:01 Federica Sicchiero <
***@***.***> ha scritto:

**Comment by FedericaSicchiero** [comment]
Se due servizi contenevano la stessa OpenAPI anche se la versione è cambiata il sistema di PA Digitale continua a contare sempre un e-service invece di due. Il secondo sarebbe da creare da zero con OpenAPI differenti

**Comment by AlessandraB19** [comment]
Ma queste modifiche, per essere effettive, quanto tempo richiedono?

**Comment by FedericaSicchiero** [comment]
Io posso rispondere solo lato PDND e come avete visto una volta pubblicati gli e-service sono già fruibili, lato PA Digitale non so rispondere perchè non è una nostra piattaforma ma di base il sistema gira ogni 24 ore per aggiornarsi
