### ISSUE TITLE
Controllo voucher per dati pubblici

### ISSUE THREAD

**Issue by marcobelf** [pagopa/pdnd-interop-frontend#743]
Buongiorno,
vorrei sapere se erogando un servizio che fornisce dati pubblici sia comunque obbligatorio effettuare il controllo del voucher da parte dell'erogatore.

**Comment by FedericaSicchiero** [comment]
Buongiorno, è fortemente consigliato ma non ci sono dei blocchi nel caso in cui si decida di non farlo.

**Comment by marcobelf** [comment]
Va bene, grazie mille.
