### ISSUE TITLE
Informazione collaudo e produzione erogazione api interoperabilità

### ISSUE THREAD

**Issue by gefilsrl** [pagopa/pdnd-interop-frontend#744]
Buongiorno,

Abbiamo completato lo sviluppo per l'interoperabilità, e attivato un e-service di testing.
Siamo ora pronti per procedere con il collaudo e la messa in produzione delle API.

potreste fornirci indicazioni di dettaglio  per procedere al collaudo delle API e andare in produzione.

Resto in attesa di vostri indicazioni.

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno,
per poter provare le API in ambiente di Collaudo potete iscrivervi al vostro e-service e arrivare allo stacco del token seguendo la [documentazione](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/e-service) indicata qui e le pagine a seguire. Se tutto funziona potete poi creare un e-service anche in ambiente di Produzione seguendo sempre gli stessi passi e ricevere le richieste di fruizione degli enti che si iscrivono.
