### ISSUE TITLE
Finalità con e-service associato errato in fase di fruizione

### ISSUE THREAD

**Issue by lucamontano98** [pagopa/pdnd-interop-frontend#746]
Buongiorno, ho provato ad inserire una nuova finalità specificando l'e-service da associare alla medesima, però nel riepilogo finale ho notato che la finalità è stata associata ad un'altro e-service.

Step per riprodurre il bug

    Vai su "Le tue finalità" e crea una nuova finalità;
    Associa l'e-service alla finalità
    Procedi con gli step mancanti.

Comportamento atteso
associato e-service = x, alla fine del processo e-service = x

Il codice IPA del tuo ente
r_friuve -> Regione Autonoma Friuli-Venezia Giulia

Data e ora in cui si è riscontrato il problema
28/02/2024 17:20

Ambiente
Collaudo

Quali permessi ha la tua utenza?
Amministratore

Screenshot
![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/144030486/841d3666-565e-4994-ba4e-f1a67b77c89d)
![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/144030486/d2030596-ecbd-4518-8673-b97a173c9506)

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione ci stiamo lavorando e aggiorno il ticket appena ci sono aggiornamenti.

**Comment by lucamontano98** [comment]
Buongiorno,
perfetto. Avete per caso aggiornamenti a riguardo? Dobbiamo pubblicare le API in produzione e prima di proseguire vorremmo testare le fruizioni in ambiente di collaudo di Interoperabilità. Grazie mille.

Distinti saluti.

Luca Montano

**Comment by lucamontano98** [comment]
Buongiorno,
avete qualche novità? Grazie mille.

Distinti saluti.

Luca Montano

**Comment by FedericaSicchiero** [comment]
Buongiorno,
abbiamo rilasciato poco fa il fix al bug. Ora l'e-service da associare dovrebbe essere quello corretto, grazie
