### ISSUE TITLE
e-service C019-servizioAccertamentoEsistenzaVitaapprovazione_ automati

### ISSUE THREAD

**Issue by FranzMotta** [pagopa/pdnd-interop-frontend#747]
Buongiorno, una domanda. Dovendo usufruire del e-service C-019, è possibile caricare un file massivo di Codici Fiscali per la verifica esistenza in vita? 

Grazie

**Comment by FedericaSicchiero** [comment]
Buonasera, in questo caso vi consiglio di chiedere direttamente ad ANPR aprendo una issue sulla loro [board](https://github.com/italia/anpr/issues) perchè noi non abbiamo la visibilità necessaria per rispondere alla domanda. Grazie
