### ISSUE TITLE
PDND, Ambiente di Collaudo, C019

### ISSUE THREAD

**Issue by cla13** [pagopa/pdnd-interop-frontend#748]
Stiamo effettuando delle prove di comunicazione con l'e-service C019 nell'ambiente di collaudo, ma abbiamo bisogno di avere delle informazioni aggiuntive sulla tipologia di errore prodotto.
L'errore ottenuto con l'ultimo test è il seguente:
{
    "type": "https://govway.org/handling-errors/400/InteroperabilityInvalidRequest.html",
    "title": "InteroperabilityInvalidRequest",
    "status": 400,
    "detail": "Received request is not conform to the required interoperability profile",
    "govway_id": "cb44e0c4-d7c2-11ee-8b15-005056ae1884"
}

**Data e ora del tentativo** : 01/03/2024 h. 13.51
**Ambiente**:                        Collaudo
**client_id**                           1df3069a-84b8-4e2c-b241-8d840d248826
**purposeId **                       446014fb-1c85-4be7-8c10-2a74f5e7587f

**Comment by FedericaSicchiero** [comment]
Buon pomeriggio,
avete già provato ad usare il tool di debug del voucher presente in piattaforma?
Comunque a vedere dall'errore indicato è qualcosa a cui solo ANPR direttamente può rispondere perchè non dipende dalla piattaforma. Hanno questa [repository](https://github.com/italia/anpr/issues) github dove si possono aprire delle issue.

**Comment by cla13** [comment]
Ciao, si con il tool il voucher è valido.
Scriverò nella repository indicata.
Grazie mille.
