### ISSUE TITLE
Impossibile creare una nuova bozza dell'e-service

### ISSUE THREAD

**Issue by lucamontano98** [pagopa/pdnd-interop-frontend#756]
Si vorrebbe creare una nuova versione dell'e-service, però si riceve l'errore riportato in fondo.

**Step per riprodurre il bug**
1. Vai su un e-service pubblicato dal tuo ente
2. Clicca su 'Crea nuova bozza"
3. Vedi l'errore

**Comportamento atteso**
Possibilità di impostare i dati relativi alla nuova versione dell'e-service

**Il codice IPA del tuo ente**
c_f832 | Comune di Muzzana del Turgnano (UD)

**Data e ora in cui si è riscontrato il problema**
08/03/2024 13:21

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore

**Screenshot**
![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/144030486/cfc0c34e-8ffa-4945-8cde-2aaa95f03eb7)

**Comment by FedericaSicchiero** [comment]
Buongiorno,
stiamo lavorando al fix per questo problema e aggiorno la issue appena è stato rilasciato, grazie

**Comment by FedericaSicchiero** [comment]
Buonasera, abbiamo rilasciato il fix per questo bug, chiudo la issue
