### ISSUE TITLE
crea bozza va in errore

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#757]
In ambiente di collaudo,
quando tentiamo di creare una bozza di un e-service prendiamo errore

![immagine](https://github.com/pagopa/pdnd-interop-frontend/assets/29304687/57016787-19f7-4dda-9fd2-4eea9a139ff6)

**Comment by FedericaSicchiero** [comment]
Buongiorno, si stiamo lavorando al fix proprio su questo bug. Appena lo rilasciamo aggiorno la issue.

**Comment by FedericaSicchiero** [comment]
Buonasera, abbiamo rilasciato il fix per questo bug, chiudo la issue
