### ISSUE TITLE
Chiarimento creazione finalitá in fase di creazione di e-service

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#758]
Buonasera,
vorremmo un chiarimento riguardo al processo di creazione di un e-service che riceve dati.

Innanzitutto vorrei chiedervi se la discriminante tra servizio che eroga dati e riceve è sempre stata presente o è stata introdotta successivamente.

Al netto di questo, nel processo di creazione, selezionando al primo step "Riceve",
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/9409505/17951165-950a-40c3-8cca-8e2869af7f2c)
appare tra gli step la necessitá di creare una finalitá per i dati ricevuti.

Scorrendo però tra le varie domande, questa ci sembra ambigua in questo contesto in quando stiamo creando un servizio da erogare ma nel contempo siamo fruitori del dato.
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/9409505/4a19ccae-c1b3-43e1-a8ee-a033096138ac)

In questo caso quale delle parti assume il soggetto erogatore del servizio?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
Ciao Marco,
questa distinzione è stata introdotta un po' di mesi fa a seguito dell'apertura di PDND ad ANAC e alle piattaforme di e-procurement.

In questo caso è l'erogatore a creare la finalità che poi il fruitore si andrà a trovare già compilata in quanto è l'erogatore che va ad indicare il caso d'uso per cui intende raccogliere i dati.

**Comment by mrubiero** [comment]
Ciao Federica, ma in questo caso per staccare un voucher per un servizio che riceve dati un fruitore deve comunque inserire l'id della finalitá nella client assertion? Se sì come può recuperarlo dato che la crea l'erogatore? 

Nel caso di un erogatore pubblichi un servizio che riceve dati e volesse staccare un voucher per testare che funzioni correttamente, in questo caso come può farlo? 

Grazie,
Marco
