### ISSUE TITLE
Problema generazione token PDND

### ISSUE THREAD

**Issue by ruggerocastagnola** [pagopa/pdnd-interop-frontend#76]
@diegopedone scrive

**Descrivi il bug**
Stiamo provando a generare un token per i servizi di ANPR, ritorna il seguente errore:
```
{
  "errors": [
    {
      "code": "015-0008",
      "detail": "Unable to generate a token for the given request"
    }
  ],
  "status": 400, 
  "title": "The request contains bad syntax or cannot be fulfilled.",
  "type": "about:blank"
}
```

**Comportamento atteso**
Di poter generare il token

**Note**
Inoltro via mail i parametri che inserisco in chiamata, compresa l'assertion

**Comment by ruggerocastagnola** [comment]
Verifico

**Comment by diegopedone** [comment]
@ruggerocastagnola ho sbagliato a inviarti l'assertion, nel copia e incolla ho commesso un errore. Ho inviato tramite mail una nuova assertion.

**Comment by ruggerocastagnola** [comment]
Grazie, quest'asserzione sembra corretta. Stiamo verificando internamente

**Comment by ruggerocastagnola** [comment]
@diegopedone, abbiamo fatto un check e ci risulta che la chiave privata con cui è stata firmata l'asserzione non corrisponde alla pubblica che avete caricato su Interoperabilità. È possibile?

**Comment by diegopedone** [comment]
Effettivamente era stata caricata una chiave pubblica errata.

**Comment by ruggerocastagnola** [comment]
Perfetto, almeno l'abbiamo trovato. Mi ha segnalato @beetlecrunch che non è necessario inserire l'header `x5c`
