### ISSUE TITLE
Il server ha smesso di andare

### ISSUE THREAD

**Issue by euberdeveloper** [pagopa/pdnd-interop-frontend#769]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Inizialmente il servizio funzionava correttamente. Usavamo il servizio sia per test che per prod. Ottenevamo il voucher e lo usavamo tranquillamente per il servizio C019 anagrafe. 

Un giorno test ha smesso di funzionare ed il giorno successivo lo stesso errore ha iniziato a verificarsi su prod. Il codice e le credenziali sono rimaste invariate.

**Step per riprodurre il bug**
Non applicabile

**Comportamento atteso**
il voucher dovrebbe arrivare come aveva sempre fatto

**Il codice IPA del tuo ente**
_Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente_

**Data e ora in cui si è riscontrato il problema**
Su test, la prima volta il 15/03/2024 verso circa le 11 di mattina. Poi ha proseguito ed è ancora malfunzionante

**Ambiente**
sia produzione che collaudo

**Quali permessi ha la tua utenza?**

**Screenshot**

**Note**
La risposta ottenuta:
```json
{"correlationId":"db4c2610-9882-48e0-87e4-44e5228d97dc","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}
```

**Comment by FedericaSicchiero** [comment]
Avete provato ad usare il tool di debug del voucher presente in piattaforma?
Perchè se lì ricevete tutte le spunte verdi vuol dire che l'errore dipende dall'erogatore e in questo caso vi consiglio di aprire una issue direttamente ad [ANPR](https://github.com/italia/anpr/issues)

**Comment by euberdeveloper** [comment]
L'erogazione del voucher non dovrebbe dipendere solo da pdnd?

**Comment by FedericaSicchiero** [comment]
No perchè PDND mette in contatto i server di fruitore ed erogatore fornendo il perimetro di sicurezza per lo scambio dei dati. Lato nostro possiamo garantire che il token sia completo delle varie componenti necessarie, ma se poi il token incontra un blocco dal lato dell'erogatore perchè ad esempio il loro server è in down noi non possiamo farci niente

**Comment by gcaferra** [comment]
Confermo che il voucher viene fornito correttamente, sembra ci sia un problema "dopo" lato ANPR

**Comment by FedericaSicchiero** [comment]
Allora l'unica è aprire una issue alla repository linkata sopra che è proprio di ANPR. 
Chiudo la issue ma restiamo di supporto per il futuro

**Comment by euberdeveloper** [comment]
> No perchè PDND mette in contatto i server di fruitore ed erogatore fornendo il perimetro di sicurezza per lo scambio dei dati. Lato nostro possiamo garantire che il token sia completo delle varie componenti necessarie, ma se poi il token incontra un blocco dal lato dell'erogatore perchè ad esempio il loro server è in down noi non possiamo farci niente

Quindi anche durante la prima richiesta che facciamo a voi per ottenere il voucher, prima di generare ed inviate la risposta con il voucher entrate in contatto con il server dell'e-service?

Ok se è così apro un issue and ANPR

**Comment by amollicone1982** [comment]
Scusami Federica, ma l'errore
{"correlationId":"db4c2610-9882-48e0-87e4-44e5228d97dc","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

è dato in riposta alla chiamata dell'endpoint per lo stacco del voucher pdnd.
Non potete continuare a dire che è un problema di ANPR.
