### ISSUE TITLE
Problema durante la generazione del token sul client ANPR

### ISSUE THREAD

**Issue by EmaPace** [pagopa/pdnd-interop-frontend#77]
Buonasera,

abbiamo un client associato al Ministero della Infrastrutture e della Mobilità Sostenibili verso gli eService di ANPR e riceviamo un errore durante la generazione del token.

abbiamo verificato che le chiavi pubblica e privata corrispondo e non riusciamo a capire da cosa possa dipendere.

endpoint: https://uat.gateway.test.pdnd-interop.pagopa.it/authorization-server/token.oauth2

di seguito la richiesta inviata:
client_id: 350e7ccf-34f5-4c64-a7d7-b527f2152371
client_assertion: eyJraWQiOiJGVTV1UU9wM3d5Mk9SRU0xTGhpcUxDSEI0N01EbnlSMF92YllCUDFjZGRZIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIzNTBlN2NjZi0zNGY1LTRjNjQtYTdkNy1iNTI3ZjIxNTIzNzEiLCJzdWIiOiIzNTBlN2NjZi0zNGY1LTRjNjQtYTdkNy1iNTI3ZjIxNTIzNzEiLCJhdWQiOiJ0ZXN0LmludGVyb3AucGFnb3BhLml0L2NsaWVudC1hc3NlcnRpb24iLCJqdGkiOiIzZWMwNzcyOS0zMjYyLTQxZGEtYjY3Mi1hZWU5N2I5NGIzNTUiLCJpYXQiOjE2NTQ3MDA3OTQsImV4cCI6MTY1NDcwNzk5NH0.dX4gFEjqpZ5WbhrxrFvYxfOyCI5hGDnjQ1Q5SLGteABdTUQ6IeY7jSg8MHueuKiq6V4Lb_oqcmEO9DQ-8KsTiihF8E68y6oiekHOAQmh4-krhIEXea7TN7xi_cGVY6ImDnK1pd4R9oRTmJrzTs1uXEd3rzw5LELR_uPSWatWydk2p49An1zsbZJT2abKj95BB6hxUBO-hfv9FoUrAW-o78tosT-bPTt1GH6PFG1vsdL0_P27KssCHD0ulJpOlKRnDJIZBC_R8suwr7g_e38Vr1en3tYUsOXB9CgymE5Hh7Jbc-Ir5hOQYPIraL02tONtMKozAjUAFIYvL38_Ieu70g
client_assertion_type: urn:ietf:params:oauth:client-assertion-type:jwt-bearer
grant_type: client_credentials

questa è la response che riceviamo:
{
    "errors": [
        {
            "code": "015-0008",
            "detail": "Unable to generate a token for the given request"
        }
    ],
    "status": 400,
    "title": "The request contains bad syntax or cannot be fulfilled.",
    "type": "about:blank"
}

Grazie
Emanuele

**Comment by EmaPace** [comment]
Buongiorno,

abbiamo trovato il problema.
nel payload non era presente il purposeId relativo al client.
usavamo la stessa composizione di assertion per il client m2m.

Grazie ancora
Emanuele

**Comment by ruggerocastagnola** [comment]
Grazie, perfetto!
