### ISSUE TITLE
Recupero informazioni fruitore da voucher

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#777]
Salve,
per implementare delle logiche applicative su dei servizi dovremmo ricavare dal voucher l'informazione relativa a quale è il fruitore che contiene il client da cui è stato staccato. 
Leggendo la documentazione delle API di interop siamo arrivati ad ottenerlo tramite la chiamata API
https://**API_URL_INTEROP**/1.0/clients/**ID_CLIENT** per ottenere il consumerId e quindi chiamando l'API https://**API_URL_INTEROP**/1.0/organizations/**CONSUMER_ID_OTTENUTO** per ottenere le informazioni parlanti del consumer, è corretto come flusso?

A seguire abbiamo bisogno della lista dei consumatori per tutti i nostri servizi attivi, quindi pensavamo di utilizzare l'API
https://**API_URL_INTEROP**/1.0/agreements?producerId=**ID_ORG_NOSTRO**&states=ACTIVE
chiamandola ad intervalli regolari per aggiornarci sui nuovi fruitori, anche in questo caso vi torna?

Grazie,
Marco

**Comment by FedericaSicchiero** [comment]
ciao Marco, scusa per il ritardo nella risposta.
Si confermiamo che entrambi i flussi sono corretti come li hai scritti.
