### ISSUE TITLE
API chiavi pubbliche

### ISSUE THREAD

**Issue by costantinog** [pagopa/pdnd-interop-frontend#778]
Buongiorno, è disponibile un'API di interoperabilità in grado di automatizzare l'acquisizione della lista di chiavi pubbliche dall'URL messo a disposizione dopo la creazione di un e-service lato erogatore?

**Comment by FedericaSicchiero** [comment]
Buongiorno, potete trovare tutte le informazioni a proposito [qui](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#indicazioni-architetturali). Facciamo presente che tra qualche mese l'API getaway verrà risistemato e quindi bisognerà ripetere il processo.

**Comment by costantinog** [comment]
Perfetto. Un'ultima cosa, l'URL messo a disposizione nella sezione "_vedi i dettagli tecnici dell'e-service_", cambia per ogni singolo e-service o è unico per tutti gli e-service dell'erogatore?
