### ISSUE TITLE
Forbidden in ambiente di collaudo

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#781]
Da stamattina prendo message:forbidden nel tentativo di entrare nell'ambiente di collaudo.
In produzione entro tranquillamente
![Cattura](https://github.com/pagopa/pdnd-interop-frontend/assets/29304687/cd10783d-e2c6-41fb-a27e-92c5d69b1f16)

**Comment by FedericaSicchiero** [comment]
Si stiamo rilasciando degli aggiornamenti in ambiente di collaudo, abbiamo aperto questa [issue](https://github.com/pagopa/pdnd-interop-frontend/issues/779) l'altro giorno per avvisare. Entro stasera torna tutto funzionante.
