### ISSUE TITLE
Errore in sottoscrizione servizio

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#782]
Stiamo cercando di sottoscrivere un nostro servizio "Anpr-Elaborazioni-Massive-dev" in qualità di Ministero dell'interno ma prendiamo un errore che ci chiede di riprovare.

Potete controllare?

**Comment by FedericaSicchiero** [comment]
Buongiorno, in quale ambiente state facendo le prove? L'errore lo ricevete quando provate a cliccare sul bottone di iscrizone all'e-service o in altri momenti?

**Comment by amollicone1982** [comment]
in collaudo quando si clicca su richiedi fruizione

**Comment by FedericaSicchiero** [comment]
C'è un bug che stiamo risolvendo, nel frattempo vi chiedo di provare ad inserire una mail di contatto nella sezione Il mio ente e vedere se così funziona. Nel frattempo appena il fix per questo bug viene risolto aggiorno la issue

**Comment by amollicone1982** [comment]
Cia Federica,
La mail di contatto è presente
