### ISSUE TITLE
Informazioni su manutenzione programmata  PDND del 27 aprile p.v. 

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#786]
Buonasera, 
la manutenzione programmata prevista per il 27 aprile p.v.  in ambiente di esercizio  riguarderà solo il sito PDND oppure avrà un impatto anche sull'operatività dei servizi?
Grazie

**Comment by FedericaSicchiero** [comment]
Buonasera, la manutenzione riguarda solo la piattaforma PDND e non andrà ad impattare lo stacco dei token, tranne qualche possibile interruzione non a lungo termine

**Comment by azabatta** [comment]
grazie
