### ISSUE TITLE
Esistenza Vita [C019] "correlationId":"37f45c6f-c1d1-4f48-8cd9-b76ca681c48f"

### ISSUE THREAD

**Issue by JeyjooMilano** [pagopa/pdnd-interop-frontend#791]
Buongiorno,

Devo implementare il web service Esistenza Vita.

Siamo riusciti a generare il voucher, ma su Github è stato richiesto di aggiungere il "digest" al client assertion. Fatto questo riceviamo un nuovo errore. Ecco l'issue - https://github.com/italia/anpr/issues/4496

Qui sotto c'è una copia dell'errore che riceviamo:

`{"correlationId":"37f45c6f-c1d1-4f48-8cd9-b76ca681c48f","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}`

Aveta idea del problema? Tranne il digest abbiamo usato una copia / incolla dalla piattaforma selfcare.uat.interop.pagopa.it.

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno,
avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
l'errore probabilmente è dato dal fatto che il campo value lì indicato non sia della lunghezza corretta. Se codificato con sha256 la lunghezza è standard e quindi dovrebbe andare.

Il fatto che col tool di debug tutte le spunte siano verdi vuol dire che c'è il via libera allo stacco del token, ma non che l'erogatore fornisce i dati di sicuro .

**Comment by FedericaSicchiero** [comment]
È da inserire se l'erogatore lo chiede esplicitamente, dopo averlo codificata usando sha256 (campo value) e mettendo nel campo alg sha256.

**Comment by FedericaSicchiero** [comment]
Salve, dai nostri controlli risulta corretto il payload 1 ma se avete aggiunto la codifica base64 non serve metterla, basta solo sha256 e non dovrebbe dare errori
