### ISSUE TITLE
Manutenzione programmata della piattaforma 

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#793]
Buongiorno,
accedendo alla piattaforma non viene più proposto il messaggio informativo sul fermo per manutenzione del 27  aprile p.v.
E' stato rinviato?
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno,
la manutenzione è ancora programmata per il 27. Consigliamo sempre di dare un'occhiata anche alle issue github perchè le varie manutenzioni le segnaliamo anche qui, grazie
