### ISSUE TITLE
Richiesta attributi certificati per e-service ANAC

### ISSUE THREAD

**Issue by matteorovigatti** [pagopa/pdnd-interop-frontend#795]
Descrivi il bug
Abbiamo la necessità di avere gli attributi in ambiente di COLLAUDO per i seguenti e-service:
• PCP - Comunica appalto
• PCP - Comunica post pubblicazione
• PCP - Gestione utenti
• PCP - Servizi comuni
• PCP - Pubblica avviso

Step per riprodurre il bug

vai su anagrafica ente (888 Software Products)
non compare almeno uno dei seguenti attributi richiesti da anac in pdnd di collaudo ovvero:
Gestore che ha in carico una o più componenti non certificate con accesso all'ambiente di qualificazione
Gestore che ha sottomesso una richiesta di certificazione per una o più componenti con accesso all'ambiente di qualificazione
Gestore che ha in carico una o più componenti certificate con accesso all'ambiente di esercizio

Comportamento atteso
Poter inoltrare richiesta di fruizione in pdnd di collaudo per i suddetti e-service

Data e ora in cui si è riscontrato il problema
OGGI

Ambiente
Collaudo

Quali permessi ha la tua utenza?
Amministratore,

Screenshot
In allegato alcuni screenshot

Note
Dopo aver rifatto la domanda di certificazione componente ed accettata in data 24/04/2024 ci sono stati tolti gli attributi per richiedere la fruizione degli eservice con la dicitura "Attributo revocato dal certificatore".
Abbiamo scritto all'assistenza dal portale ma ci hanno detto di aprire una issue su github

<img width="1521" alt="ScreenAttributiCertificati" src="https://github.com/pagopa/pdnd-interop-frontend/assets/103248673/75c8f4dc-2861-4623-8ff1-72edce21d97f">

**Comment by FedericaSicchiero** [comment]
Buongiorno,
mi scuso per il ritardo nella risposta. Stiamo verificando come mai l'attributo è stato revocato, appena abbiamo aggiornamenti vi faccio sapere

**Comment by FedericaSicchiero** [comment]
Buonasera, abbiamo rilasciato in collaudo il fix che vi ha ridato gli attributi, chiudo la issue

**Comment by matteorovigatti** [comment]
grazie
