### ISSUE TITLE
Errore 403 nella chiamata a servizi M2M in esercizio

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#799]
Prendiamo un errore 403 nella seguente chiamata a servizi M2M in esercizio:

'https://api.interop.pagopa.it/1.0/purposes?consumerId=6c07e769-b418-4210-bc0f-7d56470a06e9&eserviceId=919f4373-396c-4eac-9585-0211e7652c1a'

In collaudo va a buon fine.

Potreste aiutarci?

**Comment by amollicone1982** [comment]
chiamo i vostri servizi M2M e in particolare
'https://api.interop.pagopa.it/1.0/purposes?consumerId=6c07e769-b418-4210-bc0f-7d56470a06e9&eserviceId=919f4373-396c-4eac-9585-0211e7652c1a'

**Comment by FedericaSicchiero** [comment]
Avremmo bisogno del correlationID per procedere più velocemente con i controlli

**Comment by amollicone1982** [comment]
Il 403 non resituisce il correlationid come fa il 400

**Comment by FedericaSicchiero** [comment]
Okay stiamo aggiornando una cosa che dovrebbe sistemare tutto e aggiorno la issue appena è fatto

**Comment by amollicone1982** [comment]
Grazie e buona giornata

**Comment by FedericaSicchiero** [comment]
Potete riprovare? Dovrebbe essere tutto corretto ora

**Comment by amollicone1982** [comment]
Adesso funziona, grazie mille
