### ISSUE TITLE
Chiarimento su attributi schema TipoGeneralità di ANPR

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#80]
Salve,

stiamo implementando l'integrazione con ANPR via PDND ed avremmo alcuni dubbi su degli attributi delle Generalità (C020) e della Residenza (C015), presenti negli schema previsti dal servizio REST. 

Nel caso delle Generalità lo schema TipoGeneralità prevede i seguenti attributi:
- senzaCognome
- senzaNome
- senzaGiorno
- senzaMese
- soggettoAIRE

cosa rappresentano? Quali informazioni dovremmo attenderci per tali attributi?
I dubbi che abbiamo sono i seguenti:
- ci possono essere casi di anagrafiche per le quali non siano presenti il Nome, il Cognome 
- ci possono essere casi per cui una data di nascita che non includa anche il giorno ed il mese.
- quale valore è previsto per l'attributo soggettoAIRE? La presenza di un valore indica che il soggetto è residente all'estero?

Nel caso della Residenza lo schema TipoIndirizzo prevede i seguenti attributi:
- siglaProvinciaIstat: contiene la sigla a due lettere oppure il codice Istat del comune della provincia?
- non riusciamo a capire quale sia l'attributo che indica il nome della Via, Piazza, ecc...

Restiamo in attesa di un cortese feedback.
Grazie della collaborazione.

**Comment by amollicone1982** [comment]
ci possono essere casi di anagrafiche per le quali non siano presenti il Nome, il Cognome **_SI_**
    ci possono essere casi per cui una data di nascita che non includa anche il giorno ed il mese. **_SI_**
    quale valore è previsto per l'attributo soggettoAIRE? La presenza di un valore indica che il soggetto è residente  all'estero? **_SI_**



    siglaProvinciaIstat: contiene la sigla a due lettere
    non riusciamo a capire quale sia l'attributo che indica il nome della Via, Piazza, ecc... (è la specie)

**Comment by giovannidenicola** [comment]
Grazie per le risposte precedenti, avremmo purtroppo qualche altra domanda:

- Nel caso in cui un soggetto sia senza nome, quindi con l'attributo Nome non valorizzato quale sarebbe il valore restituito per 
l'attributo SenzaNome?

- Nel caso in cui un soggetto sia senza cognome, quindi con l'attributo Cognome non valorizzato quale sarebbe il valore restituito per l'attributo SenzaCognome?

- Nel caso in cui un soggetto sia con data di nascita incompleta, quali sarebbero i valori restituito per gli attributi SenzaGiorno e SenzaMese?

- In archivio ANPR sono presenti anche le anagrafiche delle imprese individuali? Ovvero imprese individuali che non hanno partita IVA ma codice fiscale?

- Come sono gestiti i nomi ed i cognomi con caratteri diacritici? Ad esempio per il caso di un residente a Bolzano con cognome Müller il servizio restituisce il valore Müller oppure Muller nell'attributo Cognome?

- Avendo delle limitazioni di natura funzionale per le emissioni dei documenti come la Patente avremmo necessità di avere delle statistiche sulle lunghezze dei nomi e dei cognomi ad oggi presenti su ANPR. 
Ci sono casi ed eventualmente quanti in termini percentuale di persone che hanno il cognome che supera 35 caratteri? (ovviamente facciamo riferimento a casi di persone con più di un cognome ad es. CARBONERIS MORETTINI PARACUCCHI)
Ci sono casi ed eventualmente quanti in termini percentuale di persone che hanno il nome che supera 35 caratteri? 

- Dal documento pdf scaricabile dal portale dell'interoperabilità PDND risulta che per gli E-Service C015 e C020 i parametri di input per eseguire la richiesta non includono l'identificativo ANPR del soggetto, è una informazione corretta oppure c'è una omissione nel documento?

Restiamo in attesa di un cortese feedback.
Grazie della collaborazione.

**Comment by amollicone1982** [comment]
Nel caso in cui un soggetto sia senza nome, quindi con l'attributo Nome non valorizzato quale sarebbe il valore restituito per
    l'attributo SenzaNome? **sarebbe restituito 1**

    Nel caso in cui un soggetto sia senza cognome, quindi con l'attributo Cognome non valorizzato quale sarebbe il valore restituito per l'attributo SenzaCognome? **sarebbe restituito 1**

    Nel caso in cui un soggetto sia con data di nascita incompleta, quali sarebbero i valori restituito per gli attributi SenzaGiorno e SenzaMese?**senzagiorno e senzamese, se presenti, hanno come valore 1**

    In archivio ANPR sono presenti anche le anagrafiche delle imprese individuali? Ovvero imprese individuali che sono intestate ad una persona fisica e che quindi non hanno partita IVA ma codice fiscale? **NO**

    Come sono gestiti i nomi ed i cognomi con caratteri diacritici? Ad esempio per il caso di un residente a Bolzano con cognome Müller il servizio restituisce il valore Müller oppure Muller nell'attributo Cognome? **restituisce il cognome con diacritico**

    Avendo delle limitazioni di natura funzionale per le emissioni dei documenti come la Patente avremmo necessità di avere delle statistiche sulle lunghezze dei nomi e dei cognomi ad oggi presenti su ANPR.
    Ci sono casi ed eventualmente quanti in termini percentuale di persone che hanno il cognome che supera 35 caratteri? (ovviamente facciamo riferimento a casi di persone con più di un cognome ad es. CARBONERIS MORETTINI PARACUCCHI) **sono 8883**
    Ci sono casi ed eventualmente quanti in termini percentuale di persone che hanno il nome che supera 35 caratteri? **sono 21981**

    Dal documento pdf scaricabile dal portale dell'interoperabilità PDND risulta che per gli E-Service C015 e C020 i parametri di input per eseguire la richiesta non includono l'identificativo ANPR del soggetto, è una informazione corretta oppure c'è una omissione nel documento? **corretta**

    Nel caso di chiamata al servizio con dati anagrafici incompleti ad es. nome mancate il criterio di estrazione come si comporta?
        restituisce se presente un'anagrafica prima di nome
        restituisce tutte le anagrafiche per le quali corrispondono solo i valori presenti per i parametri in input **esatto**

**Comment by ruggerocastagnola** [comment]
Chiudo questa issue per inattività, sembra risolta. Se avete necessità, per cortesia riapritela
