### ISSUE TITLE
Bug servizi M2M

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#800]
Mi potete dire perchè queste due chiamate prendono 500?

https://govway-anpr-prod.sogei.it:8446/govway/rest/out/MinInternoPortaANPR/PDND/APIPDND/v1/purposes?eserviceId=fd741918-cac1-4d5f-9437-15b520b4cce3&consumerId=a72b541b-95ed-4b4b-a7f4-33ded1e3edc0
https://govway-anpr-prod.sogei.it:8446/govway/rest/out/MinInternoPortaANPR/PDND/APIPDND/v1/purposes?eserviceId=fd741918-cac1-4d5f-9437-15b520b4cce3&consumerId=30ca831d-0f76-4caf-8112-268cd3461417

**Comment by FedericaSicchiero** [comment]
In questo caso avete il correlationID?

**Comment by amollicone1982** [comment]
500 non ritorna una correlationid. cmq dovreste vedere vari errori 500 anche stamattina

**Comment by FedericaSicchiero** [comment]
Stiamo verificando, aggiorno la issue appena abbiamo aggiornamenti

**Comment by FedericaSicchiero** [comment]
Abbiamo rilasciato il fix, ora chiamando l’api GET -> /purposes non si ottiene più 500

**Comment by amollicone1982** [comment]
confermo la risoluzione
grazie
