### ISSUE TITLE
Errore Inaspettato

### ISSUE THREAD

**Issue by andreatantillo** [pagopa/pdnd-interop-frontend#802]
**Descrivi il bug**
Selezionando per alcuni comuni, per cui sono operatore API, il prodotto interoperabilità (in produzione), compare l'errore _"Errore inaspettato. Si è verificato un errore inaspettato. Per favore, ricarica la pagina. Ricarica."_

**Step per riprodurre il bug**
1. Effettuo l'accesso con SPID
2. Seleziono il comune di interesse e clicco su accedi
3. Clicco sulla freccina in corrispondenza del prodotto Interoperabilità
4. Appare l'errore

**Comportamento atteso**
Entrare nella schermata operativa del prodotto interoperabilità

**Il codice IPA del tuo ente**
Sono operatore API di innumerevoli enti. a mero titolo esemplificativo, ma non esaustivo, l'errore si presenta all'ente con il seguente codice IPA c_l419

**Data e ora in cui si è riscontrato il problema**
riscontro il problema già da ieri e lo ritrovo anche in questo esatto momento

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Operatore API

**Screenshot**
![chrome_2nFU48Sy11](https://github.com/pagopa/pdnd-interop-frontend/assets/136598770/f5fedf1f-dfec-43a6-a86c-a0c7fdba654e)

**Comment by FedericaSicchiero** [comment]
Buonasera, ogni tanto si disallineano i permessi tra Area Riservata e la piattaforma PDND. Chiedo cortesemente di cliccare su Esci in alto a destra per tutte le pagine che si aprono e solo dopo provare a rientrare. 
Noi nel frattempo facciamo altri controlli lato nostro per verificare che non ci siano altri blocchi.

**Comment by andreatantillo** [comment]
Ho provato come indicato ma viene restituito lo stesso errore. Succede cosa identica ad un'altra collega con medesima abilitazione di Operatore API.

**Comment by FedericaSicchiero** [comment]
Ci potete dare tutti i codici fiscali delle utenze che ricevono errore?

**Comment by andreatantillo** [comment]
Certo, eviterei di pubblicarli qui però: potrei avere una mail o altro canale dove comunicarli?

**Comment by andreatantillo** [comment]
Fatto, grazie
