### ISSUE TITLE
Errore nella generazione del voucher - EService C019

### ISSUE THREAD

**Issue by euberdeveloper** [pagopa/pdnd-interop-frontend#803]
**ho l'errore con i seguenti dettagli quando cerco di ottenere un voucher per il servizio C019:**
```json
{"correlationId":"8a58afb1-cb46-4aab-875a-c2206f438119","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}
```

Per favore, compila quello che puoi dei campi seguenti. Ci aiuti ad assisterti più rapidamente.
NB: la tua client assertion è un'informazione sensibile: non inserirla all'interno di questa issue. Ogni richiesta contenente informazioni riservate o sensibili sarà rimossa senza preavviso dagli amministratori.

**Step di auto-debug**
Prima di aprire un issue, puoi effettuare le seguenti verifiche per escludere un errore di configurazione:
1. Se stai richiedendo un voucher per un e-service, il `purposeId` inserito è quello corretto? 
**sì**
3. il `client_id` inserito nella richiesta al server autorizzativo corrisponde al valore inserito come subject (campo `SUB`) nella client assertion? 
**sì**
5. la chiave privata con la quale è stata firmata la client assertion corrisponde alla pubblica (campo `KID`) depositata su PDND Interoperabilità?
**sì**
7. la chiave con la quale firmi l'asserzione (campo `KID`) è inserita all'interno del client che hai indicato (campo `SUB`)?
**sì**

**Il codice IPA del tuo ente**
Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente

**Data e ora del tentativo**
es. 24/11/2021 h. 10:20

**DATA: 10 maggio 2024, verso le 15**

**Ambiente**
Produzione o Collaudo

**PROD**

**client_id**
Es. `3b0d583b-7d4c-4bcf-a27c-1d82e81fa321`

**CLIENT ID: 0d24c063-dce0-416a-b913-639591e6f689**

**correlationId**
Il campo che identifica la richiesta, viene restituito dal backend all'interno della risposta assieme all'errore. Es. `47508f4c-bc49-4d34-8adb-a85f734b45b9`

**il correlation id è: 8a58afb1-cb46-4aab-875a-c2206f438119**
```
{"correlationId":"8a58afb1-cb46-4aab-875a-c2206f438119","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}
```

**purposeId (solo per i client e-service)**
È uno dei campi che hai inserito all'interno della client assertion. Es. `69fb9f60-bd47-4b4d-9652-9747f7953234`

**PURP ID: 73b3dc19-886d-46db-a9d0-7b3e1c3410d2**

**Comment by FedericaSicchiero** [comment]
Avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by FedericaSicchiero** [comment]
Chiudo per mancata risposta
