### ISSUE TITLE
Verifica approvazioni richieste di fruizione: messaggio di errore 

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#806]
Buonasera, effettuo la seguente segnalazione per conto del Ministero dell’Interno con riferimento all’ambiente di esercizio di PDND. 

Da qualche settimana in fase di approvazione della richiesta di fruizione di un eservice il sistema invia un messaggio di  errore” Non è stato possibile attivare la richiesta. Accertarsi che tutti gli attributi siano stati verificati e riprovare”.  Facendo un refresh della pagina l’eservice risulta attivo. In un solo caso non è stato possibile attivare una richiesta di fruizione: terza richiesta da approvare in cascata per lo stesso fruitore. L’operazione è stata ritentata più volte.

E’ possibile effettuare una verifica?
Grazie

**Comment by FedericaSicchiero** [comment]
È possibile avere il nome dell'e-service e dell'ente per cui il sistema si blocca? grazie

**Comment by azabatta** [comment]
L'eservice è C029-servizioAccertamentoDatiAnagrafici

**Comment by FedericaSicchiero** [comment]
E il nome dell'ente fruitore per cui non si attiva?

**Comment by azabatta** [comment]
Buongiorno, è il MEF

**Comment by FedericaSicchiero** [comment]
Grazie, mentre per quali enti poi refreshando la pagina la richiesta si è attivata?

**Comment by azabatta** [comment]
Su tutte le richieste approvate nelle ultime due settimane, riguardavano diversi eservice ed enti differenti.

**Comment by FedericaSicchiero** [comment]
Ci potete dare qualche esempio così facciamo un controllo?

**Comment by FedericaSicchiero** [comment]
Buongiorno, mi scuso per il ritardo nella risposta. L'errore ricevuto è perchè la richiesta di fruizione è stata fatta verso la versione 3 dell'e-service, che è stata archiviata una volta che è stata pubblicata la versione 4 dello stesso.
È necessario ripetere la richiesta da zero verso la versione corretta del servizio.

**Comment by azabatta** [comment]
E' possibile inserire un messaggio di errore esplicativo per queste casistiche? 
Grazie

**Comment by FedericaSicchiero** [comment]
Di base questo succede quando si lascia la richiesta in bozza per troppo tempo, ma prendiamo nota della segnalazione. Grazie
