### ISSUE TITLE
Verifica  su richiesta di approvazione finalità 

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#807]
Buonasera, effettuo la seguente segnalazione per conto del Ministero dell’Interno con riferimento all’ambiente di esercizio di PDND. 

Alcuni fruitori sollecitano l’approvazione delle finalità associate ad un eservice. Il numero delle richieste inserite non supera il limite massimo stabilito da ANPR come soglia giornaliera. I fruitori non hanno effettuato un cambio piano. 
A parte il superamento del limite giornaliero ed il cambio piano ci sono altre condizioni che rendono impossibile l’approvazione automatica? 
E'possibile effettuare una verifica?
Grazie

**Comment by FedericaSicchiero** [comment]
Buonasera, ci potete dare un esempio di un ente fruitore la cui finalità non è stata approvata in automatico?
In tutto questo confermate che la somma totale di tutte le richieste di tutti i fruitori non supera la soglia giornaliera stabilita da ANPR? 
Chiedo conferma perchè anche noi abbiamo ricevuto altre segnalazioni di enti per cui le finalità non venivano approvate automaticamente da ANPR / Ministero dell'Interno e l'unico blocco resta quello del possibile superamento delle soglie

**Comment by azabatta** [comment]
Verifichiamo che non sia stata superata la soglia giornaliera per tutti i fruitori.
Ci confermate che il conteggio ai fini del blocco viene effettuato solo per le finalità attive? 
Grazie

**Comment by FedericaSicchiero** [comment]
Confermiamo, ma faccio presente che se rimangono 10.000 API disponibili e il fruitore ne richiede 15.000 è per quello che si bloccano le richieste. Quindi anche se la soglia non viene superata bisogna controllare anche questa parte.

**Comment by azabatta** [comment]
Alla luce di quest'ultimo meccanismo è inutile fare ulteriori controlli. Il blocco è stato causato dalla richiesta di un fruitore che ha inserito una soglia di milioni di chiamate giornaliere.
Una richiesta scorretta innesca ulteriori step di lavorazione che vanno a discapito di altri fruitori e dell'erogatore.
Non sarebbe più corretto bloccare un'approvazione che comporta lo sforamento del totale complessivo previsto per tutti i fruitori?

**Comment by FedericaSicchiero** [comment]
Non possiamo bloccare a prescindere richieste del genere perchè è possibile che poi l'erogatore sia in grado di scalare e approvare richieste che presentano tali numeri. L'erogatore però può rifiutare una richiesta tale e sbloccare l'accesso agli altri che rispettano la soglia massima.

**Comment by azabatta** [comment]
Grazie
