### ISSUE TITLE
C019 esistenza in vita, errore richiesta voucher

### ISSUE THREAD

**Issue by saldeangelis** [pagopa/pdnd-interop-frontend#810]
Buongiorno,

ho effettuato la chiamata per ricevere il voucher ma ho ricevuto questo errore:
{"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank","errors":[{"code":"015-9000","detail":"Invalid parameter found - Object instance has properties which are not allowed by the schema: [\"{ \\n\\\"client_id\\\":\\\"0fd28-cd36-42bb-8b91-1c6df7156795\\\", \\n\\\"client_assertion\\\":\\\"eyJraWOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiMDVhYzZiYzktOWU5Yy00NWY3LWExM2YtZDM0YzNmYjQ3Nzg5IiwiaWF0IjoxNzE1OTU1NzYyLCJleHAiOjE3MTU5NTYwNjIsInB1cnBvc2VJZCI6ImVmMGM1MDQwLTRhZGMtNDI1Ni04ZWRlLTRlZTE5OGNiYjk3ZSJ9.hNijN5eeI9PMGuLEoqLW-M2aO1fLhgDJgLQV59pZDWxGNloXwYzlhd7t5KSsv7jqR6oenfJgnoJujnFsyS61i9TeQPVLIMRP4sYMHEi0pzPCM5WKw_7tIi0xxneVK_CEJdr0BpMd54goMDxJklKDvVkBBiNJZBcSltfKa4LorF6cjtziY__QCmABokfLPShstgjl4J3NFKpAkNqldkxgfL9m7eeqnFHrK4geIn6mR3PY_WR3oKdj4Drc_YIRWd9p3G5C7AyHN195tt3zrhhk1coOj9padofaJ9Y_zWSY4yfSkdnfZNskzaaJwhJOtbbgxY_aIxWDxD98ip17iOqCzQ\\\", \\n\\\"client_assertion_type\\\":\\\"urn:ietf:params:oauth:client-assertion-type:jwt-bearer\\\", \\n\\\"grant_type\\\":\\\"client_credentials\\\" \\n}\"]"},{"code":"015-9000","detail":"Invalid parameter found - Object has missing required properties ([\"client_assertion\",\"client_assertion_type\",\"grant_type\"])"}],"status":400}

Questo è il body:

{ "client_id":"0b74fd28-cd36-42bb-8b91-1c6df7156795", "client_assertion":"eyJraWQiOiI1MnlOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiMDVhYzZiYzktOWU5Yy00NWY3LWExM2YtZDM0YzNmYjQ3Nzg5IiwiaWF0IjoxNzE1OTU1NzYyLCJleHAiOjE3MTU5NTYwNjIsInB1cnBvc2VJZCI6ImVmMGM1MDQwLTRhZGMtNDI1Ni04ZWRlLTRlZTE5OGNiYjk3ZSJ9.hNijN5eeI9PMGuLEoqLW-M2aO1fLhgDJgLQV59pZDWxGNloXwYzlhd7t5KSsv7jqR6oenfJgnoJujnFsyS61i9TeQPVLIMRP4sYMHEi0pzPCM5WKw_7tIi0xxneVK_CEJdr0BpMd54goMDxJklKDvVkBBiNJZBcSltfKa4LorF6cjtziY__QCmABokfLPShstgjl4J3NFKpAkNqldkxgfL9m7eeqnFHrK4geIn6mR3PY_WR3oKdj4Drc_YIRWd9p3G5C7AyHN195tt3zrhhk1coOj9padofaJ9Y_zWSY4yfSkdnfZNskzaaJwhJOtbbgxY_aIxWDxD98ip17iOqCzQ", "client_assertion_type":"urn:ietf:params:oauth:client-assertion-type:jwt-bearer", "grant_type":"client_credentials" }

di seguito la codifica del jwt

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/28670106/05d472c9-1edd-4427-acd0-1321dacbfa9f)

Manca qualcosa?

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by saldeangelis** [comment]
Buongiorno,
la client assertion è valida come indicato dal debugger online, ma poi quando uso lo script per la CURL ci va in errore:

curl --location --request POST https://auth.uat.interop.pagopa.it/token.oauth2 \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'client_id=0b74fd28-cd36-42bb-8b91-1c6df7156795' \
  --data-urlencode 'client_assertion=eyJraWQiOiI1MnlOdVpsYWFDT1BMWE5mMEo5UThFT3Y0ZWM5N1ByUFRUbzB6d3lFSTBvIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJzdWIiOiIwYjc0ZmQyOC1jZDM2LTQyYmItOGI5MS0xYzZkZjcxNTY3OTUiLCJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwianRpIjoiMDVhYzZiYzktOWU5Yy00NWY3LWExM2YtZDM0YzNmYjQ3Nzg5IiwiaWF0IjoxNzE1OTU1NzYyLCJleHAiOjE3MTU5NTYwNjIsInB1cnBvc2VJZCI6ImVmMGM1MDQwLTRhZGMtNDI1Ni04ZWRlLTRlZTE5OGNiYjk3ZSJ9.hNijN5eeI9PMGuLEoqLW-M2aO1fLhgDJgLQV59pZDWxGNloXwYzlhd7t5KSsv7jqR6oenfJgnoJujnFsyS61i9TeQPVLIMRP4sYMHEi0pzPCM5WKw_7tIi0xxneVK_CEJdr0BpMd54goMDxJklKDvVkBBiNJZBcSltfKa4LorF6cjtziY__QCmABokfLPShstgjl4J3NFKpAkNqldkxgfL9m7eeqnFHrK4geIn6mR3PY_WR3oKdj4Drc_YIRWd9p3G5C7AyHN195tt3zrhhk1coOj9padofaJ9Y_zWSY4yfSkdnfZNskzaaJwhJOtbbgxY_aIxWDxD98ip17iOqCzQ' \
  --data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
  --data-urlencode 'grant_type=client_credentials'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1242  100   247  100   995   1452   5849 --:--:-- --:--:-- --:--:--  7392{"correlationId":"839f4896-edc2-479b-95af-efd80c41da73","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}


Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, a noi risulta che l'unica prova per staccare il token sia stata fatta ieri e a quel punto il token è scaduto. Vi chiedo di riprovare oggi e nel caso di errori riportarli. 
Come indicato in documentazione e quando si apre la issue non incollate la client assertion perchè rientra nei dati sensibili e la repository è aperta a tutti, grazie

**Comment by saldeangelis** [comment]
Buongiorno,
ho ripetuto ora il token scade tra un paio di ore

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/28670106/2c04786d-035c-4cfb-9932-d63b3904ded3)

Risposta:

{"errors":[{"code":"015-9000","detail":"Invalid parameter found - Request Content-Type header '[none/none, none/none]' does not match any allowed types. Must be one of: [application/x-www-form-urlencoded]."},{"code":"015-9000","detail":"Invalid parameter found - A request body is required but none found."}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"}

**Comment by FedericaSicchiero** [comment]
Anche in questo caso, prima di provare a staccare il token, il tool di debug dava sempre spunte verdi?

**Comment by saldeangelis** [comment]
Ciao,
di seguito la verifica del jwt
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/28670106/d2cf87ac-f35f-4112-9cd3-cce0a79e4679)


![image](https://github.com/pagopa/pdnd-interop-frontend/assets/28670106/15730904-e631-42e1-aa71-9b0a41758731)

**Comment by saldeangelis** [comment]
Buongiorno,
Avete un log più approfondito dal quale posso capire meglio cosa sto sbagliando?
Grazie

**Comment by FedericaSicchiero** [comment]
L'unica parte che da delle istruzioni è la documentazione: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher, noi comunque stiamo facendo vari controlli per capire cosa non va

**Comment by saldeangelis** [comment]
Buongiorno Federica,
abbiamo sviluppato seguendo appunto la documentazione indicata, il debug della piattaforma ci da tutte le spunte verdi,
omettiamo qualcosa che sfugge al controllo del debugger?

Grazie

**Comment by beetlecrunch** [comment]
Buongiorno l'errore riportato indica che alcuni parametri della richiesta non sono passati.
Dallo screenshot riportante la curl sembra mancare il carattere di concatenazione di fine linea `\`, per cui il comando eseguito per come é scritta la curl si limita alla sola prima linea.

Puó provare semplicemente a modificare la curl come segue?
```
curl --location --request POST 'https://auth.uat.interop.pagopa.it/token.oauth2' 
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_assertion=<CLIENT_ASSERTION>' \
--data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
--data-urlencode 'grant_type=client_credentials'
```

**Comment by beetlecrunch** [comment]
Buongiorno @saldeangelis ha avuto modo provare?
Grazie

**Comment by FedericaSicchiero** [comment]
Chiudo la issue per non risposta, si riapre se necessario.
