### ISSUE TITLE
https://www.interop.pagopa.it/catalogo - Selezione tra "utili a pac" e "utili a pal"

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/pdnd-interop-frontend#814]
ci sarebbe un modo di selezionare anche quelli tra pac e quelli utili per le pal? es. collegamento inad-anpr non è per le pal, mentre isee inps si

**Comment by FedericaSicchiero** [comment]
Chiudo perchè segnalata e gestita nella #812
