### ISSUE TITLE
https://www.interop.pagopa.it/catalogo - Contatori

### ISSUE THREAD

**Issue by AndreaTironi1** [pagopa/pdnd-interop-frontend#815]
sarebbe possibile mettere due numeri che dicono nel quadratino quanti (enti) hanno chiesto l'accesso al servizio e quante chiamate ha avuto reali?

![image](https://github.com/pagopa/pdnd-interop-frontend/assets/29781117/b444b242-d7b3-455e-98d8-af5d2a5fc5b6)

**Comment by FedericaSicchiero** [comment]
Chiudo perchè segnalata e gestita nella #812 ma in ogni caso specifico che lo screen si riferisce al catalogo pubblico, dove non vengono condivise le stesse informazioni dell'effettivo catalogo presente in piattaforma
