### ISSUE TITLE
Impossibile pubblicare un servizio che riceve dati su ambiente di produzione

### ISSUE THREAD

**Issue by mrubiero** [pagopa/pdnd-interop-frontend#816]
**Descrivi il bug**
Non è possibile pubblicare un servizio che riceve dati su ambiente di produzione.

**Step per riprodurre il bug**
1. Loggarsi come Operatore API su produzione
2. Creare un nuovo servizio come erogatore impostando L’e-service eroga o riceve dati? a "Riceve"
3. Allo step di aggiungi finalitá premere su Aggiungi 
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/9409505/ed6a3097-29ad-429e-a3e5-ed8a2171bc9c)
4. Si manifesta l'errore
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/9409505/799189cc-924d-43ee-a4e8-98b9e2b5b529)
E su console per sviluppatori c'è un chiamata in errore
![image](https://github.com/pagopa/pdnd-interop-frontend/assets/9409505/b35d8af8-e72e-49f3-8c87-045d66645f79)
con response
```json
{
    "correlationId": "421a6f2f-3f21-4c85-848e-1224d5011832",
    "errors": [
        {
            "code": "012-9989",
            "detail": "Insufficient privileges"
        }
    ],
    "status": 403,
    "title": "The request was a legal request, but the server is refusing to respond to it.",
    "type": "about:blank"
}
```

**Comportamento atteso**
Poter aggiungere la finalitá

**Il codice IPA del tuo ente**
m_lps

**Data e ora in cui si è riscontrato il problema**
es. 20/05/2024 h. ~18:00 

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
es. Operatore API

**Comment by FedericaSicchiero** [comment]
Buonasera, gli operatori API non hanno i permessi per gestire le finalità, come per gli e-service che erogano dati. 
Questo processo deve essere fatto da un Amministratore perchè si tratta di un rapporto amministrativo.

**Comment by pezz99** [comment]
Buongiorno, quindi se fino a poco tempo fa in Erogazione potevo caricare gli e-service con il profilo Operatore sicurezza / Operatore API ora non è più possibile farlo?
Grazie in anticipo per la risposta

**Comment by FedericaSicchiero** [comment]
Buongiorno, in realtà l'Operatore API ha solo il "potere" di gestire il ciclo di vita dell'e-service ma non di crearlo, pubblicarlo e associarci le finalità. Quello ha sempre potuto farlo solo l'Amministratore

**Comment by pezz99** [comment]
In realtà con il profilo di Operatore API ho sempre potuto creare un nuovo e-service e caricare il file di configurazione con le specifiche API associate all'e-service. 
Quello che non potevo fare era la creazione di client API Interop, creazione client e-service, richieste di fruizione, creazione di finalità..

**Comment by FedericaSicchiero** [comment]
Scusa, errore mio che stavo ripensando al discorso finalità per cui era stata aperta la issue. Gli e-service si possono creare ma non si possono associare le finalità, perchè quello è potere dell'amministratore

**Comment by pezz99** [comment]
Mi sono sorti questi dubbi perchè in fase di erogazione, in questo momento, ricevo questo errore in continuazione senza riuscire a caricare un nuovo e-service.

![errore](https://github.com/pagopa/pdnd-interop-frontend/assets/57443802/864d7cdc-24cd-4c72-8129-61d9279cbc49)

**Comment by FedericaSicchiero** [comment]
Per un e-service che eroga dati o che riceve? 
Su quale ambiente?

**Comment by pezz99** [comment]
Non arrivo neanche a selezionare "+1 Crea nuovo", l'errore sorge prima

**Comment by FedericaSicchiero** [comment]
Okay, ti chiedo se per favore crei una issue ad hoc così questa che è relativa ad altre cose la chiudo, indicando quelli che hai appena scritto, l'utenza e l'ente per cui stai lavorando e che ti da errore così. Grazie
