### ISSUE TITLE
Errore inaspettato ambiente Produzione

### ISSUE THREAD

**Issue by pezz99** [pagopa/pdnd-interop-frontend#817]
**Descrivi il bug**
In fase di Erogazione non è possibile creare un nuovo e-service, non si riesce a selezionare "+1 Crea nuovo" perchè l'errore sorge subito dopo il caricamento della pagina.

**Step per riprodurre il bug**
1. Entrare in Ambiente di Produzione per il servizio Interoperabilità
2. "Erogazione"
3. "I tuoi e-service"

**codice IPA ente**
c_d226

**Data e ora in cui si è riscontrato il problema**
21/05/2024 h. 9:00

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Operatore API, Operatore di sicurezza

**Screenshot**
![errore](https://github.com/pagopa/pdnd-interop-frontend/assets/57443802/a0ee688e-1ef9-4e0f-84db-e57d600d68cd)

**Note**
![typerr](https://github.com/pagopa/pdnd-interop-frontend/assets/57443802/773347ae-e873-4ada-bb15-0823be076b95)

**Comment by FedericaSicchiero** [comment]
Grazie per la nuova issue, nel frattempo che facciamo i controlli ti chiedo di uscire da tutte le finestre, anche dall'area riservata e rientrare con le tue credenziali in modo da scartare la possibilità che sia colpa di una sessione scaduta

**Comment by pezz99** [comment]
è stato fatto di nuovo l'accesso ma l'errore persiste

**Comment by FedericaSicchiero** [comment]
okay è sempre la tua utenza che da problemi a prescindere dall'ente per cui cerchi di entrare o ci sono anche altre utenze che hanno lo stesso errore? Perchè in quel caso abbiamo già un task aperto per un fix su questo tema che una volta rilasciato andrà a sistemare la questione

**Comment by pezz99** [comment]
C'è un limite sul numero di enti in cui il mio profilo può essere abilitato come operatore sicurezza/operatore api? Grazie

**Comment by FedericaSicchiero** [comment]
No non c'è limite ma abbiamo scoperto che in alcuni casi se l'utenza è associata a troppi enti possono verificarsi dei blocchi come nel caso segnalato. Nel frattempo stiamo lavorando al fix che andrà a sistemare la problematica e aggiorno la issue appena viene rilasciato

**Comment by FedericaSicchiero** [comment]
Buongiorno, ci hanno detto dal team che se ne stava occupando di aver rilasciato un fix per questa issue. Potete provare e vedere se ricevete ancora errore? Grazie

**Comment by pezz99** [comment]
Buongiorno, ho appena eseguito l'accesso e continuo a ricevere l'errore sopra

**Comment by FedericaSicchiero** [comment]
Buonasera, abbiamo rilasciato un altro fix. Potete provare ad accedere alla piattaforma e vedere se lato vostro funziona tutto? Grazie

**Comment by pezz99** [comment]
Buongiorno, dopo aver cancellato cookies e dopo aver fatto l'accesso continuiamo a riscontrare l'errore

**Comment by FedericaSicchiero** [comment]
Nuovo giorno nuovo fix, puoi riprovare ora? Grazie

**Comment by pezz99** [comment]
Funziona! Grazie mille
