### ISSUE TITLE
Step erogazione servizio

### ISSUE THREAD

**Issue by vincbaglio** [pagopa/pdnd-interop-frontend#818]
Buongiorno,
vorremmo avere più informazioni in merito all'erogazione di un servizio.
Questo lo scenario.
Noi abbiamo già un servizio SOAP, rilasciato da anni, esposto su Internet.
Autenticazione e autorizzazione sono già gestire da noi, tramite scambio certificati.
Quali sono gli step per portalo su PDND ?

**Comment by FedericaSicchiero** [comment]
Buongiorno, potete trovare tutte le informazioni su come funziona PDND e su come pubblicare i servizi alla documentazione: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/e-service

Nonostante voi abbiate già un servizio, per portarlo su PDND è necessario crearlo in piattaforma da zero inserendo tutte le informazioni richiesta man mano. Noi supportiamo SOAP quindi non si deve modificare quella parte tecnologica.

**Comment by vincbaglio** [comment]
Grazie Federica.

Avevo letto la documentazione su come creare un servizio e sul fatto che SOAP era supportato.

Intendevo dire: noi a livello software gestiamo già autenticazione e autorizzazione, quelle funzionalità vanno rimosse dal servizio e va integrato il controllo del token del servizio REST della PDND ?
 (dove si trova l'altro la documentazione di questo servizio) 

Oppure il servizio il servizio si può censire su PDND così com'è, rimanendo a nostro carico autenticazione e autorizzazione ?


Grazie

un saluto

Vincenzo

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo,
a livello di piattaforma lo stacco del token è obbligatorio perchè il fruitore possa accedere ai dati dell'erogatore, ma per il resto sta a voi decidere come volete strutturare l'e-service.
Temo forse di non capire totalmente i vostri dubbi, quindi l'unico consiglio che posso dare è provare a creare un e-service in ambiente di collaudo e se ci sono domande sul processo della piattaforma farle liberamente in modo che posso darvi una risposta più precisa.

**Comment by vincbaglio** [comment]
Ciao Federica,
l'e-service è creato su ambiente collaudo, per ADM - agenzia dogane e monopoli, si chiama infomrn.
A parte wsdl, non vedo altra informazione tecnica da inserire, tipo endpoint ecc.

grazie

**Comment by FedericaSicchiero** [comment]
Ho una risposta più chiara alle vostre domande, per erogare un servizio su PDND dovete:

1. sganciare il vostro servizio dal meccanismo esistente di autenticazione e autorizzazione
2. seguire le istruzioni qui https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#verifica-di-un-voucher-da-parte-di-un-erogatore-di-e-service per la verifica post stacco del token da parte di fruitore
3. ricordarsi che il servizio deve rispettare i requisiti previsti dal ModI https://docs.pagopa.it/interoperabilita-1/come-integrare-i-propri-servizi-su-pdnd-interoperabilita

Di base noi siamo la fonte autoritativa, se rilasciamo voucher l'ente è autorizzato ad accedere dati ma voi dovete controllare che token sia stato effettivamente rilasciato da noi

**Comment by vincbaglio** [comment]
Grazie Federica.
Quello intendevo, il sevizio va  quindi modificato

Un'altra cosa.
L'endpoint attualmente del servizio è bilanciato su delle macchine che richiedono obbligatoriamente un certificato del consumer e che questo sia della certification authority Dogane.
Andrà configurato anche un endpoint ad hoc senza quelle caratteristiche ?

Grazie

un saluto

Vincenzo
