### ISSUE TITLE
Errore nello stacco del voucher

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#827]
Sapreste dirci a cosa è dovuto questo errore?
"correlationId":"abbb21c6-4d9b-4ee4-91c1-f0abf2f537e3","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400,"title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank"

Grazie

**Comment by FedericaSicchiero** [comment]
Il tool di debug del voucher risponde con tutte spunte verdi quando avete provato a controllare?

**Comment by amollicone1982** [comment]
si

**Comment by amollicone1982** [comment]
Ambiente di collaudo. mi ero dimenticato

**Comment by FedericaSicchiero** [comment]
Dai controlli sembra che l'errore legato al claim nbf (Not before) settato in un timestamp successivo all’utilizzo.
Se non avete particolari condizioni per settarlo nel futuro, conviene impostarlo uguale al claim iss (issued at).

**Comment by amollicone1982** [comment]
Grazie Federica, questo spiega anche perchè su alcune macchine funzionava
