### ISSUE TITLE
C019 esistenza in vita Produzione, errore recupero TOKEN

### ISSUE THREAD

**Issue by saldeangelis** [pagopa/pdnd-interop-frontend#834]
Buongiorno,
riceviamo il seguente errore per il recupero del token

{"correlationId":"70002f6c-5f0c-4a64-be42-0f08309d5006","title":"The request contains bad syntax or cannot be fulfilled.","type":"about:blank","errors":[{"code":"015-0008","detail":"Unable to generate a token for the given request"}],"status":400}

Abbiamo eseguito il debug sulla piattaforma e abbiamo questo response, ma le finalità sono attive.

Gentilmente riuscite a darci supporto in giornata? Abbiamo l'ambiente di produzione fermo, grazie

![newTest](https://github.com/pagopa/pdnd-interop-frontend/assets/28670106/9746b9b9-eb9e-40f0-9ac1-29fc987ca490)

**Comment by FedericaSicchiero** [comment]
Buongiorno, ci può ripetere ente, e-service e a quale finalità lo state collegando?

**Comment by saldeangelis** [comment]
Buongiorno Federica,
di seguito le info richieste

**Ente:** MEDIOLANUM VITA S.P.A
**e-service:** C019-servizioAccertamentoEsistenzaVita-approvazione_automati, versione 2
**Finalità:** lettera IVASS sulla gestione delle polizze dormienti

Grazie per la celere risposta

**Comment by FedericaSicchiero** [comment]
Grazie, controlliamo e aggiorno la issue appena ho novità

**Comment by FedericaSicchiero** [comment]
Potete disassociare dal client la finalità e riassociarla?

**Comment by saldeangelis** [comment]
Ciao,
Adesso stiamo effettuando le chiamate, però su alcuni abbiamo ricevuto una risposta di errore:
GovWay-Transaction-ID:"8b498122-2703-11ef-954e-005056ae1d2a"

potete indicarci cosa voglia dire questo errore?

Grazie

**Comment by FedericaSicchiero** [comment]
Un errore simile dipende dall'erogatore, in questo caso visto che si tratta di ANPR vi consiglio di aprire una issue sulla loro repository: https://github.com/italia/anpr/issues

**Comment by saldeangelis** [comment]
ok grazie , puoi chiudere questa issue
