### ISSUE TITLE
Assegnazione ruoli utente

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#848]
Salve, parlo a nome del Ministero dell'interno.
Stiamo cercando di assegnare un nuovo ruolo ad un utente in ambinete di interoperabilità ma prendiamo un errore generico.
All'utenza di Angela Frontera tentiamo di associare il ruolo di operatore api tramite l'utenza delegato della dott. Toscano.
In più non ci dà la possibilità, per il solo ambiente di interoperabilità, di assegnare il ruolo di amministratore a Filippo Viglianisi (sempre tramite utenza della dott. Toscano). In ambiente di collaudo siamo riusciti, invece, a fare queste assegnazioni

Potete verificare il motivo

Grazie e buona giornata

**Comment by FedericaSicchiero** [comment]
Mi confermate che l'utenza della Dott. Toscano è quella di amministratore per tutti gli ambienti e non solo di collaudo?

Detto questo se l'utenza di Angela Frontera è quella di amministratore e volete ridurla a Operatore API bisogna prima rimuoverla dal ruolo di amministratore seguendo il percorso indicato [qui](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione#aggiungere-o-rimuovere-un-operatore-amministrativo-a-pdnd-interoperabilita).
Stesso discorso per l'utenza di Filippo Viglianisi, bisogna seguire l'iter indicato sopra per la nomina di un nuovo utente amministratore in ambiente di produzione.

Ricordo che in prod c'è il limite di 3 amministratori per ente.

**Comment by amollicone1982** [comment]
L'utenza della Dott. Toscano è quella di amministratore per tutti gli ambienti

 Angela Frontera è solo operatore di sicurezza e vorremmo aggiungere operatore api

**Comment by FedericaSicchiero** [comment]
Okay grazie della precisazione, lo faccio presente al team che gestisce le utenze per sistemare quella di Angela Frontera

**Comment by amollicone1982** [comment]
Ciao Federica, grazie.
se ci riuscite anche a mettere come amministratore Filippo in produzione

**Comment by FedericaSicchiero** [comment]
Per quella di Filippo bisogna seguire l'iter linkato sopra di mandare i documenti firmati via PEC, perchè c'è un team apposito che segue onboarding e utenze, non abbiamo in mano noi quella parte.
Poi appena ho novità per quella di Angela aggiorno la issue

**Comment by FedericaSicchiero** [comment]
Buongiorno, dal team che si occupa delle utenze mi hanno segnalato di avere un bug che stanno risolvendo, ma che nel frattempo potete togliere tutte le utenze ad Angela e riassegnarle selezionando entrambe le funzionalità di operatore quando gliele state ridando
