### ISSUE TITLE
Chiamata servizi PCP

### ISSUE THREAD

**Issue by FavaroInsiel** [pagopa/pdnd-interop-frontend#852]
abbiamo concluso l’onboarding della piattaforma certificata  “eAppaltiFVG-SAT”, vi chiediamo di abilitare la nostra piattaforma o di verificare il motivo per cui si presenta l’errore 403

Client ID 71e6bd2f-8b0e-5dc3-8ac6-743d2ffa06d9

{
  "type": "[https://govway.org/handling-errors/403/Authorization.html"](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgovway.org%2Fhandling-errors%2F403%2FAuthorization.html%2522&data=05%7C02%7Cluciano.favaro%40insiel.it%7Cb3839af55dd5461208c408dc95292b88%7Cac2d17f7d6fb4ed9841869a351355036%7C0%7C0%7C638549251265242521%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=bu8fZKkim63BDppl9yXFegaHylT3p%2FRRSjlkHDF6phU%3D&reserved=0),
  "title": "Authorization",
  "status": 403,
  "detail": "Authorization failed",
  "govway_id": "571e9398-3301-11ef-a2a9-00505684399c"
}

Riferimenti piattaforma certificata:
**eAppaltiFVG-SAT**

Piattaforma per la gestione degli approvvigionamenti digitali della Regione FVG
71e6bd2f-8b0e-5dc3-8ac6-743d2ffa06d9
CONFORME
3.1.0
INSIEL S.p.A. con socio unico

**Comment by FedericaSicchiero** [comment]
Buongiorno, avremmo bisogno di alcuni chiarimenti:
- state lavorando come Insiel o come Regione FVG?
- per piattaforma certificata intendete un e-service con relativa finalità? Oppure un vero e proprio ente che ha fatto l'onboarding?
- l'errore lo riscontrate quando state staccando un voucher? In questo caso avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by FavaroInsiel** [comment]
Buongiorno,
Insiel è l'ente gestore, Regione FVG il titolare della Piattaforma e noi stiamo lavorando come Insiel
Dobbiamo riuscire a chiamare i servizi della PCP Anac dalla piattaforma certificata.
Stiamo attivando un primo test di verifica dei servizi AUSA

**Comment by FedericaSicchiero** [comment]
Buongiorno,
allora in questo caso vi conviene parlare direttamente con ANAC alla loro repository qui: https://github.com/anticorruzione/npa/issues
perchè noi come piattaforma mettiamo in comunicazione erogatore e fruitore ma non possiamo abilitare nulla. L'errore di mancata autorizzazione che ricevete dipende da ANAC.
Grazie
