### ISSUE TITLE
richiesta verifica invocazione API PDND

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#853]
Buonasera, 
analizzando alcune richieste di un  fruitore che non vanno a buon fine abbiamo verificato che prendiamo l'errore 500 nell'invocazioni di una API PDND.
Ad esempio chiamando la seguente risorsa: 
 [purposes/96a1b1b7-2a9e-415b-beb0-881624ba13cb/agreement](https://govway-apurposes/96a1b1b7-2a9e-415b-beb0-881624ba13cb/agreement)

Cortesemente potete verificare?

**Comment by FedericaSicchiero** [comment]
Buongiorno,
riuscite a passarci il correlationID o dare più informazioni su enti e e-service coinvolti? Grazie

**Comment by azabatta** [comment]
Buongiorno, 
prendiamo 500 per cui non abbiamo il correlationID.
L'ambiente è collaudo ed i servizi di interesse sono C018 e C030 con approvazione automatica, l'ente è l'unico di quelli con servizio attivo che non è un comune.
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, dal link risulta che il 500 che ricevete va verso Govway e quindi dipende dall'erogatore e non dalla piattaforma

**Comment by amollicone1982** [comment]
Ciao Federica,
era per farti vedere la risorsa richiamata.
ecco la cahimata che facciamo

https://api.uat.interop.pagopa.it/1.0/purposes/96a1b1b7-2a9e-415b-beb0-881624ba13cb/agreement

**Comment by amollicone1982** [comment]
Ciao federica, ho riprovato adesso e sembra risolto

**Comment by FedericaSicchiero** [comment]
Grazie dell'aggiornamento, chiudo la issue

**Comment by amollicone1982** [comment]
grazie
