### ISSUE TITLE
Servizi duplicati su PDND di collaudo

### ISSUE THREAD

**Issue by azabatta** [pagopa/pdnd-interop-frontend#854]
Buonasera,
scriviamo come erogatori dei servizi ANPR esposti dal Ministero dell'Interno. Nella visualizzazione del  catalogo PDND di collaudo - sezione Erogatore - "I tuoi eservice" abbiamo notato che alcuni servizi inseriti in bozza di recente risultano duplicati. Risultano inoltre duplicate due richieste effettuate di recente da un fruitore.
E' possibile verificare?
Grazie

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, controlliamo e vi facciamo sapere

**Comment by FedericaSicchiero** [comment]
Buongiorno, dopo un fix rilasciato di recente la situazione dovrebbe essersi sistemata. Se potete controllare anche lato vostro che sia tutto corretto. Grazie

**Comment by azabatta** [comment]
Buongiorno, confermo che non ci sono più duplicazioni.
Grazie
