### ISSUE TITLE
Errore chiamata end-point E-service INAD

### ISSUE THREAD

**Issue by svilsail** [pagopa/pdnd-interop-frontend#864]
Buongiorno,
abbiamo effettuato tutta la procedura di configurazione in ambiente sia di collaudo che di produzione del servizio 
INAD CONSULTAZIONE DD, v. 2
fino alle verifica in debug della Client Assertion. tutto è andato a buon fine e con la chiamanta
https://auth.uat.interop.pagopa.it/token.oauth2
arriviamo ad ottenre il Barer Token senza problemi.
quando però proviamo ad effettuare un chiamata del servizio per il recupero delle PEC
https://api.inad.gov.it/rest/inad/v1/domiciliodigitale/listDigitalAddress
Abbiamo un messaggio di errore sia provando tramite lo swagger a partire dallo YAML messo a disposizione (errore di seguito)
Undocumented	Failed to fetch.
Possible Reasons:
•	CORS
•	Network Failure
•	URL scheme must be "http" or "https" for CORS request.
Sia a partire da PostMan andando ad importare la Curl messa a disposizione (errore di seguito)
{
    "status": 401,
    "type": "UNAUTHORIZED",
    "detail": "Invalid Bearer JWT Token"
}
 
Restiamo a disposizione per qualsiasi informazione integrativa sia necessaria per arrivare a identificare quale sia l'origine del problema
 
Grazie e a presto

**Comment by FedericaSicchiero** [comment]
Buongiorno,
se utilizzando il tool di debug del voucher presente in piattaforma ricevete tutte spunte verdi e comunque riuscite a staccare un token lato PDND, vuol dire che l'errore dipende dall'erogatore e dovreste contattare loro. Ho visto che nella scheda erogatore la mail di contatto è protocollo@pec.agid.gov.it
