### ISSUE TITLE
Elenco finalità: applicazione dei filtri errata

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#867]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Si rileva una non corretta applicazione dei filtri delle finalità in PDND Interoperabilità Collaudo, nello specifico non viene applicato il filtro "Cerca per e-service"

**Step per riprodurre il bug**
1. Vai su 'erogazione/finalita'
2. Clicca su 'Cerca per e-service'
3. Seleziona uno degli e-service
4. Il filtro non è applicato

**Comportamento atteso**
L'elenco delle finalità DEVE essere limitato solo all'e-service selezionato/i

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
08/07/2024 h. 10:40

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
ciao Vincenzo, grazie della segnalazione lo faccio presente al team e poi aggiorno la issue appena è stato risolto.

**Comment by FedericaSicchiero** [comment]
ciao Vincenzo, abbiamo rilasciato il fix per questo bug, ora è risolto. Grazie
