### ISSUE TITLE
Servizio INPS - ConsultazioneISEE - clone - richiesta messaggio SOAP per il test

### ISSUE THREAD

**Issue by ctamietti** [pagopa/pdnd-interop-frontend#87]
Buongiorno,
stiamo iniziando a testare il Servizio INPS - ConsultazioneISEE - clone.
La documentazione associata al servizio è piuttosto completa ed abbiamo visto il wsdl. 
Tuttavia, iI servizio esposto richiede dati in input (date, codici fiscali, numeri di protocollo ecc. ecc.) dei quali non conosciamo eventuali valorizzazioni significative, soprattutto tenendo conto che siamo in ambiente di test.
E' possibile avere alcuni esempi di tracciati XML da usare come input nella busta SOAP (o alcuni messaggi SOAP di esempio) in modo da ottenere un risultato significativo nel testing del servizio erogato?
Grazie e cordiali saluti,
Corrado Tamietti

**Comment by ruggerocastagnola** [comment]
Buongiorno Corrado, 

la persona di riferimento per questo E-Service di INPS è Maila Mancinelli (maila.mancinelli@inps.it).

Per qualsiasi cosa, sono a disposizione

Ruggero
