### ISSUE TITLE
Cancellazione utente

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#877]
Bungiorno,
in che modo è possibile cancellare un utenza?

Nel dettaglio, fatto salvo il caso di utente con ruolo Amministratore in PDND Interoperabilità per cui si applica la procedura indicata in https://docs.pagopa.it/interoperabilita-1/manuale-operativo/guida-alladesione#aggiungere-o-rimuovere-un-operatore-amministrativo-a-pdnd-interoperabilita, come è possibile cancellare le altre tipologie di utenti?

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno Vincenzo,
un amministratore può entrare nella sezione Utenti nell'Area riservata - quindi prima di entrare nella card di Interoperabilità - e da lì modificare tutte le utenze necessarie.
