### ISSUE TITLE
Nuova versione ConsultazioneISEE su PDND - Impossibile allegare file

### ISSUE THREAD

**Issue by mailamancinelli** [pagopa/pdnd-interop-frontend#88]
Sto cercando di caricare della documentazione aggiuntiva nella PDND di test servizio ConsultazioneISEE per supportare gli enti fruitori che ci chiedono file di esempio ecc…
Ho fatto come  indicato in riunione 
Crea bozza nuova versione ma quando vado a mettere gli allegati non me li fa salvare.
Facendo salva e poi rientrando l’allegato non c’è
Attualmente la nuova versione è in bozza.
Potete verificare e farmi sapere
Per ora invierò l’allegato via mail all’ente, ma sarebbe bene fare una prova da piattaforma
![allegtoNuovaversione](https://user-images.githubusercontent.com/108742183/177344655-e0e93ef3-a887-40f6-b2cb-60b11c48e1c4.JPG)

**Comment by ruggerocastagnola** [comment]
Buongiorno Maila, probabilmente non sta mostrando il messaggio di errore (indago sul perché) ma da quello che vedo è corretto che non accetti il file che sta provando a caricare. Il punto è che alla voce "Interfaccia" si può caricare solamente il documento `.wsdl` in caso di servizi SOAP o quello OpenAPI (`.yml` o `.yaml`) in caso di servizi REST, mentre lì vedo che si sta tentando di caricare uno `.zip`. Se si necessita di caricare ulteriore documentazione (es. documenti PDF oppure zip, lo si può fare nella sezione seguente, cioè "Documentazione"). Il caricamento di un file di interfaccia è obbligatorio, quello dei file di documentazione è opzionale e a descrizione del gestore del servizio. Per qualsiasi dubbio, ci sono!

**Comment by mailamancinelli** [comment]
L’ho fatto su Interfaccia ho caricato anche il solo wsdl e succede la stessa cosa, 
Inoltre l’esigenza è proprio quella di caricare altra documentazione, il wsdl l'ho già caricato nella prima bozza, ora devo aggiungere anche lo zip che contiene altra documentazione, ho provato in documentazione e non allega niente.

**Comment by ruggerocastagnola** [comment]
Grazie mille della segnalazione. Dunque, posso chiederle cortesemente di inviare una copia dei file a `ruggero.castagnola@pagopa.it`? Vorrei fare un test per capire dov'è il problema

**Comment by ruggerocastagnola** [comment]
@mailamancinelli confermo che riesco a replicare il problema di caricamento dello .zip come documentazione. Ho necessità di confrontarmi con il resto del team prima di tornare da lei

**Comment by ruggerocastagnola** [comment]
@mailamancinelli ho fatto una verifica ma purtroppo non è possibile rilasciare una fix per questo problema nell'ambiente di test attualmente in uso. La patch sarà comunque presente direttamente nell'ambiente di produzione pubblicato qualche giorno fa, o nel nuovo ambiente di sviluppo che sarà messo a disposizione degli enti

**Comment by ruggerocastagnola** [comment]
Buongiorno Maila, riscontra ancora il problema? Vedo che mi ha risposto ad un messaggio precedente, ma ci sono stati diversi aggiornamenti nel frattempo

**Comment by ruggerocastagnola** [comment]
Buonasera, chiudo la issue, risolta attraverso altri canali
