### ISSUE TITLE
errore sulle finalità 

### ISSUE THREAD

**Issue by annamariapalmieri** [pagopa/pdnd-interop-frontend#882]
Buongiorno

l'Anac ha creato i servizi per il Ministero della Giustizia: 

MG - callback Certificazione Casellario v.1

MG - Callback Certificazione Sanzioni v1 

e di cui ho fatto la richiesta di fruizione e le richiesta sono attive,
Successivamente  ho effettuato la richiesta di finalità per entrambi i servizi , ma la finalità va in errore 

 riporto nei file in allegato i passaggi effettuati e l'errore  si presenta dopo salva e prosegui della maschera 2 in particolare l'errore è " non è stato possibile aggiornare la finalità per favore riprova! 

[maschera2.pdf](https://github.com/user-attachments/files/16281680/maschera2.pdf)
[Maschera1.pdf](https://github.com/user-attachments/files/16281682/Maschera1.pdf)

**Comment by annamariapalmieri** [comment]
si comunica che l'errore è presente sia sul collaudo che produzione

**Comment by annamariapalmieri** [comment]
Buongiorno
le comunico che sto utilizzando l'utenza di amministratore, sono amministratore per il ministero della Giustizia

**Comment by FedericaSicchiero** [comment]
Grazie dell'informazione, facciamo dei controlli e aggiorno la issue appena ho novità

**Comment by annamariapalmieri** [comment]
Aggiungo che essendo servizi di callback l'ANAC ha impostato il servizio callback con l'opzione riceve , pertanto ha impostato la finalità . Il ministero della Giustizia quando crea la finalità ottiene già la precompilazione della finalità impostata da ANAC e che è stata condivisa con il Ministero

**Comment by FedericaSicchiero** [comment]
Buongiorno, si confermo che è un errore solo per gli e-service che ricevono dati e quindi creano loro la finalità. Stiamo lavorando per risolverlo.

**Comment by annamariapalmieri** [comment]
Buongiorno
si chiede se si conoscono i tempi per la correzione , al fine di pianificare le attività in produzione con ANAC dei servizi collegati

**Comment by annamariapalmieri** [comment]
Buongiorno
si chiede se ci sono aggiornamenti sul rilascio in quanto volevamo pianificare l'avvio dei servizi.
Grazie

**Comment by Carminepo2** [comment]
Buongiorno, entro la fine della giornata di oggi il problema sarà risolto in tutti gli ambienti e riprenderà il regolare funzionamento. Grazie della pazienza

**Comment by beetlecrunch** [comment]
Buonasera,
abbiamo appena concluso le operazioni di rilascio negli ambienti di collaudo e produzione.
Restiamo in attesa di un vostro feedback per procedere con la chiusura dell'issue.
Grazie.

**Comment by annamariapalmieri** [comment]
Buongiorno
si comunica che la finalità è stata pubblicata pertanto l'errore è stato corretto.
