### ISSUE TITLE
Impossibile aggiornare la richiesta di fruizione dell'e-service arch-common-service_SDG alla versione 18 (amb. collaudo)

### ISSUE THREAD

**Issue by AndreaS-RL** [pagopa/pdnd-interop-frontend#883]
Buongiorno,
ho una richiesta di fruizione attiva, in ambiente di collaudo PDND, per l'e-service "arch-common-service_SDG" - versione 17. Ho la necessità di aggiornare tale richiesta alla versione 18 dell'e-service, ma quando tento di procedere con l'aggiornamento mi viene mostrato l'errore "Non è possibile aggiornare la richiesta. Per favore riprova".

Per riprodurre il bug:
1. Sono entrato sulla PDND in modalità collaudo.
2. Ho selezionato l'elenco delle mie richieste di fruizione.
3. Ho aperto la richiesta di fruizione attiva dell'e-service "arch-common-service_SDG".
4. Ho cliccato su Aggiorna.
5. Ho selezionato gli elementi consigliati prima di fare l'aggiornamento.
6. Ho cliccato su Aggiorna.

CODICE IPA DI APPARTENENZA: r_lombar

Il problema è stato riscontrato il giorno 17/07/2024, quando ho provato ad aggiornare la richiesta in AMBIENTE DI COLLAUDO, accedendo con la mia utenza di Amministratore

[bug_agg_richiesta_eserviceSDG.pdf](https://github.com/user-attachments/files/16283833/bug_agg_richiesta_eserviceSDG.pdf)

**Comment by FedericaSicchiero** [comment]
Grazie della segnalazione, controlliamo e aggiorno la issue appena ho novità

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete riprovato ad aggiornare la versione?

**Comment by AndreaS-RL** [comment]
Appena provato.
Questo l’errore mostrato.
d2ea5d65-c37e-4a47-b615-d07d146fe2ea

***@***.***

Andrea Sion
PROGETTAZIONE E ATTUAZIONE DI INIZIATIVE PER LA VALORIZZAZIONE DEL PATRIMONIO INFORMATIVO PUBBLICO, L'INTEROPERABILITA' TRA SISTEMI INFORMATIVI, LO SVILUPPO DI ECOSISTEMI DIGITALI E LA DIGITALIZZAZIONE DELLA PUBBLICA AMMINISTRAZIONE

Unità Organizzativa Trasformazione Digitale per la Modernizzazione e la Semplificazione
Presidenza - Direzione Centrale PNRR, Olimpiadi e Digitalizzazione
***@***.***
Piazza Città di Lombardia 1 - 20124 Milano
Nucleo N 3 - piano N° 5 - stanza  44
Telefono 02/67652653
Cellulare 366.6359923

Da: Federica Sicchiero ***@***.***>
Inviato: lunedì 29 luglio 2024 08:12
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Andrea Sion ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] Impossibile aggiornare la richiesta di fruizione dell'e-service arch-common-service_SDG alla versione 18 (amb. collaudo) (Issue #883)


Buongiorno, avete riprovato ad aggiornare la versione?

**Comment by AndreaS-RL** [comment]
[like]  Andrea Sion reacted to your message:
________________________________

**Comment by AndreaS-RL** [comment]
Certo, nessun problema.
Questo il nuovo identificativo dell’errore: d19737cf-4e88-4540-b59e-e816ca795db4
Sotto lo screenshot.

***@***.***
Saluti


Andrea Sion
PROGETTAZIONE E ATTUAZIONE DI INIZIATIVE PER LA VALORIZZAZIONE DEL PATRIMONIO INFORMATIVO PUBBLICO, L'INTEROPERABILITA' TRA SISTEMI INFORMATIVI, LO SVILUPPO DI ECOSISTEMI DIGITALI E LA DIGITALIZZAZIONE DELLA PUBBLICA AMMINISTRAZIONE

Unità Organizzativa Trasformazione Digitale per la Modernizzazione e la Semplificazione
Presidenza - Direzione Centrale PNRR, Olimpiadi e Digitalizzazione
***@***.***
Piazza Città di Lombardia 1 - 20124 Milano
Nucleo N 3 - piano N° 5 - stanza  44
Telefono 02/67652653
Cellulare 366.6359923

Da: Federica Sicchiero ***@***.***>
Inviato: martedì 30 luglio 2024 17:08
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Andrea Sion ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] Impossibile aggiornare la richiesta di fruizione dell'e-service arch-common-service_SDG alla versione 18 (amb. collaudo) (Issue #883)


Buonasera, potete riprovare? Avvisiamo già che riceverete errore ma risulterà sui nostri sistemi così che abbiamo il momento puntuale del bug. Grazie

**Comment by FedericaSicchiero** [comment]
Buonasera, potreste riprovare? Grazie

**Comment by AndreaS-RL** [comment]
Buonasera,
l'aggiornamento alla versione 18, in ambiente di collaudo, dell'e-service "arch-common-service_SDG" è andato a buon fine.

Saluti


Andrea Sion

PROGETTAZIONE E ATTUAZIONE DI INIZIATIVE PER LA VALORIZZAZIONE DEL PATRIMONIO INFORMATIVO PUBBLICO, L'INTEROPERABILITA' TRA SISTEMI INFORMATIVI, LO SVILUPPO DI ECOSISTEMI DIGITALI E LA DIGITALIZZAZIONE DELLA PUBBLICA AMMINISTRAZIONE



Unità Organizzativa Trasformazione Digitale per la Modernizzazione e la Semplificazione

Presidenza - Direzione Centrale PNRR, Olimpiadi e Digitalizzazione

[cid:24510aea-1487-4d11-83a1-aadd8adfcfba]

Piazza Città di Lombardia 1 - 20124 Milano
Nucleo N 3 - piano N° 5 - stanza  44

Telefono 02/67652653

Cellulare 366.6359923



________________________________
Da: Federica Sicchiero ***@***.***>
Inviato: venerdì 2 agosto 2024 17:17
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Andrea Sion ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] Impossibile aggiornare la richiesta di fruizione dell'e-service arch-common-service_SDG alla versione 18 (amb. collaudo) (Issue #883)


Buonasera, potreste riprovare? Grazie
