### ISSUE TITLE
Richiesta chiarimento per casi di omocodia

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#90]
Salve, 

ci servirebbe sapere se a fronte di una richiesta di generalità di una persona fisica potremmo ottenere casi di omocodia per i quali il codice fiscale non è stato ancora rettificato dall'Agenzia delle Entrate. 
In questo caso si configurerebbe una risposta composta da due occorrenze con il valore degli attributi delle generalità identiche salvo che per il valore dell'identificativo ANPR?

Grazie

**Comment by giovannidenicola** [comment]
Ha ragione mi scuso per l'omissione.

La domanda è riferita all'E-Service C015 - Servizio Accertamento Generalita di ANPR.

Grazie

**Comment by ruggerocastagnola** [comment]
Grazie. Chiedo cortesemente supporto ad @amollicone1982 per rispondere al dubbio

**Comment by azabatta** [comment]
Buongiorno, 
sì confermo quanto ha indicato: il sistema restituisce due risposte accodate con le generalità di ambedue i cittadini con diverso identificativo ANPR. 
Nella ricerca per dati anagrafici i codici fiscali restituiti dal sistema potrebbero essere differenti o per la presenza di un codice fiscale provvisorio per omocodia (numerico di lunghezza 11) oppure perché l'omocodia è già stata risolta. 
Nella ricerca per codice fiscale c'è l'eventualità che i dati anagrafici possano non coincidere perfettamente ad esempio per differenze di una o più vocali nel nome e/o nel cognome dei due cittadini in trattamento.
Saluti

**Comment by giovannidenicola** [comment]
Grazie per la risposta,

vi chiedo cortesemente un ulteriore chiarimento:
- per l'E-Service C015, nell'attributo noteGeneralità cosa è possiible trovare? Sono informazioni significative ai fini del riconoscimento di una angrafica?
- per l'E-Service C020, nell'attributo noteIndirizzo cosa è possiible trovare? Sono informazioni significative ai fini del riconoscimento di una anagrafica?

Grazie

**Comment by azabatta** [comment]
Buonasera, 
riguardo agli indicatori di assenza  (nome, cognome, giorno nascita, giorno e mese nascita) il valore  assunto dall'attributo è 1. Si specifica che tali indicatori non individuano una mancanza del dato in ANPR  oppure la possibilità di effettuare una ricerca di tipo generico ma si riferiscono a particolari cittadini stranieri nei cui paesi di origine è prevista l'assenza di uno di tali dati anagrafici.
Riguardo ai campi note di Generalità ed Indirizzo per il momento non è prevista la loro valorizzazione. I tracciati sono stati predisposti con un'estensione più ampia rispetto a quanto effettivamente restituito dai servizi per futuri utilizzi. Per il dettaglio dei dati  trattati si può far riferimento alla documentazione in formato  "pdf" che specifica dati di ingresso e di uscita previsti per ogni eservice. 
Buona serata

**Comment by giovannidenicola** [comment]
Grazie per il feedback.

**Comment by azabatta** [comment]
Buongiorno, 
sì esatto, l'indicatore è valorizzato con 1 oppure  il campo non viene restituito nella risposta.
Se un indicatore sulla data di nascita è valorizzato il relativo campo giorno e/o mese presenta il valore 01.
La documentazione rilasciata è una prima versione che sicuramente può essere oggetto di miglioramenti. Approfitteremo di questo primo periodo di introduzione della piattaforma per raccogliere tutte le segnalazioni che ci consentiranno di renderla  più esaustiva. 
Grazie per le sue osservazioni
Buona giornata

**Comment by giovannidenicola** [comment]
Grazie per le risposte.
Buona giornata.
