### ISSUE TITLE
Validazione Client Assertion

### ISSUE THREAD

**Issue by kampusses** [pagopa/pdnd-interop-frontend#900]
**Il codice IPA del tuo ente**: c_e549
Comune di LESINA (FG)

**Ambiente**
Collaudo

**client_id**
4fd9abf0-29a2-46cf-9fe1-580eeb5617bc

Salve,
dopo alcune settimane, in ambiente di collaudo per il comune di Lesina (FG), ho eseguito nuovamente le nostre procedure che utilizzano i servizi SEND con previo ottenimento del voucher da Interoperabilità. Le procedure hanno funzionato regolarmente fino a quest'oggi, quando la piattaforma di interoperabilità non genera più il voucher. Su selfcare di interoperabilità, in ambiente di collaudo, ho provarto ad eseguire il debug della client assertion dove mi viene restituito il seguente errore: Client assertion validation failure. Reason: Expired JWT
Qual'è il limite temporale entro cui poter utilizzare una client assertion?
Allego screenshot del debug eseguito in ambiente di collaudo.
![client_assertion](https://github.com/user-attachments/assets/11a91467-9c67-402a-83f8-da85f4f7d3fb)

**Comment by FedericaSicchiero** [comment]
Buongiorno, il limite è dato dalla durata del token e non dalla client assertion in se'. In questo caso essendo scaduto bisogna crearne un altro e rifare l'operazione

**Comment by kampusses** [comment]
E' possibile sapere che durata ha il token? Scade per inattività oppure ha una durata prefissata?
Ringrazio per la collaborazione

**Comment by FedericaSicchiero** [comment]
Potete trovare tutte le informazioni nella nostra documentazione: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/utilizzare-i-voucher#richiesta-di-un-voucher-spendibile-presso-le-api-di-interoperabilita
