### ISSUE TITLE
Impossibile visualizzare la motivazione data per un rifiuto finalità

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#901]
**Descrivi il bug**
Impossibilità di visualizzare motivazione data per rifiuto finalità

**Step per riprodurre il bug**
1. Vai su 'Erogazione'
2. Selezione 'Finalità'
3. Applica filtro 'Stato della finalità' = rifiutata
4. Clicca su "Visualizza" di una finalità presente nell'elenco (ad esempio https://selfcare.interop.pagopa.it/ui/it/erogazione/finalita/f1bd5ca2-c95c-4b34-a064-82767cbab5d3)
5. Clicca su "Leggi qui i motivi del rifiuto."

**Comportamento atteso**
Visualizzazione della morivazione espressa per il rifiuto della finalità selezionata

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
29/07/2024 h.15.50

**Ambiente**
Produzione 

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Screenshot**
![Screenshot](https://github.com/user-attachments/assets/c6eb7330-6a69-45c4-8e3d-64f7093f3ada)

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, grazie della segnalazione lo faccio presente al team.

**Comment by FedericaSicchiero** [comment]
Ciao Vincenzo, abbiamo rilasciato ieri il fix per questo bug, chiudo la issue
