### ISSUE TITLE
Richiesta di fruizione PCP - Comunica post pubblicazione

### ISSUE THREAD

**Issue by tommaso-gobbato** [pagopa/pdnd-interop-frontend#905]
Salve, 
ho un problema con la creazione di una richiesta di fruizione per il servizio in oggetto "PCP - Comunica Post Pubblicazione"; il sistema mi permette di creare una nuova richiesta di fruizione ma, arrivati al momento della "pubblicazione" della richiesta di fruizione, non mi permette di completare l'operazione.
Qui sotto screen shot con il warning "Questa bozza non è più pubblicabile. Dal momento della sua creazione è uscita una nuova versione dell’analisi del rischio. Eliminala e creane una nuova." e il tasto "Pubblica" disabilitato.

Ente = Deda Next s.r.l.
Ambiente = Produzione

![image](https://github.com/user-attachments/assets/501b71eb-7771-4758-9e56-f8bd56017b32)

**Comment by FedericaSicchiero** [comment]
Buongiorno, quella in screen è una finalità e non una richiesta di fruizione. Quello che è successo è che è stata aggiornata la versione di e-service a cui è associata la finalità, per questo bisogna andare sulle proprie richieste di fruizione, aggiornare quella con il simbolo "dell'orologio" e poi collegarci la nuova finalità che state creando come da screen.
In questo modo l'errore scompare. Grazie

**Comment by tommaso-gobbato** [comment]
Salve, 
chiedo scusa, sì, è una finalità non una richiesta di fruizione; il problema è che non c'è alcuna richiesta di fruizione con simbolo "orologio"

![image](https://github.com/user-attachments/assets/5897b2c7-68d4-492e-86f3-8ed12494dd6d)

e cercando di creare la nuova finalità la schermata dove è obbligatorio selezionare e-service e finalità proposta (unica scelta possibile), selezionando poi "crea bozza" e completando i passi successivi si arriva al punto descritto nel post precedente, con messaggio di warning e tasti "pubblica" disabilitato

![image](https://github.com/user-attachments/assets/7c9017d6-137f-454f-a574-d4f0020d71d4)

D'altra parte avevo appena fatto la richiesta di fruizione di tale e-service e subito dopo l'inserimento della finalità, e ha dato subito l'errore

**Comment by FedericaSicchiero** [comment]
Grazie delle informazioni, l'utenza con cui state facendo tutti i passaggi è quella di amministratore?

**Comment by tommaso-gobbato** [comment]
Sì sì certo, è l'utenza di amministratore, con cui è stata fatta anche la richiesta iniziale di adesione a PDND

![image](https://github.com/user-attachments/assets/67e3f22e-fe72-44a9-ba02-3cd37b6aa915)

**Comment by FedericaSicchiero** [comment]
Buongiorno, vedo che ora la vostra finalità è stata attivata. Mi confermate che anche lato vostro funziona tutto?

**Comment by tommaso-gobbato** [comment]
Salve, sì, in effetti sono riuscito a pubblicarla comunque; la cosa un po' bizzarra è che, nonostante il warning e il blocco del "pubblica" di cui sopra (che tuttora permane), tornando nell'elenco era possibile effettuare l'operazione dal "menu contestuale" (i tre puntini) utilizzando la funzione "Attiva", e la cosa ha funzionato... mistero ;-)

![image](https://github.com/user-attachments/assets/c4927ebc-2858-4eed-9daa-867ef4f2081f)

**Comment by FedericaSicchiero** [comment]
Grazie anche di questa segnalazione, passo tutto al team in modo da fare dei controlli ed evitare questo genere di situazioni!
