### ISSUE TITLE
Il Voucher ottenuto non è completo 

### ISSUE THREAD

**Issue by robragu** [pagopa/pdnd-interop-frontend#906]
Effettuata la chiamata all'endpoint per ottenere il bearer token, passando i campi purposeId e digest, nel token di ritorno
questi campi non sono presenti, pur non ottenendo nessun codice di errore.

Sperando in un celere riscontro da parte vostra, ringrazio in anticipo.
Roberto Ragusa
300 Software S.r.l.

**Comment by FedericaSicchiero** [comment]
Salve, per ottenere il token state usando "Client e-service" oppure "Client API interop"? Perchè per staccare il token bisogna usare il primo, mentre il secondo serve a ottenere informazioni sugli eventi che accadono in piattaforma

**Comment by robragu** [comment]
Buongiorno, la ringrazio per la celere risposta.
In effetti il problema era quello, ora usiamo correttamente "Client
e-service" e otteniamo i campi che prima erano mancanti.
Purtroppo ancora la richiesta ad ANAC non passa per errore 400,
govway_id":"fc42478d-4fe2-11ef-8dc0-0050568e08b3".
Cordiali saluti
Roberto Ragusa
Trecento Software S.r.l.


Il giorno gio 1 ago 2024 alle ore 08:54 Federica Sicchiero <
***@***.***> ha scritto:

**Comment by FedericaSicchiero** [comment]
In questo caso allora dovreste contattare direttamente ANAC o aprire una issue nella loro repository: https://github.com/anticorruzione/npa/issues
ma potete fare una prova ulteriore che non dipenda dalla piattaforma utilizzando il tool di debug del voucher che trovate sempre lì in piattaforma. Se ricevete tutte spunte verdi vuol dire che lato nostro funziona tutto. Grazie
