### ISSUE TITLE
abilitazione profilo master

### ISSUE THREAD

**Issue by beoluc** [pagopa/pdnd-interop-frontend#907]
Buongiorno,

avrei necessità di abilitare il mio profilo sul sito pagopa come utente master per poter variare gli altri utenti e attivare le funzionalità delle diverse misure.

Nello specifico sto cercando di attivare le notifiche digitali ma non trovo il menu di interoperabilità.

Gazie.

Luca

Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Una breve descrizione

**Step per riprodurre il bug**
1. Vai su '...'
2. Clicca su '....'
3. Vedi l'errore

**Comportamento atteso**
Cosa ti aspetteresti?

**Il codice IPA del tuo ente**
Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente

**Data e ora in cui si è riscontrato il problema**
es. 24/11/2021 h. 10:20

**Ambiente**
Produzione o Collaudo

**Quali permessi ha la tua utenza?**
es. Amministratore (operatore amministrativo), Operatore API, Operatore di sicurezza

**Screenshot**
Se possibile, incolla uno screenshot che mostra il punto in cui si presenta il bug

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Buongiorno, questo canale è unicamente per la piattaforma PDND Interoperabilità. 
Non abbiamo nella piattaforma un profilo master, potrebbe spiegare meglio quale problema incontra? E soprattutto per quale ente lavora?
Per il sito pagoPA la pagina di assistenza è questa in ogni caso: https://www.pagopa.gov.it/it/assistenza/

Grazie
