### ISSUE TITLE
Attributi ambiente di collaudo

### ISSUE THREAD

**Issue by matteorovigatti** [pagopa/pdnd-interop-frontend#914]
Abbiamo la necessità di avere gli attributi in ambiente di COLLAUDO per testare gli e-service:

In anagrafica ente (888 Software Products)
l'attributo seguente, richiesto da anac in pdnd di collaudo :
"Gestore che ha in carico una o più componenti non certificate con accesso all'ambiente di qualificazione"
è nello stato "Attributo revocato dal certificatore"

Ambiente
Collaudo

Quali permessi ha la tua utenza?
Amministratore

Note
Dopo aver rifatto la domanda di certificazione componente ed accettata in data 06/08/2024 ci sono stati tolti gli attributi per richiedere la fruizione degli eservice con la dicitura "Attributo revocato dal certificatore".
Di seguito i dati della domanda:
Denominazione: 888 Software Products Srl 
Codice fiscale: 01003500293 
Richiesta: [#9] Richiesta certificazione nuovo componente. 
UUID: 224b3a1e-95aa-5061-b68c-7e3f7ae55ec4 
CODICE FASCICOLO: 2024-0013137
![image](https://github.com/user-attachments/assets/17ce66ee-c24f-4620-8732-4cc216c09a26)

Grazie per la disponibilità
distinti saluti
 Matteo Rovigatti

**Comment by FedericaSicchiero** [comment]
Buongiorno, controlliamo e vi aggiorniamo.
Noi per gli attributi ci basiamo su quello che ci dice ANAC, se dovessero esserci altri errori simili consigliamo di scrivere anche nella loro repository: https://github.com/anticorruzione/npa/issues

**Comment by FedericaSicchiero** [comment]
Buongiorno, il bug è stato risolto, avete di nuovo l'attributo.
Saluti
