### ISSUE TITLE
Interperabilità collaudo per il comune di monleale restituisce un errore di accesso nella fase di preload .MSG :  User is not authorized to access this resource with an explicit deny

### ISSUE THREAD

**Issue by ideasistemi-dev** [pagopa/pdnd-interop-frontend#916]
Buongiorno

A seguire la descrizione del problema che rileviamo inviando un notifica pe rconto del comune di monleale al collaudo.
Restiamo in attesa di un gentile riscontro.
Cordiali saluti

**Descrivi il bug**
eseguendo la fase  denominata  preload otteniamo il seguente MESSAGGIO  : User is not authorized to access this resource with an explicit deny

**Step per riprodurre il bug**
le operazioni sono eseguito da programma 

**Comportamento atteso**
Che accetti il preload 

**Il codice IPA del tuo ente**
c_f374 

**Data e ora in cui si è riscontrato il problema**
27-08-2024 17:40:21

**Ambiente**
Ineroperabilità Collaudo

**Quali permessi ha la tua utenza?**
 Amministratore (operatore amministrativo)

**Screenshot**
Il problema si presenta durante un uso da programma 

**Note**

**Comment by FedericaSicchiero** [comment]
Buongiorno, potreste allegare degli screen dell'errore o spiegare un po' più approfonditamente in quale momento esatto ricevete l'errore? Grazie

**Comment by FedericaSicchiero** [comment]
Grazie delle specifiche, vi chiedo di contattare il supporto di SEND perchè lato piattaforma non c'è errore e loro riusciranno a spiegarvi meglio il perchè di quel messaggio: enti-send@assistenza.pagopa.it
