### ISSUE TITLE
Utilizzo Certificati wildcard

### ISSUE THREAD

**Issue by markbattle** [pagopa/pdnd-interop-frontend#918]
Buongiorno vorremmo utilizzare un certificato wildcard *.agea.gov.it per rendere disponibili i servizi sul nuovo FQDN che andremo a definire per PDND dell'Agenzia Erogazioni in Agricoltura (pdnd.agea.gov.it).
Ci sono delle limitazioni all'uso del certificato wildcard ?
Grazie Saluti Marco Battaglia

**Comment by FedericaSicchiero** [comment]
Buongiorno, noi sulla piattaforma non richiediamo certificati. Lo volevate utilizzare come erogatore da richiedere ai propri fruitori?

**Comment by markbattle** [comment]
Buongiorno , si volevamo pubblicare un nuovo dominio per erogare i servizi su pdnd senza acquistare un nuovo certificato utilizzando *.agea.gov.it , il certificato wildcard. Sent from my iPhoneOn 6 Sep 2024, at 09:09, Federica Sicchiero ***@***.***> wrote:﻿
Buongiorno, noi sulla piattaforma non richiediamo certificati. Lo volevate utilizzare come erogatore da richiedere ai propri fruitori?

**Comment by FedericaSicchiero** [comment]
Lato PDND noi chiediamo solo di caricare una chiave pubblica a cui far corrispondere la privata per la client assertion e queste chiavi possono essere generate senza dover acquistare altri certificati. Detto questo se volete fare intanto delle prove a creare gli e-service e mandarci gli screen se qualcosa nel processo non dovesse tornare noi siamo a disposizione.
