### ISSUE TITLE
Richiesta informazioni tipologia certificato per integrazione servizi consultazione ANPR

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#92]
Salve,

la presente per richiedere se per l'integrazione con gli E-Service C015 e C024 e quindi per l'implementazione dei profili di sicurezza previsti di seguito: 

1.           Profilo di sicurezza Modl ID_AUTH_CHANNEL_02 (Direct Trust mutual Transport-Level Security) 
2.           Profilo di sicurezza Modl INTEGRITY_REST_01 (Integrity Payload Rest)

Quale tipologia di certificato è necessaria:
- certificati SSL DV (Domain Validated)
- certificati SSL OV (Organization Validated) 
- certificati SSL EV (Extended Validated)

Restiamo in attesa di un cortese feedback.
Grazie della collaborazione.

**Comment by ruggerocastagnola** [comment]
Buongiorno Giovanni, esattamente come #93 credo che anche questa sia per @amollicone1982

**Comment by giovannidenicola** [comment]
Ciao @amollicone1982,

potresti cortesemente quando possibile fornirci un feedback su questa Issue?

Grazie della collaborazione.
Buon lavoro.

**Comment by amollicone1982** [comment]
Accettiamo tutti e tre

**Comment by giovannidenicola** [comment]
Grazie per la risposta, buon lavoro.
