### ISSUE TITLE
Help accesso banca dati ANIS

### ISSUE THREAD

**Issue by torta49** [pagopa/pdnd-interop-frontend#925]
Buongiorno, 

sono Stefano Tortarolo, dsga dell'ITTL nautico san giorgio di genova. Ho iniziato la procedura per consentire al ns istituto di accedere in modo automatico alla verifica dei titoli accademici (rilasciata da Cineca) al fine di soddisfare quanto richiesto dal Ministero dell'Istruzione e del Merito relativamente alla verifica in capo alle singole scuole dei titoli dichiarati dai docenti inseriti nelle graduatorie provinciali. Nell'ambiente Interoperabilità collaudo ho fatto la richiesta di fruizione (approvata), inserito la finalità (approvata) e il client ma ora non so dove devo andare per fare queste verifiche o se devo fare ancora qualcosa..leggo di chiavi crittografate ma mi pare davvero molto complicato da soddisfare anche per un funzionario pubblico qualificato, quale mi ritengo. Cosi fosse chiedo di poter essere supportato telefonicamente da qualcuno che mi spieghi passo passo cosa devo fare. 

Grazie

**Comment by FedericaSicchiero** [comment]
Salve, se ha già associato il client alla finalità può proseguire seguendo i video che può trovare in questa [playlist](https://www.youtube.com/watch?v=w3ynRRMyrxg&list=PLZcD-ZoVxFzi1f2-taSdg7a3d2UQse3_Q&index=10) (parte dal video 9 sull'associazione client-finalità e prosegue con quello sul materiale crittografato).
In aggiunta può trovare maggiori informazioni nella nostra documentazione: https://docs.pagopa.it/interoperabilita-1/manuale-operativo/client-e-materiale-crittografico#ciclo-di-vita-e-operazioni-sui-client
Un saluto

**Comment by torta49** [comment]
Ci siamo fermati al test in Pyton in cui ho questo errore:
python create_client_assertion.py \
  --kid=h3WmVnYN1NBtdDFdVbIqcledmJ_Mhok1VBsndSc_0MU \
  --alg=RS256 \
  --typ=JWT \
  --issuer=bcb73e4e-39e2-4d19-a973-21daa0d95c4a \
  --subject=bcb73e4e-39e2-4d19-a973-21daa0d95c4a \
  --audience=auth.uat.interop.pagopa.it/client-assertion \
  --purposeId=abfbe705-b8ab-41d6-abb6-3acf796788fc \
  --keyPath=C:\Users\utente\Desktop\client_assertion_test\Keys

SyntaxError: invalid decimal literal
viene evidenziato in questa riga
--issuer=bcb73e4e-39e2-4d19-a973-21daa0d95c4a \
il numero 4 della sequenza 4d19
Saluti
