### ISSUE TITLE
Errore voucher anche se finalità è associata al client

### ISSUE THREAD

**Issue by mirko-cr** [pagopa/pdnd-interop-frontend#927]
Salve,

in ambiente collaudo, non riesco ad ottenere un voucher per la fruizione dell' [e-service C018. ](https://selfcare.uat.interop.pagopa.it/ui/it/fruizione/catalogo-e-service/27e42e6e-eb00-4f4a-bf07-3d6a87ef6199/526c07e8-4ce6-477c-b050-5b962f69636d)
Utilizzando la vostra feature di debug della client assertion ricevo il seguente feedback:
"L'id della finalità che hai indicato (purposeId) non corrisponde a nessuna finalità associata al client id che hai indicato". Eppure la finalità è associata al client indicato.
La risposta che ottengo è la seguente:
{
  "correlationId": "6abf1db1-e72a-4804-9857-0037aa266201",
  "errors": [
    {
      "code": "015-0008",
      "detail": "Unable to generate a token for the given request"
    }
  ],
  "status": 400,
  "title": "The request contains bad syntax or cannot be fulfilled.",
  "type": "about:blank"
}

la mia correlation id :
eyJhbGciOiJSUzI1NiIsImtpZCI6IkoxSk1ST2txTzBCMWxhay1ZU0hDdlkzdUNlLVJJWHpuMmxmUzVIWUF6SDAiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoLnVhdC5pbnRlcm9wLnBhZ29wYS5pdC9jbGllbnQtYXNzZXJ0aW9uIiwiZGlnZXN0Ijp7ImFsZyI6IlNIQTI1NiIsInZhbHVlIjoiYmEwNTcwOTVkNjU5ZjUzMTU2YmUyNjdmODk5ODJmZWFlMGE4NmUyNjU1NzM2MGNjOTIzYjIzZTI4ZGMwZTQ3YiJ9LCJleHAiOjE3MjY1OTA3MzgsImlhdCI6MTcyNjUwNDMzOCwiaXNzIjoiYjNkNzlkY2MtNzczZS00MWI0LTg5ODQtZmZlODY2OGNkMGQ2IiwianRpIjoiYWU0ZDdhNTItMWJiNy00ZTQxLWIwNDMtM2I4YjM1MjdlMmQxIiwibmJmIjoxNzI2NTA0MzM4LCJwdXJwb3NlSWQiOiIwNTkxODlkYS1iNWY4LTQ2OTgtYmM3OS1lN2I5YmEyN2JmN2MiLCJzdWIiOiJiM2Q3OWRjYy03NzNlLTQxYjQtODk4NC1mZmU4NjY4Y2QwZDYifQ.FNRZTN6EMPPWAMe1sa43slV_K4_27rTNK7698a3zA12whcIx3pZxQytNjfIppOZrizwqzm_r5RmVajn4NxZhYn9MoBxvIfuP9cjMbzSFRq2IBe8cSFaynyFuFxfcaeAY1HFzfx41Vu1SDvZT0bQAUCqpr7-KjWDL3xEiye_atLgmb-mLm3yHVrVgFXofvNAeeUz2-3OGSSi3QK2cS5k_1r2VF85qwe4104D3kQbtXkew_OpYyH13rgfguSKL-cGppoby4kvjN1Cku4Q75Zq_GKQG2HEf8zSY65umZJtGROit5f9mdY1dRrkIWcAjovNYeFSnL1xeSKa_pJYEI3cm-A

Potete aiutarmi a capire perchè con questa finalità, anche se associata come le altre nello stesso client, non funziona?

Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, con quale ente e su quale e-service e finalità state lavorando? Così facciamo tutti i controlli. Grazie

**Comment by FedericaSicchiero** [comment]
Grazie dei dettagli, facciamo dei controlli e aggiorno la issue. Probabilmente ci sarà un po' di ritardo nella risposta perchè oggi l'ambiente di collaudo è sottoposto a manutenzione e quindi sarà possibile controllare a partire da domani. Un saluto

**Comment by mirko-cr** [comment]
Si va benissimo,
Grazie tante per la disponibilità e la prontezza di risposta!
Allora attendo una vostra risposta.

Buon lavoro e buona giornata!

Il mar 17 set 2024, 09:53 Federica Sicchiero ***@***.***> ha
scritto:

**Comment by FedericaSicchiero** [comment]
Buongiorno, l'ambiente di Collaudo è tornato funzionante. Se riprovate ricevete di nuovo lo stesso errore?

**Comment by mirko-cr** [comment]
Buongiorno Federica,

appena provato e funziona alla perfezione!
Magari questo pomeriggio farò delle prove con lo stesso client e diverse
finalità.
Grazie mille per la velocità!

C'è qualche azione che devo eseguire manualmente per la chiusura del ticket
o della issue?

Il giorno gio 19 set 2024 alle ore 10:20 Federica Sicchiero <
***@***.***> ha scritto:

**Comment by FedericaSicchiero** [comment]
Chiudo io senza problemi, grazie! Noi restiamo a disposizione per qualsiasi evenienza

**Comment by FedericaSicchiero** [comment]
Ciao Mirko,
potete sempre aprire una issue nuova qui su github che praticamente è il contatto diretto col team tecnico.
Grazie
