### ISSUE TITLE
Errore nella creazione finalità 'Pianificazione'

### ISSUE THREAD

**Issue by dpagliari** [pagopa/pdnd-interop-frontend#928]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Non riesco a creare la finalità 'Pianificazione'

**Step per riprodurre il bug**
1. Nuova finalità'
2. Selezione servizio 'PCP Pianificazione'
3. Accettazione analisi del rischio
4. Errore:
Provando a creare la finalità su PDND non riesco a pubblicarla il sistema mi avvisa che la bozza non è più pubblicabile; dice di eliminarla e creare una nuova finalità: ho provato diverse volte ma sempre lo stesso errore

**Comportamento atteso**
Creazione finalità per poter associare il client e avere accesso agli e-service BDNCP in ambiente di collaudo

**Il codice IPA del tuo ente**
sono un'azienda privata gestore e titolare di una piattaforma di approvvigionamento digitale qualificata PCP

**Data e ora in cui si è riscontrato il problema**
es. 13/09/2021 h. 14:30

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
es. Amministratore (operatore amministrativo), Operatore API, Operatore di sicurezza

**Screenshot**

![Immagine 2024-09-13 142822](https://github.com/user-attachments/assets/6d53d269-a545-43b0-96b7-95bfd10eaa5a)

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Buongiorno, qual è il vostro ente? Così facciamo dei controlli più approfonditi. Grazie

**Comment by dpagliari** [comment]
Buongiorno,

siamo Net4market

**Comment by dpagliari** [comment]
> Buongiorno,
> 
> siamo Net4market

Il nostro problema non è nell'ottenimento del Voucher di autorizzazione ma ancora prima, nella sottoscrizione dei servizi in ambiente di collaudo. Ho provato stamattina ma l'ambiente è down per manutenzione programmata. Appena ritorna disponibile riprovo
Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, l'ambiente di Collaudo è tornato disponibile. Potreste riprovare e vedere se ricevete ancora errore? Grazie

**Comment by dpagliari** [comment]
Buongiorno,

ho appena provato e ho lo stesso identico errore. Quando creo una nuova finalità non si riesce a pubblicare.
Lo screenshot dell'errore è sempre il medesimo

Avremmo urgenza di risolvere per poter fare i test dello sviluppo nell'ambiente di collaudo

**Comment by dpagliari** [comment]
Buongiorno,

ho rifatto tutto dall'inizio eliminando anche la richiesta e ora sono riuscito
Grazie
