### ISSUE TITLE
Voucher ottenuto ma fallimento autorizzazione

### ISSUE THREAD

**Issue by giovanni-caprilli** [pagopa/pdnd-interop-frontend#929]
Salve,
abbiamo un problema relativo al prodotto Interoperabilità in ambiente di produzione.

Riusciamo a generare correttamente un voucher che poi inseriamo nell'apposito header della richiesta verso l'e-service PCP – Comunica appalto erogato da ANAC.
Riguardo all'e-service abbiamo sia la richiesta di fruizione che il relativo client e finalità attivi e collegati fra loro.
La chiamata all'e-service fallisce con un errore 403 Authorization failed.

Come prima richiesta di assistenza ci siamo rivolti al supporto dell'e-service che ci ha fornito il dettaglio dell'errore:
Eccezione ERROR con codice [GOVWAY-1352] - EccezioneValidazioneProtocollo: Applicativo Mittente non identificato

Ci è stato fatto presente che l'errore viene rilevato dal gateway di perimetro che agisce prima della verifica del JWS, e che quindi è necessario comunicare con l'assistenza di PDND per avere maggiori dettagli.

Riporto di seguito i dati essenziali delle ultime richieste fatte, quella per richiedere il voucher e quella verso l'e-service.
In caso abbiate necessità di maggiori dettagli sui dati inviati fatemi sapere.

**Richiesta voucher a PDND**
**Data e ora della richiesta:** 2024-09-16 14:41:16
**Url della chiamata:** https://auth.interop.pagopa.it/token.oauth2
**Dati della client_assertion**
{
  "typ": "JWT",
  "kid": [ricavato dall'area selfcare],
  "alg": "RS256"
}
{
  "iss": [clientId ricavato dall'area selfcare],
  "sub": [clientId ricavato dall'area selfcare],
  "aud": "auth.interop.pagopa.it/client-assertion",
  "jti": "17b128ce-74be-ecd7-555c-907f234536b5",
  "iat": 1726490475,
  "exp": 1726491075,
  "nbf": 1726490475,
  "purposeId": [ricavato dall'area selfcare],
  "digest": {
    "alg": "SHA256",
    "value": "abe596fa1c761d94f490574ebff780fdd3f2e48d11c9ce85c9b22c7a7d914941"
  }
}
Abbiamo verificato che l'hash SHA256 inserito nel digest è corretto.

**Chiamata all'e-service PCP - Comunica appalto**
**Data e ora della richiesta:** 2024-09-16 14:41:16
**Url della chiamata:** https://apigw.anticorruzione.it/modi/rest/ComunicaAppalto/v2/crea-appalto
**GovWay-Transaction-ID:** c7f54aba-7428-11ef-852e-005056844885
**Errore:** 403 Authorization failed
Da quel che mi è stato detto i dati inviati nel JWS inserito come header Agid-JWT-TrackingEvidence non dovrebbero essere rilevanti. In caso siano necessari fatemelo sapere così da fornirveli.

Avete modo di darmi maggiori dettagli su cosa sta esattamente causando il fallimento dell'autorizzazione?

Grazie
Giovanni Caprilli

**Comment by FedericaSicchiero** [comment]
Buongiorno, in questo caso vi chiedo di sentire direttamente ANAC nella loro repository: https://github.com/anticorruzione/npa/issues perchè una volta staccato il token vuol dire che lato piattaforma piattaforma funziona tutto e il blocco avviene lato erogatore. Un saluto

**Comment by giovanni-caprilli** [comment]
Ok, provo a sentire, ma come già indicato era stato il supporto di ANAC stessa ad indirizzarmi presso questo canale di assistenza.
Giovanni Caprilli

**Comment by FedericaSicchiero** [comment]
Facciamo degli ulteriori controlli anche lato nostro e aggiorno la issue appena ho novità. Grazie

**Comment by giovanni-caprilli** [comment]
Grazie molte.
Giovanni Caprilli

**Comment by giovanni-caprilli** [comment]
Salve,
avendo letto la issue [928](https://github.com/pagopa/pdnd-interop-frontend/issues/928) aggiungo queste informazioni in caso dovessero essere in qualche modo legate al problema principale segnalato.

Abbiamo riscontrato anche noi lo stesso problema, in ambiente di produzione, che ci impediva di pubblicare le richieste di finalità inserite in bozza.
Avendo fretta di procedere, a seguito di una ricerca delle issue di questo repository, abbiamo seguito quanto segnalato [qui](https://github.com/pagopa/pdnd-interop-frontend/issues/905#issuecomment-2262657931).
Questo ci ha permesso di procedere ed ottenere poi l'attivazione delle finalità da parte dell'erogatore.

L'area selfcare dove si è presentato il problema è relativo alla società Kinetica S.r.l. che è censita come gestore della piattaforma del CNAPPC (e del relativo componente).

Spero possa risultare utile
Un saluto
Giovanni Caprilli

**Comment by giovanni-caprilli** [comment]
Abbiamo infine verificato che era necessario da parte nostra comunicare ad ANAC il clientId affinché venisse autorizzato dai loro sistemi. Era quindi una configurazione lato e-service.
Grazie
Giovanni Caprilli

**Comment by FedericaSicchiero** [comment]
Grazie per il collegamento alla altra issue e l'analisi del bug, lo stiamo lavorando per evitare che si ripresenti in futuro. Un saluto
