### ISSUE TITLE
Impossibilità di aggiungere membri al Client e-service

### ISSUE THREAD

**Issue by gilliale** [pagopa/pdnd-interop-frontend#931]
Buongiorno,
segnalo che per l'Ente Comune di Trento (codice IPA 00355870221  )non è più possibile assegnare utenti ai nuovi client creati, ad eccezione del solo utente amministratore creatore del client e-service; in passato confermo che si riusciva ad aggiungere anche gli altri utenti presenti in piattaforma.

Chiedo cortese riscontro ed eventuali istruzioni per poter procedere

grazie, 
cordiali saluti

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione, stiamo già lavorando al problema e aggiorno la issue appena ci sono novità. Grazie

**Comment by giovannidicaro** [comment]
Anche il Comune di Caltagirone ha riscontrato lo stesso problema.

**Comment by sis-info-pn** [comment]
Anche il Comune di Pordenone riscontra la stessa anomalia. Grazie.

**Comment by FedericaSicchiero** [comment]
Grazie a tutti delle segnalazioni, ci stiamo lavorando per risolverlo il prima possibile.

**Comment by FedericaSicchiero** [comment]
Buongiorno a tutti, abbiamo risolto questo bug. Un saluto
