### ISSUE TITLE
Finalità SOSPESA nonostante richiesta di ri-attivazione.

### ISSUE THREAD

**Issue by pierluigiComuneMSS** [pagopa/pdnd-interop-frontend#933]
Buongiorno,
sono passato dalla versione 2.3 alla versione 10 del servizio SEND.
Dopo questo passaggio la chiamata per la generazione dei Voucher si è bloccata non funzionando più, nonostante fosse ancora associato il client correttamente e fosse nello stato di "attivo".
Facendo il DEBUG con lo strumento messo a disposizione, risultava in errore con motivazione che il client non era autorizzato alla finalità benché nel pannello lo fosse invece. 
In ultima analisi ho quindi provato a "sospendere" la finalità per poi riattivarla, nella speranza di riattivare l'associazione, ma invece ho ottenuto che adesso risulta SOSPESA e ogni richiesta di ATTIVAZIONE sembra andare in pubblicazione, ma la finalità rimane sempre SOSPESA .

CODICE IPA: c_f628

Data e ora in cui si è riscontrato il problema**
DAL 16.09.2024

Ambiente
Produzione

Quali permessi ha la tua utenza?
Amministratore

Screenshot
![image](https://github.com/user-attachments/assets/c474020b-2ae8-47d3-81ff-53b2793e6c06)

![image](https://github.com/user-attachments/assets/e723c7cd-6302-45ad-a285-e597c934780d)

![image](https://github.com/user-attachments/assets/e4c10663-7fd5-4aa3-9b87-a547e52b7433)

Grazie

Pier Luigi Tavanti

**Comment by FedericaSicchiero** [comment]
Buonasera, vi chiedo di scrivere direttamente a pn-supporto-enti@pagopa.it in modo che possano darvi un aiuto più veloce e a sbloccare la situazione. Grazie

**Comment by pierluigiComuneMSS** [comment]
Ahahahaha

Sono loro che mi hanno detto di aprire un ticket su github

… che faccio ?


Tavanti Pier Luigi

Il giorno 18 set 2024, alle ore 16:07, Federica Sicchiero ***@***.***> ha scritto:

﻿

Buonasera, vi chiedo di scrivere direttamente a ***@***.******@***.***> in modo che possano darvi un aiuto più veloce e a sbloccare la situazione. Grazie
