### ISSUE TITLE
Error: Unable to generate a token for the given request

### ISSUE THREAD

**Issue by Martimarina** [pagopa/pdnd-interop-frontend#935]
**Descrivi il bug**
La risposta di PDND è "Error: Unable to generate a token for the given request"

**Step per riprodurre il bug**
Il PT SEND (noi di Progetti e Soluzioni) abbiamo ottenuto i parametri di configurazione dal Comune di Modena. 
Abbiamo creato la client assertion
"eyJhbGciOiJSUzI1NiIsImtpZCI6IkFPWEJYcTViUXZPakgyeGFocWx3dExsWDNEZU9vN0RVOXViZURqSTNiZWsiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI3YzFjNzI3MC0wZTM0LTQzODYtODE2Mi0wNGNlMDEzYzcxYmEiLCJzdWIiOiI3YzFjNzI3MC0wZTM0LTQzODYtODE2Mi0wNGNlMDEzYzcxYmEiLCJhdWQiOiJhdXRoLmludGVyb3AucGFnb3BhLml0L2NsaWVudC1hc3NlcnRpb24iLCJwdXJwb3NlSWQiOiI5NjNjMDQ3NS1kMWJhLTQ5MTYtYmFkZi1kNjZlNjI0NDkyZjUiLCJqdGkiOiI4NzUxNTA3OS03MjE4LTRmMTEtOGZjNS05MjA5NTNkMzdiOWUiLCJpYXQiOjE3MjY0ODQyMDksImV4cCI6MTcyOTA3NjIwOX0.Ij4zvL3OEkxoHh5S-suot4zH-jEHvHxoLLhwCsJKxj-klbEirlkBUMLkkPH6GveDgFoROD1oHUWhu1JB4YtZKkuXoZ9YvLNrGNhfAKxdfM_UTRSjWu0pc9kYG8YSqfvE58x-eFxZ8FQYM-YwPoEUOCmWjibEPJBwNRpbHeF-BwEZFFD4sm0gt8q9be04iSdgXCXV6A7Y6MnpBkT6uR0w7o34C12gv2ScwQpRCynAbdB9q-OZrtxAAJXy-z6jvBGbRxSbsqtaHZgYAV3bBilizBHTPWzed2IlIlYhZm4wGF5w78I_knGJKpO--0s7g_VS3ajtaUGuOkNHqCpv7pit6Q"

La cui decodifica dell' header è:
{

  "alg": "RS256",

  "kid": "AOXBXq5bQvOjH2xahqlwtLlX3DeOo7DU9ubeDjI3bek",

  "typ": "JWT"

}

Mentre quella del payload è:
{

  "iss": "7c1c7270-0e34-4386-8162-04ce013c71ba",

  "sub": "7c1c7270-0e34-4386-8162-04ce013c71ba",

  "aud": "[auth.interop.pagopa.it/client-assertion](http://auth.interop.pagopa.it/client-assertion)",

  "purposeId": "963c0475-d1ba-4916-badf-d66e624492f5",

  "jti": "87515079-7218-4f11-8fc5-920953d37b9e",

"iat": 1726484209,

"exp": 1729076209

}
La risposta di PDND è però "Error: Unable to generate a token for the given request"

**Comportamento atteso**
L’invio della client assertion a PDND permette di ottenere il token.

**Il codice IPA del tuo ente**
c_f257

**Data e ora in cui si è riscontrato il problema**
16/09/2024 

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Note**
La mia mail di riferimento è m.marti@progettiesoluzioni.it

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by Martimarina** [comment]
Intendi questo tool, in allegato?

Selfcare>interoperabilità>produzione>Fruizione>debug client assertion
al link https://selfcare.interop.pagopa.it/ui/it/fruizione/debug-voucher

![screen](https://github.com/user-attachments/assets/7c5ebecb-e33a-4c34-b8f7-5cd4611bfdbe)

Grazie

**Comment by FedericaSicchiero** [comment]
Si esatto proprio questo, dovrebbe aiutarvi a fare una prima scrematura di eventuali errori

**Comment by FedericaSicchiero** [comment]
Chiudo la issue, se servono altri chiarimenti è possibile riaprirla in seguito
