### ISSUE TITLE
La client assertion è valida ma la richiesta di fruizione per la quale stai richiedendo il voucher non è attiva

### ISSUE THREAD

**Issue by pierluigiComuneMSS** [pagopa/pdnd-interop-frontend#937]
Nuova finalità ATTIVA
Nuovo client associato alla finalità ed ATTIVO

Se faccio il DEBUG ASSERTION ottengo tutti i punti validi tranne l'ultimo dove ottengo l'errore in oggetto.

Codice IPA
f_628

Data e ora del tentativo
19/09/2024 h. 15:11

Ambiente
Produzione

CLIENT ID
84f4054c-60d4-412a-8e84-1dc6dcfa322b

correlationId
30513430-7dbf-4823-97cc-788517de76ce

purposeId
1baae00b-50d4-4099-8229-1f6caf7ac277

Grazie

Pier Luigi Tavanti

**Comment by FedericaSicchiero** [comment]
Salve, controlliamo e aggiorno la issue. Grazie

**Comment by pierluigiComuneMSS** [comment]
Buongiorno, 
nel frattempo che indagate sulla motivazione non sarebbe possibile retrocedere le nostre finalità alla vecchia 3 funzionante ? 
La chiave è utilizzata anche dal processo sincrono di aggiornamento delle spese di notifica, ho degli avvisi PagoPA già passati e pagati dai contribuenti senza il ricalcolo delle spese di notifica, stiamo rimettendo le spese di notifica in questo momento. Grazie !

**Comment by FedericaSicchiero** [comment]
Buongiorno, purtroppo una volta aggiornata la finalità non si può tornare indietro, così come se si aggiornano le richieste di fruizione quelle vecchie diventano obsolete e vengono archiviate automaticamente. Abbiamo trovato il bug e ci stiamo lavorando quindi a breve dovrebbe essere tutto risolto.

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo rilasciato il fix per questo bug. Potete provare e vedere se lato vostro ora funziona tutto? Grazie

**Comment by pierluigiComuneMSS** [comment]
Si avevo già visto ieri sera intorno alle 20.00 è ripartito tutto … grazie !

Pier Luigi


Da: Federica Sicchiero ***@***.***>
Inviato: mercoledì 25 settembre 2024 08:58
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Pier Luigi Tavanti ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] La client assertion è valida ma la richiesta di fruizione per la quale stai richiedendo il voucher non è attiva (Issue #937)


Buongiorno, abbiamo rilasciato il fix per questo bug. Potete provare e vedere se lato vostro ora funziona tutto? Grazie
