### ISSUE TITLE
La client assertion è valida ma ....

### ISSUE THREAD

**Issue by Davide-Almaviva** [pagopa/pdnd-interop-frontend#939]
Errore in fase di generazione del Voucher. Ho provato sia da cURL che da Postman, ma da sempre errore 400.
Utilizzando la modalità "_Debug client assertion_", vedo tutto ok tranne lo step "**4. Verifica degli stati delle componenti su PDND Interoperabilità**", dove ritrovo i seguenti errori:
- La client assertion è valida ma la versione di e-service per la quale stai richiedendo il voucher non è attiva
- La client assertion è valida ma la richiesta di fruizione per la quale stai richiedendo il voucher non è attiva

cosa però che non sembra corrispondere in quanto:
- Nuova finalità ATTIVA
- Nuovo client associato alla finalità ed ATTIVO
- Fruizione associata ad una versione ATTIVA del servizio

Di seguito le info richieste per un check dell'anomalia.
Grazie.

--------
Codice IPA:
r_toscan

Data e ora del tentativo:
20/09/2024 11:32AM CEST  (+ diverse chiamate di test dalle 10:30AM in avanti)

Ambiente:
Collaudo

client_id:
381b309a-e2eb-4749-b012-b56b5e98c11f

correlationId:
873a3388-9e89-4e87-a042-fd68fcc38c40

purposeId:
c5b6f964-0fa0-4301-b169-5c42a745efbd

**Comment by FedericaSicchiero** [comment]
Buongiorno, grazie della segnalazione, ci stiamo lavorando e aggiorno la issue appena ho novità. Un saluto

**Comment by Davide-Almaviva** [comment]
Buondì,

Sono emerse novità rispetto alla segnalazione di anomalia in fase di generazione del Voucher ?

E' un problema di utilizzo dell'assertion jwt verso il servizio di Voucher ? O un bug su quest'ultimo ?
Oppure risultano a sistema delle configurazioni mancanti causa portale PDND ?

Grazie per il supporto.
Saluti.

**Comment by FedericaSicchiero** [comment]
Buongiorno, si tratta di un bug che stiamo seguendo e per cui rilasceremo un fix in settimana e che al momento dipende da noi. Appena ho novità aggiorno la issue. Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo rilasciato il fix per questo bug. Potete provare e vedere se lato vostro ora funziona tutto? Grazie

**Comment by Davide-Almaviva** [comment]
Buondì,

Generando una nuova Client-Assertion in ambiente di Collaudo per la finalità prevista, tale assertion jwt viene ora validata correttamente sia dal tool di debug del portale sia dal servizio di rilascio access-token che ora da 200 OK in chiamata.

Grazie per il supporto.
Saluti.
