### ISSUE TITLE
Errore in fruizione servizio aggiornato

### ISSUE THREAD

**Issue by rglauco** [pagopa/pdnd-interop-frontend#942]
In aggiunta a https://github.com/pagopa/pdnd-interop-frontend/issues/939 sto sperimentando l'aggiornamento di un e-service in fase collaudo. Ho aggiornato la versione del servizio come erogatore e successivamente, come fruitore, ho attivato la versione nuova, associando al client-eservice una nuova finalita', in seguito attivata lato erogatore. Io vedo tutto attivo (richiesta, finalita' ed e-service).

In sede di debug della client_assertion ottengo due errori:

- La client assertion è valida ma la versione di e-service per la quale stai richiedendo il voucher non è attiva

- La client assertion è valida ma la richiesta di fruizione per la quale stai richiedendo il voucher non è attiva

**codice IPA**
c_h022

**Ambiente**
Collaudo

**client_id**
Es. `8ff5ca73-9523-4721-8efd-eaed8dbd6b331`

**purposeId (solo per i client e-service)**
6d48d936-04ef-40b5-a455-59c2aa67dbfb

organizationId (erogatore e fruitore) 
206fc67b-979b-444b-849f-c94016523a22

**Comment by FedericaSicchiero** [comment]
Grazie anche di questa segnalazione, abbiamo un bug aperto sul tema che stiamo seguendo e fixando

**Comment by rglauco** [comment]
Buongiorno ho verificato e funziona, grazie mille!
