### ISSUE TITLE
Interoperabilità UAT

### ISSUE THREAD

**Issue by kampusses** [pagopa/pdnd-interop-frontend#948]
Buongiorno.
Non riesco ad utilizzare intropoerabilità in ambiente di collauto per il comune di SOVERATO.
Solitamente, si apre un popup dove mi viene chiesto in quale ambiente voglio operare. Nel caso di Soverato, cliccando sulla scheda “Interoperabilità”, mi porta direttamente in produzione.

**Il codice IPA del tuo ente**
c_i872 

**Data e ora in cui si è riscontrato il problema**
24/09/2024

**Comment by FedericaSicchiero** [comment]
Buongiorno, controlliamo e aggiorno la issue appena ho novità.

**Comment by FedericaSicchiero** [comment]
Con quale utenza state provando ad entrare? Nome, cognome e codice fiscale

**Comment by kampusses** [comment]
L'utenza è quella a nome di CAMPOREALE VINCENZO (C.F.: CMPVCN72E18A883L)

**Comment by kampusses** [comment]
Segnalo che, in selfcare, non avevano abilitato la mia utenza per l'ambiente di test.
Adesso riesco ad entrare in UAT.
Mi scuso per aver aperto il ticket senza aver eseguito una verifica preventiva.

**Comment by FedericaSicchiero** [comment]
Nessun problema! Un saluto
