### ISSUE TITLE
Impossibile caricare l'OpenAPI

### ISSUE THREAD

**Issue by Anna1139** [pagopa/pdnd-interop-frontend#949]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Nel momento in cui vado a caricare l'OpenAPI per il servizio che sto creando (Dati storici del cittadino), mi esce il seguente messaggio di errore: "Non è stato possibile caricare il documento. Assicurati di aver caricato il documento corretto. Per favore, riprova! Attenzione: il documento non può contenere la stringa "localhost". 
L'OpenAPI è lo stesso che ho caricato per tutti i comuni configurati finora.

**Step per riprodurre il bug**
Erogazione > I tuoi e-service > Crea nuovo 
Nell'ultima sezione (n.4) "Documentazione di versione", carico L'OpenAPI e clicco su "carica", esce il seguente errore:
 "Non è stato possibile caricare il documento. Assicurati di aver caricato il documento corretto. Per favore, riprova! Attenzione: il documento non può contenere la stringa "localhost"

**Comportamento atteso**
Mi aspetterei di pubblicare con successo il servizio.

**Il codice IPA del tuo ente**
c_a739

**Data e ora in cui si è riscontrato il problema**
25/09/2024 09.35

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
L'operatore con cui stavo eseguendo la configurazione è amministratore dell'interoperabilità

**Screenshot**
![Immagine 2024-09-25 124810](https://github.com/user-attachments/assets/7863f014-6d7a-4ffd-b123-3f17fcfdb6d0)

**Comment by FedericaSicchiero** [comment]
Salve, potete riprovare? Abbiamo sistemato alcune impostazioni

**Comment by Anna1139** [comment]
Funziona, grazie.
