### ISSUE TITLE
Impossibile caricare file YAML e documentazione PDF durante la creazione di un nuovo e-service nell'ambiente di interoperabilità in produzione

### ISSUE THREAD

**Issue by Patrick140795** [pagopa/pdnd-interop-frontend#951]
Salve,
durante il caricamento di un nuovo e-service per l'ente con codice IPA c_c996, riscontro difficoltà sia nell'upload del file OpenAPI in formato YAML, sia della documentazione in formato PDF. In entrambi i casi appare l'alert:
"Non è stato possibile caricare il documento. Assicurati di aver caricato il documento corretto. Per favore, riprova! Attenzione: il documento non può contenere la stringa 'localhost'."
Ho verificato i file e non dovrebbero esserci incongruenze, poiché sono gli stessi che ho utilizzato per altri e-service di diversi enti senza problemi.

**Step per riprodurre il bug**
 Vai su "Interoperabilità produzione - Erogazione - I tuoi e-service" ultima tab di Caricamento documentazione
[Manuale Integrazione Albo V1.pdf](https://github.com/user-attachments/files/17131470/Manuale.Integrazione.Albo.V1.pdf)

**Comportamento atteso**
Caricamento API come di consueto

**Il codice IPA del tuo ente**
c_c996

**Data e ora in cui si è riscontrato il problema**
es. 25/09/2024 h. 15:10

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
 Operatore API, Operatore di sicurezza

**Screenshot**
![image](https://github.com/user-attachments/assets/e638df85-afe6-493e-b99e-ac9d0414de53)
![image](https://github.com/user-attachments/assets/c90c450f-d84b-4ac5-b726-e80c22943926)

[Manuale Integrazione Albo V1.pdf](https://github.com/user-attachments/files/17131484/Manuale.Integrazione.Albo.V1.pdf)

**Comment by FedericaSicchiero** [comment]
Salve, potete riprovare? Abbiamo sistemato alcune impostazioni

**Comment by Patrick140795** [comment]
Perfetto, sono riuscito a caricare il servizio senza problemi. Grazie mille!
