### ISSUE TITLE
Errore nell'interrogazione della vostra “api-gateway”

### ISSUE THREAD

**Issue by Anna1139** [pagopa/pdnd-interop-frontend#952]
Nell’interrogare la vostra “api-gateway”
[https://selfcare.interop.pagopa.it/api-gateway/1.0/keys/{kid}](https://selfcare.interop.pagopa.it/api-gateway/1.0/keys/%7bkid%7d)
per recuperare la chiave pubblica del fruitore mediante Kid, durante le operazioni di auto testing post esposizione di un nostro servizio, otteniamo il seguente messaggio di errore:

{"message":"'eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJvcmdhbml6YXRpb25JZCI6IjE2ZWQ2OWY1LTRmM2QtNDI3ZS1iNzU1LTk5ZjMwMDdjMWZmYSIsImF1ZCI6ImludGVyb3AucGFnb3BhLml0L20ybSIsInN1YiI6ImY1YzcwMzE4LTc3YzktNGIxOC1iNzZkLTNkZmY5ODk2MjI2YiIsInJvbGUiOiJtMm0iLCJuYmYiOjE3MjcyNzE5ODIsImlzcyI6ImludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzI3MjcyNTgyLCJpYXQiOjE3MjcyNzE5ODIsImNsaWVudF9pZCI6ImY1YzcwMzE4LTc3YzktNGIxOC1iNzZkLTNkZmY5ODk2MjI2YiIsImp0aSI6IjYzMjkwZjM0LTBjMGQtNDY2Mi05ZDllLWRmZjZmMjY3NDYwMCJ9.pgiaCFxgVqn07GdRnLbrTiplH76pdb41Fwjqh9-5P1uggfLHZNLpRtjTQU9wKtU7IMSXMUNowoS3HmvwryKJYYKeYRXsxVtwAxAkU1qtEOD504REXCqAnbm_r6Xbn9Xi0eGqwS9dgvUGdk6sYwMW8XIyaZb1jSy_wxx4ykVOWP-Y2RdNV3HeWsrWu4trT-nvPbvhSW2zAf7JrMaNX5ndtspcanwuxfCEh9fyodIJSA_GVTt4czri3a1aOg9Yc5bT9W7rmllTwocmKW2e7zvJEN6xQGy88evJGt0Av0g-hf_6BDo0HtETiTOEa7_ms2jzJRfPPPpQTfTNe632_SLV2Q' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJvcmdhbml6YXRpb25JZCI6IjE2ZWQ2OWY1LTRmM2QtNDI3ZS1iNzU1LTk5ZjMwMDdjMWZmYSIsImF1ZCI6ImludGVyb3AucGFnb3BhLml0L20ybSIsInN1YiI6ImY1YzcwMzE4LTc3YzktNGIxOC1iNzZkLTNkZmY5ODk2MjI2YiIsInJvbGUiOiJtMm0iLCJuYmYiOjE3MjcyNzE5ODIsImlzcyI6ImludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzI3MjcyNTgyLCJpYXQiOjE3MjcyNzE5ODIsImNsaWVudF9pZCI6ImY1YzcwMzE4LTc3YzktNGIxOC1iNzZkLTNkZmY5ODk2MjI2YiIsImp0aSI6IjYzMjkwZjM0LTBjMGQtNDY2Mi05ZDllLWRmZjZmMjY3NDYwMCJ9.pgiaCFxgVqn07GdRnLbrTiplH76pdb41Fwjqh9-5P1uggfLHZNLpRtjTQU9wKtU7IMSXMUNowoS3HmvwryKJYYKeYRXsxVtwAxAkU1qtEOD504REXCqAnbm_r6Xbn9Xi0eGqwS9dgvUGdk6sYwMW8XIyaZb1jSy_wxx4ykVOWP-Y2RdNV3HeWsrWu4trT-nvPbvhSW2zAf7JrMaNX5ndtspcanwuxfCEh9fyodIJSA_GVTt4czri3a1aOg9Yc5bT9W7rmllTwocmKW2e7zvJEN6xQGy88evJGt0Av0g-hf_6BDo0HtETiTOEa7_ms2jzJRfPPPpQTfTNe632_SLV2Q'."}

L’ID del fruitore è passato è il seguente:
ZLATPCrRpk7MC9_FeCk6OYnk0bO0qv6MNprZtzm-v3w

Abbiamo richiesto un voucher di fruizione API Interop che viene restituito da PDND correttamente ed è proprio quello sopra; Questo voucher viene poi allegato alla chiamata verso il vostro “api-gateway” nell’header della richiesta in questo modo:

Authorization: Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6IjE5OWQwOGQyLTk5NzEtNDk3OS1hNzhkLWU2ZjdhNTQ0ZjI5NiJ9.eyJvcmdhbml6YXRpb25JZCI6IjE2ZWQ2OWY1LTRmM2QtNDI3ZS1iNzU1LTk5ZjMwMDdjMWZmYSIsImF1ZCI6ImludGVyb3AucGFnb3BhLml0L20ybSIsInN1YiI6ImY1YzcwMzE4LTc3YzktNGIxOC1iNzZkLTNkZmY5ODk2MjI2YiIsInJvbGUiOiJtMm0iLCJuYmYiOjE3MjcyNzE5ODIsImlzcyI6ImludGVyb3AucGFnb3BhLml0IiwiZXhwIjoxNzI3MjcyNTgyLCJpYXQiOjE3MjcyNzE5ODIsImNsaWVudF9pZCI6ImY1YzcwMzE4LTc3YzktNGIxOC1iNzZkLTNkZmY5ODk2MjI2YiIsImp0aSI6IjYzMjkwZjM0LTBjMGQtNDY2Mi05ZDllLWRmZjZmMjY3NDYwMCJ9.pgiaCFxgVqn07GdRnLbrTiplH76pdb41Fwjqh9-5P1uggfLHZNLpRtjTQU9wKtU7IMSXMUNowoS3HmvwryKJYYKeYRXsxVtwAxAkU1qtEOD504REXCqAnbm_r6Xbn9Xi0eGqwS9dgvUGdk6sYwMW8XIyaZb1jSy_wxx4ykVOWP-Y2RdNV3HeWsrWu4trT-nvPbvhSW2zAf7JrMaNX5ndtspcanwuxfCEh9fyodIJSA_GVTt4czri3a1aOg9Yc5bT9W7rmllTwocmKW2e7zvJEN6xQGy88evJGt0Av0g-hf_6BDo0HtETiTOEa7_ms2jzJRfPPPpQTfTNe632_SLV2Q

Dovrebbe essere formalmente corretto, quindi non è ben chiara la natura dell’errore. Aggiungo che fino a 2 giorni fa, come da ormai diversi mesi, tale chiamata funzionava senza problemi. Avete per caso fatto delle modifiche o sussiste un disservizio temporaneo? Grazie

**Comment by FedericaSicchiero** [comment]
Sono cambiate le KID solo per l'ambiente di Collaudo, mentre per il resto non è cambiato nulla. Avete provato ad usare il tool di debug del voucher presente in piattaforma?

**Comment by Anna1139** [comment]
sì

**Comment by Anna1139** [comment]
Abbiamo fatto una prova in ambiente di produzione con il nuovo link e sembra che funzioni. Supposto che in ambiente di collaudo il link corrispondente sia:
https://api.uat.interop.pagopa.it/api-gateway/1.0

abbiamo ripetuto test anche in ambiente di collaudo ma in questo caso riceviamo messaggio di errore “Forbidden”. Alcune informazioni utili:

-	Abbiamo chiesto voucher API interop di un client configurato in collaudo e ci è stato generato correttamente questo voucher
eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJvcmdhbml6YXRpb25JZCI6IjM5NmNkOWMxLTI0ZDAtNGQ5NS05ZjYwLTA3NmRhYTA0MzkzYyIsImF1ZCI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdC9tMm0iLCJzdWIiOiI1NTU1YzhlZC03ZDVmLTQ2NWItODNmYS0wNzdiODIxNmFmNzMiLCJyb2xlIjoibTJtIiwibmJmIjoxNzI3MzM3NDAzLCJpc3MiOiJ1YXQuaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MjczMzgwMDMsImlhdCI6MTcyNzMzNzQwMywiY2xpZW50X2lkIjoiNTU1NWM4ZWQtN2Q1Zi00NjViLTgzZmEtMDc3YjgyMTZhZjczIiwianRpIjoiODJhYzRlMjUtYzA5MS00NjUzLWIyY2MtYmFiZTk0MmQxZDU5In0.AVyzistli52s-AQ9bz9I1js0PLzwyVjGtYKCJHmlEE43SqXh4VkbOk7KPknouRVHpz5bNqgLzyexUaCmzTsCv0eA45f3lRjdnGo9l2eLQ7lq8VTXLkLdA_9erwPLxwVOUtc31K3hooYbamS6ZQXZYxJyemZhEQv4DR4MUMEXgLzts_2oBJt2lTs7tmtSLdvhKML9ljcRVS6nY__FK8QXJgkXnavDFXpzYR4VFBeH1P0iXJElazbqRskRm0bQFFOhsdJyH_GNIIjbkX7Ej9KuK-X4olFLMKd1qVLLRjJV1wUpSmpeE_rw1hvnNp-xtyc0l69CUr0S-_Wm4nq6r7QMuw
-	Abbiamo allegato voucher di cui sopra chiamando con metodo GET 
https://api.uat.interop.pagopa.it/api-gateway/1.0/keys/o5uFfYK4rT8ryjg_M1uDx-vTtgYd_iLruXqUEjQm-EI

Ottenendo l’errore indicato sopra. Vorremmo anche segnalare che dal selfcare, entrando su un client API interop, al termine della configurazione appare bottone per scaricare il descrittore YAML delle API gateway ma non funziona. Invece al contrario in produzione fa scaricare il descrittore YAML correttamente.
