### ISSUE TITLE
Errore nell'interrogazione della vostra “api-gateway” #952

### ISSUE THREAD

**Issue by Anna1139** [pagopa/pdnd-interop-frontend#954]
In riferimento alla segnalazione "Errore nell'interrogazione della vostra “api-gateway” #952":

Abbiamo fatto una prova in ambiente di produzione con il nuovo link e sembra che funzioni. Supposto che in ambiente di collaudo il link corrispondente sia:

https://api.uat.interop.pagopa.it/api-gateway/1.0

abbiamo ripetuto test anche in ambiente di collaudo ma in questo caso riceviamo messaggio di errore “Forbidden”. 
Alcune informazioni utili:

-	Abbiamo chiesto voucher API interop di un client configurato in collaudo e ci è stato generato correttamente questo voucher

eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJvcmdhbml6YXRpb25JZCI6IjM5NmNkOWMxLTI0ZDAtNGQ5NS05ZjYwLTA3NmRhYTA0MzkzYyIsImF1ZCI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdC9tMm0iLCJzdWIiOiI1NTU1YzhlZC03ZDVmLTQ2NWItODNmYS0wNzdiODIxNmFmNzMiLCJyb2xlIjoibTJtIiwibmJmIjoxNzI3MzM3NDAzLCJpc3MiOiJ1YXQuaW50ZXJvcC5wYWdvcGEuaXQiLCJleHAiOjE3MjczMzgwMDMsImlhdCI6MTcyNzMzNzQwMywiY2xpZW50X2lkIjoiNTU1NWM4ZWQtN2Q1Zi00NjViLTgzZmEtMDc3YjgyMTZhZjczIiwianRpIjoiODJhYzRlMjUtYzA5MS00NjUzLWIyY2MtYmFiZTk0MmQxZDU5In0.AVyzistli52s-AQ9bz9I1js0PLzwyVjGtYKCJHmlEE43SqXh4VkbOk7KPknouRVHpz5bNqgLzyexUaCmzTsCv0eA45f3lRjdnGo9l2eLQ7lq8VTXLkLdA_9erwPLxwVOUtc31K3hooYbamS6ZQXZYxJyemZhEQv4DR4MUMEXgLzts_2oBJt2lTs7tmtSLdvhKML9ljcRVS6nY__FK8QXJgkXnavDFXpzYR4VFBeH1P0iXJElazbqRskRm0bQFFOhsdJyH_GNIIjbkX7Ej9KuK-X4olFLMKd1qVLLRjJV1wUpSmpeE_rw1hvnNp-xtyc0l69CUr0S-_Wm4nq6r7QMuw

-	Abbiamo allegato voucher di cui sopra chiamando con metodo GET 
-
https://api.uat.interop.pagopa.it/api-gateway/1.0/keys/o5uFfYK4rT8ryjg_M1uDx-vTtgYd_iLruXqUEjQm-EI

Ottenendo l’errore indicato sopra. Nella precedente segnalazione si faceva riferimento al fatto che su collaudo sono cambiante le KID. 
Di quali KID si tratta ?

Vorremmo anche segnalare che dal selfcare, entrando su un client API Interop, al termine della configurazione appare bottone per scaricare il descrittore YAML delle API gateway ma non funziona. Invece al contrario in produzione fa scaricare il descrittore YAML correttamente.

**Comment by FedericaSicchiero** [comment]
Le nuove KID le potete trovare nel well.known di collaudo qui https://uat.interop.pagopa.it/.well-known/jwks.json
Grazie per la segnalazione del bottone non funzionante, lo segnalo al team

**Comment by Anna1139** [comment]
Ok, quel link l’abbiamo già visto in realtà ma non dovrebbe riguardare la chiamata fatta sopra rivolta alla vostra API gateway di collaudo. Anzitutto a questo punto chiediamo se l’indirizzo :
https://api.uat.interop.pagopa.it/api-gateway/1.0
è corretto (abbiamo preso quello di produzione e anteposto. uat.)? 
Secondariamente vorremmo capire cosa c’è di sbagliato nella nostra chiamata e perché ci viene restituito il messaggio di errore “Forbidden”.

**Comment by Anna1139** [comment]
Abbiamo fatto dei test e sono andati a buon fine. Ci è stato un errore battitura sull'indirizzo utilizzato.
