### ISSUE TITLE
Funzionalità "sospendi" utente amministratore

### ISSUE THREAD

**Issue by nicolalaginestra** [pagopa/pdnd-interop-frontend#956]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Un utente amministratore, pur avendo a disposizione la funzionalità di sospensione per gli altri utenti abilitati al proprio ente, non riesce a causa di un errore ad effettuare l'operazione su un altro amministratore. Sia ben chiaro che ci si riferisce alla funzionalità di SOSPENSIONE e non di RIMOZIONE.

**Step per riprodurre il bug**
Prerequisito: utente amministratore ente
1. Vai su funzione 'Utenti' menu di sinistra
2. Clicca su un altro amministratore ente
3. Clicca su sospendi
4. Nel popup sospendi Ruolo clicca su sospendi
5. Popup di errore con titolo "Non è stato possibile sospendere il RUOLO. Riprova" e messaggio "Spiacenti qualcosa è andato storto"

**Comportamento atteso**
Cosa ti aspetteresti?
Che sospenda l'amministratore senza errori.

**Il codice IPA del tuo ente**
UICCIAA

**Data e ora in cui si è riscontrato il problema**
es. 27/09/2024 h. 07:45

**Ambiente**
Produzione

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Note**
L'anomalia già stata segnalata all'indirizzo mail dell'assistenza indicata nel portale selfcare di pagopa. A tale email sono seguite richieste di informazioni ulteriori e nonostante siano stati forniti screenshot dettagliati, l'assistenza si è dimostrata incapace di verificare l'esistenza del bug ed a domande dirette ha fornito solo risposte interlocutorie rimandando genericamente alle faq e a questo repository. A tal proposito mi permetto di far notare che questo rimando non è corretto, perché la funzione utenti non fa parte del servizio di interoperabilità, ma è trasversale ai servizi che il portale selfcare offre. Sarebbe auspicabile una maggiore chiarezza su quali siano i canali di assistenza corretti sulle varie funzionalità evitando che si mandino email che poi vengono gestite da chi non ha competenza e conoscenza per risolvere quanto segnalato. Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, confermo che si tratta di un'anomalia lato area riservata. Sento internamente il team che se ne occupa in modo da sbloccarvi la situazione e risolvere il bug

**Comment by FedericaSicchiero** [comment]
Buongiorno, chiudo la issue che Assistenza mi ha confermato di aver preso in carico il task.
