### ISSUE TITLE
Descrittore OpenAPI non valido in fase creazione bozza e-service.

### ISSUE THREAD

**Issue by eqcola** [pagopa/pdnd-interop-frontend#962]
Nella creazione della bozza di un nuovo e-service per il mio ente, provando a caricare il descrittore OpenAPI in allegato ottengo sempre un errore ".... non deve contenere localhost..." non riuscendo a completare il caricamento e quindi la definizione dell'e-service.

**Step per riprodurre il bug**
1. definisci un nuovo e-service e procedi fino al punto in cui ti chiede di caricare il descrittore OpenAPI
2. Seleziona il file in allegato 
3. Vedi l'errore

**Comportamento atteso**
Mi aspetto che il file venga caricato.

**Il codice IPA del mio ente**
c_a662

**Data e ora in cui si è riscontrato il problema**
04/10/2024 h. 10:27

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
 Amministratore (operatore amministrativo)

**screenshot**
[Immagine 2024-10-04 102740](https://github.com/user-attachments/assets/6857acb1-3c76-4aca-997f-587abc5fcb90)

**Note**
Ho rimosso gradualmente le chiavi del json fino ad arrivare alla chiave che determinava il problema.
Il problema sembra essere alla riga 453 alla chiave description di datetime:
**....Either a date-time or an interval, open or.....**
infatti rimuovendo alcuni caratteri speciali l'errore non si presenta più.

**Descrittore di test:**
[api_g3wsuite.json](https://github.com/user-attachments/files/17255512/api_g3wsuite.json)

**Comment by FedericaSicchiero** [comment]
Buongiorno, controlliamo e vi facciamo sapere. Grazie

**Comment by FedericaSicchiero** [comment]
Buongiorno, stiamo implementando un nuovo avviso in piattaforma in modo che sia più specifico quando capitano errori del genere. È possibile che in alcuni casi noi non ci possiamo fare niente perchè il nostro firewall blocca determinate combinazioni di caratteri e per quello da errore, ma almeno avere chiarezza dell'errore può aiutare (come avete fatto voi) a capire la riga che blocca il caricamento. Grazie ancora della segnalazione
