### ISSUE TITLE
Errore in fase di caricamento del file .yaml

### ISSUE THREAD

**Issue by Monica-Ghidelli** [pagopa/pdnd-interop-frontend#963]
Per favore, compila quello che puoi dei campi seguenti. Ci aiuti a risolvere il problema più rapidamente

**Descrivi il bug**
Ambiente collaudo errore quando tento di fare upload di un file .yaml

**Step per riprodurre il bug**
1.sposto il file nel box
2. Clicca su carica
3. Vedi l'errore d27fdb5f-80de-4598-8e78-097577c21085

**Comportamento atteso**
Cosa ti aspetteresti? il caricamento del file

**Il codice IPA del tuo ente**
Se non lo sai, lo trovi così: 
1. vai [qui](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente)
2. inserisci il nome del tuo ente e clicca "Ricerca"
3. sul risultato che ti interessa, clicca nella casella di "Ulteriori informazioni"
4. nella nuova pagina che si apre, sarà visibile il codice IPA di fianco al nome dell'ente
m_it

**Data e ora in cui si è riscontrato il problema**
es. 24/11/2021 h. 10:20

**Ambiente**
 Collaudo

**Quali permessi ha la tua utenza?**
 Operatore API, Operatore di sicurezza

**Screenshot**

**Note**
Ulteriori informazioni che possono aiutare per fare debugging

**Comment by FedericaSicchiero** [comment]
Salve, oltre al correlationID che avete indicato ricevete anche un messaggio di errore del genere "local host" ?

**Comment by Monica-Ghidelli** [comment]
Sono riuscita a fare upload del file. Non avevo indicato la macchina.

La ringrazio del suggerimento.

 

Monica Ghidelli

Funzionario informatico                  

* 06/46529561

e-mail  ***@***.***> ***@***.***

 



  

Dipartimento per l’amministrazione generale, per le Politiche del personale dell'amministrazione civile e per le Risorse strumentali e finanziarie

Direzione Centrale per l’Innovazione tecnologica per l’amministrazione generale

Ufficio II - Reti telematiche, sistemi informativi e sicurezza informatica
Via Cavour, 6 00184 Roma

 

 

 

 

 

Da: Federica Sicchiero ***@***.***> 
Inviato: lunedì 7 ottobre 2024 14:47
A: pagopa/pdnd-interop-frontend ***@***.***>
Cc: Monica-Ghidelli ***@***.***>; Author ***@***.***>
Oggetto: Re: [pagopa/pdnd-interop-frontend] Errore in fase di caricamento del file .yaml (Issue #963)

 

Salve, oltre al correlationID che avete indicato ricevete anche un messaggio di errore del genere "local host" ?
