### ISSUE TITLE
Richiesta caso di test persona fisica con cambio residenza ANPR E-service C020

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#97]
Salve,

stiamo integrando l'E-service C020 ed avremmo bisogno di un caso di test per il quale una persona fisica abbia avuto cambi di residenza in modo da poter ottenere più occorrenze di residenza in output dall' E-Service C020.

Restiamo in attesa di un cortese feedback.
Grazie della collaborazione.
Buon lavoro.

**Comment by ruggerocastagnola** [comment]
Buongiorno Giovanni, 

se ha già avuto un contatto, le chiedo per favore di taggare lei direttamente nell'issue la persona di riferimento dell'ente che gestisce il servizio (@amollicone1982).

Grazie e a presto

Ruggero

**Comment by giovannidenicola** [comment]
Buongiorno @amollicone1982,

un gentile memo, grazie.

**Comment by azabatta** [comment]
Buongiorno,
il caso d'uso non restituisce lo storico delle residenze ma solo la residenza del cittadino alla data specificata come data di riferimento della richiesta. E' possibile avere i dati di una residenza antecedente valorizzando opportunamente la data di riferimento. In ogni caso viene sempre restituita una sola occorrenza.
In generale questa è la logica elaborativa comune a  tutti gli eservice per rispondere al principio di minimizzazione dei dati previsto dal GDPR.

**Comment by giovannidenicola** [comment]
Grazie molte per la risposta.
