### ISSUE TITLE
Impossibile accedere alla documentazione API PDND

### ISSUE THREAD

**Issue by ggianoglio** [pagopa/pdnd-interop-frontend#974]
Non è possibile accedere alla definizione dell'API pubblicata in https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml, in quanto è richiesto un token di autenticazione.

L'indirizzo è corretto o sono state pubblicate nuove versioni dell'API?

Grazie.

**Comment by FedericaSicchiero** [comment]
Buongiorno,
confermo che l'indirizzo corretto è https://api.uat.interop.pagopa.it/api-gateway/1.0 ma per ottenere i file yaml stiamo risolvendo un bug che ultimamente dava errore

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo rilasciato il fix al problema. Faccio solo presente che nel link che avete indicato il formato è yaml e non yml. Probabilmente anche per questo dava errore. Grazie

**Comment by ggianoglio** [comment]
Buongiorno,

ho provato 2 link:
- https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yaml
- https://selfcare.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml

in entrambi i casi ricevo in risposta la pagina
`{
    "message": "Missing Authentication Token"
}`

i link
- https://api.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yaml
- https://api.uat.interop.pagopa.it/api-gateway/1.0/interface-specification.yml

riportano invece
`{
    "message": "Forbidden"
}`

Allego i file .har ottenuti nei 4 casi.
[har.zip](https://github.com/user-attachments/files/17408959/har.zip)

**Comment by FedericaSicchiero** [comment]
Chiedo per favore di provare dalla piattaforma e cliccare sui link da lì per scaricare i documenti allora e vedere che tutto sia corretto
