### ISSUE TITLE
Errore finalità 

### ISSUE THREAD

**Issue by incloudteam** [pagopa/pdnd-interop-frontend#976]
Buongiorno,
Compare questa schermata nella sezione finalità, per il comune di Sanremo
 
![image008](https://github.com/user-attachments/assets/d95acf4e-0da4-4e46-9eb0-ddfad7e36261)

**Comment by FedericaSicchiero** [comment]
Buongiorno, stiamo risolvendo un bug che va a sistemare proprio questo problema. Appena è rilasciato aggiorno la issue. Questo succede solo con le utenze di Operatore, con quella di Amministratore non accade

**Comment by FedericaSicchiero** [comment]
Buonasera, abbiamo rilasciato il fix che risolve questo bug. Ora il portale non dovrebbe più andare in crash. Grazie
