### ISSUE TITLE
Il portale PDND va continuamente in crash su alcune pagine con filtri

### ISSUE THREAD

**Issue by Davide-Almaviva** [pagopa/pdnd-interop-frontend#977]
Buongiorno,

Stiamo riscontrando una strana anomalia sul portale PDND in fase di navigazione.
Nello specifico, ogni tot. secondi compare la pagina di errore come se non caricasse correttamente qualcosa nelle varie pagine. In allegato evidenza del problema. Succede sia in Collaudo sia in Produzione, in diverse pagine quando si effettuano ricerche nelle combo-box, ad esempio per nome eService.
Segnalo che il problema permane. Anche provando a pulire cache/cookies, provando con altri browser e anche provando in incognito. 

Id errore =
9417cade-486e-4838-84d3-c86e3e5e2e68
2ebc1972-6193-41f0-94ee-d49a4c105395
ba223465-2b5b-4eb7-a4a3-2670a196c13b
etc....
Browser = MS Edge (latest v129.0.2792.79-64b)

Di seguito immagine per evidenza del problema in pagina:
![Issue](https://github.com/user-attachments/assets/eb70bb40-2d2b-4cd4-b90d-db0eccd64ea7)

Abbiamo provato a contattare l'Assistenza Area Riservata selfcare.pagopa.it, ma non abbiamo più avuto riscontro.
Per favore potete verificare e farci sapere ? 
Cosa vedete come errori associati a tutti i correlation-id segnalati ?

Se volete possiamo anche fare una rapida call per desktop sharing. Se per voi più comodo.
 
Grazie.
D.

**Comment by FedericaSicchiero** [comment]
Buongiorno, avevo fatto sapere all'assistenza che si tratta di un bug che stiamo risolvendo e che riguarda l'utenza di Operatore e non quella di Amministratore, lo dobbiamo rilasciare nei prossimi giorni

**Comment by Davide-Almaviva** [comment]
Buondì,

Grazie mille per il feedback preciso ed immediato.
Purtroppo dal team di Assistenza Area Riservata ([areariservata@assistenza.pagopa.it](mailto:areariservata@assistenza.pagopa.it)) non era più pervenuta alcuna risposta a seguito della nostra ultima mail verso di loro.

L'ultimo loro feedback sembrava indicare altro:
![image](https://github.com/user-attachments/assets/cd751d47-21e9-4f5b-aac8-ffb39e91eb6b)

Rimaniamo in attesa della risoluzione del bug allora.

Grazie ancora.
D.

**Comment by Davide-Almaviva** [comment]
Confermo che ora questa parte del portale PDND sembra funzionante e stabile sui vari filtri.

Grazie mille per il supporto sempre preciso e puntuale.
D.
