### ISSUE TITLE
Dubbio su attributo IdOperazioneClient, codMittente in Schema TipoTestataRichiestaE000 - ANPR EService C015 e C020

### ISSUE THREAD

**Issue by giovannidenicola** [pagopa/pdnd-interop-frontend#98]
Ciao,

avremmo un dubbio sul valore da utilizzare per i seguentìi attributi, da specifiche OAPI:

- TipoTestataRichiestaE000 / idOperazioneClient* : Identificativo  univoco attribuito all'operazione dall'ente. Deve essere numerico e crescente. Se esiste in ANPR, l'ente riceve come esito la risposta in  precedenza fornita da ANPR con lo stesso ID; se non esiste ed e'  inferiore all'ultimo inviato, l'elaborazione termina con errore.

TipoTestataRichiestaE000 / codMittente*: Il codice identificativo dell'ente che effettua la richiesta (deve essere 600010)

TipoDatiRichiestaE002 / schedaAnagraficaRichiesta* : ?? 

Domanda:

- TipoTestataRichiestaE000 / idOperazioneClient deve essere fornito dal client ed identificativo dell'operazione del client? Al momento, in ambiente di test questo valore sembra venga ignorato dal servizio, anche sempre con lo stesso valore e differenti parametri di input per la consultazione il servizio risponde sempre correttamente e non come indicato nella descrizione.

- TipoTestataRichiestaE000 / codMittente: se identificativo dell'ente che sta eseguendo la richiesta dovrebbe avere valore differente per ogni ente oppure come indicato nella descrizione deve valere sempre 600010? Se è vera la seconda opzione come vengono differenziati gli idOperazioneClient tra enti differenti? C'è un altro attributo per questo?

- TipoDatiRichiestaE002 / schedaAnagraficaRichiesta: non ci è chiaro cosa sia, al momento abbiamo applicato un valore fisso come da esempio riportato nella descrizione del file di specifiche OAPI

Restiamo in attesa di un cortese feedback.
Grazie per la collaborazione.
Buon lavoro.

**Comment by ruggerocastagnola** [comment]
Anche in questo caso, @amollicone1982.

Grazie mille e a presto

Ruggero

**Comment by giovannidenicola** [comment]
Buongiorno @amollicone1982,

un gentile memo, grazie.

**Comment by amollicone1982** [comment]
TipoTestataRichiestaE000 / idOperazioneClient* : Identificativo univoco attribuito all'operazione dall'ente. Deve essere numerico e crescente. Se esiste in ANPR, l'ente riceve come esito la risposta in precedenza fornita da ANPR con lo stesso ID; se non esiste ed e' inferiore all'ultimo inviato, l'elaborazione termina con errore. **è un id utile ai fine del tracciamento. Non viene applicato nessun controllo (non viene restituita la risposta precedente se viene fornito lostesso)**
TipoTestataRichiestaE000 / codMittente*: Il codice identificativo dell'ente che effettua la richiesta (deve essere 600010) **si, diciamo che serve piu' a noi internamente. Vo verrete riconosciuti principalmente con il clientid**

TipoDatiRichiestaE002 / schedaAnagraficaRichiesta* : **per futuri utilizzi,avete fatto bene a lasciare quanto specificato nell'OAPI**

**Comment by giovannidenicola** [comment]
Grazie per le risposte.
