### ISSUE TITLE
Risorsa linkata ma non disponibile su portale PDND

### ISSUE THREAD

**Issue by Davide-Almaviva** [pagopa/pdnd-interop-frontend#980]
Buongiorno,

Sul portale PDND, segnalo che sembra essere mancante una risorsa:
https://selfcare.uat.interop.pagopa.it/m2m/interface-specification.yaml
collegata dalle pagine del portale.

Di seguito trovate tutti i dettagli richiesti.
Per favore potete verificare a rimettere disponibile la risorsa ?

Grazie.
D.

--------------------------------------

**Data e ora in cui si è riscontrato il problema** : 2024-10-16 13:02

**Ambiente**: Collaudo (non so se succede anche in Produzione, non ho un test case per provare)

**Quali permessi ha la tua utenza?**: Operatore API, Operatore di sicurezza

**Screenshot**
![image](https://github.com/user-attachments/assets/403feeb3-387c-4be9-a57a-340cdf6534fd)

**Link verso**:
https://selfcare.uat.interop.pagopa.it/m2m/interface-specification.yaml
... ma poi quando si apre la risorsa, per accedere allo YAML delle API Interoperabilità PDND e fare discovery dei servizi, non c'è alcun file disponibile per lo scaricamento.

**Screenshot**
![image](https://github.com/user-attachments/assets/0bf47eb0-e6da-45e8-902e-dc0b1f4029ef)

**Comment by FedericaSicchiero** [comment]
Buongiorno, abbiamo rilasciato il fix a questo bug. Ora i link funzionano correttamente. Grazie

**Comment by Davide-Almaviva** [comment]
Buondì

Grazie mille per il feedback. La risorsa YAML sembra ora disponibile per lo scaricamento ed utilizzo.

Solo un **dubbio** sul contenuto: all'interno del file non troviamo traccia dell'endpoint (**base url**) che espone i servizi.
Troviamo i path e le strutture dati, ma non troviamo una sezione "service" o degli endpoint per effettuare chiamate alle API in ambiente di Collaudo.

Per favore potete verificare che il file caricato sia completo ?
O anche solo fornirci tale informazione per effettuare dei test di chiamata.

Grazie.
D.

**Comment by FedericaSicchiero** [comment]
Si li stiamo riaggiungendo perchè a causa di alcune modifiche erano stati tolti:

PROD: https://api.interop.pagopa.it/
COLLAUDO: https://api.uat.interop.pagopa.it/

**Comment by Davide-Almaviva** [comment]
Grazie mille per il feedback immediato.
Appena poi ri-aggiunti allo swagger sul portale, provvediamo poi ad integrare il tutto lato client con gli endpoint corretti etc...

Bye.
D.
