### ISSUE TITLE
C002 Collaudo errore 015-0008 

### ISSUE THREAD

**Issue by incloudteam** [pagopa/pdnd-interop-frontend#983]
Buongiorno, 
potreste indicarci cosa non sta andando?

ente: Comune di Parma
Ambiente: Collaudo
Client: ANPR client collaudo Polizia Municipale 
Client id: 54cbc3a9-fd04-4e88-aaed-3f6c268199e0
E-service di riferimento : [C020-servizioAccertamentoResidenza-approvazione_automatica, versione 5]
Finalità: Polizia Municipale: accertamento generalità
client_assertion: 
eyJraWQiOiJGT3FGRTlYcVlDdzdwWmlIOXF2RDFwN3NTY3hUdkZ2bUt3dUh1UEw1Mmo0IiwiYWxnIjoiUlMyNTYifQ.eyJwdXJwb3NlSWQiOiIyMTVlYWY1OC0yYWU3LTQ4ZDYtOTFlNC1hYTdkMTFhNjc5MmEiLCJkaWdlc3QiOnsiYWxnIjoiU0hBMjU2IiwidmFsdWUiOiJiYTkzOTdlZWIwMjg2NzkwNzg4MzVlODU4ZjU4ZmM5NmRjYmU4YzQ0NzdiNDQ5ZmM2Zjc4ZDJjNTdlZGYyODg4In0sImp0aSI6ImExNGU0MDUzLTE2YTEtNDc4ZC1iOWYwLTE5OGNkMDQzZjI3MyIsImlhdCI6MTcyOTE1NTQxNywiZXhwIjoxNzI5MTU1NzE3LCJuYmYiOjE3MjkxNTU0MTd9.sxl9xCgZu1fv60CqotX0LM1AdkUjdS8MYxWScsThLqVcp5yhxVgjj8hlI7V2RLr-oAaiPGU5WQVldtx3BYVPuUGmaqKe-X9KytaAXEb0THEHpWySHq2vrV8bTP_hiERgOtKjxgYt6Y13UPCDC3qSKy4q_ufqXCcqpaWpYGMszR--KcorSMdvmoHc0wD2qnJm_aYfj5w7q9h5Wv8Q8NwWP0a9thvZvzt_9R9PycFsSTN54whqUnp3SQiLJlmUKNDUeTlaVr4uTXD0TvrMC1GxMZzMM_cbSjlFJC5u3GP4J-82fxJRvLLgAblP2yKWAJnmhpYZT3YQyWnLMmETf-EsTA

Risposta
```json
{
   "correlationId":"dc62acd9-97d9-42a6-9830-8ac4ddd58101",
   "errors":[
      {
         "code":"015-0008",
         "detail":"Unable to generate a token for the given request"
      }
   ],
   "status":400,
   "title":"The request contains bad syntax or cannot be fulfilled.",
   "type":"about:blank"
}
```

**Comment by FedericaSicchiero** [comment]
Buongiorno, avete provato ad utilizzare il tool di debug della client assertion presente in piattaforma? Vi fa una prima analisi di quale può essere il problema

**Comment by FedericaSicchiero** [comment]
A vedere dal tool sembra che il token sia scaduto e ci sia necessità di ottenerne un altro

**Comment by incloudteam** [comment]
ho notato che qua 
![image](https://github.com/user-attachments/assets/bc2a51a8-1056-46a1-80af-85c1dba830a1)
l'audience è differente ma anche con questo ottengo lo stesso errore 

_Il claim AUD (audience) non contiene l'audience corretta_
