### ISSUE TITLE
ERROR: render finalità fruitori

### ISSUE THREAD

**Issue by vintra73** [pagopa/pdnd-interop-frontend#985]
**Descrivi il bug**
Nel ruolo di Erogatore, la feature finalità, che dovrebbe mostrare l'elenco delle finalità dei fruitori degli e-service erogati, restituisce "Errore del server".

**Step per riprodurre il bug**
1. Vai su "Erogatore"
2. Clicca su "Finalità"
3. Vedi l'errore

**Comportamento atteso**
elenco delle finalità dei fruitori degli e-service erogati

**Il codice IPA del tuo ente**
AgID

**Data e ora in cui si è riscontrato il problema**
18/10/2024 h. 10:40

**Ambiente**
Collaudo

**Quali permessi ha la tua utenza?**
Amministratore (operatore amministrativo)

**Comment by FedericaSicchiero** [comment]
ciao Vincenzo, stiamo sistemando delle cose in collaudo per questo al momento dà errore. Per l'ora di pranzo dovrebbe essere concluso. Grazie

**Comment by FedericaSicchiero** [comment]
Ora è di nuovo utilizzabile.

**Comment by vintra73** [comment]
Grazie
