### ISSUE TITLE
L'accesso alle API di PDND Interoperabilità non sembra funzionare

### ISSUE THREAD

**Issue by Davide-Almaviva** [pagopa/pdnd-interop-frontend#986]
Buondì,

In fase di interrogazione delle API di PDND Interoperabilità otteniamo sempre un errore "403 Forbidden".
Indipendentemente dal servizio richiamato e dal Bearer Token di sicurezza passato correttamente nell'header, generato come da documentazione.
Di seguito trovate i dettagli di una delle chiamate di prova fatte e l'errore ricevuto.

Per favore potete aiutarci a capire che cosa non stia funzionando o cosa sia errato ?

Grazie per il supporto.
D.

---------------------------

**Descrizione**
Es. di request e response
GET https://api.uat.interop.pagopa.it/v1/agreements
![image](https://github.com/user-attachments/assets/38f84eee-04b9-4166-9f2e-efed18047cc9)

La generazione dell'Assertion è fatta correttamente ed è valida per il portale:
![image](https://github.com/user-attachments/assets/13bdc05d-ab31-4cc1-becc-9fd6aa43ee83)

Anche la generazione del Bearer Token finale funziona correttamente e restituisce un token apparentemente valido:
![image](https://github.com/user-attachments/assets/b16affc5-6cac-415f-bcb8-aa28e74c5d00)

**Comportamento atteso**
Un 2xx oppure al massimo errore funzionale sulla ricerca effettuata. Ma riceviamo solo errori di sicurezza (ipotizzo legati al token) anche se questa parte dovrebbe funzionare correttamente per le chiamate.

**Data e ora**
2024-10-21 --> tra le 12:30 e le 13:00 (CEST)

**Ambiente**
Collaudo
KID = 5G6mH_C9vgoK13ib0z5x3kIdDJ_4H2_q7fnBQts8xRk
ClientId = 38f6e6d5-a194-4ed2-bb7e-b60dd26e2482

**Quali permessi ha la tua utenza?**
Operatore API, Operatore di sicurezza

**Screenshot**
![image](https://github.com/user-attachments/assets/d6b23fec-0fe8-47cd-abde-a90d66be2276)
![image](https://github.com/user-attachments/assets/f7b7deca-66fb-4a0a-a64c-e873b24139f4)

**Note**
Di seguito vi riporto i response header popolati dal servizio PDND, qualora vi servano come Correlation-Id per verifica sui logs =
- x-amzn-RequestId: 16b0469b-f566-4d9d-ba86-8fe15f1be6dd
- x-amzn-ErrorType: ForbiddenException
- x-amz-apigw-id: f_wjqFJVsu8EXHQ=

**Comment by Davide-Almaviva** [comment]
Buondì,

Grazie mille per il feedback puntuale. Quell'url credo sia stato creato (generato) da Postman in fase di importazione dello swagger attuale.
Abbiamo riprovato modificando manualmente come indicato ed ora la situazione risulta migliore (con errori funzionali).

Domanda: dove possiamo trovare degli esempi di chiamate valide per l'ambiente di Collaudo ? O comunque degli use-cases di prova.
Parlo in generale per tutti i vari path esposti dalle API di Interop della PDND.
Per gli eService ad esempio, in genere provvediamo a verifiche di funzionamento in base ai test-cases messi a disposizione dall'erogatore sul portale della PDND.

Thanks.
D.

**Comment by FedericaSicchiero** [comment]
Ottimo!

Per le API stiamo lavorando a una versione 2 che verrà rilasciata nel 2025 e che porterà tutta una serie di implementazioni che ora mancano, tipo i path citati. Al momento quindi mancano e ci sarà da attendere la nuova versione. Grazie
