### ISSUE TITLE
Errore creazione Finalità

### ISSUE THREAD

**Issue by marcoPistilli** [pagopa/pdnd-interop-frontend#988]
Il problema si presenta in ambiente di produzione per il prodotto Interoperabilità:
1. Vai su "Finalità"
2. Seleziona il prodotto, in questo caso "Protocollo Interoperabile comune di Orune"
3. Clicca su "Crea Finalità"
4. Errore creazione finalità con ID d0eba2f7-7ce8-4c2f-bd22-3735ba984c69

L'errore si presenta sul comune di Orune, codice IPA c_g147 il 22/10/2024 alle 12:50 con un utente amministratore

**Comment by FedericaSicchiero** [comment]
Buonasera, controlliamo e vi aggiorniamo

**Comment by marcoPistilli** [comment]
Oggi ho tentato nuovamente a creare la finalità, il problema non si presenta più.
