### ISSUE TITLE
Impossibile accedere all'ambiente di attestazione

### ISSUE THREAD

**Issue by fdl90** [pagopa/pdnd-interop-frontend#989]
Stiamo provando a collegarci a questo url: https://selfcare.att.interop.pagopa.it, ma riceviamo questo errore:
{
    "errors": [
        {
            "code": "016-9000",
            "detail": "tenantId is not valid - Input string \"undefined\" is not a valid UUID"
        }
    ],
    "status": 400,
    "title": "The request contains bad syntax or cannot be fulfilled.",
    "type": "about:blank"
}

In generale, esiste una procedura che possiamo seguire per usare l'ambiente di attestazione?

Grazie

**Comment by FedericaSicchiero** [comment]
Salve, con quale ente e utente state provando ad accedere all'ambiente di attestazione?

**Comment by fdl90** [comment]
L'errore si presenta semplicemente cliccando sull'url indicata, ancor prima di inserire qualsiasi dato:

![image](https://github.com/user-attachments/assets/937fd646-97ba-4b73-82ce-2a80a46e3ebf)
