### ISSUE TITLE
Pdnd produzione: creazione client m2minterop

### ISSUE THREAD

**Issue by amollicone1982** [pagopa/pdnd-interop-frontend#99]
Ho fatto l'accesso in ambiente di produzione ma non mi fa creare un nuovo client sotto m2minterop nonostante abbia i ruoli

Questa è la mail che mi è arrivata:
DESIDERIA TOSCANO ti ha assegnato i ruoli Operatore API e Operatore Sicurezza per il prodotto Interoperabilità nell’Area Riservata di Ministero dell'Interno.

**Comment by ruggerocastagnola** [comment]
Ciao Angelo, ho avuto bisogno di verifica le linee guida di AgID. Quello che vedi è corretto, non è possibile che un utente con ruolo Operatore di sicurezza o API crei un Client. Questa funzionalità è a pannaggio di Amministratori e Delegati (Operatori amministrativi). Ecco il [riferimento alla linea guida](https://trasparenza.agid.gov.it/moduli/downloadFile.php?file=oggetto_allegati/213481832130O__O20211210_LG+Infrastruttura+Interoperabilit%26%23224%3B+PDND_v1_allegato+2.pdf), pag. 22

**Comment by ruggerocastagnola** [comment]
Intanto questa la considero chiusa, in caso ci siano modifiche da fare ne creeremo una nuova
