### ISSUE TITLE
Errore download "Analisi del Rischio"

### ISSUE THREAD

**Issue by gilliale** [pagopa/pdnd-interop-frontend#991]
Per alcune finalità "attive" non è più possibile scaricare il documento "Analisi del Rischio"  (funzione "Scarica analisi del rischio" sulla schermata Fruizione-> Le tue finalità -> Gestione singola finalità

**Comment by FedericaSicchiero** [comment]
Buongiorno,
ci potete dare un esempio per quali e-service, finalità e ente? Grazie

**Comment by gilliale** [comment]
Buongiorno di seguito le info richieste per alcuni dei casi **non funzionanti**.
Dall' ultimo test sembra che il download non sia più possibile per nessuna finalità, anche se dai test eseguiti questa mattina il download per alcune finalità era funzionante .

1)
ente: "Comune di Trento"
Finalità : "Accesso alla PND per notificazione atti"
e-service : SEND
errore: "Non è stato possibile scaricare il documento dell'analisi del rischio. Per favore, riprova!"

2)
ente: "Comune di Trento"
Finalità : "Domanda Iscrizione Asilo Nido"
e-service : C021-servizioAccertamentoStatoFamiglia-approvazione_automati, versione 2
errore: "Non è stato possibile scaricare il documento dell'analisi del rischio. Per favore, riprova!"

**Comment by FedericaSicchiero** [comment]
Personalmente sono riuscita a scaricarle e le posso passare via mail volendo, l'utenza con cui state provando a scaricarle è quella di amministratore?

**Comment by gilliale** [comment]
Buongiorno Federica,
possiedo il ruoli di "Operatore API" e "Operatore Sicurezza".
Con utente Amministratore non ho provato.

**Comment by FedericaSicchiero** [comment]
Per conferma vi chiedo di far provare anche ad un Amministratore, perchè se anche con quel ruolo non si riesce allora apro un bug internamente

**Comment by gilliale** [comment]
Buongiorno, oggi il problema sembra rientrato. E' possibile scaricare sia come Amministratore sia come ""Operatore API" e "Operatore Sicurezza"."
Grazie
