### ISSUE TITLE
Erogazione - Flusso di verifica PurposeId

### ISSUE THREAD

**Issue by mircogamberinirer** [pagopa/pdnd-interop-frontend#993]
Stiamo implementando l'erogazione dei servizi in modalità PDND nell'ambito del bando PNRR relativo a tale tema.
Nell'ambito di verifica del voucher pdnd, su doc ufficiale c'è scritto questo nel capitolo verifica sul payload:

_"In ultimo, il parametro purposeId dà il riferimento della finalità per la quale il fruitore fa richiesta all'erogatore. Attraverso successive chiamate all'API gateway di PDND Interoperabilità è possibile richiedere tutte le informazioni di contesto, in caso siano necessarie (ossia i client associati, la richiesta di fruizione e l'e-service di riferimento, ecc)."_

A partire da questa frase, ho alcune domande:
- Il controllo sul purposeid da parte dell'erogatore è obbligatorio? se si quale api bisogna invocare? 
- per evitare di sovracccaricare il server pdnd si consiglia di cachare? se si per quanto?

**Comment by FedericaSicchiero** [comment]
Salve, il controllo non è obbligatorio, sta all'erogatore decidere quali controlli vuole effettuare per consentire poi lo stacco del voucher. Noi come piattaforma garantiamo la sicurezza sui dati scambiati, ma ci limitiamo a questo.

Per quanto riguarda il sovraccarico non c'è problema, non è richiesto di cachare.

**Comment by FedericaSicchiero** [comment]
Un aggiunta per quanto riguarda il purposeID: è legato alla finalità che viene approvata dall'erogatore, quindi è informativo e finchè il fruitore non invia una nuova finalità (che l'erogatore dovrà approvare) si può cachare indefinitamente
