### ISSUE TITLE
Errore nel caricamento della chiave Pubblica

### ISSUE THREAD

**Issue by gilliale** [pagopa/pdnd-interop-frontend#996]
Buongiorno,
sto cercando di caricare la chiave pubblica per un nuovo "client e-service".
Ho provato diverse volte ma ottengo sempre un errore.
Riporto di seguito l'ultimo identificativo errore

dfe02930-9fd7-4b5f-91c3-a507d136d97f

**Comment by FedericaSicchiero** [comment]
Buongiorno, l'errore è dovuto al fatto che la chiave è già associata al client "Fruitore Comune Trento Test"

**Comment by gilliale** [comment]
Ok grazie
